/**
 * @fileOverview Arabic strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ar', 'العربية', {
    alignCenterTitle: "محاذاة توسيط النص",
    alignJustifyTitle: "محاذاة النص إلى تبرير",
    alignLeftTitle: "محاذاة النص لليسار",
    alignRightTitle: "محاذاة النص إلى اليمين",
    cancelDialogCancelButton: "مواصلة تحرير",
    cancelDialogContent: "هل أنت متأكد من أنك تريد إلغاء التحرير؟ سيتم فقدان كافة التغييرات!",
    cancelDialogOKButton: "إلغاء التحرير",
    cancelDialogTitle: "إلغاء التحرير",
    cancelTitle: "إلغاء التحرير",
    classMenuTitle: "منتقي نمط",
    clearFormattingTitle: "مسح التنسيق",
    clickButtonToEditText: "تحرير",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "تلقائي",
    colorMenuBasicBlack: "الأسود",
    colorMenuBasicBlue: "الأزرق",
    colorMenuBasicGreen: "الأخضر",
    colorMenuBasicGrey: "رمادي",
    colorMenuBasicOrange: "أورانج",
    colorMenuBasicPurple: "اللون الأرجواني",
    colorMenuBasicRed: "الأحمر",
    colorMenuBasicTitle: "تغيير لون النص",
    colorMenuBasicWhite: "الأبيض",
    dockToElementTitle: "الإرساء\/إلغاء إرساء محرر لعنصر",
    dockToScreenTitle: "الإرساء\/إلغاء إرساء محرر للشاشة",
    embedDialogCancelButton: "إلغاء الأمر",
    embedDialogOKButton: "تضمين كائن",
    embedDialogTabCode: "تضمين التعليمات البرمجية",
    embedDialogTabCodeContent: "لصق الخاص بك تضمين رمز في ناحية النص أدناه:",
    embedDialogTabPreview: "معاينة",
    embedDialogTabPreviewContent: "يتم عرض معاينة للكائن المضمن الخاص بك أدناه:",
    embedDialogTitle: "تضمين كائن",
    embedTitle: "تضمين كائن",
    errorUINoName: "واجهة المستخدم \"{{ui}}\" غير صالح (يجب أن يكون لديك خاصية اسم)",
    errorUINotObject: "واجهة المستخدم \"{{ui}}\" غير صالح (يجب أن يكون كائن)",
    errorUIOverride: "تم بالفعل تسجيل واجهة المستخدم \"{{name}}\"، وسيتم الكتابة فوق",
    fileManagerDialogTitle: "إدارة الملفات",
    fileManagerTitle: "إدارة الملفات",
    floatLeftTitle: "محاذاة الصورة إلى اليسار",
    floatNoneTitle: "إزالة الصورة محاذاة",
    floatRightTitle: "محاذاة الصورة إلى اليمين",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "هزلية دون",
    fontFamilyMenuFontCourier: "الحقيبة الجديدة",
    fontFamilyMenuFontDefault: "الخط الافتراضي",
    fontFamilyMenuFontGeorgia: "جورجيا",
    fontFamilyMenuFontImpact: "أثر",
    fontFamilyMenuFontPalatino: "بلاطي",
    fontFamilyMenuFontTimes: "تايمز الرومانية الجديدة",
    fontFamilyMenuTitle: "اختيار الخط الخاص بك",
    guidesTitle: "إظهار خطوط إرشاد العنصر",
    historyRedoTitle: "الإعادة",
    historyUndoTitle: "التراجع عن",
    hrCreateTitle: "إدراج مسطرة أفقية",
    imageResizeButtonDialogCancelButton: "إلغاء الأمر",
    imageResizeButtonDialogHeight: "ارتفاع الصورة",
    imageResizeButtonDialogHeightPlaceHolder: "الارتفاع",
    imageResizeButtonDialogOKButton: "تغيير حجم",
    imageResizeButtonDialogTitle: "تغيير حجم الصورة",
    imageResizeButtonDialogWidth: "عرض الصورة",
    imageResizeButtonDialogWidthPlaceHolder: "العرض",
    imageResizeButtonText: "تغيير حجم الصورة",
    insertFileDialogCancelButton: "إلغاء الأمر",
    insertFileDialogOKButton: "إدراج ملف",
    insertFileNameLabel: "اسم الملف",
    insertFileNamePlaceHolder: "اسم الملف...",
    insertFileTitle: "إدراج ملف",
    insertFileURLLabel: "ملف URL",
    insertFileURLPlaceHolder: "ملف URL...",
    languageMenuTitle: "تغيير اللغة",
    linkCreateDialogCancelButton: "إلغاء الأمر",
    linkCreateDialogMenuHeader: "اختر نوع ارتباط",
    linkCreateDialogOKButton: "إدراج ارتباط",
    linkCreateDialogTitle: "إدراج ارتباط",
    linkCreateTitle: "إدراج ارتباط",
    linkRemoveTitle: "إزالة الارتباط",
    linkTypeDocumentHeader: "ارتباط إلى مستند أو ملف آخر",
    linkTypeDocumentInfo: "<h2>لم تكن متأكداً من ما وضع في المربع أعلاه؟<\/h2><ol>    <li>تأكد من تحميل الملف إلى موقع الويب الخاص بك.<\/li>    <li>قم بفتح الملف الذي تم تحميله في المتصفح الخاص بك.<\/li>    <li>انسخ عنوان URL الملف من شريط العناوين في المستعرض الخاص بك ولصقه في المربع أعلاه.<\/li><\/ol>",
    linkTypeDocumentLabel: "مستند أو ملف آخر",
    linkTypeDocumentLocationLabel: "الموقع:",
    linkTypeDocumentLocationPlaceHolder: "أدخل عنوان URL",
    linkTypeDocumentNewWindowHeader: "نافذة جديدة",
    linkTypeDocumentNewWindowLabel: "حدد هذا المربع لفتح في نافذة مستعرض جديدة\/علامة تبويب الملف.",
    linkTypeEmailHeader: "ارتباط إلى عنوان بريد إلكتروني",
    linkTypeEmailLabel: "عنوان البريد الإلكتروني",
    linkTypeEmailSubjectLabel: "الموضوع (اختياري):",
    linkTypeEmailSubjectPlaceHolder: "أدخل هذا الموضوع",
    linkTypeEmailToLabel: "البريد الإلكتروني:",
    linkTypeEmailToPlaceHolder: "أدخل عنوان البريد الإلكتروني",
    linkTypeExternalHeader: "وصلة إلى صفحة على موقع آخر",
    linkTypeExternalInfo: "<h2>لم تكن متأكداً من ما وضع في المربع أعلاه؟<\/h2><ol>    <li>العثور على الصفحة على ويب الذي تريد الارتباط.<\/li>    <li>انسخ عنوان ويب من شريط العناوين في المستعرض الخاص بك ولصقه في المربع أعلاه.<\/li><\/ol>",
    linkTypeExternalLabel: "صفحة على موقع آخر",
    linkTypeExternalLocationLabel: "الموقع:",
    linkTypeExternalLocationPlaceHolder: "أدخل عنوان URL",
    linkTypeExternalNewWindowHeader: "نافذة جديدة",
    linkTypeExternalNewWindowLabel: "حدد هذا المربع لفتح في نافذة مستعرض جديدة\/علامة تبويب الارتباط.",
    linkTypeInternalHeader: "وصلة إلى صفحة في هذا الموقع",
    linkTypeInternalInfo: "<h2>لم تكن متأكداً من ما وضع في المربع أعلاه؟<\/h2><ol>    <li>العثور على الصفحة على هذا الرابط موقع إلى.<\/li>    <li>نسخ عنوان الويب من العنوان المستعرض الخاص بك بار، باستثناء \"{{domain}}\" ولصقه في المربع أعلاه.<\/li><\/ol>",
    linkTypeInternalLabel: "صفحة على موقع ويب هذا",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "إدخال URI",
    linkTypeInternalNewWindowHeader: "نافذة جديدة",
    linkTypeInternalNewWindowLabel: "حدد هذا المربع لفتح في نافذة مستعرض جديدة\/علامة تبويب الارتباط.",
    listOrderedTitle: "قائمة مرتبة",
    listUnorderedTitle: "قائمة غير مرتبة",
    logoTitle: "مزيد من المعلومات حول محرر WYSIWYG رابتور",
    navigateAway: "\nهناك تغييرات غير محفوظة في هذه الصفحة. \nإذا انتقلت من هذه الصفحة فستفقد التغييرات غير المحفوظة الخاصة بك",
    pasteDialogCancelButton: "إلغاء الأمر",
    pasteDialogFormattedCleaned: "تنسيق وتنظيفها",
    pasteDialogFormattedUnclean: "تنسيق غير نظيفة",
    pasteDialogOKButton: "إدراج",
    pasteDialogPlain: "نص عادي",
    pasteDialogSource: "التعليمات البرمجية المصدر",
    pasteDialogTitle: "لصق",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "فشل استرداد التنقيحات",
    revisionsApplyButtonDialogCancelButton: "إلغاء الأمر",
    revisionsApplyButtonDialogOKButton: "العودة إلى الحالة السابقة",
    revisionsApplyButtonDialogTitle: "تأكيد العودة إلى الحالة السابقة",
    revisionsApplyButtonTitle: "العودة إلى الحالة السابقة",
    revisionsApplyDialogContent: "سيؤدي ذلك إلى استبدال المحتوى الحالي مع مراجعة مختارة.<br>المحتوى الحالي سوف تضاف كمراجعة، وسوف تظهر في قائمة تنقيحات لهذه الكتلة.",
    revisionsButtonCurrent: "الحالي",
    revisionsButtonViewDiffText: "الاختلافات",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "إلغاء الأمر",
    revisionsDialogTitle: "عرض محتوى التنقيحات",
    revisionsDiffButtonDialogCancelButton: "قم بإغلاق",
    revisionsDiffButtonDialogTitle: "عرض الاختلافات",
    revisionsDiffButtonTitle: "عرض الاختلافات",
    revisionsLoading: "تحميل المراجعات...",
    revisionsNone: "لا تنقيحات لهذا العنصر",
    revisionsPreviewButtonTitle: "معاينة",
    revisionsText: "التنقيحات",
    revisionsTextEmpty: "لا تنقيحات",
    revisionsTitle: "",
    rfmClose: "قم بإغلاق",
    rfmContinue: "مواصلة",
    rfmDelete: "حذف",
    rfmDownload: "تحميل",
    rfmFileActions: "الإجراءات",
    rfmFileModificationTime: "تعديل",
    rfmFileName: "الاسم",
    rfmFileSize: "الحجم",
    rfmFileType: "نوع",
    rfmFilteredTotal: "عرض {{start}} {{end}} {{filteredTotal}} ملفات",
    rfmFirst: "الأولى",
    rfmHeadingDirectories: "الدلائل",
    rfmHeadingSearch: "البحث",
    rfmHeadingTags: "العلامات",
    rfmHeadingUpload: "تحميل",
    rfmInsert: "إدراج",
    rfmLast: "آخر صورة",
    rfmSearch: "الذهاب",
    rfmTotal: "، التي تمت تصفيتها من {{total}}",
    rfmUpload: "تحميل",
    rfmUploadBrowse: "تصفح",
    rfmUploadDrop: "إسقاط الملفات هنا",
    rfmUploadFileRemove: "إزالة",
    rfmView: "طريقة العرض",
    saveJsonFail: "فشل في حفظ block(s) المحتوى {{failed}}",
    saveJsonSaved: "حفظ {{saved}} block(s) المحتوى بنجاح.",
    saveNotConfigured: "حفظ لم يتم تكوينه، أو معطل.",
    saveRestFail: "فشل في حفظ block(s) المحتوى {{failed}}.",
    saveRestPartial: "حفظ من كتل محتوى {{saved}} {{failed}}.",
    saveRestSaved: "حفظ {{saved}} block(s) المحتوى بنجاح.",
    saveTitle: "حفظ المحتوى",
    snippetMenuTitle: "قصاصات",
    specialCharactersDialogOKButton: "موافق",
    specialCharactersDialogTitle: "إدراج أحرف خاصة",
    specialCharactersHelp: "انقر فوق حرف خاص لإضافته. انقر فوق \"موافق\" عندما يتم إغلاق مربع الحوار هذا",
    specialCharactersTitle: "إدراج حرف خاص",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} أحرف أكثر من الحد",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} الأحرف المتبقية",
    statisticsButtonCharacters: "أحرف {{characters}}",
    statisticsDialogCharactersOverLimit: "أحرف {{characters}}، {{charactersRemaining}} أكثر من الحد الموصى به",
    statisticsDialogCharactersRemaining: "أحرف {{characters}}، {{charactersRemaining}} المتبقية",
    statisticsDialogNotTruncated: "سوف لا يتم اقتطاع محتوى",
    statisticsDialogOKButton: "موافق",
    statisticsDialogSentence: "الجملة {{sentences}}",
    statisticsDialogSentences: "الجمل {{sentences}}",
    statisticsDialogTitle: "إحصائيات المحتوى",
    statisticsDialogTruncated: "المحتوى يحتوي على أكثر من حرف {{limit}}، وقد يتم اقتطاعها",
    statisticsDialogWord: "كلمة {{words}}",
    statisticsDialogWords: "{{words}} كلمات",
    statisticsTitle: "انقر فوق لعرض الإحصائيات",
    tableCreateTitle: "إنشاء جدول",
    tableDeleteColumnTitle: "حذف عمود الجدول",
    tableDeleteRowTitle: "حذف صف الجدول",
    tableInsertColumnTitle: "إدراج عمود جدول",
    tableInsertRowTitle: "إدراج صف جدول",
    tableMergeCellsTitle: "دمج خلايا الجدول",
    tableSplitCellsTitle: "تقسيم خلايا الجدول",
    tagMenuTagAddress: "عنوان",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "العنوان 1",
    tagMenuTagH2: "العنوان 2",
    tagMenuTagH3: "العنوان 3",
    tagMenuTagH4: "العنوان 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "الفقرة",
    tagMenuTagPre: "تمت تهيئتها مسبقاً",
    tagMenuTitle: "تغيير نمط عنصر",
    tagTreeElementLink: "حدد عنصر {{element}}",
    tagTreeElementTitle: "انقر فوق لتحديد محتويات العنصر \"{{element}}\"",
    tagTreeRoot: "الجذر",
    tagTreeRootLink: "حدد كافة المحتويات القابلة للتحرير",
    tagTreeRootTitle: "انقر لتحديد كافة المحتويات القابلة للتحرير",
    textBlockQuoteTitle: "اقتباس كتلة",
    textBoldTitle: "غامق",
    textItalicTitle: "مائل",
    textSizeDecreaseTitle: "إنقاص حجم النص",
    textSizeIncreaseTitle: "زيادة حجم النص",
    textStrikeTitle: "الإضراب من خلال",
    textSubTitle: "البرنامج النصي الفرعية",
    textSuperTitle: "البرنامج النصي فائقة",
    textUnderlineTitle: "تسطير",
    unsavedEditWarningText: "هناك تغييرات غير محفوظة في هذه الصفحة",
    viewSourceDialogCancelButton: "قم بإغلاق",
    viewSourceDialogOKButton: "تطبيق التعليمات البرمجية المصدر",
    viewSourceDialogTitle: "رمز مصدر المحتوى",
    viewSourceTitle: "عرض\/تحرير التعليمات البرمجية المصدر"
});