/**
 * @fileOverview Bulgarian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('bg', 'Български', {
    alignCenterTitle: "Подравните текста спрямо центъра",
    alignJustifyTitle: "Подравняване на текста оправдават",
    alignLeftTitle: "Подравняване на текста вляво",
    alignRightTitle: "Подравняване на текста вдясно",
    cancelDialogCancelButton: "Продължаване на редактирането",
    cancelDialogContent: "Наистина ли искате да отмените редактирането? Всички промени ще бъдат загубени!",
    cancelDialogOKButton: "Отмени редактирането",
    cancelDialogTitle: "Отмени редактирането",
    cancelTitle: "Отмени редактирането",
    classMenuTitle: "Избор на стил",
    clearFormattingTitle: "Изчисти форматирането",
    clickButtonToEditText: "Редактиране",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Автоматично",
    colorMenuBasicBlack: "Черно",
    colorMenuBasicBlue: "Син",
    colorMenuBasicGreen: "Грийн",
    colorMenuBasicGrey: "Сив",
    colorMenuBasicOrange: "Ориндж",
    colorMenuBasicPurple: "Лилаво",
    colorMenuBasicRed: "Червен",
    colorMenuBasicTitle: "Промяна на цвета на текста",
    colorMenuBasicWhite: "Бяло",
    dockToElementTitle: "Лапад\/откачване редактор на елемент",
    dockToScreenTitle: "Лапад\/откачване редактор на екрана",
    embedDialogCancelButton: "Отказ",
    embedDialogOKButton: "Вграждане на обект",
    embedDialogTabCode: "Код за вграждане",
    embedDialogTabCodeContent: "Поставете кода за вграждане в областта за текст по-долу:",
    embedDialogTabPreview: "Визуализация",
    embedDialogTabPreviewContent: "Визуализация на вашия вграден обект е показана по-долу:",
    embedDialogTitle: "Вграждане на обект",
    embedTitle: "Вграждане на обект",
    errorUINoName: "Потребителски интерфейс \"{{ui}}\" е невалиден (трябва да има име на свойство)",
    errorUINotObject: "Потребителски интерфейс \"{{ui}}\" е невалиден (трябва да бъде обект)",
    errorUIOverride: "Потребителски интерфейс \"{{name}}\" вече е регистриран и ще бъде заместен",
    fileManagerDialogTitle: "Файлов мениджър",
    fileManagerTitle: "Файлов мениджър",
    floatLeftTitle: "Подравняване на изображение отляво",
    floatNoneTitle: "Премахнете изображението подравняване",
    floatRightTitle: "Подравняване на изображение отдясно",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Комикс без",
    fontFamilyMenuFontCourier: "Куриер нов",
    fontFamilyMenuFontDefault: "Шрифт по подразбиране",
    fontFamilyMenuFontGeorgia: "Грузия",
    fontFamilyMenuFontImpact: "Въздействие",
    fontFamilyMenuFontPalatino: "Палатин",
    fontFamilyMenuFontTimes: "Време нов римски",
    fontFamilyMenuTitle: "Изберете вашия шрифт",
    guidesTitle: "Показване на елемент ръководства",
    historyRedoTitle: "Върни",
    historyUndoTitle: "Отмени",
    hrCreateTitle: "Вмъкни хоризонтална линийка",
    imageResizeButtonDialogCancelButton: "Отказ",
    imageResizeButtonDialogHeight: "Височина на изображението",
    imageResizeButtonDialogHeightPlaceHolder: "Височина",
    imageResizeButtonDialogOKButton: "Преоразмеряване",
    imageResizeButtonDialogTitle: "Преоразмеряване на изображение",
    imageResizeButtonDialogWidth: "Ширина на изображението",
    imageResizeButtonDialogWidthPlaceHolder: "Ширина",
    imageResizeButtonText: "Преоразмеряване на изображение",
    insertFileDialogCancelButton: "Отказ",
    insertFileDialogOKButton: "Вмъкване на файл",
    insertFileNameLabel: "Име на файла",
    insertFileNamePlaceHolder: "Име на файл...",
    insertFileTitle: "Вмъкване на файл",
    insertFileURLLabel: "Файл URL",
    insertFileURLPlaceHolder: "Файл URL...",
    languageMenuTitle: "Промяна на езика",
    linkCreateDialogCancelButton: "Отказ",
    linkCreateDialogMenuHeader: "Изберете тип на връзка",
    linkCreateDialogOKButton: "Вмъкване на връзка",
    linkCreateDialogTitle: "Вмъкване на връзка",
    linkCreateTitle: "Вмъкване на връзка",
    linkRemoveTitle: "Премахни връзката",
    linkTypeDocumentHeader: "Връзка към документ или друг файл",
    linkTypeDocumentInfo: "<h2>Не сте сигурни какво да поставите в полето по-горе?<\/h2><ol>    <li>Осигуряване на файла е бил качен на вашия сайт.<\/li>    <li>Отворете качения файл във вашия браузър.<\/li>    <li>Копирайте URL на файла от адресната лента на браузъра си и да го поставите в полето по-горе.<\/li><\/ol>",
    linkTypeDocumentLabel: "Документ или друг файл",
    linkTypeDocumentLocationLabel: "Местоположение:",
    linkTypeDocumentLocationPlaceHolder: "Въведете URL адрес",
    linkTypeDocumentNewWindowHeader: "Нов прозорец",
    linkTypeDocumentNewWindowLabel: "Отметнете това квадратче, за да е отворил файла в нов прозорец.",
    linkTypeEmailHeader: "Връзка към имейл адрес",
    linkTypeEmailLabel: "Имейл адрес",
    linkTypeEmailSubjectLabel: "Относно (по избор):",
    linkTypeEmailSubjectPlaceHolder: "Въведете въпрос",
    linkTypeEmailToLabel: "Имейл:",
    linkTypeEmailToPlaceHolder: "Въведете имейл адрес",
    linkTypeExternalHeader: "Връзка към страница на друг уеб сайт",
    linkTypeExternalInfo: "<h2>Не сте сигурни какво да поставите в полето по-горе?<\/h2><ol>    <li>Намерите на страницата уеб искате да се свържете.<\/li>    <li>Копирайте уеб адреса от адресната лента на браузъра си и да го поставите в полето по-горе.<\/li><\/ol>",
    linkTypeExternalLabel: "Страница на друг уеб сайт",
    linkTypeExternalLocationLabel: "Местоположение:",
    linkTypeExternalLocationPlaceHolder: "Въведете URL адрес",
    linkTypeExternalNewWindowHeader: "Нов прозорец",
    linkTypeExternalNewWindowLabel: "Отметнете това квадратче, за да има на връзката отвори в нов прозорец.",
    linkTypeInternalHeader: "Връзка към страницата на този сайт",
    linkTypeInternalInfo: "<h2>Не сте сигурни какво да поставите в полето по-горе?<\/h2><ol>    <li>Намерите на страницата на този сайт връзка към.<\/li>    <li>Копирайте уеб адреса от вашия браузър адресната лента, с изключение на \"{{domain}}\" и да го поставите в полето по-горе.<\/li><\/ol>",
    linkTypeInternalLabel: "Страница на този сайт",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Въведете URI",
    linkTypeInternalNewWindowHeader: "Нов прозорец",
    linkTypeInternalNewWindowLabel: "Отметнете това квадратче, за да има на връзката отвори в нов прозорец.",
    listOrderedTitle: "Подреден списък",
    listUnorderedTitle: "Неподреден списък",
    logoTitle: "Научете повече за Raptor WYSIWYG редактор",
    loremIpsumTitle: "Вмъкване на текст за тестване",
    navigateAway: "\nИма незаписани промени на тази страница. \nАко напуснете тази страница Вие ще загубите вашите незаписани промени",
    pasteDialogCancelButton: "Отказ",
    pasteDialogFormattedCleaned: "Форматиран &amp; почиства",
    pasteDialogFormattedUnclean: "Форматиран нечисти",
    pasteDialogOKButton: "Вмъкване",
    pasteDialogPlain: "Обикновен текст",
    pasteDialogSource: "Изходен код",
    pasteDialogTitle: "Паста",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Неуспешно извличане на ревизии",
    revisionsApplyButtonDialogCancelButton: "Отказ",
    revisionsApplyButtonDialogOKButton: "Намаление на цените",
    revisionsApplyButtonDialogText: "Потвърждение на възстановяването",
    revisionsApplyButtonDialogTitle: "Потвърждение на възстановяването",
    revisionsApplyButtonText: "Намаление на цените",
    revisionsApplyButtonTitle: "Намаление на цените",
    revisionsApplyDialogContent: "Това ще замени текущото съдържание с избраната.<br>Текущото съдържание ще бъдат добавени като преразглеждане и ще се вижда в списъка на корекциите за този блок.",
    revisionsButtonCurrent: "Ток",
    revisionsButtonViewDiffText: "Разлики",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Създаден",
    revisionsDialogCancelButton: "Отказ",
    revisionsDialogTitle: "Преглед съдържание ревизии",
    revisionsDiffButtonDialogCancelButton: "Затвори",
    revisionsDiffButtonDialogTitle: "Изглед разлики",
    revisionsDiffButtonText: "Изглед разлики",
    revisionsDiffButtonTitle: "Изглед разлики",
    revisionsLoading: "Зареждане на ревизии...",
    revisionsNone: "Няма ревизии за този елемент",
    revisionsPreviewButtonText: "Визуализация",
    revisionsPreviewButtonTitle: "Визуализация",
    revisionsText: "Ревизии",
    revisionsTextEmpty: "Не корекции",
    revisionsTitle: "",
    rfmClose: "Затвори",
    rfmContinue: "Продължи",
    rfmDelete: "Изтриване",
    rfmDownload: "Изтегляне",
    rfmFileActions: "Действия",
    rfmFileModificationTime: "Модифицирани",
    rfmFileName: "Име",
    rfmFileSize: "Размер",
    rfmFileType: "Тип",
    rfmFilteredTotal: "Показване {{start}} до {{end}} {{filteredTotal}} файлове",
    rfmFirst: "Първо",
    rfmHeadingDirectories: "Директории",
    rfmHeadingSearch: "Търсене",
    rfmHeadingTags: "Тагове",
    rfmHeadingUpload: "Качване",
    rfmInsert: "Вмъкване",
    rfmLast: "Последно",
    rfmSearch: "Отидете",
    rfmTagDocument: "Документ",
    rfmTagImage: "Изображение",
    rfmTotal: ", филтрирани от {{total}}",
    rfmUpload: "Качване",
    rfmUploadBrowse: "Преглед",
    rfmUploadDrop: "Пуснете файлове тук",
    rfmUploadFileRemove: "Премахване на",
    rfmUploadOr: "или",
    rfmView: "Изглед",
    saveJsonFail: "Неуспешно записване на {{failed}} съдържание block(s)",
    saveJsonSaved: "Настил {{saved}} съдържание block(s).",
    saveNotConfigured: "Запиши не е конфигуриран, или е забранен.",
    saveRestFail: "Неуспешно записване на {{failed}} съдържание block(s).",
    saveRestPartial: "Записан {{saved}} на {{failed}} съдържание блокове.",
    saveRestSaved: "Настил {{saved}} съдържание block(s).",
    saveTitle: "Запишете съдържание",
    snippetMenuTitle: "Откъси",
    specialCharactersArrows: "Стрелките",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "Вмъкване на специални знаци",
    specialCharactersGreekAlphabet: "Гръцката азбука",
    specialCharactersHelp: "Щракнете върху специалния знак, за да го добавите. Щракнете върху \"OK\" когато сте готови да затворите този диалогов прозорец",
    specialCharactersMathematics: "Математика",
    specialCharactersSymbols: "Символи",
    specialCharactersTitle: "Вмъкване на специален знак",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} знаците над ограничението",
    statisticsButtonCharacterRemaining: "оставащи знаци на {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} знака",
    statisticsDialogCharactersOverLimit: "знака {{characters}}, {{charactersRemaining}} над препоръчваната граница",
    statisticsDialogCharactersRemaining: "{{characters}}, {{charactersRemaining}} оставащи знаци",
    statisticsDialogNotTruncated: "Съдържанието не ще бъдат орязани",
    statisticsDialogOKButton: "OK",
    statisticsDialogSentence: "{{sentences}} изречение",
    statisticsDialogSentences: "{{sentences}} изречения",
    statisticsDialogTitle: "Съдържание статистика",
    statisticsDialogTruncated: "Съдържанието съдържа повече от {{limit}} знака и може да бъде изрязана",
    statisticsDialogWord: "{{words}} дума",
    statisticsDialogWords: "{{words}} думите",
    statisticsTitle: "Щракнете, за да видите статистика",
    tableCreateTitle: "Създаване на таблица",
    tableDeleteColumnTitle: "Изтриване на колона от таблица",
    tableDeleteRowTitle: "Изтриване на ред от таблица",
    tableInsertColumnTitle: "Вмъкни колона на таблица",
    tableInsertRowTitle: "Вмъкване на ред в таблица",
    tableMergeCellsTitle: "Обединяване на клетки от таблица",
    tableSplitCellsTitle: "Разделяне на клетки от таблица",
    tagMenuTagAddress: "Адрес",
    tagMenuTagDiv: "DIV",
    tagMenuTagH1: "Заглавие 1",
    tagMenuTagH2: "Заглавие 2",
    tagMenuTagH3: "Заглавие 3",
    tagMenuTagH4: "Функция 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Параграф",
    tagMenuTagPre: "Предварително форматиран",
    tagMenuTitle: "Промяна на стила на елемент",
    tagTreeElementLink: "Изберете елемент на {{element}}",
    tagTreeElementTitle: "Щракнете, за да изберете съдържанието на елемент \"{{element}}\"",
    tagTreeRoot: "корен",
    tagTreeRootLink: "Изберете всички редактира съдържание",
    tagTreeRootTitle: "Щракнете за да изберете всички редактира съдържание",
    textBlockQuoteTitle: "Блоков цитат",
    textBoldTitle: "Получер",
    textItalicTitle: "Курсив",
    textSizeDecreaseTitle: "Намаляване на размера на текста",
    textSizeIncreaseTitle: "Увеличи размера на текста",
    textStrikeTitle: "Зачеркнато",
    textSubTitle: "Под-скрипт",
    textSuperTitle: "Супер скрипт",
    textUnderlineTitle: "Подчертаване",
    unsavedEditWarningText: "Има незаписани промени на тази страница",
    viewSourceDialogCancelButton: "Затвори",
    viewSourceDialogOKButton: "Прилага изходен код",
    viewSourceDialogTitle: "Код на източник на съдържание",
    viewSourceTitle: "Преглед\/редактиране на изходния код"
});