/**
 * @fileOverview Czech strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('cs', 'Čeština', {
    alignCenterTitle: "Zarovnání textu na střed",
    alignJustifyTitle: "Zarovnat text zarovnat",
    alignLeftTitle: "Zarovnat text doleva",
    alignRightTitle: "Zarovnat text doprava",
    cancelDialogCancelButton: "Pokračovat v úpravách",
    cancelDialogContent: "Jste si jisti, že chcete zrušit úpravy? Všechny změny budou ztracena!",
    cancelDialogOKButton: "Zrušit úpravy",
    cancelDialogTitle: "Zrušit úpravy",
    cancelTitle: "Zrušit úpravy",
    classMenuTitle: "Výběr stylu",
    clearFormattingTitle: "Vymazat formátování",
    clickButtonToEditText: "Úpravy",
    clickButtonToEditTitle: null,
    colorMenuBasicAutomatic: "Automatický",
    colorMenuBasicBlack: "Černá",
    colorMenuBasicBlue: "Modrá",
    colorMenuBasicGreen: "Zelená",
    colorMenuBasicGrey: "Šedá",
    colorMenuBasicOrange: "Oranžová",
    colorMenuBasicPurple: "Fialová",
    colorMenuBasicRed: "Červená",
    colorMenuBasicTitle: "Změnit barvu textu",
    colorMenuBasicWhite: "Bílá",
    dockToElementTitle: "Doku\/uvolnit editor prvek",
    dockToScreenTitle: "Doku\/uvolnit editor na obrazovce",
    embedDialogCancelButton: "Storno",
    embedDialogOKButton: "Vložit objekt",
    embedDialogTabCode: "Kód pro vložení",
    embedDialogTabCodeContent: "Do oblasti textu vložte kód pro vložení:",
    embedDialogTabPreview: "Náhled",
    embedDialogTabPreviewContent: "Níže je zobrazen náhled vloženého objektu:",
    embedDialogTitle: "Vložit objekt",
    embedTitle: "Vložit objekt",
    errorUINoName: "UI \"{{ui}}\" je neplatná (musí mít vlastnost název)",
    errorUINotObject: "UI \"{{ui}}\" je neplatná (musí být objekt)",
    errorUIOverride: "UI \"{{name}}\" již byla registrována a budou přepsány",
    fileManagerDialogTitle: "Správce souborů",
    fileManagerTitle: "Správce souborů",
    floatLeftTitle: "Zarovnat obrázek nalevo",
    floatNoneTitle: "Odstranit obrázek zarovnat",
    floatRightTitle: "Zarovnat obrázek vpravo",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komiks bez",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Výchozí písmo",
    fontFamilyMenuFontGeorgia: "Gruzie",
    fontFamilyMenuFontImpact: "Dopad",
    fontFamilyMenuFontPalatino: "Palatin",
    fontFamilyMenuFontTimes: "Shlédnuto New Roman",
    fontFamilyMenuTitle: "Zvolte písmo",
    guidesTitle: "Zobrazit vodítka prvek",
    historyRedoTitle: "Znovu:",
    historyUndoTitle: "Zpět:",
    hrCreateTitle: "Vložit vodorovnou čáru",
    imageResizeButtonDialogCancelButton: "Storno",
    imageResizeButtonDialogHeight: "Výška obrázku",
    imageResizeButtonDialogHeightPlaceHolder: "Výška",
    imageResizeButtonDialogOKButton: "Změna velikosti",
    imageResizeButtonDialogTitle: "Změna velikosti obrázku",
    imageResizeButtonDialogWidth: "Šířka obrázku",
    imageResizeButtonDialogWidthPlaceHolder: "Šířka",
    imageResizeButtonText: "Změna velikosti obrázku",
    insertFileDialogCancelButton: "Storno",
    insertFileDialogOKButton: "Vložit soubor",
    insertFileNameLabel: "Název souboru",
    insertFileNamePlaceHolder: "Název souboru...",
    insertFileTitle: "Vložit soubor",
    insertFileURLLabel: "URL souboru",
    insertFileURLPlaceHolder: "URL souboru...",
    languageMenuTitle: "Změna jazyka",
    linkCreateDialogCancelButton: "Storno",
    linkCreateDialogMenuHeader: "Zvolte typ vazby",
    linkCreateDialogOKButton: "Vložit odkaz",
    linkCreateDialogTitle: "Vložit odkaz",
    linkCreateTitle: "Vložit odkaz",
    linkRemoveTitle: "Odstranit odkaz",
    linkTypeDocumentHeader: "Odkaz na dokument nebo jiný soubor",
    linkTypeDocumentInfo: "<h2>Nejste si jisti co do výše uvedeného pole?<\/h2><ol>    <li>Ujistěte se, že soubor byl odeslán do vaší webové stránky.<\/li>    <li>Otevřete soubor uložený ve vašem prohlížeči.<\/li>    <li>Zkopírujte tento soubor URL z adresního řádku vašeho prohlížeče a vložte ji do pole výše.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokument nebo jiný soubor",
    linkTypeDocumentLocationLabel: "Místo:",
    linkTypeDocumentLocationPlaceHolder: "Zadejte adresu URL",
    linkTypeDocumentNewWindowHeader: "Nové okno",
    linkTypeDocumentNewWindowLabel: "Zaškrtněte toto políčko, chcete-li soubor otevřít v novém okně prohlížeče\/položky.",
    linkTypeEmailHeader: "Odkaz na e-mailovou adresu",
    linkTypeEmailLabel: "E-mailová adresa",
    linkTypeEmailSubjectLabel: "Předmět (nepovinné):",
    linkTypeEmailSubjectPlaceHolder: "Zadejte předmět",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Zadejte e-mailovou adresu",
    linkTypeExternalHeader: "Odkaz na stránky na jiném webu",
    linkTypeExternalInfo: "<h2>Nejste si jisti co do výše uvedeného pole?<\/h2><ol>    <li>Vyhledejte stránku na webu, který chcete odkázat.<\/li>    <li>Zkopírujte webovou adresu z adresního řádku vašeho prohlížeče a vložte ji do pole výše.<\/li><\/ol>",
    linkTypeExternalLabel: "Stránky na jiném webu",
    linkTypeExternalLocationLabel: "Místo:",
    linkTypeExternalLocationPlaceHolder: "Zadejte adresu URL",
    linkTypeExternalNewWindowHeader: "Nové okno",
    linkTypeExternalNewWindowLabel: "Zaškrtněte toto políčko, aby byl odkaz otevřít v novém okně prohlížeče\/položky.",
    linkTypeInternalHeader: "Odkaz na stránky na tomto webu",
    linkTypeInternalInfo: "<h2>Nejste si jisti co do výše uvedeného pole?<\/h2><ol>    <li>Vyhledejte stránku na tomto spojení sítí.<\/li>    <li>Zkopírujte webovou adresu z vašeho prohlížeče do adresního řádku, s výjimkou \"{{domain}}\" a vložte jej do pole výše.<\/li><\/ol>",
    linkTypeInternalLabel: "Stránky na tomto webu",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Zadejte identifikátor URI",
    linkTypeInternalNewWindowHeader: "Nové okno",
    linkTypeInternalNewWindowLabel: "Zaškrtněte toto políčko, aby byl odkaz otevřít v novém okně prohlížeče\/položky.",
    listOrderedTitle: "Seřazený seznam",
    listUnorderedTitle: "Neseřazený seznam",
    logoTitle: "Další informace o Raptor WYSIWYG Editor",
    loremIpsumTitle: "Vložit fiktivní text pro testování",
    navigateAway: "\nNa této stránce jsou neuložené změny. \nPokud opustíte tuto stránku dojde ke ztrátě neuložených změn:",
    pasteDialogCancelButton: "Storno",
    pasteDialogFormattedCleaned: "Formátovat &amp; vyčistit",
    pasteDialogFormattedUnclean: "Formátovaný nečisté",
    pasteDialogOKButton: "Vložit",
    pasteDialogPlain: "Prostý Text",
    pasteDialogSource: "Zdrojový kód",
    pasteDialogTitle: "Vložit",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Nepodařilo se načíst revize",
    revisionsApplyButtonDialogCancelButton: "Storno",
    revisionsApplyButtonDialogOKButton: "Vrácení zpět",
    revisionsApplyButtonDialogText: "Vrácení zpět potvrzení",
    revisionsApplyButtonDialogTitle: "Vrácení zpět potvrzení",
    revisionsApplyButtonText: "Vrácení zpět",
    revisionsApplyButtonTitle: "Vrácení zpět",
    revisionsApplyDialogContent: "Touto akcí nahradíte stávající obsah vybrané revize.<br>Současný obsah bude přidán jako revizi a bude zobrazena v seznamu revizí pro tento blok.",
    revisionsButtonCurrent: "Proud",
    revisionsButtonViewDiffText: "Rozdíly",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Vytvořil(a)",
    revisionsDialogCancelButton: "Storno",
    revisionsDialogTitle: "Zobrazit obsah revize",
    revisionsDiffButtonDialogCancelButton: "Zavřít",
    revisionsDiffButtonDialogTitle: "Zobrazit rozdíly",
    revisionsDiffButtonText: "Zobrazit rozdíly",
    revisionsDiffButtonTitle: "Zobrazit rozdíly",
    revisionsLoading: "Načítání revize...",
    revisionsNone: "Žádná revize tohoto prvku",
    revisionsPreviewButtonText: "Náhled",
    revisionsPreviewButtonTitle: "Náhled",
    revisionsText: "Revize",
    revisionsTextEmpty: "Bez revize",
    revisionsTitle: "",
    rfmClose: "Zavřít",
    rfmContinue: "Pokračovat",
    rfmDelete: "Odstranit",
    rfmDownload: "Stáhnout",
    rfmFileActions: "Akce",
    rfmFileModificationTime: "Změněno",
    rfmFileName: "Jméno",
    rfmFileSize: "Velikost",
    rfmFileType: "Typ",
    rfmFilteredTotal: "Zobrazeno {{start}} {{end}} {{filteredTotal}} souborů",
    rfmFirst: "První",
    rfmHeadingDirectories: "Adresáře",
    rfmHeadingSearch: "Hledat",
    rfmHeadingTags: "Značky",
    rfmHeadingUpload: "Nahrát",
    rfmInsert: "Vložit",
    rfmLast: "Poslední",
    rfmSearch: "Jít",
    rfmTagDocument: "Dokument",
    rfmTagImage: "Obrázek",
    rfmTotal: ", filtrované od {{total}}",
    rfmUpload: "Nahrát",
    rfmUploadBrowse: "Procházet",
    rfmUploadDrop: "Sem přetáhněte soubory",
    rfmUploadFileRemove: "Odstranit",
    rfmUploadOr: "nebo",
    rfmView: "Pohled",
    saveJsonFail: "Nepodařilo se uložit {{failed}} obsah bloků",
    saveJsonSaved: "Úspěšně uloženo {{saved}} obsah bloků.",
    saveNotConfigured: "Uložit není nakonfigurována nebo zakázána.",
    saveRestFail: "Nepodařilo se uložit {{failed}} obsah bloků.",
    saveRestPartial: "Uloženo {{saved}} z {{failed}} bloků obsahu.",
    saveRestSaved: "Úspěšně uloženo {{saved}} obsah bloků.",
    saveTitle: "Uložit obsah",
    snippetMenuTitle: "Úryvky",
    specialCharactersArrows: "Šipky",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Vložit speciální znaky",
    specialCharactersGreekAlphabet: "Řecká abeceda",
    specialCharactersHelp: "Klepněte na speciální znak, přidejte jej. Klikněte na \"OK\", po dokončení zavřete toto dialogové okno",
    specialCharactersMathematics: "Matematika",
    specialCharactersSymbols: "Symboly",
    specialCharactersTitle: "Vložení speciálního znaku",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} znaků nad limit",
    statisticsButtonCharacterRemaining: "Zbývající počet znaků: {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} znaky",
    statisticsDialogCharactersOverLimit: "znaky {{characters}}, {{charactersRemaining}} za doporučený limit",
    statisticsDialogCharactersRemaining: "{{characters}} znaky, {{charactersRemaining}} zbývající",
    statisticsDialogNotTruncated: "Obsah nebude zkrácen.",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "{{sentences}} věta",
    statisticsDialogSentences: "{{sentences}} vět",
    statisticsDialogTitle: "Obsah statistiky",
    statisticsDialogTruncated: "Obsah obsahuje více než {{limit}} znaků a může být zkrácen",
    statisticsDialogWord: "slovo {{words}}",
    statisticsDialogWords: "{{words}} slov",
    statisticsTitle: "Klepnutím zobrazíte statistiku",
    tableCreateTitle: "Vytvořit tabulku",
    tableDeleteColumnTitle: "Odstranit sloupce tabulky",
    tableDeleteRowTitle: "Odstranit řádek tabulky",
    tableInsertColumnTitle: "Vložit sloupec tabulky",
    tableInsertRowTitle: "Vložit řádek tabulky",
    tableMergeCellsTitle: "Sloučit buňky tabulky",
    tableSplitCellsTitle: "Rozdělit buňky tabulky",
    tagMenuTagAddress: "Adresa",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Nadpis 1",
    tagMenuTagH2: "Nadpis 2",
    tagMenuTagH3: "Nadpis 3",
    tagMenuTagH4: "Nadpis 4",
    tagMenuTagNA: "NENÍ K DISPOZICI",
    tagMenuTagP: "Odstavec",
    tagMenuTagPre: "Pre-formátovaný",
    tagMenuTitle: "Změnit styl prvku",
    tagTreeElementLink: "Vyberte element {{element}}",
    tagTreeElementTitle: "Klepnutím vyberte obsah elementu \"{{element}}\"",
    tagTreeRoot: "kořen",
    tagTreeRootLink: "Vyberte veškerý obsah upravitelné",
    tagTreeRootTitle: "Klepnutím vyberete všechny upravovat obsah",
    textBlockQuoteTitle: "Bloková citace",
    textBoldTitle: "Tučné",
    textItalicTitle: "Kurzíva",
    textSizeDecreaseTitle: "Snížit velikost textu",
    textSizeIncreaseTitle: "Zvýšit velikost textu",
    textStrikeTitle: "Přeškrtnuté",
    textSubTitle: "Dílčí skript",
    textSuperTitle: "Super-skript",
    textUnderlineTitle: "Podtržení",
    unsavedEditWarningText: "Existují neuložené změny na této stránce",
    viewSourceDialogCancelButton: "Zavřít",
    viewSourceDialogOKButton: "Použít zdrojový kód",
    viewSourceDialogTitle: "Obsahu zdrojového kódu",
    viewSourceTitle: "Zobrazit či upravit zdrojový kód"
});
