/**
 * @fileOverview Greek strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('el', 'Ελληνικά', {
    alignCenterTitle: "Πλήρης στοίχιση στο κέντρο κείμενο",
    alignJustifyTitle: "Στοιχίσετε κείμενο να δικαιολογήσει",
    alignLeftTitle: "Στοίχιση κειμένου αριστερά",
    alignRightTitle: "Στοίχιση κειμένου δεξιά",
    cancelDialogCancelButton: "Συνεχίσετε την επεξεργασία",
    cancelDialogContent: "Είστε βέβαιοι ότι θέλετε να ακυρώσετε την επεξεργασία; Όλες οι αλλαγές θα χαθούν!",
    cancelDialogOKButton: "Ακυρώσετε την επεξεργασία",
    cancelDialogTitle: "Ακυρώσετε την επεξεργασία",
    cancelTitle: "Ακυρώσετε την επεξεργασία",
    classMenuTitle: "Στυλ επιλογέα",
    clearFormattingTitle: "Απαλοιφή μορφοποίησης",
    clickButtonToEditText: "Επεξεργασία",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Αυτόματη",
    colorMenuBasicBlack: "Μαύρο",
    colorMenuBasicBlue: "Μπλε",
    colorMenuBasicGreen: "Πράσινο",
    colorMenuBasicGrey: "Γκρι",
    colorMenuBasicOrange: "Πορτοκαλί",
    colorMenuBasicPurple: "Μωβ",
    colorMenuBasicRed: "Κόκκινο",
    colorMenuBasicTitle: "Αλλαγή χρώμα κειμένου",
    colorMenuBasicWhite: "Λευκό",
    dockToElementTitle: "Αποβάθρα\/απαγκύρωση editor για να στοιχείο",
    dockToScreenTitle: "Αποβάθρα\/απαγκύρωση πρόγραμμα επεξεργασίας οθόνη",
    embedDialogCancelButton: "\"Άκυρο\"",
    embedDialogOKButton: "Ενσωματώσετε αντικείμενο",
    embedDialogTabCode: "Ενσωματώστε τον κώδικα",
    embedDialogTabCodeContent: "Επικολλήστε το παρακάτω κείμενο περιοχή σας ενσωματώνει τον κώδικα:",
    embedDialogTabPreview: "Προεπισκόπηση",
    embedDialogTabPreviewContent: "Μια προεπισκόπηση του ενσωματωμένου αντικειμένου σας εμφανίζεται παρακάτω:",
    embedDialogTitle: "Ενσωματώσετε αντικείμενο",
    embedTitle: "Ενσωματώσετε αντικείμενο",
    errorUINoName: "UI \"{{ui}}\" δεν είναι έγκυρος (πρέπει να έχει μια ιδιότητα name)",
    errorUINotObject: "UI \"{{ui}}\" δεν είναι έγκυρος (πρέπει να είναι ένα αντικείμενο)",
    errorUIOverride: "UI \"{{name}}\" έχει καταχωρηθεί ήδη, και θα αντικατασταθούν",
    fileManagerDialogTitle: "Διαχειριστής αρχείων",
    fileManagerTitle: "Διαχειριστής αρχείων",
    floatLeftTitle: "Στοίχιση εικόνας προς τα αριστερά",
    floatNoneTitle: "Κατάργηση εικόνας ευθυγράμμιση",
    floatRightTitle: "Στοίχιση εικόνας προς τα δεξιά",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Κόμικ χωρίς",
    fontFamilyMenuFontCourier: "Courier νέα",
    fontFamilyMenuFontDefault: "Προεπιλεγμένη γραμματοσειρά",
    fontFamilyMenuFontGeorgia: "Γεωργία",
    fontFamilyMenuFontImpact: "Επιπτώσεις",
    fontFamilyMenuFontPalatino: "Παλατίνο",
    fontFamilyMenuFontTimes: "Φορές τα νέα Ρωμαϊκή",
    fontFamilyMenuTitle: "Ἐπιλογὴ γραμματοσειρᾶς",
    guidesTitle: "Στοιχείο Εμφάνιση οδηγών",
    historyRedoTitle: "Ακύρωση αναίρεσης",
    historyUndoTitle: "Αναίρεση",
    hrCreateTitle: "Εισαγωγή οριζόντιος κανόνας",
    imageResizeButtonDialogCancelButton: "\"Άκυρο\"",
    imageResizeButtonDialogHeight: "Ύψος εικόνας",
    imageResizeButtonDialogHeightPlaceHolder: "Ύψος",
    imageResizeButtonDialogOKButton: "Αλλαγή μεγέθους",
    imageResizeButtonDialogTitle: "Το μέγεθος της εικόνας",
    imageResizeButtonDialogWidth: "Πλάτος εικόνας",
    imageResizeButtonDialogWidthPlaceHolder: "Πλάτος",
    imageResizeButtonText: "Το μέγεθος της εικόνας",
    insertFileDialogCancelButton: "\"Άκυρο\"",
    insertFileDialogOKButton: "Εισαγωγή αρχείου",
    insertFileNameLabel: "Όνομα αρχείου",
    insertFileNamePlaceHolder: "Όνομα αρχείου...",
    insertFileTitle: "Εισαγωγή αρχείου",
    insertFileURLLabel: "URL αρχείου",
    insertFileURLPlaceHolder: "URL αρχείου...",
    languageMenuTitle: "Αλλαγή γλώσσας",
    linkCreateDialogCancelButton: "\"Άκυρο\"",
    linkCreateDialogMenuHeader: "Επιλέξτε έναν τύπο σύνδεσης",
    linkCreateDialogOKButton: "Εισαγάγετε το σύνδεσμο",
    linkCreateDialogTitle: "Εισαγάγετε το σύνδεσμο",
    linkCreateTitle: "Εισαγάγετε το σύνδεσμο",
    linkRemoveTitle: "Κατάργηση σύνδεσης",
    linkTypeDocumentHeader: "Σύνδεση σε ένα έγγραφο ή άλλο αρχείο",
    linkTypeDocumentInfo: "<h2>Δεν είμαι σίγουρος τι θα βάλουμε στο παραπάνω πλαίσιο;<\/h2><ol>    <li>Εξασφαλιστεί το αρχείο έχει αναρτηθεί στην ιστοσελίδα σας.<\/li>    <li>Ανοίξτε το αρχείο στο πρόγραμμα περιήγησης.<\/li>    <li>Αντιγράψτε το URL του αρχείου από τη γραμμή διευθύνσεων του browser σας και επικολλήστε το στο παραπάνω πλαίσιο.<\/li><\/ol>",
    linkTypeDocumentLabel: "Έγγραφο ή άλλο αρχείο",
    linkTypeDocumentLocationLabel: "Τοποθεσία:",
    linkTypeDocumentLocationPlaceHolder: "Πληκτρολογήστε μια διεύθυνση URL",
    linkTypeDocumentNewWindowHeader: "Νέο παράθυρο",
    linkTypeDocumentNewWindowLabel: "Επιλέξτε αυτό το πλαίσιο να έχει το αρχείο ανοίξει σε ένα νέο παράθυρο\/tab.",
    linkTypeEmailHeader: "Σύνδεση με μια διεύθυνση ηλεκτρονικού ταχυδρομείου",
    linkTypeEmailLabel: "Διεύθυνση ηλεκτρονικού ταχυδρομείου",
    linkTypeEmailSubjectLabel: "Θέμα (προαιρετικό):",
    linkTypeEmailSubjectPlaceHolder: "Εισάγετε θέμα",
    linkTypeEmailToLabel: "Ηλεκτρονικό ταχυδρομείο:",
    linkTypeEmailToPlaceHolder: "Εισάγετε τη διεύθυνση ηλεκτρονικού ταχυδρομείου",
    linkTypeExternalHeader: "Σύνδεση σε μια σελίδα σε μια άλλη ιστοσελίδα",
    linkTypeExternalInfo: "<h2>Δεν είμαι σίγουρος τι θα βάλουμε στο παραπάνω πλαίσιο;<\/h2><ol>    <li>Βρείτε τη σελίδα στο web που θέλετε να συνδέσετε.<\/li>    <li>Αντιγράψτε τη διεύθυνση web από τη γραμμή διευθύνσεων του browser σας και επικολλήστε το στο παραπάνω πλαίσιο.<\/li><\/ol>",
    linkTypeExternalLabel: "Σελίδα σε μια άλλη ιστοσελίδα",
    linkTypeExternalLocationLabel: "Τοποθεσία:",
    linkTypeExternalLocationPlaceHolder: "Πληκτρολογήστε μια διεύθυνση URL",
    linkTypeExternalNewWindowHeader: "Νέο παράθυρο",
    linkTypeExternalNewWindowLabel: "Επιλέξτε αυτό το πλαίσιο να έχει το link ανοίξει σε ένα νέο παράθυρο\/tab.",
    linkTypeInternalHeader: "Σύνδεση σε μια σελίδα σε αυτή την ιστοσελίδα",
    linkTypeInternalInfo: "<h2>Δεν είμαι σίγουρος τι θα βάλουμε στο παραπάνω πλαίσιο;<\/h2><ol>    <li>Βρίσκετε στην σελίδα πάνω να αυτής της σύνδεσης τοποθεσίας.<\/li>    <li>Αντιγράψτε τη διεύθυνση ιστού από του προγράμματος περιήγησης διεύθυνση μπαρ, εκτός από \"{{domain}}\" και επικολλήστε το στο παραπάνω πλαίσιο.<\/li><\/ol>",
    linkTypeInternalLabel: "Σελίδα σε αυτή την ιστοσελίδα",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Εισάγετε ένα URI",
    linkTypeInternalNewWindowHeader: "Νέο παράθυρο",
    linkTypeInternalNewWindowLabel: "Επιλέξτε αυτό το πλαίσιο να έχει το link ανοίξει σε ένα νέο παράθυρο\/tab.",
    listOrderedTitle: "Ταξινομημένη λίστα",
    listUnorderedTitle: "Μη ταξινομημένη λίστα",
    logoTitle: "Μάθετε περισσότερα για την αρπακτικών WYSIWYG Editor",
    navigateAway: "\nΥπάρχουν μη αποθηκευμένες αλλαγές σε αυτή τη σελίδα. \nΕάν απομακρυνθείτε από αυτή τη σελίδα θα χάσετε σας μη αποθηκευμένες αλλαγές",
    pasteDialogCancelButton: "\"Άκυρο\"",
    pasteDialogFormattedCleaned: "Μορφοποίηση &amp; καθαρίζονται",
    pasteDialogFormattedUnclean: "Μορφοποιημένο ακάθαρτο",
    pasteDialogOKButton: "Εισαγωγή",
    pasteDialogPlain: "Απλό κείμενο",
    pasteDialogSource: "Πηγαίος κώδικας",
    pasteDialogTitle: "Πάστα",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Απότυχε να ανακτήσει τις αναθεωρήσεις",
    revisionsApplyButtonDialogCancelButton: "\"Άκυρο\"",
    revisionsApplyButtonDialogOKButton: "Επαναφορά",
    revisionsApplyButtonDialogTitle: "Επιβεβαίωση Επαναφορά",
    revisionsApplyButtonTitle: "Επαναφορά",
    revisionsApplyDialogContent: "Αυτό θα αντικαταστήσει το τρέχον περιεχόμενο με το επιλεγμένο αναθεώρηση.<br>Το τρέχον περιεχόμενο θα προστεθεί ως αναθεώρηση, και θα είναι ορατή στον κατάλογο αναθεωρήσεων για αυτό το μπλοκ.",
    revisionsButtonCurrent: "Ρεύμα",
    revisionsButtonViewDiffText: "Διαφορές",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "\"Άκυρο\"",
    revisionsDialogTitle: "Προβολή περιεχομένου αναθεωρήσεις",
    revisionsDiffButtonDialogCancelButton: "Κλείσιμο",
    revisionsDiffButtonDialogTitle: "Προβολή διαφορές",
    revisionsDiffButtonTitle: "Προβολή διαφορές",
    revisionsLoading: "Φόρτωση αναθεωρήσεις...",
    revisionsNone: "Καμία αναθεώρηση για αυτό το στοιχείο",
    revisionsPreviewButtonTitle: "Προεπισκόπηση",
    revisionsText: "Αναθεωρήσεις",
    revisionsTextEmpty: "Καμία αναθεώρηση",
    revisionsTitle: "",
    rfmClose: "Κλείσιμο",
    rfmContinue: "Συνεχίσει",
    rfmDelete: "Διαγραφή",
    rfmDownload: "Κατεβάσετε",
    rfmFileActions: "Δράσεις",
    rfmFileModificationTime: "Τροποποιηθεί",
    rfmFileName: "Όνομα",
    rfmFileSize: "Μέγεθος",
    rfmFileType: "Τύπος",
    rfmFilteredTotal: "Προβολή {{start}} Ολοκληρώνοντας {{end}}, {{filteredTotal}} αρχείων",
    rfmFirst: "Πρώτη",
    rfmHeadingDirectories: "Κατάλογοι",
    rfmHeadingSearch: "Αναζήτηση",
    rfmHeadingTags: "Ετικέτες",
    rfmHeadingUpload: "Ανεβάστε",
    rfmInsert: "Εισαγωγή",
    rfmLast: "Το τελευταίο",
    rfmSearch: "Πάει",
    rfmTotal: ", φιλτράρεται από {{total}}",
    rfmUpload: "Ανεβάστε",
    rfmUploadBrowse: "Αναζήτηση",
    rfmUploadDrop: "Απόθεση αρχείων εδώ",
    rfmUploadFileRemove: "Κατάργηση",
    rfmView: "Θέα",
    saveJsonFail: "Απέτυχε η αποθήκευση του {{failed}} περιεχομένου ογκόλιθο (ες)",
    saveJsonSaved: "Με επιτυχία αποθηκεύονται {{saved}} περιεχομένου ογκόλιθο (ες).",
    saveNotConfigured: "Αποθήκευση δεν έχει ρυθμιστεί, ή είναι απενεργοποιημένη.",
    saveRestFail: "Απέτυχε η αποθήκευση του {{failed}} περιεχομένου ογκόλιθο (ες).",
    saveRestPartial: "Σώθηκαν {{saved}} από {{failed}} μπλοκ περιεχομένου.",
    saveRestSaved: "Με επιτυχία αποθηκεύονται {{saved}} περιεχομένου ογκόλιθο (ες).",
    saveTitle: "Αποθηκεύσετε περιεχόμενο",
    snippetMenuTitle: "Αποσπάσματα",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Εισάγετε ειδικούς χαρακτήρες",
    specialCharactersHelp: "Κάντε κλικ σε έναν ειδικό χαρακτήρα, να το προσθέσετε. Κάντε κλικ στο κουμπί \"OK\" όταν τελειώσετε να κλείσετε αυτό το παράθυρο διαλόγου",
    specialCharactersTitle: "Εισαγάγετε έναν ειδικό χαρακτήρα",
    statisticsButtonCharacterOverLimit: "χαρακτήρες {{charactersRemaining}} πάνω από το όριο",
    statisticsButtonCharacterRemaining: "χαρακτήρες που απομένουν: {{charactersRemaining}}",
    statisticsButtonCharacters: "οι χαρακτήρες {{characters}}",
    statisticsDialogCharactersOverLimit: "χαρακτήρες {{characters}}, {{charactersRemaining}} πάνω από το προτεινόμενο όριο",
    statisticsDialogCharactersRemaining: "χαρακτήρες {{characters}}, {{charactersRemaining}} που απομένουν",
    statisticsDialogNotTruncated: "Περιεχόμενο δεν θα περικοπούν",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "πρόταση {{sentences}}",
    statisticsDialogSentences: "ποινές {{sentences}}",
    statisticsDialogTitle: "Περιεχομένου στατιστικές",
    statisticsDialogTruncated: "Περιεχόμενο που περιέχει περισσότερο από το {{limit}} χαρακτήρες και ενδέχεται να έχει περικοπεί",
    statisticsDialogWord: "λέξη {{words}}",
    statisticsDialogWords: "λέξεις {{words}}",
    statisticsTitle: "Κάντε κλικ για να δείτε τα στατιστικά στοιχεία",
    tableCreateTitle: "Δημιουργία πίνακα",
    tableDeleteColumnTitle: "Διαγραφή στήλης πίνακα",
    tableDeleteRowTitle: "Διαγραφή γραμμής πίνακα",
    tableInsertColumnTitle: "Εισαγωγή στήλης πίνακα",
    tableInsertRowTitle: "Εισαγωγή γραμμής πίνακα",
    tableMergeCellsTitle: "Συγχώνευση κελιών πίνακα",
    tableSplitCellsTitle: "Διαίρεση κελιών πίνακα",
    tagMenuTagAddress: "Διεύθυνση",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Επικεφαλίδα 1",
    tagMenuTagH2: "Τομέας2",
    tagMenuTagH3: "Κατηγορία 3",
    tagMenuTagH4: "Κατηγορία 4",
    tagMenuTagNA: "Δ\/Υ",
    tagMenuTagP: "Παράγραφο",
    tagMenuTagPre: "Προ-διαμορφωμένη",
    tagMenuTitle: "Αλλαγή στυλ στοιχείο",
    tagTreeElementLink: "Επιλέξτε το στοιχείο {{element}}",
    tagTreeElementTitle: "Κάντε κλικ για να επιλέξετε το περιεχόμενο του στοιχείου \"{{element}}\"",
    tagTreeRoot: "ρίζα",
    tagTreeRootLink: "Επιλέξτε όλα επεξεργάσιμα περιεχόμενο",
    tagTreeRootTitle: "Κάντε κλικ για να επιλέξετε όλο το περιεχόμενο επεξεργάσιμο",
    textBlockQuoteTitle: "Αποκλεισμός προσφοράς",
    textBoldTitle: "Τολμηρή",
    textItalicTitle: "Πλάγια γραφή",
    textSizeDecreaseTitle: "Μείωση μεγέθους κειμένου",
    textSizeIncreaseTitle: "Αύξηση μεγέθους κειμένου",
    textStrikeTitle: "Απεργία με",
    textSubTitle: "Υπο-σενάριο",
    textSuperTitle: "Σούπερ-σενάριο",
    textUnderlineTitle: "Υπογράμμιση",
    unsavedEditWarningText: "Υπάρχουν μη αποθηκευμένες αλλαγές σε αυτή τη σελίδα",
    viewSourceDialogCancelButton: "Κλείσιμο",
    viewSourceDialogOKButton: "Εφαρμόστε πηγαίο κώδικα",
    viewSourceDialogTitle: "Κωδικός προέλευσης περιεχομένου",
    viewSourceTitle: "Προβολή\/επεξεργασία πηγαίου κώδικα"
});