/**
 * @fileOverview Spanish strings file.
 * @license http://www.raptor-editor.com/license
 *
 * @author Francisco Martínez (JnxF), paco.7070@hotmail.com, https://twitter.com/ElJnxF
 */
extendLocale('es', 'Español', {
    alignCenterTitle: "Centrar",
    alignJustifyTitle: "Justificar",
    alignLeftTitle: "Alinear a la Izquierda",
    alignRightTitle: "Alinear a la Derecha",
    cancelDialogCancelButton: "Cerrar",
    cancelDialogContent: "¿Está seguro de que desea detener la edición? ¡Todos los cambios serán perdidos!",
    cancelDialogOKButton: "Aceptar",
    cancelDialogTitle: "Cancel Editing",
    cancelTitle: "Cancel editing",
    classMenuTitle: "Selector de estilo",
    clearFormattingTitle: "Limpiar Formato",
    clickButtonToEditPluginButton: "Haga clic para empezar a editar",
    clickButtonToEditText: "Editar",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatic",
    colorMenuBasicBlack: "Black",
    colorMenuBasicBlue: "Blue",
    colorMenuBasicGreen: "Green",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Purple",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Cambiar el color del texto seleccionado.",
    colorMenuBasicWhite: "White",
    dockToElementTitle: "Dock editor to element",
    dockToScreenTitle: "Dock editor to screen",
    embedDialogCancelButton: "Cancelar",
    embedDialogOKButton: "Incrustar objeto",
    embedDialogTabCode: "Incrustar código",
    embedDialogTabCodeContent: "Pegue el código de embed en el área de texto abajo:",
    embedDialogTabPreview: "Vista previa",
    embedDialogTabPreviewContent: "A continuación se muestra una vista previa de tu objeto incrustado:",
    embedDialogTitle: "Incrustar objeto",
    embedTitle: "Objeto incrustado",
    errorPluginNoName: "Plugin \"{{plugin}}\" is invalid (must have a name property)",
    errorPluginNotObject: "Plugin \"{{plugin}}\" is invalid (must be an object)",
    errorPluginOverride: "Plugin \"{{name}}\" has already been registered, and will be overwritten",
    errorUINoName: "UI \"{{ui}}\" is invalid (must have a name property)",
    errorUINotObject: "UI \"{{ui}}\" is invalid (must be an object)",
    errorUIOverride: "UI \"{{name}}\" has already been registered, and will be overwritten",
    fileManagerDialogTitle: "Administrador de archivos",
    fileManagerTitle: "Administrador de archivos",
    floatLeftTitle: "Flotar Imagen a la Izquierda",
    floatNoneTitle: "Remove image align",
    floatRightTitle: "Flotar Imagen a la Derecha",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic sin",
    fontFamilyMenuFontCourier: "Nuevo mensajero",
    fontFamilyMenuFontDefault: "Fuente predeterminada",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Impacto",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Elija la fuente",
    guidesTitle: "Mostrar Guías",
    historyRedoTitle: "Redo",
    historyUndoTitle: "Undo",
    hrCreateTitle: "Insertar la regla Horizontal",
    imageResizeButtonDialogCancelButton: "Cancelar",
    imageResizeButtonDialogHeight: "Altura de la imagen",
    imageResizeButtonDialogHeightPlaceHolder: "Altura",
    imageResizeButtonDialogOKButton: "Cambiar el tamaño de",
    imageResizeButtonDialogTitle: "Redimensionar imagen",
    imageResizeButtonDialogWidth: "Ancho de imagen",
    imageResizeButtonDialogWidthPlaceHolder: "Ancho",
    imageResizeButtonText: "Redimensionar imagen",
    insertFileDialogCancelButton: "Cancelar",
    insertFileDialogOKButton: "Insertar archivo",
    insertFileNameLabel: "Nombre de archivo",
    insertFileNamePlaceHolder: "Nombre de archivo...",
    insertFileTitle: "Insertar archivo",
    insertFileURLLabel: "URL del archivo",
    insertFileURLPlaceHolder: "URL del archivo...",
    languageMenuTitle: "Cambiar idioma",
    linkCreateDialogCancelButton: "Cancelar",
    linkCreateDialogMenuHeader: "Elija un tipo de enlace",
    linkCreateDialogOKButton: "Introduzca el enlace",
    linkCreateDialogTitle: "Introduzca el enlace",
    linkCreateTitle: "Introduzca el enlace",
    linkDialogCancelButton: "Cancelar",
    linkDialogMenuHeader: "Escoja un tipo de enlace:",
    linkDialogOKButton: "Insertar Enlace",
    linkDialogTitle: "Insertar Enlace",
    linkRemoveTitle: "Quitar vínculo",
    linkTypeDocumentHeader: "Enlace a un documento o de otro tipo de archivo",
    linkTypeDocumentInfo: "<h2>¿No estoy seguro qué poner en la caja de arriba?<\/h2><ol>    <li>Asegúrese de que el archivo se ha subido a su sitio Web.<\/li>    <li>Abra el archivo en su navegador.<\/li>    <li>Copiar la URL del archivo de la barra de direcciones de tu navegador y pegarlo en el cuadro de arriba.<\/li><\/ol>",
    linkTypeDocumentLabel: "Documento u otro archivo",
    linkTypeDocumentLocationLabel: "Ubicación:",
    linkTypeDocumentLocationPlaceHolder: "Introduzca una URL",
    linkTypeDocumentNewWindowHeader: "Nueva ventana",
    linkTypeDocumentNewWindowLabel: "Marque esta casilla para tener el archivo abierto en una nueva ventana\/pestaña del navegador.",
    linkTypeEmailHeader: "Enlazar a una dirección de correo electrónico",
    linkTypeEmailLabel: "Dirección de correo electrónico",
    linkTypeEmailSubjectLabel: "Sujeto (opcional):",
    linkTypeEmailSubjectPlaceHolder: "Introduzca un sujeto",
    linkTypeEmailToLabel: "Correo electrónico:",
    linkTypeEmailToPlaceHolder: "Introduzca una dirección de correo electrónico",
    linkTypeExternalHeader: "Link to a page on another website",
    linkTypeExternalInfo: "<h2>¿No está seguro de qué poner en la caja anterior?<\/h2><ol>    <li>Busque la página web a la que desee enlazar<\/li>    <li>Copie la dirección web desde la barra de dirección de su navegador y péguela en la caja superior.<\/li><\/ol>",
    linkTypeExternalLabel: "Page on another website",
    linkTypeExternalLocationLabel: "Localización",
    linkTypeExternalLocationPlaceHolder: "Introduzca una URL",
    linkTypeExternalNewWindowHeader: "Nueva ventana",
    linkTypeExternalNewWindowLabel: "Marque esta casilla para que el enlace se abra en una nueva ventana.",
    linkTypeInternalHeader: "Link to a page on this website",
    linkTypeInternalInfo: "<h2>¿No está seguro de qué poner en la caja anterior?<\/h2><ol>    <li>Find the page on this site link to.<\/li>    <li>Copy the web address from your browser's address bar, excluding \"{{domain}}\" and paste it into the box above.<\/li><\/ol>",
    linkTypeInternalLabel: "Page on this website",
    linkTypeInternalLocationLabel: "Localización",
    linkTypeInternalLocationPlaceHolder: "Introducir un identificador URI",
    linkTypeInternalNewWindowHeader: "Nueva ventana",
    linkTypeInternalNewWindowLabel: "Marque esta casilla para que el enlace se abra en una nueva ventana.",
    listOrderedTitle: "Lista Ordenada",
    listUnorderedTitle: "Lista Desordenada",
    logoTitle: "Saber más sobre el editor WYSIWYG Raptor",
    navigateAway: "\nAllí están sin guardar los cambios en esta página. \nSi usted navegar lejos esta página perderá los cambios no guardados",
    pasteDialogCancelButton: "Cancelar",
    pasteDialogFormattedCleaned: "Formatear y limpiar",
    pasteDialogFormattedUnclean: "Formato inmundo",
    pasteDialogOKButton: "Insertar",
    pasteDialogPlain: "Texto sin formato",
    pasteDialogSource: "Código fuente",
    pasteDialogTitle: "Pasta",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "No se pudo recuperar revisiones",
    revisionsApplyButtonDialogCancelButton: "Cancelar",
    revisionsApplyButtonDialogOKButton: "Rollback",
    revisionsApplyButtonDialogTitle: "Confirmación de reversión",
    revisionsApplyButtonTitle: "Rollback",
    revisionsApplyDialogContent: "Esto reemplazará el contenido actual con la revisión seleccionada.<br>El contenido actual se añadirá como revisión y será visible en la lista de revisiones de este bloque.",
    revisionsButtonCurrent: "Corriente",
    revisionsButtonViewDiffText: "Diferencias",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Cancelar",
    revisionsDialogTitle: "Ver contenidas revisiones",
    revisionsDiffButtonDialogCancelButton: "Cerrar",
    revisionsDiffButtonDialogTitle: "Diferencias de opinión",
    revisionsDiffButtonTitle: "Diferencias de opinión",
    revisionsLoading: "Cargando las revisiones...",
    revisionsNone: "No hay revisiones para este elemento",
    revisionsPreviewButtonTitle: "Vista previa",
    revisionsText: "Revisiones",
    revisionsTextEmpty: "No hay revisiones",
    revisionsTitle: "",
    rfmClose: "Cerrar",
    rfmContinue: "Continuar",
    rfmDelete: "Borrar",
    rfmDownload: "Descargar",
    rfmFileActions: "Acciones",
    rfmFileModificationTime: "Modificado",
    rfmFileName: "Nombre",
    rfmFileSize: "Tamaño",
    rfmFileType: "Tipo",
    rfmFilteredTotal: "{{start}} muestra acabar {{end}} {{filteredTotal}} archivos",
    rfmFirst: "Primero",
    rfmHeadingDirectories: "Directorios",
    rfmHeadingSearch: "Búsqueda de",
    rfmHeadingTags: "Etiquetas",
    rfmHeadingUpload: "Subir",
    rfmInsert: "Insertar",
    rfmLast: "Duran",
    rfmSearch: "Ir",
    rfmTotal: ", filtrado de {{total}}",
    rfmUpload: "Subir",
    rfmUploadBrowse: "Browse",
    rfmUploadDrop: "Soltar archivos aquí",
    rfmUploadFileRemove: "Quitar",
    rfmView: "Vista",
    saveJsonFail: "No se pudo guardar bloques contenidos {{failed}}",
    saveJsonSaved: "Guardado correctamente bloques contenidos {{saved}}.",
    saveNotConfigured: "Guardar no se ha configurado, o está deshabilitada.",
    saveRestFail: "Error al guardar bloques contenidos {{failed}}.",
    saveRestPartial: "Salvado {{saved}} {{failed}} bloques de contenido.",
    saveRestSaved: "Guardado correctamente bloques contenidos {{saved}}.",
    saveTitle: "Guardar",
    snippetMenuTitle: "Fragmentos de código",
    specialCharactersDialogOKButton: "Vale",
    specialCharactersDialogTitle: "Insertar caracteres especiales",
    specialCharactersHelp: "Haga clic en un carácter especial para añadirla. Haga clic en \"Aceptar\" cuando se hace para cerrar este cuadro de diálogo",
    specialCharactersTitle: "Insertar un carácter especial",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} carácter(es) sobre el límite",
    statisticsButtonCharacterRemaining: "Queda(n) {{charactersRemaining}} carácter(es)",
    statisticsButtonCharacters: "{{characters}} carácteres",
    statisticsDialogCharactersOverLimit: "{{characters}} carácter(es), {{charactersRemaining}} sobre el límite recomendado",
    statisticsDialogCharactersRemaining: "{{characters}} carácter(es), queda(n) {{charactersRemaining}}",
    statisticsDialogNotTruncated: "El contenido no será truncado",
    statisticsDialogOKButton: "Aceptar",
    statisticsDialogSentence: "{{sentences}} sentence",
    statisticsDialogSentences: "{{sentences}} oraciones",
    statisticsDialogTitle: "Contenidos Estadísticos",
    statisticsDialogTruncated: "El contenido contiene más de {{limit}} carácteres y debe ser truncado",
    statisticsDialogWord: "{{words}} palabra",
    statisticsDialogWords: "{{words}} palabras",
    statisticsTitle: "Haga clic para ver las estadísticas",
    tableCreateTitle: "Create table",
    tableDeleteColumnTitle: "Delete table column",
    tableDeleteRowTitle: "Delete table row",
    tableInsertColumnTitle: "Insert table column",
    tableInsertRowTitle: "Insert table row",
    tableMergeCellsTitle: "Combinar celdas de una tabla",
    tableSplitCellsTitle: "Dividir celdas de tabla",
    tagMenuTagAddress: "Dirección",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Encabezado&nbsp;1",
    tagMenuTagH2: "Encabezado&nbsp;2",
    tagMenuTagH3: "Encabezado&nbsp;3",
    tagMenuTagH4: "Rúbrica 4",
    tagMenuTagNA: false,
    tagMenuTagP: "Párrafo",
    tagMenuTagPre: "Preformateados",
    tagMenuTitle: "Change element style",
    tagTreeElementLink: "Seleccionar el elemento {{element}}",
    tagTreeElementTitle: "Haga clic para selecionar el contenido del elemento \"{{element}}\"",
    tagTreeRoot: "orígen",
    tagTreeRootLink: "Seleccionar todo el contenido editable",
    tagTreeRootTitle: "Haga clic para seleccionar todo el contenido editable",
    textBlockQuoteTitle: "Cita en bloque",
    textBoldTitle: "Negrita",
    textItalicTitle: "Cursiva",
    textSizeDecreaseTitle: "Disminuir el tamaño del texto",
    textSizeIncreaseTitle: "Aumentar tamaño del texto",
    textStrikeTitle: "Tachado",
    textSubTitle: "Subíndice",
    textSuperTitle: "Superíndice",
    textUnderlineTitle: "Subrayar",
    unsavedEditWarningText: "Hay cambios sin guardar en esta página.",
    viewSourceDialogCancelButton: "Cerrar",
    viewSourceDialogOKButton: "Aplicar Fuente",
    viewSourceDialogTitle: "Content source code",
    viewSourceTitle: "Ver \/ Editar Código Fuente"
});
