/**
 * @fileOverview Estonian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('et', 'Eesti', {
    alignCenterTitle: "Joonda tekst keskele",
    alignJustifyTitle: "Teksti joondamine õigustada",
    alignLeftTitle: "Joonda tekst vasakule",
    alignRightTitle: "Joonda tekst paremale",
    cancelDialogCancelButton: "Jätka redigeerimist",
    cancelDialogContent: "Kas kindlasti redigeerimise tühistada? Kõik muudatused lähevad kaotsi!",
    cancelDialogOKButton: "Tühista redigeerimine",
    cancelDialogTitle: "Tühista redigeerimine",
    cancelTitle: "Tühista redigeerimine",
    classMenuTitle: "Stiili valija",
    clearFormattingTitle: "Eemalda vorming",
    clickButtonToEditText: "Redigeeri",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automaatne",
    colorMenuBasicBlack: "Must",
    colorMenuBasicBlue: "Sinine",
    colorMenuBasicGreen: "Roheline",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Lilla",
    colorMenuBasicRed: "Punane",
    colorMenuBasicTitle: "Teksti värvi muutmine",
    colorMenuBasicWhite: "Valge",
    dockToElementTitle: "Elemendi toimetaja Doki\/Doki lahti",
    dockToScreenTitle: "Doki\/lahtidokkimine toimetaja kuvale",
    embedDialogCancelButton: "Loobu",
    embedDialogOKButton: "Embed objekt",
    embedDialogTabCode: "Integreeritud kood",
    embedDialogTabCodeContent: "Embed koodeksi kleepige tekst ala allpool:",
    embedDialogTabPreview: "Eelvaade",
    embedDialogTabPreviewContent: "Allpool kuvatakse eelvaade teie manusobjekti:",
    embedDialogTitle: "Embed objekt",
    embedTitle: "Embed objekt",
    errorUINoName: "UI \"{{ui}}\" ei sobi (peab olema nime atribuut)",
    errorUINotObject: "UI \"{{ui}}\" ei sobi (peab olema objekt)",
    errorUIOverride: "UI \"{{name}}\" on juba registreeritud ja kirjutatakse",
    fileManagerDialogTitle: "Failihaldur",
    fileManagerTitle: "Failihaldur",
    floatLeftTitle: "Joonda vasakule pildi",
    floatNoneTitle: "Eemalda foto joondamine",
    floatRightTitle: "Joonda paremale pilt",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Koomiline ilma",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Vaikefont",
    fontFamilyMenuFontGeorgia: "Gruusia",
    fontFamilyMenuFontImpact: "Mõju",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Korda uus Rooma",
    fontFamilyMenuTitle: "Teie fondi valimine",
    guidesTitle: "Kuva element juhendid",
    historyRedoTitle: "Tee uuesti",
    historyUndoTitle: "Võta tagasi",
    hrCreateTitle: "Sisesta horisontaalne joonlaud",
    imageResizeButtonDialogCancelButton: "Loobu",
    imageResizeButtonDialogHeight: "Pildi kõrgus",
    imageResizeButtonDialogHeightPlaceHolder: "Kõrgus",
    imageResizeButtonDialogOKButton: "Suuruse muutmine",
    imageResizeButtonDialogTitle: "Pildi suuruse muutmine",
    imageResizeButtonDialogWidth: "Pildi laius",
    imageResizeButtonDialogWidthPlaceHolder: "Laius",
    imageResizeButtonText: "Pildi suuruse muutmine",
    insertFileDialogCancelButton: "Loobu",
    insertFileDialogOKButton: "Faili lisamine",
    insertFileNameLabel: "Faili nimi",
    insertFileNamePlaceHolder: "Faili nimi...",
    insertFileTitle: "Faili lisamine",
    insertFileURLLabel: "Faili URL",
    insertFileURLPlaceHolder: "Faili URL...",
    languageMenuTitle: "Keele muutmine",
    linkCreateDialogCancelButton: "Loobu",
    linkCreateDialogMenuHeader: "Valige seose tüüp",
    linkCreateDialogOKButton: "Lingi lisamine",
    linkCreateDialogTitle: "Lingi lisamine",
    linkCreateTitle: "Lingi lisamine",
    linkRemoveTitle: "Eemalda Link",
    linkTypeDocumentHeader: "Link dokumendi või muu fail",
    linkTypeDocumentInfo: "<h2>Ei ole kindel, mida teha eespool kasti?<\/h2><ol>    <li>Tagada faili veebisaidile üles laadida.<\/li>    <li>Üleslaaditud faili avada brauseris.<\/li>    <li>Kopeerida selle faili URL brauseri aadressiribale ja kleepige see kasti eespool.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumendi või muu fail",
    linkTypeDocumentLocationLabel: "Asukoht:",
    linkTypeDocumentLocationPlaceHolder: "Sisestage URL",
    linkTypeDocumentNewWindowHeader: "Uues aknas",
    linkTypeDocumentNewWindowLabel: "Märkige see ruut, et avage uus brauseri aken\/kaart faili.",
    linkTypeEmailHeader: "Link e-posti aadress",
    linkTypeEmailLabel: "E-posti aadress",
    linkTypeEmailSubjectLabel: "Teema (kohustuslik):",
    linkTypeEmailSubjectPlaceHolder: "Sisestage teema",
    linkTypeEmailToLabel: "E-post:",
    linkTypeEmailToPlaceHolder: "Sisestage e-posti aadress",
    linkTypeExternalHeader: "Lehe teisele veebilehele linkimine",
    linkTypeExternalInfo: "<h2>Ei ole kindel, mida teha eespool kasti?<\/h2><ol>    <li>Leida lehele soovite linkida veebis.<\/li>    <li>Kopeeri aadress oma brauseri aadressiribale ja kleepige see kasti eespool.<\/li><\/ol>",
    linkTypeExternalLabel: "Lehe teisele lehele",
    linkTypeExternalLocationLabel: "Asukoht:",
    linkTypeExternalLocationPlaceHolder: "Sisestage URL",
    linkTypeExternalNewWindowHeader: "Uues aknas",
    linkTypeExternalNewWindowLabel: "See märkeruut on avage uus brauseri aken\/kaart link.",
    linkTypeInternalHeader: "Link lehele sellel veebilehel",
    linkTypeInternalInfo: "<h2>Ei ole kindel, mida teha eespool kasti?<\/h2><ol>    <li>Leida lehe selle saidi link.<\/li>    <li>Kopeeri aadress oma brauseri aadressiribale, välja arvatud \"{{domain}}\" ja kleepige see kasti eespool.<\/li><\/ol>",
    linkTypeInternalLabel: "Lehekülje sellel veebilehel",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Sisestage URI",
    linkTypeInternalNewWindowHeader: "Uues aknas",
    linkTypeInternalNewWindowLabel: "See märkeruut on avage uus brauseri aken\/kaart link.",
    listOrderedTitle: "Järjestatud loend",
    listUnorderedTitle: "Järjestamata loend",
    logoTitle: "Rohkem teavet Raptor WYSIWYG Editor",
    navigateAway: "\nSellel lehel on salvestamata muutusi. \nSellelt lehelt lahkumisel te kaotate salvestamata muutused",
    pasteDialogCancelButton: "Loobu",
    pasteDialogFormattedCleaned: "Vormindatud ja puhastada",
    pasteDialogFormattedUnclean: "Vormindatud ebapuhas",
    pasteDialogOKButton: "Lisamine",
    pasteDialogPlain: "Lihttekst",
    pasteDialogSource: "Lähtekoodi",
    pasteDialogTitle: "Kleebi",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Ei saanud tuua parandused",
    revisionsApplyButtonDialogCancelButton: "Loobu",
    revisionsApplyButtonDialogOKButton: "Tagasipööramine",
    revisionsApplyButtonDialogTitle: "Tagasipööramise kinnitus",
    revisionsApplyButtonTitle: "Tagasipööramine",
    revisionsApplyDialogContent: "See asendab praeguse sisu valitud läbivaatamist.<br>Praeguse sisu lisatakse muutmisena ja paranduste loendis selle bloki jaoks nähtav.",
    revisionsButtonCurrent: "Praegune",
    revisionsButtonViewDiffText: "Erinevused",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Loobu",
    revisionsDialogTitle: "Kuva sisu parandused",
    revisionsDiffButtonDialogCancelButton: "Sulgege",
    revisionsDiffButtonDialogTitle: "Vaata erinevused",
    revisionsDiffButtonTitle: "Vaata erinevused",
    revisionsLoading: "Peale parandusi...",
    revisionsNone: "Selle elemendi parandusi",
    revisionsPreviewButtonTitle: "Eelvaade",
    revisionsText: "Parandused",
    revisionsTextEmpty: "Parandusi",
    revisionsTitle: "",
    rfmClose: "Sulgege",
    rfmContinue: "Jätkata",
    rfmDelete: "Kustuta",
    rfmDownload: "Lae",
    rfmFileActions: "Tegevused",
    rfmFileModificationTime: "Muudetud",
    rfmFileName: "Nimi",
    rfmFileSize: "Suurus",
    rfmFileType: "Tüüp",
    rfmFilteredTotal: "Näitamist {{start}} {{end}} {{filteredTotal}} faili",
    rfmFirst: "Esimese",
    rfmHeadingDirectories: "Kataloogid",
    rfmHeadingSearch: "Otsi hotelle",
    rfmHeadingTags: "Sildid",
    rfmHeadingUpload: "Lisamise kuupäev",
    rfmInsert: "Lisamine",
    rfmLast: "Kesta",
    rfmSearch: "Mine",
    rfmTotal: ", filtreeritud {{total}}",
    rfmUpload: "Lisamise kuupäev",
    rfmUploadBrowse: "Sirvi",
    rfmUploadDrop: "Failid siin",
    rfmUploadFileRemove: "Eemaldamine",
    rfmView: "Vaade",
    saveJsonFail: "{{failed}} sisu numbriplokki\/plokke salvestamine nurjus",
    saveJsonSaved: "Edukalt salvestatud {{saved}} sisu numbriplokki\/plokke.",
    saveNotConfigured: "Salvesta pole konfigureeritud või on keelatud.",
    saveRestFail: "{{failed}} sisu numbriplokki\/plokke salvestamine nurjus.",
    saveRestPartial: "Salvestada {{saved}} {{failed}} sisu plokkidest välja.",
    saveRestSaved: "Edukalt salvestatud {{saved}} sisu numbriplokki\/plokke.",
    saveTitle: "Salvesta sisu",
    snippetMenuTitle: "Pikad",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Erimärkide lisamine",
    specialCharactersHelp: "Klõpsake erimärki lisada. Vajuta \"OK\" kui teha selle dialoogi sulgemiseks",
    specialCharactersTitle: "Erimärgi lisamine",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} märki üle piiri",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} märki jäänud",
    statisticsButtonCharacters: "{{characters}} märki",
    statisticsDialogCharactersOverLimit: "{{characters}} märki, {{charactersRemaining}} üle soovitatava piiri",
    statisticsDialogCharactersRemaining: "{{characters}}, {{charactersRemaining}} allesjäänud märke",
    statisticsDialogNotTruncated: "Sisu ei ole kärbitud",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "{{sentences}} lause",
    statisticsDialogSentences: "{{sentences}} laused",
    statisticsDialogTitle: "Sisu statistika",
    statisticsDialogTruncated: "Sisu sisaldab kuni {{limit}} märki ja võib olla kärbitud",
    statisticsDialogWord: "{{words}} Wordi",
    statisticsDialogWords: "{{words}} sõnad",
    statisticsTitle: "Statistika kuvamiseks klõpsake",
    tableCreateTitle: "Tabeli loomine",
    tableDeleteColumnTitle: "Kustuta tabeli veerg",
    tableDeleteRowTitle: "Kustuta tabeli rida",
    tableInsertColumnTitle: "Lisa tabeli veerg",
    tableInsertRowTitle: "Lisa tabeli rida",
    tableMergeCellsTitle: "Ühenda tabeli lahtrid",
    tableSplitCellsTitle: "Tükelda tabeli lahtrid",
    tagMenuTagAddress: "Aadress",
    tagMenuTagDiv: "DIV",
    tagMenuTagH1: "Rubriigi 1",
    tagMenuTagH2: "Rubriigi 2",
    tagMenuTagH3: "Rubriik 3",
    tagMenuTagH4: "Rubriik 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Lõikes",
    tagMenuTagPre: "Eelvormindatud",
    tagMenuTitle: "Elemendi laadi muutmine",
    tagTreeElementLink: "{{element}} elemendi valimine",
    tagTreeElementTitle: "Märkige \"{{element}}\" elemendi sisu",
    tagTreeRoot: "juur",
    tagTreeRootLink: "Valige muudetav sisu",
    tagTreeRootTitle: "Valige muudetav sisu",
    textBlockQuoteTitle: "Block tsitaat",
    textBoldTitle: "Paks kiri",
    textItalicTitle: "Kursiiv",
    textSizeDecreaseTitle: "Vähenda teksti",
    textSizeIncreaseTitle: "Suurenda teksti",
    textStrikeTitle: "Läbikriipsutus",
    textSubTitle: "Sub skript",
    textSuperTitle: "Super-skript",
    textUnderlineTitle: "Allakriipsutus",
    unsavedEditWarningText: "Sellel lehel on salvestamata muutusi",
    viewSourceDialogCancelButton: "Sulgege",
    viewSourceDialogOKButton: "Rakenda lähtekoodi",
    viewSourceDialogTitle: "Sisuallika kood",
    viewSourceTitle: "Kuva\/Redigeeri lähtekoodi"
});