/**
 * @fileOverview Finnish strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('fi', 'suomi', {
    alignCenterTitle: "Tasaa teksti keskelle",
    alignJustifyTitle: "Tasaa teksti perustella",
    alignLeftTitle: "Tasaa teksti vasemmalle",
    alignRightTitle: "Tasaa teksti oikealle",
    cancelDialogCancelButton: "Jatka muokkaamista",
    cancelDialogContent: "Oletko varma, että haluat peruuttaa muokkaamisen? Kaikki muutokset menetetään!",
    cancelDialogOKButton: "Peruuttaa muokkaamisen",
    cancelDialogTitle: "Peruuttaa muokkaamisen",
    cancelTitle: "Peruuttaa muokkaamisen",
    classMenuTitle: "Tyylin valinta",
    clearFormattingTitle: "Poista muotoilut",
    clickButtonToEditText: "Muokkaa",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automaattinen",
    colorMenuBasicBlack: "Musta",
    colorMenuBasicBlue: "Sininen",
    colorMenuBasicGreen: "Vihreä",
    colorMenuBasicGrey: "Harmaa",
    colorMenuBasicOrange: "Oranssi",
    colorMenuBasicPurple: "Violetti",
    colorMenuBasicRed: "Punainen",
    colorMenuBasicTitle: "Tekstivärin muuttaminen",
    colorMenuBasicWhite: "Valkoinen",
    dockToElementTitle: "Osa telakka\/irrottaa editor",
    dockToScreenTitle: "Editorin näytön Dock irrottaa",
    embedDialogCancelButton: "Peruuta",
    embedDialogOKButton: "Objektin upottaminen",
    embedDialogTabCode: "Upota koodi",
    embedDialogTabCodeContent: "Liitä upottaa koodi tekstin alapuolella:",
    embedDialogTabPreview: "Esikatselu",
    embedDialogTabPreviewContent: "Upotetun objektin esikatselu näkyy alla:",
    embedDialogTitle: "Objektin upottaminen",
    embedTitle: "Objektin upottaminen",
    errorUINoName: "UI \"{{ui}}\" on virheellinen (on oltava name-ominaisuus)",
    errorUINotObject: "UI \"{{ui}}\" on virheellinen (on oltava objektin)",
    errorUIOverride: "UI \"{{name}}\" on jo rekisteröity, ja se korvataan",
    fileManagerDialogTitle: "Tiedostonhallinta",
    fileManagerTitle: "Tiedostonhallinta",
    floatLeftTitle: "Tasaa kuva vasemmalle",
    floatNoneTitle: "Poistaa kuvan tasaaminen",
    floatRightTitle: "Tasaa kuva oikealla",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Sarjakuva ilman",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Oletusfontti",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Vaikutus",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Kertaa New Roman",
    fontFamilyMenuTitle: "Valitse fontti",
    guidesTitle: "Näytä elementti oppaat",
    historyRedoTitle: "Tee uudelleen",
    historyUndoTitle: "Kumoa",
    hrCreateTitle: "Lisää vaakaviiva",
    imageResizeButtonDialogCancelButton: "Peruuta",
    imageResizeButtonDialogHeight: "Kuvan korkeus",
    imageResizeButtonDialogHeightPlaceHolder: "Korkeus",
    imageResizeButtonDialogOKButton: "Muuta kokoa",
    imageResizeButtonDialogTitle: "Muuta kuvan kokoa",
    imageResizeButtonDialogWidth: "Kuvan leveys",
    imageResizeButtonDialogWidthPlaceHolder: "Leveys",
    imageResizeButtonText: "Muuta kuvan kokoa",
    insertFileDialogCancelButton: "Peruuta",
    insertFileDialogOKButton: "Lisää tiedosto",
    insertFileNameLabel: "Tiedostonimi",
    insertFileNamePlaceHolder: "Tiedostonimi...",
    insertFileTitle: "Lisää tiedosto",
    insertFileURLLabel: "Tiedoston URL",
    insertFileURLPlaceHolder: "Tiedoston URL...",
    languageMenuTitle: "Vaihda kieli",
    linkCreateDialogCancelButton: "Peruuta",
    linkCreateDialogMenuHeader: "Valitse linkkityyppi",
    linkCreateDialogOKButton: "Lisää linkki",
    linkCreateDialogTitle: "Lisää linkki",
    linkCreateTitle: "Lisää linkki",
    linkRemoveTitle: "Poista linkki",
    linkTypeDocumentHeader: "Linkittää asiakirjan tai muun tiedoston",
    linkTypeDocumentInfo: "<h2>Ole varma, mitä laittaa yllä olevaan ruutuun?<\/h2><ol>    <li>Varmista tiedoston ladata sivustoosi.<\/li>    <li>Avaa ylöslataamasi tiedosto selaimessa.<\/li>    <li>Kopioi tiedoston URL-osoite selaimen osoiteriville ja liitä yllä olevassa ruudussa.<\/li><\/ol>",
    linkTypeDocumentLabel: "Asiakirjan tai muun tiedoston",
    linkTypeDocumentLocationLabel: "Sijainti:",
    linkTypeDocumentLocationPlaceHolder: "Kirjoita URL-osoite",
    linkTypeDocumentNewWindowHeader: "Uusi ikkuna",
    linkTypeDocumentNewWindowLabel: "Valitse tämä valintaruutu tiedosto on avattu uusi selaimen ikkunassa\/välilehdellä.",
    linkTypeEmailHeader: "Linkki sähköpostiosoitteeseen",
    linkTypeEmailLabel: "Sähköpostiosoite",
    linkTypeEmailSubjectLabel: "Aihe (valinnainen):",
    linkTypeEmailSubjectPlaceHolder: "Kirjoita aihe",
    linkTypeEmailToLabel: "Sähköposti:",
    linkTypeEmailToPlaceHolder: "Astua email kohdistaa",
    linkTypeExternalHeader: "Linkki sivu toisella sivustolla",
    linkTypeExternalInfo: "<h2>Ole varma, mitä laittaa yllä olevaan ruutuun?<\/h2><ol>    <li>Löydä sivua haluat linkittää Web.<\/li>    <li>Kopioi selaimen osoiteriviltä web-osoite ja liitä se yllä olevassa ruudussa.<\/li><\/ol>",
    linkTypeExternalLabel: "Sivu toisella sivustolla",
    linkTypeExternalLocationLabel: "Sijainti:",
    linkTypeExternalLocationPlaceHolder: "Kirjoita URL-osoite",
    linkTypeExternalNewWindowHeader: "Uusi ikkuna",
    linkTypeExternalNewWindowLabel: "Tämä ruutu on linkki avaa uuden selaimen ikkunassa\/välilehdellä.",
    linkTypeInternalHeader: "Linkki sivu tällä sivustolla",
    linkTypeInternalInfo: "<h2>Ole varma, mitä laittaa yllä olevaan ruutuun?<\/h2><ol>    <li>Löydä sivua tähän saittilinkkiin.<\/li>    <li>Kopioi web-osoite selaimen osoite Baari, lukuun ottamatta \"{{domain}}\" ja liitä se yllä olevassa ruudussa.<\/li><\/ol>",
    linkTypeInternalLabel: "Sivun tällä sivustolla",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Kirjoita URI",
    linkTypeInternalNewWindowHeader: "Uusi ikkuna",
    linkTypeInternalNewWindowLabel: "Tämä ruutu on linkki avaa uuden selaimen ikkunassa\/välilehdellä.",
    listOrderedTitle: "Järjestetty luettelo",
    listUnorderedTitle: "Järjestämätön lista",
    logoTitle: "Saat lisätietoja Raptor WYSIWYG-editorista",
    navigateAway: "\nTällä sivulla on tallentamattomia muutoksia. \nJos siirryt pois tältä sivulta menetät tallentamattomat muutokset",
    pasteDialogCancelButton: "Peruuta",
    pasteDialogFormattedCleaned: "Muotoiltu &amp; puhdistaa",
    pasteDialogFormattedUnclean: "Muotoiltu epäpuhdas",
    pasteDialogOKButton: "Lisää",
    pasteDialogPlain: "Vain teksti",
    pasteDialogSource: "Lähdekoodi",
    pasteDialogTitle: "Liitä",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Ei voitu hakea muutoksia",
    revisionsApplyButtonDialogCancelButton: "Peruuta",
    revisionsApplyButtonDialogOKButton: "Palautus",
    revisionsApplyButtonDialogTitle: "Peruutuksen vahvistus",
    revisionsApplyButtonTitle: "Palautus",
    revisionsApplyDialogContent: "Tämä korvaa nykyisen sisällön valitussa versiossa.<br>Nykyistä sisältöä lisätään tarkistamisesta ja näkevät tämän lohkon versiot-luettelosta.",
    revisionsButtonCurrent: "Nykyinen",
    revisionsButtonViewDiffText: "Erot",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Peruuta",
    revisionsDialogTitle: "Näytä sisältö versiot",
    revisionsDiffButtonDialogCancelButton: "Sulje",
    revisionsDiffButtonDialogTitle: "Katso erot",
    revisionsDiffButtonTitle: "Katso erot",
    revisionsLoading: "Ladataan muutoksia...",
    revisionsNone: "Minkäänlaista tarkistusta ei tälle elementille",
    revisionsPreviewButtonTitle: "Esikatselu",
    revisionsText: "Muutokset",
    revisionsTextEmpty: "Ei muutoksia",
    revisionsTitle: "",
    rfmClose: "Sulje",
    rfmContinue: "Jatka",
    rfmDelete: "Poista",
    rfmDownload: "Lataa",
    rfmFileActions: "Toiminnot",
    rfmFileModificationTime: "Muutettu",
    rfmFileName: "Nimi",
    rfmFileSize: "Kokoa",
    rfmFileType: "Tyyppi",
    rfmFilteredTotal: "Osoittaminen {{start}} lopettamaan {{end}} {{filteredTotal}} tiedostot",
    rfmFirst: "Ensimmäinen",
    rfmHeadingDirectories: "Hakemistot",
    rfmHeadingSearch: "Etsi",
    rfmHeadingTags: "Tunnisteet",
    rfmHeadingUpload: "Lataa",
    rfmInsert: "Lisää",
    rfmLast: "Viimeksi",
    rfmSearch: "Go",
    rfmTotal: ", suodatettu {{total}}",
    rfmUpload: "Lataa",
    rfmUploadBrowse: "Selaa",
    rfmUploadDrop: "Pudota tiedostoja tähän.",
    rfmUploadFileRemove: "Poista",
    rfmView: "Näkymä",
    saveJsonFail: "Ei voi tallentaa {{failed}} sisältö vioittuneiden lohkojen uudelleenmäärittäminen",
    saveJsonSaved: "Tallennettu {{saved}} sisältö vioittuneiden lohkojen uudelleenmäärittäminen.",
    saveNotConfigured: "Tallenna ei ole määritetty, tai se on poistettu käytöstä.",
    saveRestFail: "{{failed}} sisältö vioittuneiden lohkojen uudelleenmäärittäminen tallentaminen epäonnistui.",
    saveRestPartial: "Tallennettu {{saved}} {{failed}} sisältö blocks pois.",
    saveRestSaved: "Tallennettu {{saved}} sisältö vioittuneiden lohkojen uudelleenmäärittäminen.",
    saveTitle: "Tallenna sisältö",
    snippetMenuTitle: "Katkelmia",
    specialCharactersDialogOKButton: "Okei",
    specialCharactersDialogTitle: "Lisätä erikoismerkkejä",
    specialCharactersHelp: "Napsauta Lisää erikoismerkki. Klikkaa \"OK\" Kun olet valmis tämän valintaikkunan voi sulkea",
    specialCharactersTitle: "Erikoismerkin lisääminen",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} merkkiä yli rajan",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} merkkiä jäljellä",
    statisticsButtonCharacters: "{{characters}} merkkiä",
    statisticsDialogCharactersOverLimit: "{{characters}} merkkiä {{charactersRemaining}} yli Suositellut raja",
    statisticsDialogCharactersRemaining: "{{characters}} {{charactersRemaining}} merkkiä jäljellä",
    statisticsDialogNotTruncated: "Sisältö ei ole katkaistu",
    statisticsDialogOKButton: "Okei",
    statisticsDialogSentence: "{{sentences}} lause",
    statisticsDialogSentences: "{{sentences}} lauseita",
    statisticsDialogTitle: "Sisältö tilastot",
    statisticsDialogTruncated: "Sisältö sisältää enintään {{limit}} merkkiä ja lyhennetään",
    statisticsDialogWord: "{{words}} sana",
    statisticsDialogWords: "{{words}} sanoja",
    statisticsTitle: "Näytä tilastot napsauttamalla tätä",
    tableCreateTitle: "Taulukon luominen",
    tableDeleteColumnTitle: "Poista sarakkeesta",
    tableDeleteRowTitle: "Poista taulukkorivi",
    tableInsertColumnTitle: "Lisää taulukon sarake",
    tableInsertRowTitle: "Lisää taulukkorivi",
    tableMergeCellsTitle: "Taulukkosolujen yhdistäminen",
    tableSplitCellsTitle: "Taulukkosolujen jakaminen",
    tagMenuTagAddress: "Osoite",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Otsakkeen 1",
    tagMenuTagH2: "Otsakkeen 2",
    tagMenuTagH3: "Otsakkeen 3",
    tagMenuTagH4: "Otsakkeen 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Kohdassa",
    tagMenuTagPre: "Alustettu",
    tagMenuTitle: "Elementin tyylin muuttaminen",
    tagTreeElementLink: "{{element}} osan valitseminen",
    tagTreeElementTitle: "Valitse sisältö \"{{element}}\" elementti",
    tagTreeRoot: "root",
    tagTreeRootLink: "Kaiken voi muokata sisällön valitseminen",
    tagTreeRootTitle: "Valitse muokattava sisältö",
    textBlockQuoteTitle: "Erotettu lainaus",
    textBoldTitle: "Lihavointi",
    textItalicTitle: "Kursivoitu",
    textSizeDecreaseTitle: "Pienennä tekstikokoa",
    textSizeIncreaseTitle: "Suurenna tekstikokoa",
    textStrikeTitle: "Yliviivata",
    textSubTitle: "Osa script",
    textSuperTitle: "Super kirjoitus",
    textUnderlineTitle: "Alleviivaus",
    unsavedEditWarningText: "Tällä sivulla on tallentamattomia muutoksia",
    viewSourceDialogCancelButton: "Sulje",
    viewSourceDialogOKButton: "Soveltaa lähdekoodi",
    viewSourceDialogTitle: "Sisältö lähdekoodi",
    viewSourceTitle: "Näytä\/Muokkaa lähdekoodia"
});