/**
 * @fileOverview French strings file.
 * @license http://www.raptor-editor.com/license
 *
 * @author SebCorbin, seb.corbin@gmail.com, https://github.com/SebCorbin/
 * @author In4matik, https://github.com/In4matik/
 */
extendLocale('fr', 'Français', {
    alignCenterTitle: "Aligner au centre",
    alignJustifyTitle: "Justifier",
    alignLeftTitle: "Aligner à gauche",
    alignRightTitle: "Aligner à droite",
    cancelDialogCancelButton: "Fermer",
    cancelDialogContent: "Êtes-vous sûr(e) de vouloir arrêter la modification ? Toutes les modifications seront perdues !",
    cancelDialogOKButton: "OK",
    cancelDialogTitle: "Annuler l'édition",
    cancelTitle: "Annuler l'édition",
    classMenuTitle: "Sélecteur de style",
    clearFormattingTitle: "Effacer la mise en forme",
    clickButtonToEditText: "Cliquer pour commencer la modification",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatique",
    colorMenuBasicBlack: "Noir",
    colorMenuBasicBlue: "Bleu",
    colorMenuBasicGreen: "Vert",
    colorMenuBasicGrey: "Gris",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Violet",
    colorMenuBasicRed: "Rouge",
    colorMenuBasicTitle: "Changer le couleur du texte",
    colorMenuBasicWhite: "Blanc",
    dockToElementTitle: "Fixer l'éditeur à l'élément",
    dockToScreenTitle: "Fixer l'éditeur à l'écran",
    embedDialogCancelButton: "Annuler",
    embedDialogOKButton: "Intégrer l'objet",
    embedDialogTabCode: "Code intégré",
    embedDialogTabCodeContent: "Collez votre code dans la zone de texte suivante :",
    embedDialogTabPreview: "Aperçu",
    embedDialogTabPreviewContent: "Un aperçu de votre code est disponible ci-dessous :",
    embedDialogTitle: "Object intégré",
    embedTitle: "Object intégré",
    errorUINoName: "UI \"{{ui}}\" est invalide (doit posséder une propriété \"name\")",
    errorUINotObject: "UI \"{{ui}}\" est invalide (doit être un objet)",
    errorUIOverride: "UI \"{{name}}\" a déjà été définie, et sera écrasée",
    fileManagerDialogTitle: "Gestionnaire de fichiers",
    fileManagerTitle: "Gestionnaire de fichiers",
    floatLeftTitle: "Image à gauche du texte",
    floatNoneTitle: "Retirer l'aligement de l'image",
    floatRightTitle: "Image à droite du texte",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic Sans",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Police par défaut",
    fontFamilyMenuFontGeorgia: "Géorgie",
    fontFamilyMenuFontImpact: "Impact",
    fontFamilyMenuFontPalatino: "Palatin",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Choisissez votre police",
    guidesTitle: "Afficher les guides",
    historyRedoTitle: "Rétablir",
    historyUndoTitle: "Annuler",
    hrCreateTitle: "Insérer une ligne horizontale",
    imageResizeButtonDialogCancelButton: "Annuler",
    imageResizeButtonDialogHeight: "Hauteur de l'image",
    imageResizeButtonDialogHeightPlaceHolder: "Hauteur",
    imageResizeButtonDialogOKButton: "Redimmensionner",
    imageResizeButtonDialogTitle: "Redimmensionner l'image",
    imageResizeButtonDialogWidth: "Largeur de l'image",
    imageResizeButtonDialogWidthPlaceHolder: "Largeur",
    imageResizeButtonText: "Redimmensionner l'image",
    insertFileDialogCancelButton: "Anuuler",
    insertFileDialogOKButton: "Insérer le fichier",
    insertFileNameLabel: "Nom du fichier",
    insertFileNamePlaceHolder: "Nom du fichier...",
    insertFileTitle: "Insérer un fichier",
    insertFileURLLabel: "URL du fichier",
    insertFileURLPlaceHolder: "URL du fichier...",
    languageMenuDE: "Deutsch",
    languageMenuEN: "English",
    languageMenuES: "Español",
    languageMenuFR: "Français",
    languageMenuNL: "Nederlandse",
    languageMenuRU: "Pусский",
    languageMenuSV: "Svensk",
    languageMenuTitle: "Changer de langue",
    languageMenuZHCN: "简体中文版",
    linkCreateDialogCancelButton: "Annuler",
    linkCreateDialogMenuHeader: "Choisissez un type de lien :",
    linkCreateDialogOKButton: "Insérer un lien",
    linkCreateDialogTitle: "Insérer un lien",
    linkCreateTitle: "Insérer un lien",
    linkRemoveTitle: "Supprimer le lien",
    linkTypeDocumentHeader: "Lien vers un document ou un autre fichier",
    linkTypeDocumentInfo: "<h2>Pas sûr(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Assurez-vous que le fichier a bien été envoyé sur votr site<\/li>    <li>Ouvrez le fichier envoyé dans votre navigateur.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur et collez-la dans le champs ci-dessous.<\/li><\/ol>",
    linkTypeDocumentLabel: "Document ou autre fichier",
    linkTypeDocumentLocationLabel: "Emplacement :",
    linkTypeDocumentLocationPlaceHolder: "Entrer une URL",
    linkTypeDocumentNewWindowHeader: "Nouvelle fenêtre",
    linkTypeDocumentNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fenêtre de navigateur.",
    linkTypeEmailHeader: "Lier une adresse e-mail",
    linkTypeEmailLabel: "Adresse e-mail",
    linkTypeEmailSubjectLabel: "Sujet (facultatif):",
    linkTypeEmailSubjectPlaceHolder: "Saisir le sujet",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Saisir l'adresse e-mail",
    linkTypeExternalHeader: "Lien vers une page sur un autre site",
    linkTypeExternalInfo: "<h2>Pas sûr(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Trouvez la page web que vous voulez lier.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur et collez-la dans le champs ci-dessous.<\/li><\/ol>",
    linkTypeExternalLabel: "Page sur une autre site",
    linkTypeExternalLocationLabel: "Emplacement",
    linkTypeExternalLocationPlaceHolder: "Entrer une URL",
    linkTypeExternalNewWindowHeader: "Nouvelle fenêtre",
    linkTypeExternalNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fenêtre de navigateur.",
    linkTypeInternalHeader: "Lien vers une page de ce site",
    linkTypeInternalInfo: "<h2>Pas sûr(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Trouvez la page web que vous voulez lier.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur, sans \"{{domain}}\" et collez-la dans le champs ci-dessous..<\/li><\/ol>",
    linkTypeInternalLabel: "Page de ce site",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Entrer une URI",
    linkTypeInternalNewWindowHeader: "Nouvelle fenêtre",
    linkTypeInternalNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fenêtre de navigateur.",
    listOrderedTitle: "Liste ordonnée",
    listUnorderedTitle: "Liste non ordonnée",
    logoTitle: "En savoir plus sur l'éditeur WYSIWYG Raptor",
    loremIpsumTitle: "Insérer du texte factice pour le test",
    navigateAway: "\nIl y a des modifications non enregistrées sur ce site. Si vous quittez cette page, elles seront définitivements perdues",
    pasteDialogCancelButton: "Annuler",
    pasteDialogFormattedCleaned: "Mis en forme & nettoyé",
    pasteDialogFormattedUnclean: "Mis en forme sans nettoyage",
    pasteDialogOKButton: "Insérer",
    pasteDialogPlain: "Texte brut",
    pasteDialogSource: "Code source",
    pasteDialogTitle: "Coller",
    placeholderPluginDefaultContent: "<br\/>",
    revisionsAJAXFailed: "Impossible de récupérer les révisions",
    revisionsApplyButtonDialogCancelButton: "Annuler",
    revisionsApplyButtonDialogOKButton: "Revenir en arrière",
    revisionsApplyButtonDialogText: "Confirmation de l'annulation",
    revisionsApplyButtonDialogTitle: "Confirmer le retour en arrière",
    revisionsApplyButtonText: "ROLLBACK",
    revisionsApplyButtonTitle: "Revenir en arrière",
    revisionsApplyDialogContent: "Cela remplacera le contenu actuel par celui de la révision sélectionnée.<br\/>Le contenu actuel sera ajouté comme une révision, et sera visible dans la liste des révisions pour ce bloc.",
    revisionsButtonCurrent: "Actuelle",
    revisionsButtonViewDiffText: "Différences",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Créé",
    revisionsDialogCancelButton: "Annuler",
    revisionsDialogTitle: "Voir le contenu des révisions",
    revisionsDiffButtonDialogCancelButton: "Fermer",
    revisionsDiffButtonDialogTitle: "Voir les différences",
    revisionsDiffButtonText: "Différences de vue",
    revisionsDiffButtonTitle: "Voir les différences",
    revisionsLoading: "Chargement des révisions...",
    revisionsNone: "Pas de révision pour cet élément",
    revisionsPreviewButtonText: "Aperçu",
    revisionsPreviewButtonTitle: "Aperçu",
    revisionsText: "Révisions",
    revisionsTextEmpty: "Aucune révision",
    revisionsTitle: "",
    rfmClose: "Fermer",
    rfmContinue: "Continuer",
    rfmDelete: "Supprimer",
    rfmDownload: "Télécharger",
    rfmFileActions: "Actions",
    rfmFileModificationTime: "Modifiée",
    rfmFileName: "Nom",
    rfmFileSize: "Taille",
    rfmFileType: "Type",
    rfmFilteredTotal: "Affichage {{start}} à {{end}} {{filteredTotal}} fichiers",
    rfmFirst: "Première",
    rfmHeadingDirectories: "Annuaires",
    rfmHeadingSearch: "Rechercher",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Télécharger",
    rfmInsert: "Insert",
    rfmLast: "Dernière",
    rfmSearch: "Aller",
    rfmTagDocument: "Document",
    rfmTagImage: "Image",
    rfmTotal: ", filtrées à partir de {{total}}",
    rfmUpload: "Télécharger",
    rfmUploadBrowse: "Parcourir",
    rfmUploadDrop: "Déposez des fichiers ici",
    rfmUploadFileRemove: "Supprimer",
    rfmUploadOr: "ou",
    rfmView: "Vue",
    saveJsonFail: "Impossible d'enregistrer {{failed}} bloc(s) de contenu",
    saveJsonSaved: "Enregistrement effectué de {{saved}} bloc(s) de contenu.",
    saveNotConfigured: "Save n'a pas été configuré, ou est désactivé.",
    saveRestFail: "Impossible d'enregistrer {{failed}} bloc(s) de contenu.",
    saveRestPartial: "Enregistrement de {{saved}} sur {{failed}} bloc(s) de contenu.",
    saveRestSaved: "Enregistrement effectué {{saved}} bloc(s) de contenu.",
    saveTitle: "Enregistrer le contenu",
    snippetMenuTitle: "Fragments",
    specialCharactersArrows: "Flèches",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "Insérer un caractère spécial",
    specialCharactersGreekAlphabet: "Alphabet grec",
    specialCharactersHelp: "Cliquez sur un caractère spécial pour l'ajouter. Cliquez sur \"OK\" lorsque vous avez fini pour fermer la fenêtre.",
    specialCharactersMathematics: "Mathématiques",
    specialCharactersSymbols: "Symboles",
    specialCharactersTitle: "Insérer un caractère spécial",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} caractères au-dessus de la limite",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} caractères restants",
    statisticsButtonCharacters: "{{characters}} caractères",
    statisticsDialogCharactersOverLimit: "{{characters}} caractères, {{charactersRemaining}} au-dessus de la limite",
    statisticsDialogCharactersRemaining: "{{characters}} caractères, {{charactersRemaining}} restants",
    statisticsDialogNotTruncated: "Le contenu ne sera pas tronqué",
    statisticsDialogOKButton: "OK",
    statisticsDialogSentence: "{{sentences}} phrase",
    statisticsDialogSentences: "{{sentences}} phrases",
    statisticsDialogTitle: "Statistiques de contenu",
    statisticsDialogTruncated: "Le contenu contient plus de {{limit}} caractères et peut être tronqué",
    statisticsDialogWord: "{{words}} mot",
    statisticsDialogWords: "{{words}} mots",
    statisticsTitle: "Cliquez pour voir les statistiques",
    tableCreateTitle: "Créer un tableau",
    tableDeleteColumnTitle: "Supprimer une colonne du tableau",
    tableDeleteRowTitle: "Supprimer une ligne du tableau",
    tableInsertColumnTitle: "Insérer une colonne",
    tableInsertRowTitle: "Insérer une ligne",
    tableMergeCellsTitle: "Fusionner des cellules",
    tableSplitCellsTitle: "Tronquer des cellules",
    tagMenuTagAddress: "Address",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Titre&nbsp;1",
    tagMenuTagH2: "Titre&nbsp;2",
    tagMenuTagH3: "Titre&nbsp;3",
    tagMenuTagH4: "Titre&nbsp;4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Paragraphe",
    tagMenuTagPre: "Pré-formaté",
    tagMenuTitle: "Modifier le style de l'élément",
    tagTreeElementLink: "Sélectionner l'élément {{element}}",
    tagTreeElementTitle: "Cliquer pour sélectionner le contenu de l'élément \"{{element}}\"",
    tagTreeRoot: "racine",
    tagTreeRootLink: "Sélectionner tout le contenu modifiable",
    tagTreeRootTitle: "Cliquer pour sélectionner tout le contenu modifiable",
    textBlockQuoteTitle: "Citation",
    textBoldTitle: "Gras",
    textItalicTitle: "Italique",
    textSizeDecreaseTitle: "Diminuer la taille du texte",
    textSizeIncreaseTitle: "Augmenter la taille du texte",
    textStrikeTitle: "Barré",
    textSubTitle: "Indice",
    textSuperTitle: "Exposant",
    textUnderlineTitle: "Souligné",
    unsavedEditWarningText: "Il y a des modifications non enregistrées sur cette page",
    viewSourceDialogCancelButton: "Fermer",
    viewSourceDialogOKButton: "Appliquer le code source",
    viewSourceDialogTitle: "Code source du contenu",
    viewSourceTitle: "Voir \/ Modifier le code source"
});