/**
 * @fileOverview French strings file.
 * @license http://www.raptor-editor.com/license
 *
 * @author SebCorbin, seb.corbin@gmail.com, https://github.com/SebCorbin/
 * @author In4matik, https://github.com/In4matik/
 */
extendLocale('fr', 'Français', {
    alignCenterTitle: "Aligner au centre",
    alignJustifyTitle: "Justifier",
    alignLeftTitle: "Aligner &agrave; gauche",
    alignRightTitle: "Aligner &agrave; droite",
    cancelDialogCancelButton: "Fermer",
    cancelDialogContent: "Êtes-vous s&ucirc;r(e) de vouloir arr&ecirc;ter la modification ? Toutes les modifications seront perdues !",
    cancelDialogOKButton: "OK",
    cancelDialogTitle: "Annuler l'&eacute;dition",
    cancelTitle: "Annuler l'&eacute;dition",
    classMenuTitle: "S&eacute;lecteur de style",
    clearFormattingTitle: "Effacer la mise en forme",
    clickButtonToEditText: "Cliquer pour commencer la modification",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatique",
    colorMenuBasicBlack: "Noir",
    colorMenuBasicBlue: "Bleu",
    colorMenuBasicGreen: "Vert",
    colorMenuBasicGrey: "Gris",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Violet",
    colorMenuBasicRed: "Rouge",
    colorMenuBasicTitle: "Changer le couleur du texte",
    colorMenuBasicWhite: "Blanc",
    dockToElementTitle: "Fixer l'&eacute;diteur &agrave; l'&eacute;l&eacute;ment",
    dockToScreenTitle: "Fixer l'&eacute;diteur &agrave; l'&eacute;cran",
    embedDialogCancelButton: "Annuler",
    embedDialogOKButton: "Int&eacute;grer l'objet",
    embedDialogTabCode: "Code int&eacute;gr&eacute;",
    embedDialogTabCodeContent: "Collez votre code dans la zone de texte suivante :",
    embedDialogTabPreview: "Aperçu",
    embedDialogTabPreviewContent: "Un aperçu de votre code est disponible ci-dessous :",
    embedDialogTitle: "Object int&eacute;gr&eacute;",
    embedTitle: "Object int&eacute;gr&eacute;",
    errorUINoName: "UI \"{{ui}}\" est invalide (doit poss&eacute;der une propri&eacute;t&eacute; \"name\")",
    errorUINotObject: "UI \"{{ui}}\" est invalide (doit &ecirc;tre un objet)",
    errorUIOverride: "UI \"{{name}}\" a d&eacute;j&agrave; &eacute;t&eacute; d&eacute;finie, et sera &eacute;cras&eacute;e",
    fileManagerDialogTitle: "Gestionnaire de fichiers",
    fileManagerTitle: "Gestionnaire de fichiers",
    floatLeftTitle: "Image &agrave; gauche du texte",
    floatNoneTitle: "Retirer l'aligement de l'image",
    floatRightTitle: "Image &agrave; droite du texte",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic Sans",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Police par défaut",
    fontFamilyMenuFontGeorgia: "Géorgie",
    fontFamilyMenuFontImpact: "Impact",
    fontFamilyMenuFontPalatino: "Palatin",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Choisissez votre police",
    guidesTitle: "Afficher les guides",
    historyRedoTitle: "R&eacute;tablir",
    historyUndoTitle: "Annuler",
    hrCreateTitle: "Ins&eacute;rer une ligne horizontale",
    imageResizeButtonDialogCancelButton: "Annuler",
    imageResizeButtonDialogHeight: "Hauteur de l'image",
    imageResizeButtonDialogHeightPlaceHolder: "Hauteur",
    imageResizeButtonDialogOKButton: "Redimmensionner",
    imageResizeButtonDialogTitle: "Redimmensionner l'image",
    imageResizeButtonDialogWidth: "Largeur de l'image",
    imageResizeButtonDialogWidthPlaceHolder: "Largeur",
    imageResizeButtonText: "Redimmensionner l'image",
    insertFileDialogCancelButton: "Anuuler",
    insertFileDialogOKButton: "Ins&eacute;rer le fichier",
    insertFileNameLabel: "Nom du fichier",
    insertFileNamePlaceHolder: "Nom du fichier...",
    insertFileTitle: "Ins&eacute;rer un fichier",
    insertFileURLLabel: "URL du fichier",
    insertFileURLPlaceHolder: "URL du fichier...",
    languageMenuDE: "Deutsch",
    languageMenuEN: "English",
    languageMenuES: "Español",
    languageMenuFR: "Français",
    languageMenuNL: "Nederlandse",
    languageMenuRU: "Pусский",
    languageMenuSV: "Svensk",
    languageMenuTitle: "Changer de langue",
    languageMenuZHCN: "简体中文版",
    linkCreateDialogCancelButton: "Annuler",
    linkCreateDialogMenuHeader: "Choisissez un type de lien :",
    linkCreateDialogOKButton: "Ins&eacute;rer un lien",
    linkCreateDialogTitle: "Ins&eacute;rer un lien",
    linkCreateTitle: "Ins&eacute;rer un lien",
    linkRemoveTitle: "Supprimer le lien",
    linkTypeDocumentHeader: "Lien vers un document ou un autre fichier",
    linkTypeDocumentInfo: "<h2>Pas s&ucirc;r(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Assurez-vous que le fichier a bien &eacute;t&eacute; envoy&eacute; sur votr site<\/li>    <li>Ouvrez le fichier envoy&eacute; dans votre navigateur.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur et collez-la dans le champs ci-dessous.<\/li><\/ol>",
    linkTypeDocumentLabel: "Document ou autre fichier",
    linkTypeDocumentLocationLabel: "Emplacement :",
    linkTypeDocumentLocationPlaceHolder: "Entrer une URL",
    linkTypeDocumentNewWindowHeader: "Nouvelle fen&ecirc;tre",
    linkTypeDocumentNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fen&ecirc;tre de navigateur.",
    linkTypeEmailHeader: "Lier une adresse e-mail",
    linkTypeEmailLabel: "Adresse e-mail",
    linkTypeEmailSubjectLabel: "Sujet (facultatif):",
    linkTypeEmailSubjectPlaceHolder: "Saisir le sujet",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Saisir l'adresse e-mail",
    linkTypeExternalHeader: "Lien vers une page sur un autre site",
    linkTypeExternalInfo: "<h2>Pas s&ucirc;r(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Trouvez la page web que vous voulez lier.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur et collez-la dans le champs ci-dessous.<\/li><\/ol>",
    linkTypeExternalLabel: "Page sur une autre site",
    linkTypeExternalLocationLabel: "Emplacement",
    linkTypeExternalLocationPlaceHolder: "Entrer une URL",
    linkTypeExternalNewWindowHeader: "Nouvelle fen&ecirc;tre",
    linkTypeExternalNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fen&ecirc;tre de navigateur.",
    linkTypeInternalHeader: "Lien vers une page de ce site",
    linkTypeInternalInfo: "<h2>Pas s&ucirc;r(e) de savoir quoi mettre dans le champ ci-dessus ?<\/h2><ol>    <li>Trouvez la page web que vous voulez lier.<\/li>    <li>Copiez l'adresse de la barre d'adresse de votre navigateur, sans \"{{domain}}\" et collez-la dans le champs ci-dessous..<\/li><\/ol>",
    linkTypeInternalLabel: "Page de ce site",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Entrer une URI",
    linkTypeInternalNewWindowHeader: "Nouvelle fen&ecirc;tre",
    linkTypeInternalNewWindowLabel: "Cochez cette case pour ouvrir le lien dans une nouvelle fen&ecirc;tre de navigateur.",
    listOrderedTitle: "Liste ordonn&eacute;e",
    listUnorderedTitle: "Liste non ordonn&eacute;e",
    logoTitle: "En savoir plus sur l'&eacute;diteur WYSIWYG Raptor",
    navigateAway: "\nIl y a des modifications non enregistr&eacute;es sur ce site. Si vous quittez cette page, elles seront d&eacute;finitivements perdues",
    pasteDialogCancelButton: "Annuler",
    pasteDialogFormattedCleaned: "Mis en forme &amp; nettoy&eacute;",
    pasteDialogFormattedUnclean: "Mis en forme sans nettoyage",
    pasteDialogOKButton: "Ins&eacute;rer",
    pasteDialogPlain: "Texte brut",
    pasteDialogSource: "Code source",
    pasteDialogTitle: "Coller",
    placeholderPluginDefaultContent: "<br\/>",
    revisionsAJAXFailed: "Impossible de r&eacute;cup&eacute;rer les r&eacute;visions",
    revisionsApplyButtonDialogCancelButton: "Annuler",
    revisionsApplyButtonDialogOKButton: "Revenir en arri&egrave;re",
    revisionsApplyButtonDialogTitle: "Confirmer le retour en arri&egrave;re",
    revisionsApplyButtonTitle: "Revenir en arri&egrave;re",
    revisionsApplyDialogContent: "Cela remplacera le contenu actuel par celui de la r&eacute;vision s&eacute;lectionn&eacute;e.<br\/>Le contenu actuel sera ajout&eacute; comme une r&eacute;vision, et sera visible dans la liste des r&eacute;visions pour ce bloc.",
    revisionsButtonCurrent: "Actuelle",
    revisionsButtonViewDiffText: "Diff&eacute;rences",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Annuler",
    revisionsDialogTitle: "Voir le contenu des r&eacute;visions",
    revisionsDiffButtonDialogCancelButton: "Fermer",
    revisionsDiffButtonDialogTitle: "Voir les diff&eacute;rences",
    revisionsDiffButtonTitle: "Voir les diff&eacute;rences",
    revisionsLoading: "Chargement des r&eacute;visions...",
    revisionsNone: "Pas de r&eacute;vision pour cet &eacute;l&eacute;ment",
    revisionsPreviewButtonTitle: "Aperçu",
    revisionsText: "R&eacute;visions",
    revisionsTextEmpty: "Aucune r&eacute;vision",
    revisionsTitle: "",
    rfmClose: "Fermer",
    rfmContinue: "Continuer",
    rfmDelete: "Supprimer",
    rfmDownload: "Télécharger",
    rfmFileActions: "Actions",
    rfmFileModificationTime: "Modifiée",
    rfmFileName: "Nom",
    rfmFileSize: "Taille",
    rfmFileType: "Type",
    rfmFilteredTotal: "Affichage {{start}} à {{end}} {{filteredTotal}} fichiers",
    rfmFirst: "Première",
    rfmHeadingDirectories: "Annuaires",
    rfmHeadingSearch: "Rechercher",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Télécharger",
    rfmInsert: "Insert",
    rfmLast: "Dernière",
    rfmSearch: "Aller",
    rfmTotal: ", filtrées à partir de {{total}}",
    rfmUpload: "Télécharger",
    rfmUploadBrowse: "Parcourir",
    rfmUploadDrop: "Déposez des fichiers ici",
    rfmUploadFileRemove: "Supprimer",
    rfmView: "Vue",
    saveJsonFail: "Impossible d'enregistrer {{failed}} bloc(s) de contenu",
    saveJsonSaved: "Enregistrement effectu&eacute; de {{saved}} bloc(s) de contenu.",
    saveNotConfigured: "Save n'a pas été configuré, ou est désactivé.",
    saveRestFail: "Impossible d'enregistrer {{failed}} bloc(s) de contenu.",
    saveRestPartial: "Enregistrement de {{saved}} sur {{failed}} bloc(s) de contenu.",
    saveRestSaved: "Enregistrement effectu&eacute; {{saved}} bloc(s) de contenu.",
    saveTitle: "Enregistrer le contenu",
    snippetMenuTitle: "Fragments",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "Ins&eacute;rer un caract&egrave;re sp&eacute;cial",
    specialCharactersHelp: "Cliquez sur un caract&egrave;re sp&eacute;cial pour l'ajouter. Cliquez sur \"OK\" lorsque vous avez fini pour fermer la fen&ecirc;tre.",
    specialCharactersTitle: "Ins&eacute;rer un caract&egrave;re sp&eacute;cial",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} caract&egrave;res au-dessus de la limite",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} caract&egrave;res restants",
    statisticsButtonCharacters: "{{characters}} caract&egrave;res",
    statisticsDialogCharactersOverLimit: "{{characters}} caract&egrave;res, {{charactersRemaining}} au-dessus de la limite",
    statisticsDialogCharactersRemaining: "{{characters}} caract&egrave;res, {{charactersRemaining}} restants",
    statisticsDialogNotTruncated: "Le contenu ne sera pas tronqu&eacute;",
    statisticsDialogOKButton: "OK",
    statisticsDialogSentence: "{{sentences}} phrase",
    statisticsDialogSentences: "{{sentences}} phrases",
    statisticsDialogTitle: "Statistiques de contenu",
    statisticsDialogTruncated: "Le contenu contient plus de {{limit}} caract&egrave;res et peut &ecirc;tre tronqu&eacute;",
    statisticsDialogWord: "{{words}} mot",
    statisticsDialogWords: "{{words}} mots",
    statisticsTitle: "Cliquez pour voir les statistiques",
    tableCreateTitle: "Cr&eacute;er un tableau",
    tableDeleteColumnTitle: "Supprimer une colonne du tableau",
    tableDeleteRowTitle: "Supprimer une ligne du tableau",
    tableInsertColumnTitle: "Ins&eacute;rer une colonne",
    tableInsertRowTitle: "Ins&eacute;rer une ligne",
    tableMergeCellsTitle: "Fusionner des cellules",
    tableSplitCellsTitle: "Tronquer des cellules",
    tagMenuTagAddress: "Address",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Titre&nbsp;1",
    tagMenuTagH2: "Titre&nbsp;2",
    tagMenuTagH3: "Titre&nbsp;3",
    tagMenuTagH4: "Titre&nbsp;4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Paragraphe",
    tagMenuTagPre: "Pr&eacute;-format&eacute;",
    tagMenuTitle: "Modifier le style de l'&eacute;l&eacute;ment",
    tagTreeElementLink: "S&eacute;lectionner l'&eacute;l&eacute;ment {{element}}",
    tagTreeElementTitle: "Cliquer pour s&eacute;lectionner le contenu de l'&eacute;l&eacute;ment \"{{element}}\"",
    tagTreeRoot: "racine",
    tagTreeRootLink: "S&eacute;lectionner tout le contenu modifiable",
    tagTreeRootTitle: "Cliquer pour s&eacute;lectionner tout le contenu modifiable",
    textBlockQuoteTitle: "Citation",
    textBoldTitle: "Gras",
    textItalicTitle: "Italique",
    textSizeDecreaseTitle: "Diminuer la taille du texte",
    textSizeIncreaseTitle: "Augmenter la taille du texte",
    textStrikeTitle: "Barr&eacute;",
    textSubTitle: "Indice",
    textSuperTitle: "Exposant",
    textUnderlineTitle: "Soulign&eacute;",
    unsavedEditWarningText: "Il y a des modifications non enregistr&eacute;es sur cette page",
    viewSourceDialogCancelButton: "Fermer",
    viewSourceDialogOKButton: "Appliquer le code source",
    viewSourceDialogTitle: "Code source du contenu",
    viewSourceTitle: "Voir \/ Modifier le code source"
});