/**
 * @fileOverview Hebrew strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('he', 'עברית', {
    alignCenterTitle: "ישר טקסט למרכז",
    alignJustifyTitle: "יישור טקסט להצדיק",
    alignLeftTitle: "יישור טקסט לשמאל",
    alignRightTitle: "ישר טקסט לימין",
    cancelDialogCancelButton: "להמשיך בעריכה",
    cancelDialogContent: "האם אתה בטוח שברצונך לבטל עריכה? כל השינויים יאבדו!",
    cancelDialogOKButton: "ביטול העריכה",
    cancelDialogTitle: "ביטול העריכה",
    cancelTitle: "ביטול העריכה",
    classMenuTitle: "סגנון בורר",
    clearFormattingTitle: "נקה עיצוב",
    clickButtonToEditText: "עריכה",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "אוטומטי",
    colorMenuBasicBlack: "שחור",
    colorMenuBasicBlue: "כחול",
    colorMenuBasicGreen: "גרין",
    colorMenuBasicGrey: "גריי",
    colorMenuBasicOrange: "כתום",
    colorMenuBasicPurple: "סגול",
    colorMenuBasicRed: "אדום",
    colorMenuBasicTitle: "שינוי צבע הטקסט",
    colorMenuBasicWhite: "לבן",
    dockToElementTitle: "מזח העגינה עורך לרכיב",
    dockToScreenTitle: "מזח העגינה עורך למסך",
    embedDialogCancelButton: "ביטול",
    embedDialogOKButton: "להטביע אובייקט",
    embedDialogTabCode: "הטמע קוד",
    embedDialogTabCodeContent: "הדבק את קוד ה embed של אזור הטקסט שלהלן:",
    embedDialogTabPreview: "תצוגה מקדימה",
    embedDialogTabPreviewContent: "תצוגה מקדימה של האובייקט המוטבע שלך מוצג להלן:",
    embedDialogTitle: "להטביע אובייקט",
    embedTitle: "להטביע אובייקט",
    errorUINoName: "ממשק המשתמש ממשק \"{{ui}}\" אינו חוקי (חייב להיות שם מאפיין)",
    errorUINotObject: "ממשק המשתמש ממשק \"{{ui}}\" אינו חוקי (חייב להיות אובייקט)",
    errorUIOverride: "ממשק המשתמש \"{{name}}\" כבר נרשם, והוא יוחלף",
    fileManagerDialogTitle: "מנהל קבצים",
    fileManagerTitle: "מנהל קבצים",
    floatLeftTitle: "יישור התמונה משמאל",
    floatNoneTitle: "להסיר את התמונה ליישר",
    floatRightTitle: "יישור התמונה מימין",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "קומיקס ללא",
    fontFamilyMenuFontCourier: "שליח חדש",
    fontFamilyMenuFontDefault: "גופן ברירת המחדל",
    fontFamilyMenuFontGeorgia: "גרוזיה",
    fontFamilyMenuFontImpact: "ההשפעה",
    fontFamilyMenuFontPalatino: "פלטין",
    fontFamilyMenuFontTimes: "פעמים רומן חדש",
    fontFamilyMenuTitle: "בחר את הגופן שלך",
    guidesTitle: "הצג קווי יסוד",
    historyRedoTitle: "בצע שוב",
    historyUndoTitle: "בטל",
    hrCreateTitle: "הוספת הסרגל האופקי",
    imageResizeButtonDialogCancelButton: "ביטול",
    imageResizeButtonDialogHeight: "גובה תמונה",
    imageResizeButtonDialogHeightPlaceHolder: "גובה",
    imageResizeButtonDialogOKButton: "שינוי גודל",
    imageResizeButtonDialogTitle: "שינוי גודל של תמונה",
    imageResizeButtonDialogWidth: "רוחב תמונה",
    imageResizeButtonDialogWidthPlaceHolder: "רוחב",
    imageResizeButtonText: "שינוי גודל של תמונה",
    insertFileDialogCancelButton: "ביטול",
    insertFileDialogOKButton: "להוסיף קובץ",
    insertFileNameLabel: "שם קובץ",
    insertFileNamePlaceHolder: "שם קובץ...",
    insertFileTitle: "להוסיף קובץ",
    insertFileURLLabel: "כתובת url של קובץ",
    insertFileURLPlaceHolder: "כתובת URL של קובץ...",
    languageMenuTitle: "שינוי שפה",
    linkCreateDialogCancelButton: "ביטול",
    linkCreateDialogMenuHeader: "בחרו סוג הקישור",
    linkCreateDialogOKButton: "הוסף קישור",
    linkCreateDialogTitle: "הוסף קישור",
    linkCreateTitle: "הוסף קישור",
    linkRemoveTitle: "הסר קישור",
    linkTypeDocumentHeader: "קישור של מסמך או קובץ אחר",
    linkTypeDocumentInfo: "<h2>לא בטוח מה לשים בתיבה לעיל?<\/h2><ol>    <li>ודא שהקובץ הועלה לאתר האינטרנט שלך.<\/li>    <li>פתח את הקובץ שהועלה בדפדפן שלך.<\/li>    <li>העתק URL של הקובץ בשורת הכתובת של הדפדפן שלך ולהדביקו בתיבת לעיל.<\/li><\/ol>",
    linkTypeDocumentLabel: "מסמך או קובץ אחר",
    linkTypeDocumentLocationLabel: "מיקום:",
    linkTypeDocumentLocationPlaceHolder: "הזן כתובת URL",
    linkTypeDocumentNewWindowHeader: "חלון חדש",
    linkTypeDocumentNewWindowLabel: "סמן תיבה זו כדי קובץ לפתוח דפדפן בחלון\/טאב חדש.",
    linkTypeEmailHeader: "קישור אל כתובת דואר אלקטרוני",
    linkTypeEmailLabel: "כתובת הדוא ל שלך",
    linkTypeEmailSubjectLabel: "נושא (אופציונלי):",
    linkTypeEmailSubjectPlaceHolder: "הזן נושא",
    linkTypeEmailToLabel: "דוא:",
    linkTypeEmailToPlaceHolder: "הזן את כתובת הדוא",
    linkTypeExternalHeader: "קישור לדף באתר אחר",
    linkTypeExternalInfo: "<h2>לא בטוח מה לשים בתיבה לעיל?<\/h2><ol>    <li>מצא את העמוד על האינטרנט שברצונך לקשר.<\/li>    <li>העתק את כתובת האינטרנט בשורת הכתובת של הדפדפן שלך ולהדביקו בתיבת לעיל.<\/li><\/ol>",
    linkTypeExternalLabel: "דף באתר אחר",
    linkTypeExternalLocationLabel: "מיקום:",
    linkTypeExternalLocationPlaceHolder: "הזן כתובת URL",
    linkTypeExternalNewWindowHeader: "חלון חדש",
    linkTypeExternalNewWindowLabel: "סמן תיבה זו כדי שהקישור לפתוח דפדפן בחלון\/טאב חדש.",
    linkTypeInternalHeader: "קישור לדף באתר זה",
    linkTypeInternalInfo: "<h2>לא בטוח מה לשים בתיבה לעיל?<\/h2><ol>    <li>מצא את העמוד על הקישור באתר זה כדי.<\/li>    <li>להעתיק את כתובת האינטרנט של הדפדפן לכתובת בר, למעט \"{{domain}}\" ולהדביקו בתיבת לעיל.<\/li><\/ol>",
    linkTypeInternalLabel: "דף באתר זה",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "הזן כתובת URI",
    linkTypeInternalNewWindowHeader: "חלון חדש",
    linkTypeInternalNewWindowLabel: "סמן תיבה זו כדי שהקישור לפתוח דפדפן בחלון\/טאב חדש.",
    listOrderedTitle: "רשימה מסודרת",
    listUnorderedTitle: "רשימה שאינה מסודרת",
    logoTitle: "למד עוד אודות עורך WYSIWYG את הראפטור",
    loremIpsumTitle: "הוספת טקסט בדיקה",
    navigateAway: "\nיש נשמרו השינויים בדף זה. \nאם תנווט מחוץ לדף זה תאבד את השינויים שלא נשמרו",
    pasteDialogCancelButton: "ביטול",
    pasteDialogFormattedCleaned: "מעוצב &amp; לנקות",
    pasteDialogFormattedUnclean: "מעוצב טמאה",
    pasteDialogOKButton: "הוספה",
    pasteDialogPlain: "טקסט רגיל",
    pasteDialogSource: "קוד מקור",
    pasteDialogTitle: "הדבק",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "נכשל באחזור מהדורות",
    revisionsApplyButtonDialogCancelButton: "ביטול",
    revisionsApplyButtonDialogOKButton: "חזרה למצב קודם",
    revisionsApplyButtonDialogText: "אישור חזרה למצב קודם",
    revisionsApplyButtonDialogTitle: "אישור חזרה למצב קודם",
    revisionsApplyButtonText: "חזרה למצב קודם",
    revisionsApplyButtonTitle: "חזרה למצב קודם",
    revisionsApplyDialogContent: "זה יחליף את התוכן הנוכחי עם הגרסה שנבחרה.<br>התוכן הנוכחי יתווסף כמהדורה, יהיה גלוי ברשימת התיקונים של קוביית מידע זו.",
    revisionsButtonCurrent: "זרם",
    revisionsButtonViewDiffText: "ההבדלים",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "נוצר",
    revisionsDialogCancelButton: "ביטול",
    revisionsDialogTitle: "הצג תיקונים תוכן",
    revisionsDiffButtonDialogCancelButton: "סגור",
    revisionsDiffButtonDialogTitle: "ההבדלים תצוגה",
    revisionsDiffButtonText: "ההבדלים תצוגה",
    revisionsDiffButtonTitle: "ההבדלים תצוגה",
    revisionsLoading: "טוען תיקונים...",
    revisionsNone: "אין תיקונים עבור רכיב זה",
    revisionsPreviewButtonText: "תצוגה מקדימה",
    revisionsPreviewButtonTitle: "תצוגה מקדימה",
    revisionsText: "מהדורות",
    revisionsTextEmpty: "אין תיקונים",
    revisionsTitle: "",
    rfmClose: "סגור",
    rfmContinue: "המשך",
    rfmDelete: "מחק",
    rfmDownload: "להורדה",
    rfmFileActions: "פעולות",
    rfmFileModificationTime: "שונה",
    rfmFileName: "שם",
    rfmFileSize: "גודל",
    rfmFileType: "סוג",
    rfmFilteredTotal: "מראה {{start}} לסיים {{end}} {{filteredTotal}} קבצים",
    rfmFirst: "הראשון",
    rfmHeadingDirectories: "ספריות",
    rfmHeadingSearch: "חיפוש",
    rfmHeadingTags: "תגיות",
    rfmHeadingUpload: "להעלות",
    rfmInsert: "הוספה",
    rfmLast: "אחרונה",
    rfmSearch: ". קדימה",
    rfmTagDocument: "המסמך",
    rfmTagImage: "התמונה",
    rfmTotal: ", מסוננים מסכום {{total}}",
    rfmUpload: "להעלות",
    rfmUploadBrowse: "עיון",
    rfmUploadDrop: "להוריד קבצים כאן",
    rfmUploadFileRemove: "הסר",
    rfmUploadOr: "או",
    rfmView: "תצוגה",
    saveJsonFail: "הצלחתי להציל גושי תוכן {{failed}}",
    saveJsonSaved: "נשמר בהצלחה גושי תוכן {{saved}}.",
    saveNotConfigured: "שמור לא נקבעה, או אינו זמין.",
    saveRestFail: "שמירת גושי תוכן {{failed}} נכשלה.",
    saveRestPartial: "הציל {{saved}} מקוביות תוכן {{failed}}.",
    saveRestSaved: "נשמר בהצלחה גושי תוכן {{saved}}.",
    saveTitle: "שמירת תוכן",
    snippetMenuTitle: "גזירים",
    specialCharactersArrows: "חצים",
    specialCharactersDialogOKButton: "אוקיי",
    specialCharactersDialogTitle: "הוספת תווים מיוחדים",
    specialCharactersGreekAlphabet: "אלפבית יווני",
    specialCharactersHelp: "לחץ על תו מיוחד כדי להוסיף אותו. לחץ על \"אישור\" כאשר נעשה כדי לסגור תיבת דו-שיח זו",
    specialCharactersMathematics: "מתמטיקה",
    specialCharactersSymbols: "סמלים",
    specialCharactersTitle: "הוספת תו מיוחד",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} תווים ממגבלת",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} תווים שנותרו",
    statisticsButtonCharacters: "{{characters}} תווים",
    statisticsDialogCharactersOverLimit: "תווים {{characters}}, {{charactersRemaining}} מעל הגבול מומלצים",
    statisticsDialogCharactersRemaining: "תווים {{characters}}, {{charactersRemaining}} שנותרו",
    statisticsDialogNotTruncated: "תוכן לא יקוצר",
    statisticsDialogOKButton: "אוקיי",
    statisticsDialogSentence: "גזר הדין {{sentences}}",
    statisticsDialogSentences: "משפטים {{sentences}}",
    statisticsDialogTitle: "תוכן סטטיסטיקות",
    statisticsDialogTruncated: "תוכן מכיל יותר תווים {{limit}}, עשויים להיחתך",
    statisticsDialogWord: "המילה {{words}}",
    statisticsDialogWords: "מילים {{words}}",
    statisticsTitle: "לחץ כדי להציג נתונים סטטיסטיים",
    tableCreateTitle: "יצירת טבלה",
    tableDeleteColumnTitle: "מחק עמודה בטבלה",
    tableDeleteRowTitle: "מחק שורת הטבלה",
    tableInsertColumnTitle: "הוספת עמודת הטבלה",
    tableInsertRowTitle: "הוסף שורת הטבלה",
    tableMergeCellsTitle: "מיזוג תאים בטבלה",
    tableSplitCellsTitle: "פיצול תאים בטבלה",
    tagMenuTagAddress: "כתובת",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "כותרת 1",
    tagMenuTagH2: "כותרת 2",
    tagMenuTagH3: "' כותרת 3",
    tagMenuTagH4: "כותרת 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "פסקה",
    tagMenuTagPre: "מעוצב מראש",
    tagMenuTitle: "שינוי סגנון רכיב",
    tagTreeElementLink: "בחר ברכיב {{element}}",
    tagTreeElementTitle: "לחץ כדי לבחור את התוכן של רכיב \"{{element}}\"",
    tagTreeRoot: "שורש",
    tagTreeRootLink: "בחר את כל התוכן לעריכה",
    tagTreeRootTitle: "לחץ כדי לבחור את כל התוכן לעריכה",
    textBlockQuoteTitle: "בלוק ציטוט",
    textBoldTitle: "מודגש",
    textItalicTitle: "נטוי",
    textSizeDecreaseTitle: "להקטין את גודל הטקסט",
    textSizeIncreaseTitle: "להגדיל את גודל הטקסט",
    textStrikeTitle: "חוצה",
    textSubTitle: "קובץ script משנה",
    textSuperTitle: "סופר-הסקריפט",
    textUnderlineTitle: "קו תחתון",
    unsavedEditWarningText: "יש נשמרו השינויים בדף זה",
    viewSourceDialogCancelButton: "סגור",
    viewSourceDialogOKButton: "להחיל את קוד המקור",
    viewSourceDialogTitle: "קוד מקור תוכן",
    viewSourceTitle: "הצג\/ערוך קוד המקור"
});