/**
 * @fileOverview Hindi strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('hi', 'मानक हिन्दी', {
    alignCenterTitle: "पाठ मध्य संरेखित करें",
    alignJustifyTitle: "पाठ को संरेखित करना का औचित्य साबित",
    alignLeftTitle: "पाठ बाएँ संरेखित करें",
    alignRightTitle: "पाठ दाएँ संरेखित करें",
    cancelDialogCancelButton: "संपादन जारी रखें",
    cancelDialogContent: "आप सुनिश्चित करें कि आप संपादन रद्द करना चाहते हैं? सभी परिवर्तन खो जाएँगे!",
    cancelDialogOKButton: "संपादन रद्द करें",
    cancelDialogTitle: "संपादन रद्द करें",
    cancelTitle: "संपादन रद्द करें",
    classMenuTitle: "शैली पिकर",
    clearFormattingTitle: "स्वरूपण साफ़ करें",
    clickButtonToEditText: "संपादित करें",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "स्वत:",
    colorMenuBasicBlack: "ब्लैक",
    colorMenuBasicBlue: "ब्लू",
    colorMenuBasicGreen: "ग्रीन",
    colorMenuBasicGrey: "ग्रे",
    colorMenuBasicOrange: "ऑरेंज",
    colorMenuBasicPurple: "बैंगनी",
    colorMenuBasicRed: "लाल",
    colorMenuBasicTitle: "पाठ का रंग परिवर्तित करें",
    colorMenuBasicWhite: "व्हाइट",
    dockToElementTitle: "डॉक\/संपादक तत्व को अनडॉक करें",
    dockToScreenTitle: "डॉक\/अनडॉक करने के लिए स्क्रीन संपादक",
    embedDialogCancelButton: "रद्द करें",
    embedDialogOKButton: "ऑब्जेक्ट एम्बेड करें",
    embedDialogTabCode: "एम्बेड कोड",
    embedDialogTabCodeContent: "नीचे दिए गए पाठ क्षेत्र में अपने एम्बेड कोड चिपकाएँ:",
    embedDialogTabPreview: "पूर्वावलोकन",
    embedDialogTabPreviewContent: "अपने एम्बेडेड ऑब्जेक्ट का एक पूर्वावलोकन के नीचे प्रदर्शित होता है:",
    embedDialogTitle: "ऑब्जेक्ट एम्बेड करें",
    embedTitle: "ऑब्जेक्ट एम्बेड करें",
    errorUINoName: "UI \"{{ui}}\" अमान्य है (एक नाम गुण होना आवश्यक है)",
    errorUINotObject: "UI \"{{ui}}\" अमान्य है (एक ऑब्जेक्ट होना चाहिए)",
    errorUIOverride: "UI \"{{name}}\" पहले से ही पंजीकृत किया गया है, और अधिलेखित हो जाएगा",
    fileManagerDialogTitle: "फ़ाइल प्रबंधक",
    fileManagerTitle: "फ़ाइल प्रबंधक",
    floatLeftTitle: "छवि को बाईं ओर संरेखित करें",
    floatNoneTitle: "छवि निकालें संरेखित करें",
    floatRightTitle: "छवि ठीक से संरेखित करें",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "हास्य बिना",
    fontFamilyMenuFontCourier: "कोरियर नया",
    fontFamilyMenuFontDefault: "डिफ़ॉल्ट फ़ॉन्ट",
    fontFamilyMenuFontGeorgia: "जॉर्जिया",
    fontFamilyMenuFontImpact: "प्रभाव",
    fontFamilyMenuFontPalatino: "पैलेटाइन",
    fontFamilyMenuFontTimes: "टाइम्स न्यू रोमन",
    fontFamilyMenuTitle: "आपका फ़ॉन्ट चुनें",
    guidesTitle: "तत्व मार्गदर्शिकाएँ दिखाएँ",
    historyRedoTitle: "फिर से करें",
    historyUndoTitle: "पूर्ववत् करें",
    hrCreateTitle: "क्षैतिज रूल डालें",
    imageResizeButtonDialogCancelButton: "रद्द करें",
    imageResizeButtonDialogHeight: "छवि ऊँचाई",
    imageResizeButtonDialogHeightPlaceHolder: "ऊँचाई",
    imageResizeButtonDialogOKButton: "आकार बदलें",
    imageResizeButtonDialogTitle: "छवि का आकार बदलना",
    imageResizeButtonDialogWidth: "छवि चौड़ाई",
    imageResizeButtonDialogWidthPlaceHolder: "चौड़ाई",
    imageResizeButtonText: "छवि का आकार बदलना",
    insertFileDialogCancelButton: "रद्द करें",
    insertFileDialogOKButton: "फ़ाइल सम्मिलित करें",
    insertFileNameLabel: "फ़ाइल का नाम",
    insertFileNamePlaceHolder: "फ़ाइल का नाम...",
    insertFileTitle: "फ़ाइल सम्मिलित करें",
    insertFileURLLabel: "फ़ाइल यूआरएल",
    insertFileURLPlaceHolder: "फ़ाइल URL...",
    languageMenuTitle: "भाषा बदलें",
    linkCreateDialogCancelButton: "रद्द करें",
    linkCreateDialogMenuHeader: "एक लिंक प्रकार चुनें",
    linkCreateDialogOKButton: "लिंक सम्मिलित करें",
    linkCreateDialogTitle: "लिंक सम्मिलित करें",
    linkCreateTitle: "लिंक सम्मिलित करें",
    linkRemoveTitle: "लिंक निकालें",
    linkTypeDocumentHeader: "किसी दस्तावेज़ या अन्य फ़ाइल के लिए लिंक",
    linkTypeDocumentInfo: "<h2>नहीं यकीन है कि क्या इसके बाद के संस्करण बॉक्स में डाल दिया है?<\/h2><ol>    <li>सुनिश्चित करें कि आपकी वेबसाइट के लिए फ़ाइल अपलोड किया गया है।<\/li>    <li>अपलोड की गई फ़ाइल आपके ब्राउज़र में खोलें।<\/li>    <li>अपने ब्राउज़र की पता पट्टी से फ़ाइल के URL की प्रतिलिपि बनाएँ और इसे उपरोक्त बॉक्स में पेस्ट करें।<\/li><\/ol>",
    linkTypeDocumentLabel: "दस्तावेज़ या अन्य फ़ाइल",
    linkTypeDocumentLocationLabel: "स्थान:",
    linkTypeDocumentLocationPlaceHolder: "कोई URL दर्ज करें",
    linkTypeDocumentNewWindowHeader: "नई विंडो",
    linkTypeDocumentNewWindowLabel: "एक नई ब्राउज़र विंडो\/टैब में खोलें फ़ाइल के लिए इस बॉक्स को चेक करें।",
    linkTypeEmailHeader: "एक ईमेल पता करने के लिए लिंक",
    linkTypeEmailLabel: "ईमेल पता",
    linkTypeEmailSubjectLabel: "विषय (वैकल्पिक):",
    linkTypeEmailSubjectPlaceHolder: "विषय दर्ज करें",
    linkTypeEmailToLabel: "ईमेल:",
    linkTypeEmailToPlaceHolder: "ईमेल पता दर्ज करें",
    linkTypeExternalHeader: "एक अन्य वेबसाइट पर एक पृष्ठ से लिंक करें",
    linkTypeExternalInfo: "<h2>नहीं यकीन है कि क्या इसके बाद के संस्करण बॉक्स में डाल दिया है?<\/h2><ol>    <li>पृष्ठ लिंक करने के लिए इच्छित वेब पर खोजें।<\/li>    <li>अपने ब्राउज़र की पता बार से वेब पते की प्रतिलिपि बनाएँ और इसे उपरोक्त बॉक्स में पेस्ट करें।<\/li><\/ol>",
    linkTypeExternalLabel: "एक अन्य वेबसाइट पर पृष्ठ",
    linkTypeExternalLocationLabel: "स्थान:",
    linkTypeExternalLocationPlaceHolder: "कोई URL दर्ज करें",
    linkTypeExternalNewWindowHeader: "नई विंडो",
    linkTypeExternalNewWindowLabel: "एक नई ब्राउज़र विंडो\/टैब में खोलें लिंक है करने के लिए इस बॉक्स को चेक करें।",
    linkTypeInternalHeader: "इस वेबसाइट पर एक पृष्ठ से लिंक करें",
    linkTypeInternalInfo: "<h2>नहीं यकीन है कि क्या इसके बाद के संस्करण बॉक्स में डाल दिया है?<\/h2><ol>    <li>पृष्ठ पर इस साइट लिंक करने के लिए मिल।<\/li>    <li>अपने ब्राउज़र की पता पट्टी, \"{{domain}}\" को छोड़कर से वेब पते की प्रतिलिपि बनाएँ और इसे उपरोक्त बॉक्स में पेस्ट करें।<\/li><\/ol>",
    linkTypeInternalLabel: "इस वेबसाइट पर पृष्ठ",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "एक URI दर्ज करें",
    linkTypeInternalNewWindowHeader: "नई विंडो",
    linkTypeInternalNewWindowLabel: "एक नई ब्राउज़र विंडो\/टैब में खोलें लिंक है करने के लिए इस बॉक्स को चेक करें।",
    listOrderedTitle: "आदेश सूची",
    listUnorderedTitle: "Unordered सूची",
    logoTitle: "और Raptor WYSIWYG संपादक के बारे में जानें",
    loremIpsumTitle: "परीक्षण के लिए डमी पाठ सम्मिलित करें",
    navigateAway: "\nवहाँ परिवर्तन इस पेज पर बिना सहेजे गए हैं। \nयदि आप इस पृष्ठ से दूर नेविगेट आप अपने न सहेजे गए परिवर्तन खो देंगे",
    pasteDialogCancelButton: "रद्द करें",
    pasteDialogFormattedCleaned: "स्वरूपित और साफ किया",
    pasteDialogFormattedUnclean: "अस्वच्छ स्वरूपित किया गया",
    pasteDialogOKButton: "सम्मिलित करें",
    pasteDialogPlain: "सादा पाठ",
    pasteDialogSource: "स्रोत कोड",
    pasteDialogTitle: "चिपकाएँ",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "संशोधन को पुनः प्राप्त करने में विफल रहा",
    revisionsApplyButtonDialogCancelButton: "रद्द करें",
    revisionsApplyButtonDialogOKButton: "रोलबैक",
    revisionsApplyButtonDialogText: "रोलबैक पुष्टिकरण",
    revisionsApplyButtonDialogTitle: "रोलबैक पुष्टिकरण",
    revisionsApplyButtonText: "रोलबैक",
    revisionsApplyButtonTitle: "रोलबैक",
    revisionsApplyDialogContent: "यह चयनित संशोधन के साथ वर्तमान सामग्री बदल देगा।<br>वर्तमान सामग्री एक संशोधन के रूप में जोड़ दिया जाएगा, और इस खंड के लिए संशोधन सूची में दिखाई जाएगी।",
    revisionsButtonCurrent: "वर्तमान",
    revisionsButtonViewDiffText: "मतभेद",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "बनाया गया",
    revisionsDialogCancelButton: "रद्द करें",
    revisionsDialogTitle: "दृश्य सामग्री पुनरावलोकन",
    revisionsDiffButtonDialogCancelButton: "बंद करें",
    revisionsDiffButtonDialogTitle: "दृश्य अंतर",
    revisionsDiffButtonText: "दृश्य अंतर",
    revisionsDiffButtonTitle: "दृश्य अंतर",
    revisionsLoading: "पुनरावलोकन लोड हो रहा है...",
    revisionsNone: "इस तत्व के लिए कोई संशोधन",
    revisionsPreviewButtonText: "पूर्वावलोकन",
    revisionsPreviewButtonTitle: "पूर्वावलोकन",
    revisionsText: "पुनरावलोकन",
    revisionsTextEmpty: "कोई संशोधन",
    revisionsTitle: "",
    rfmClose: "बंद करें",
    rfmContinue: "जारी रखें",
    rfmDelete: "हटाएँ",
    rfmDownload: "डाउनलोड करें",
    rfmFileActions: "क्रियाएँ",
    rfmFileModificationTime: "संशोधित",
    rfmFileName: "नाम",
    rfmFileSize: "का आकार",
    rfmFileType: "प्रकार",
    rfmFilteredTotal: "{{start}} {{end}} के दिखा {{filteredTotal}} फ़ाइलें",
    rfmFirst: "प्रथम",
    rfmHeadingDirectories: "निर्देशिकाएँ",
    rfmHeadingSearch: "खोज",
    rfmHeadingTags: "टैग",
    rfmHeadingUpload: "अपलोड करें",
    rfmInsert: "सम्मिलित करें",
    rfmLast: "अंतिम",
    rfmSearch: "जाओ",
    rfmTagDocument: "दस्तावेज़",
    rfmTagImage: "छवि",
    rfmTotal: ", छान {{total}}",
    rfmUpload: "अपलोड करें",
    rfmUploadBrowse: "ब्राउज़ करें",
    rfmUploadDrop: "फ़ाइलें यहाँ छोड़ें",
    rfmUploadFileRemove: "निकालें",
    rfmUploadOr: "या",
    rfmView: "दृश्य",
    saveJsonFail: "{{failed}} सामग्री लुभाने सहेजने में विफल",
    saveJsonSaved: "{{saved}} सामग्री लुभाने सफलतापूर्वक सहेजा गया।",
    saveNotConfigured: "सहेजें नहीं कॉन्फ़िगर किया गया है, या अक्षम किया गया है।",
    saveRestFail: "{{failed}} सामग्री लुभाने सहेजने में विफल।",
    saveRestPartial: "{{saved}} सामग्री ब्लॉक से बाहर {{failed}} बचाया।",
    saveRestSaved: "{{saved}} सामग्री लुभाने सफलतापूर्वक सहेजा गया।",
    saveTitle: "बचाने के लिए सामग्री",
    snippetMenuTitle: "स्निपेट्स",
    specialCharactersArrows: "तीर",
    specialCharactersDialogOKButton: "ठीक है",
    specialCharactersDialogTitle: "विशेष वर्ण सम्मिलित करें",
    specialCharactersGreekAlphabet: "यूनानी वर्णमाला",
    specialCharactersHelp: "इसे जोड़ने के लिए कोई विशेष वर्ण क्लिक करें। \"इस संवाद को बंद करने के लिए जब किया ठीक\" क्लिक करें",
    specialCharactersMathematics: "गणित",
    specialCharactersSymbols: "प्रतीक",
    specialCharactersTitle: "कोई विशेष वर्ण सम्मिलित करें",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} वर्ण सीमा से अधिक",
    statisticsButtonCharacterRemaining: "शेष वर्ण {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} अक्षर",
    statisticsDialogCharactersOverLimit: "{{characters}} वर्णों, {{charactersRemaining}} की सिफारिश की सीमा से अधिक",
    statisticsDialogCharactersRemaining: "शेष {{characters}} अक्षर, {{charactersRemaining}}",
    statisticsDialogNotTruncated: "सामग्री छोटा नहीं हो जाएगा",
    statisticsDialogOKButton: "ठीक है",
    statisticsDialogSentence: "{{sentences}} वाक्य",
    statisticsDialogSentences: "{{sentences}} वाक्य",
    statisticsDialogTitle: "सामग्री आँकड़े",
    statisticsDialogTruncated: "सामग्री {{limit}} वर्णों से अधिक होता है और काटे जा सकते हैं",
    statisticsDialogWord: "{{words}} शब्द",
    statisticsDialogWords: "{{words}} शब्द",
    statisticsTitle: "आँकड़े देखने के लिए क्लिक करें",
    tableCreateTitle: "तालिका बनाएँ",
    tableDeleteColumnTitle: "तालिका स्तंभ हटाएँ",
    tableDeleteRowTitle: "तालिका पंक्ति हटाएँ",
    tableInsertColumnTitle: "तालिका स्तंभ सम्मिलित करें",
    tableInsertRowTitle: "तालिका पंक्ति सम्मिलित करें",
    tableMergeCellsTitle: "टेबल कोशिकाओं विलय",
    tableSplitCellsTitle: "तालिका कक्षों को विभाजित",
    tagMenuTagAddress: "पते",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "शीर्ष 1",
    tagMenuTagH2: "शीर्ष 2",
    tagMenuTagH3: "शीर्ष 3",
    tagMenuTagH4: "शीर्ष 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "अनुच्छेद",
    tagMenuTagPre: "पूर्व स्वरूपित",
    tagMenuTitle: "तत्व शैली परिवर्तित करें",
    tagTreeElementLink: "{{element}} तत्व का चयन करें",
    tagTreeElementTitle: "\"{{element}}\" तत्व की सामग्री का चयन करने के लिए क्लिक करें",
    tagTreeRoot: "रूट",
    tagTreeRootLink: "सभी संपादन योग्य सामग्री का चयन करें",
    tagTreeRootTitle: "सभी संपादन योग्य सामग्री का चयन करने के लिए क्लिक करें",
    textBlockQuoteTitle: "ब्लॉक उद्धरण",
    textBoldTitle: "बोल्ड",
    textItalicTitle: "इटैलिक",
    textSizeDecreaseTitle: "पाठ का आकार घटाएँ",
    textSizeIncreaseTitle: "पाठ का आकार बढ़ाएँ",
    textStrikeTitle: "स्ट्राइक थ्रू",
    textSubTitle: "उप-लिपि",
    textSuperTitle: "सुपर स्क्रिप्ट",
    textUnderlineTitle: "रेखांकित करें",
    unsavedEditWarningText: "वहाँ इस पृष्ठ पर परिवर्तन बिना सहेजे गए हैं",
    viewSourceDialogCancelButton: "बंद करें",
    viewSourceDialogOKButton: "स्रोत कोड लागू करें",
    viewSourceDialogTitle: "सामग्री स्रोत कोड",
    viewSourceTitle: "देखें\/स्रोत कोड संपादित करें"
});