/**
 * @fileOverview Haitian Creole strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ht', 'Kreyòl Ayisyen', {
    alignCenterTitle: "Fè aliman tèks sant",
    alignJustifyTitle: "Fè aliman tèks jistifye",
    alignLeftTitle: "Fè aliman tèks gòch",
    alignRightTitle: "Fè aliman tèks dwat",
    cancelDialogCancelButton: "Kontinye Modification",
    cancelDialogContent: "Eske ou si ou vle pou anile pwogram modification Tout chanjman p'ap pèdi.",
    cancelDialogOKButton: "Annuler Modification",
    cancelDialogTitle: "Annuler Modification",
    cancelTitle: "Annuler modification",
    classMenuTitle: "Estil sélecteur",
    clearFormattingTitle: "Clairement en",
    clickButtonToEditText: "Edite",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Otomatik",
    colorMenuBasicBlack: "Noua",
    colorMenuBasicBlue: "Blè",
    colorMenuBasicGreen: "Vèt",
    colorMenuBasicGrey: "Gri",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Vyolèt, mov",
    colorMenuBasicRed: "Rouj",
    colorMenuBasicTitle: "Chanje koulè tèks",
    colorMenuBasicWhite: "Blan",
    dockToElementTitle: "Waf\/undock editè pou eleman",
    dockToScreenTitle: "Waf\/undock editè pou écran",
    embedDialogCancelButton: "Anile",
    embedDialogOKButton: "Houke Objet",
    embedDialogTabCode: "Houke kòd",
    embedDialogTabCodeContent: "Pat kòd intégrer ou nan tèks zòn ki pi ba:",
    embedDialogTabPreview: "Aperçu",
    embedDialogTabPreviewContent: "Yon aperçu Des objets embedded ou s' pi ba pase:",
    embedDialogTitle: "Houke Objet",
    embedTitle: "Houke objet",
    errorUINoName: "UI, \"{{ui}}\" non (pou fè sa ki rete non)",
    errorUINotObject: "UI, \"{{ui}}\" non (dwe yon objet)",
    errorUIOverride: "UI, \"{{name}}\" ki deja te anrejistre, Et Sera remplacé",
    fileManagerDialogTitle: "Responsab yon fichier",
    fileManagerTitle: "Responsab yon fichier",
    floatLeftTitle: "Fè aliman estati a gosh",
    floatNoneTitle: "Retire estati fè aliman",
    floatRightTitle: "Fè aliman estati a dwat",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Bande san",
    fontFamilyMenuFontCourier: "Nouvo courrier",
    fontFamilyMenuFontDefault: "Klavye defo",
    fontFamilyMenuFontGeorgia: "Georgie",
    fontFamilyMenuFontImpact: "Enpak",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Fwa nouvo Romèn",
    fontFamilyMenuTitle: "Chwazi klavye ou",
    guidesTitle: "Montre eleman konsèy",
    historyRedoTitle: "Refè",
    historyUndoTitle: "Delage",
    hrCreateTitle: "Mete kouche plat ki t' ap mache sou",
    imageResizeButtonDialogCancelButton: "Anile",
    imageResizeButtonDialogHeight: "Imaj wotè",
    imageResizeButtonDialogHeightPlaceHolder: "Wotè",
    imageResizeButtonDialogOKButton: "Redimensionner",
    imageResizeButtonDialogTitle: "Redimensionner imaj",
    imageResizeButtonDialogWidth: "Imaj lajè",
    imageResizeButtonDialogWidthPlaceHolder: "Ajè",
    imageResizeButtonText: "Redimensionner imaj",
    insertFileDialogCancelButton: "Anile",
    insertFileDialogOKButton: "Mete fichier",
    insertFileNameLabel: "Fichier non",
    insertFileNamePlaceHolder: "Fichier non...",
    insertFileTitle: "Mete fichier",
    insertFileURLLabel: "Adrès entènèt fichier",
    insertFileURLPlaceHolder: "Adrès entènèt fichier...",
    languageMenuTitle: "Chanjman lang",
    linkCreateDialogCancelButton: "Anile",
    linkCreateDialogMenuHeader: "Chwazi yon jan ki lye de",
    linkCreateDialogOKButton: "Mete lyen",
    linkCreateDialogTitle: "Mete lyen",
    linkCreateTitle: "Mete lyen",
    linkRemoveTitle: "Retire lyen",
    linkTypeDocumentHeader: "Lien pou yon dokiman ou fichier lòt",
    linkTypeDocumentInfo: "<h2>Pa si sa pou yo mete yo nan bwat la CI-dessus?<\/h2><ol>    <li>Asire dokiman an te chargé pou ou sit entènèt.<\/li>    <li>Louvri chargé dokiman an nan browser ou.<\/li>    <li>Copie adrès entènèt dokiman an de browser ou adrès kafe Et pat li antre nan bwat la CI-dessus.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokiman ou fichier lòt",
    linkTypeDocumentLocationLabel: "Kote yo ye:",
    linkTypeDocumentLocationPlaceHolder: "Rantre nan yon adrès entènèt",
    linkTypeDocumentNewWindowHeader: "Nouvo fenèt",
    linkTypeDocumentNewWindowLabel: "Tyeke bwat sa a gen dokiman an te ouvwi nan yon nouvo browser fennèt\/onglet.",
    linkTypeEmailHeader: "Lien pou yon adrès kouryèll",
    linkTypeEmailLabel: "Mel adrès",
    linkTypeEmailSubjectLabel: "Sijè (opsyonèl):",
    linkTypeEmailSubjectPlaceHolder: "Rantre nan sijè",
    linkTypeEmailToLabel: "Mel:",
    linkTypeEmailToPlaceHolder: "Antre fè kouryèll adrès",
    linkTypeExternalHeader: "Lien pou yon paj sou sit entènèt yon lòt",
    linkTypeExternalInfo: "<h2>Pa si sa pou yo mete yo nan bwat la CI-dessus?<\/h2><ol>    <li>Chèche paj la sou entènèt la, ou vle Lien pou.<\/li>    <li>Copie adrès entènèt la nan browser ou adrès kafe Et pat li antre nan bwat la CI-dessus.<\/li><\/ol>",
    linkTypeExternalLabel: "Page sou sit entènèt yon lòt",
    linkTypeExternalLocationLabel: "Kote yo ye:",
    linkTypeExternalLocationPlaceHolder: "Rantre nan yon adrès entènèt",
    linkTypeExternalNewWindowHeader: "Nouvo fenèt",
    linkTypeExternalNewWindowLabel: "Tyeke bwat sa a gen lyen louvri nan yon nouvo browser fennèt\/onglet.",
    linkTypeInternalHeader: "Lien pou yon paj sou sit entènèt sa a",
    linkTypeInternalInfo: "<h2>Pa si sa pou yo mete yo nan bwat la CI-dessus?<\/h2><ol>    <li>Chèche paj la sou sa a kote ki gen lyen pou.<\/li>    <li>Copie adrès entènèt la nan adrès ou browser bar, Des \"{{domain}}\" Et pat li antre nan bwat la CI-dessus.<\/li><\/ol>",
    linkTypeInternalLabel: "Page sou sit entènèt sa a",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Rantre nan yon OURI",
    linkTypeInternalNewWindowHeader: "Nouvo fenèt",
    linkTypeInternalNewWindowLabel: "Tyeke bwat sa a gen lyen louvri nan yon nouvo browser fennèt\/onglet.",
    listOrderedTitle: "Lis a",
    listUnorderedTitle: "Lis non",
    logoTitle: "Aprann plis sou editè WYSIWYG Raptor",
    loremIpsumTitle: "Mete dantrènman tèks pou yo swiv lè",
    navigateAway: "\nGen sont enregistrées chanjman nan paj sa a. \nSi w navige kite paj sa a ou pral pèdi ou chanje non",
    pasteDialogCancelButton: "Anile",
    pasteDialogFormattedCleaned: "Fòmate &amp; pwòpte",
    pasteDialogFormattedUnclean: "Fòmate kondisyon",
    pasteDialogOKButton: "Apò",
    pasteDialogPlain: "La Plèn tèks",
    pasteDialogSource: "Sous kòd",
    pasteDialogTitle: "Mòtye",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Te tonbe pou rekipere révisions",
    revisionsApplyButtonDialogCancelButton: "Anile",
    revisionsApplyButtonDialogOKButton: "Ki dekouvri dediksyon an",
    revisionsApplyButtonDialogText: "Konfimasyon ki dekouvri dediksyon an",
    revisionsApplyButtonDialogTitle: "Konfimasyon ki dekouvri dediksyon an",
    revisionsApplyButtonText: "Ki dekouvri dediksyon an",
    revisionsApplyButtonTitle: "Ki dekouvri dediksyon an",
    revisionsApplyDialogContent: "Sa ap ranplase contenu aktyèl la ak lan, sélectionnée revizyon.<br>Contenu aktyèl la ap tankou yon revizyon ajouté, epi p'ap vizib nan lis révisions la pou blòk sa a.",
    revisionsButtonCurrent: "Kouran",
    revisionsButtonViewDiffText: "Diferans",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Te kreye",
    revisionsDialogCancelButton: "Anile",
    revisionsDialogTitle: "Révisions pi kontan wè",
    revisionsDiffButtonDialogCancelButton: "Fèmen",
    revisionsDiffButtonDialogTitle: "Wè diferans",
    revisionsDiffButtonText: "Wè diferans",
    revisionsDiffButtonTitle: "Wè diferans",
    revisionsLoading: "Chaje révisions...",
    revisionsNone: "Pa révisions pou eleman sa a",
    revisionsPreviewButtonText: "Aperçu",
    revisionsPreviewButtonTitle: "Aperçu",
    revisionsText: "Révisions",
    revisionsTextEmpty: "Révisions pa",
    revisionsTitle: "",
    rfmClose: "Fèmen",
    rfmContinue: "Kontinye",
    rfmDelete: "Retire",
    rfmDownload: "Rale dosye",
    rfmFileActions: "Aksyon",
    rfmFileModificationTime: "Modifye",
    rfmFileName: "fe-apel",
    rfmFileSize: "Taille",
    rfmFileType: "Tip",
    rfmFilteredTotal: "Affichage {{start}} pou {{end}} de fichiers {{filteredTotal}}",
    rfmFirst: "Premye",
    rfmHeadingDirectories: "Répertoires",
    rfmHeadingSearch: "Recherche",
    rfmHeadingTags: "Baj",
    rfmHeadingUpload: "Téléchargement",
    rfmInsert: "Apò",
    rfmLast: "Dire",
    rfmSearch: "Ale",
    rfmTagDocument: "Dokiman",
    rfmTagImage: "Estati",
    rfmTotal: ", filtrage depi {{total}} nan",
    rfmUpload: "Téléchargement",
    rfmUploadBrowse: "Parcourir",
    rfmUploadDrop: "Ane ke yo bliye Fichiers isit la",
    rfmUploadFileRemove: "Retire",
    rfmUploadOr: "ou",
    rfmView: "Vi",
    saveJsonFail: "Te tonbe pou sove block(s) contenu {{failed}}",
    saveJsonSaved: "Anpil siksè te sove block(s) contenu {{saved}}.",
    saveNotConfigured: "Save ki pa te configuré, ou andikape.",
    saveRestFail: "Te tonbe pou sove {{failed}} block(s) contenu.",
    saveRestPartial: "Te sove {{saved}} nan blòk contenu {{failed}}.",
    saveRestSaved: "Anpil siksè te sove block(s) contenu {{saved}}.",
    saveTitle: "Mete sou kote contenu",
    snippetMenuTitle: "Extraits",
    specialCharactersArrows: "Flèch",
    specialCharactersDialogOKButton: "Oke",
    specialCharactersDialogTitle: "Mete Caractères espesyal",
    specialCharactersGreekAlphabet: "Alfabèt grèk",
    specialCharactersHelp: "Sur yon karaktè espesyal pou ajoute sa. Sur \"Bon\" lè fè pou fèmen dialog sa a",
    specialCharactersMathematics: "Matematik",
    specialCharactersSymbols: "Senbòl",
    specialCharactersTitle: "Mete yon karaktè espesyal",
    statisticsButtonCharacterOverLimit: "caractères {{charactersRemaining}} sou fwontyè",
    statisticsButtonCharacterRemaining: "caractères {{charactersRemaining}}, ki te rete",
    statisticsButtonCharacters: "caractères {{characters}}",
    statisticsDialogCharactersOverLimit: "{{characters}} caractères, {{charactersRemaining}} sou fwontyè recommandé",
    statisticsDialogCharactersRemaining: "{{characters}} caractères, {{charactersRemaining}} ki te rete",
    statisticsDialogNotTruncated: "Contenu a pa être tronqué",
    statisticsDialogOKButton: "Oke",
    statisticsDialogSentence: "fraz matematik {{sentences}}",
    statisticsDialogSentences: "{{sentences}} peines",
    statisticsDialogTitle: "Contenu Statistiques",
    statisticsDialogTruncated: "Contenu contient plis pase caractères {{limit}} Et ka tronqué",
    statisticsDialogWord: "di {{words}}",
    statisticsDialogWords: "mots {{words}}",
    statisticsTitle: "Sur pou wè statistiques",
    tableCreateTitle: "Kreye tab la",
    tableDeleteColumnTitle: "Retire kolòn tab la",
    tableDeleteRowTitle: "Retire tab la ligne",
    tableInsertColumnTitle: "Mete tab la rèl do",
    tableInsertRowTitle: "Mete tab la ligne",
    tableMergeCellsTitle: "Èstriti cellules tab la",
    tableSplitCellsTitle: "Ranp tab cellules",
    tagMenuTagAddress: "Adrès",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Rubrique 1",
    tagMenuTagH2: "Rubrique 2",
    tagMenuTagH3: "Rubrique, 3",
    tagMenuTagH4: "Rubrique, 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Paragraph",
    tagMenuTagPre: "Fòmate ki te fèt avan",
    tagMenuTitle: "Chanje fason eleman",
    tagTreeElementLink: "Fè chwa eleman {{element}}",
    tagTreeElementTitle: "Sur pou yo chwazi a eleman \"{{element}}\" sa ki nan liv",
    tagTreeRoot: "rasin",
    tagTreeRootLink: "Fè chwa tout contenu modifiable",
    tagTreeRootTitle: "Sur pou yo chwazi tout contenu modifiable",
    textBlockQuoteTitle: "Site blòk",
    textBoldTitle: "Gras",
    textItalicTitle: "En",
    textSizeDecreaseTitle: "Vini pi piti tèks taille",
    textSizeIncreaseTitle: "Fè vini pi gran tèks taille",
    textStrikeTitle: "Leve men sou à",
    textSubTitle: "Script de baz",
    textSuperTitle: "Super-script",
    textUnderlineTitle: "Soulinye",
    unsavedEditWarningText: "Gen sont enregistrées chanjman nan paj sa a",
    viewSourceDialogCancelButton: "Fèmen",
    viewSourceDialogOKButton: "Aplike sous kòd",
    viewSourceDialogTitle: "Contenu sous kòd",
    viewSourceTitle: "Wè\/edisyon sous kòd"
});