/**
 * @fileOverview Hungarian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('hu', 'magyar', {
    alignCenterTitle: "Felsorakoztat szöveg központ",
    alignJustifyTitle: "A szöveg igazítása indokolja",
    alignLeftTitle: "Szöveg balra igazítása",
    alignRightTitle: "Szöveg jobbra igazítása",
    cancelDialogCancelButton: "Tovább a Szerkesztés",
    cancelDialogContent: "Biztosan megszakítja a szerkesztő? Minden módosítás elvész!",
    cancelDialogOKButton: "Módosítás törlése",
    cancelDialogTitle: "Módosítás törlése",
    cancelTitle: "Módosítás törlése",
    classMenuTitle: "Stílus Pipetta",
    clearFormattingTitle: "Formázás törlése",
    clickButtonToEditText: "Szerkesztése",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatikus",
    colorMenuBasicBlack: "Fekete",
    colorMenuBasicBlue: "Kék",
    colorMenuBasicGreen: "Zöld",
    colorMenuBasicGrey: "Szürke",
    colorMenuBasicOrange: "Narancs",
    colorMenuBasicPurple: "Lila",
    colorMenuBasicRed: "Piros",
    colorMenuBasicTitle: "Szöveg színének módosítása",
    colorMenuBasicWhite: "Fehér",
    dockToElementTitle: "Dokk\/dokkolásának megszüntetése elem-szerkesztő",
    dockToScreenTitle: "Szerkesztő-hoz képernyő dokk\/dokkolásának megszüntetése",
    embedDialogCancelButton: "Mégse",
    embedDialogOKButton: "Beágyazott objektum",
    embedDialogTabCode: "Beágyaz kód",
    embedDialogTabCodeContent: "Illessze be az embed kódot a szöveg terület az alábbi:",
    embedDialogTabPreview: "Előnézet",
    embedDialogTabPreviewContent: "A beágyazott objektumot egy képe alatt jelenik meg:",
    embedDialogTitle: "Beágyazott objektum",
    embedTitle: "Beágyazott objektum",
    errorUINoName: "UI: \"{{ui}}\" érvénytelen (kell rendelkeznie a name tulajdonság)",
    errorUINotObject: "UI: \"{{ui}}\" érvénytelen (kell egy objektum)",
    errorUIOverride: "UI: \"{{name}}\" már regisztrált, és felül lesz írva",
    fileManagerDialogTitle: "Fájlkezelő",
    fileManagerTitle: "Fájlkezelő",
    floatLeftTitle: "Kép balra igazítás",
    floatNoneTitle: "Távolítsa el a kép igazítása",
    floatRightTitle: "Jobb kép igazítása",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Képregény, anélkül",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Alapértelmezett betűtípus",
    fontFamilyMenuFontGeorgia: "Grúzia",
    fontFamilyMenuFontImpact: "Hatása",
    fontFamilyMenuFontPalatino: "Nádor",
    fontFamilyMenuFontTimes: "Idő új római",
    fontFamilyMenuTitle: "Válassza a betűtípus",
    guidesTitle: "Elem Vezetővonalak megjelenítése",
    historyRedoTitle: "Ismét:",
    historyUndoTitle: "Visszavonás",
    hrCreateTitle: "Helyezze be a vízszintes díszítővonal",
    imageResizeButtonDialogCancelButton: "Mégse",
    imageResizeButtonDialogHeight: "Kép magassága",
    imageResizeButtonDialogHeightPlaceHolder: "Magasság",
    imageResizeButtonDialogOKButton: "Átméretezése",
    imageResizeButtonDialogTitle: "Kép átméretezése",
    imageResizeButtonDialogWidth: "Image szélességű",
    imageResizeButtonDialogWidthPlaceHolder: "Szélessége",
    imageResizeButtonText: "Kép átméretezése",
    insertFileDialogCancelButton: "Mégse",
    insertFileDialogOKButton: "Fájl beszúrása",
    insertFileNameLabel: "Fájlnév",
    insertFileNamePlaceHolder: "Fájl név...",
    insertFileTitle: "Fájl beszúrása",
    insertFileURLLabel: "Fájl URL-címe",
    insertFileURLPlaceHolder: "Fájl URL...",
    languageMenuTitle: "Nyelv módosítása",
    linkCreateDialogCancelButton: "Mégse",
    linkCreateDialogMenuHeader: "Válassza ki a hivatkozás típusa",
    linkCreateDialogOKButton: "Hivatkozás beszúrása",
    linkCreateDialogTitle: "Hivatkozás beszúrása",
    linkCreateTitle: "Hivatkozás beszúrása",
    linkRemoveTitle: "Hivatkozás eltávolítása",
    linkTypeDocumentHeader: "A dokumentum vagy egyéb fájl csatolása",
    linkTypeDocumentInfo: "<h2>Nem persze mit tenni betesz a doboz fenti?<\/h2><ol>    <li>Győződjön meg arról, a reszelő van feltöltött-hoz-a website.<\/li>    <li>Nyissa meg a feltöltött fájl a böngészőben.<\/li>    <li>Másolja a fájl URL-címet a böngésző címsorába, és illessze be a fenti mezőbe.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumentum vagy egyéb fájl",
    linkTypeDocumentLocationLabel: "Helyszín:",
    linkTypeDocumentLocationPlaceHolder: "Adjon meg egy URL-t",
    linkTypeDocumentNewWindowHeader: "Új ablak",
    linkTypeDocumentNewWindowLabel: "A négyzet bejelölésével a fájlt egy új böngésző ablakban\/lapon nyissa meg.",
    linkTypeEmailHeader: "Láncszem-hoz egy elektronikus levél cím",
    linkTypeEmailLabel: "Elektronikus levél cím",
    linkTypeEmailSubjectLabel: "Tárgy (nem kötelező):",
    linkTypeEmailSubjectPlaceHolder: "Írja be a tárgy",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Adja meg e-mail címét",
    linkTypeExternalHeader: "Láncszem-hoz egy oldal egy másik weboldalon",
    linkTypeExternalInfo: "<h2>Nem persze mit tenni betesz a doboz fenti?<\/h2><ol>    <li>Talál a oldal az interneten, ön akar-hoz láncszem-hoz.<\/li>    <li>Másolja a webcímet a böngésző címsorába, és illessze be a fenti mezőbe.<\/li><\/ol>",
    linkTypeExternalLabel: "Egy másik weboldalon oldal",
    linkTypeExternalLocationLabel: "Helyszín:",
    linkTypeExternalLocationPlaceHolder: "Adjon meg egy URL-t",
    linkTypeExternalNewWindowHeader: "Új ablak",
    linkTypeExternalNewWindowLabel: "A négyzet bejelölésével a linket egy új böngésző ablakban\/lapon nyissa meg.",
    linkTypeInternalHeader: "Láncszem-hoz egy oldalt ezen a honlapon",
    linkTypeInternalInfo: "<h2>Nem persze mit tenni betesz a doboz fenti?<\/h2><ol>    <li>Az erre a helyhivatkozásra, hogy az oldalon talál.<\/li>    <li>Másolja a webcímet a böngésző cím büfé, kivéve a \"{{domain}}\", és illessze be a fenti mezőbe.<\/li><\/ol>",
    linkTypeInternalLabel: "Ezen a honlapon oldalt",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Adjon meg egy URI",
    linkTypeInternalNewWindowHeader: "Új ablak",
    linkTypeInternalNewWindowLabel: "A négyzet bejelölésével a linket egy új böngésző ablakban\/lapon nyissa meg.",
    listOrderedTitle: "Rendezett lista",
    listUnorderedTitle: "Rendezetlen lista",
    logoTitle: "Tudjon meg többet a Raptor WYSIWYG szerkesztő",
    loremIpsumTitle: "Helyezze be a dummy text vizsgálatra",
    navigateAway: "\nMentetlen módosítások ezen az oldalon. \nHa ezen az oldalon a nem mentett változtatások elvesznek",
    pasteDialogCancelButton: "Mégse",
    pasteDialogFormattedCleaned: "Formázott &amp; tisztítani",
    pasteDialogFormattedUnclean: "Formázott tisztátalan",
    pasteDialogOKButton: "Beszúrása",
    pasteDialogPlain: "Egyszerű szöveg",
    pasteDialogSource: "Forráskód",
    pasteDialogTitle: "Paszta",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Nem sikerült beolvasni a felülvizsgálatok",
    revisionsApplyButtonDialogCancelButton: "Mégse",
    revisionsApplyButtonDialogOKButton: "Visszaállítás",
    revisionsApplyButtonDialogText: "Visszaigazolást visszaállítást",
    revisionsApplyButtonDialogTitle: "Visszaigazolást visszaállítást",
    revisionsApplyButtonText: "Visszaállítás",
    revisionsApplyButtonTitle: "Visszaállítás",
    revisionsApplyDialogContent: "Ez felváltja a jelenlegi tartalom kijelölt felülvizsgálata.<br>A jelenlegi tartalom lesz hozzáadott mint egy felülvizsgálat, és ennek a blokknak a felülvizsgálatok listában látható lesz.",
    revisionsButtonCurrent: "Aktuális",
    revisionsButtonViewDiffText: "Különbségek",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Készítette:",
    revisionsDialogCancelButton: "Mégse",
    revisionsDialogTitle: "Nézd tartalmi felülvizsgálata",
    revisionsDiffButtonDialogCancelButton: "Zár",
    revisionsDiffButtonDialogTitle: "Nézet különbségek",
    revisionsDiffButtonText: "Nézet különbségek",
    revisionsDiffButtonTitle: "Nézet különbségek",
    revisionsLoading: "Átvilágítások betöltése...",
    revisionsNone: "Ehhez az elemhez nem felülvizsgálatok",
    revisionsPreviewButtonText: "Előnézet",
    revisionsPreviewButtonTitle: "Előnézet",
    revisionsText: "Felülvizsgálatok",
    revisionsTextEmpty: "Nincs felülvizsgálatok",
    revisionsTitle: "",
    rfmClose: "Zár",
    rfmContinue: "Továbbra is",
    rfmDelete: "Törlése",
    rfmDownload: "Letöltés",
    rfmFileActions: "Műveletek",
    rfmFileModificationTime: "Módosított",
    rfmFileName: "név",
    rfmFileSize: "Méret",
    rfmFileType: "Típus",
    rfmFilteredTotal: "A {{start}} fájlok befejezéséhez {{end}} {{filteredTotal}} találat",
    rfmFirst: "Első",
    rfmHeadingDirectories: "Könyvtárak",
    rfmHeadingSearch: "Szálláshelyek keresése",
    rfmHeadingTags: "Címkék",
    rfmHeadingUpload: "Feltöltés",
    rfmInsert: "Beszúrása",
    rfmLast: "Utolsó",
    rfmSearch: "Megy",
    rfmTagDocument: "Dokumentum",
    rfmTagImage: "Kép",
    rfmTotal: ", szűrt {{total}}",
    rfmUpload: "Feltöltés",
    rfmUploadBrowse: "Tallózás",
    rfmUploadDrop: "Húzza ide a fájlok",
    rfmUploadFileRemove: "Eltávolítása",
    rfmUploadOr: "vagy",
    rfmView: "Nézet",
    saveJsonFail: "Nem sikerült menteni a {{failed}} tartalom blokk (ok)",
    saveJsonSaved: "Sikeresen mentette a {{saved}} tartalom blokk (ok).",
    saveNotConfigured: "Mentés nincs beállítva vagy le van tiltva.",
    saveRestFail: "Nem sikerült menteni a {{failed}} tartalom blokk (ok).",
    saveRestPartial: "Mentett {{saved}} {{failed}} tartalom építõelemei ki.",
    saveRestSaved: "Sikeresen mentette a {{saved}} tartalom blokk (ok).",
    saveTitle: "Tartalom mentése",
    snippetMenuTitle: "Mozaik",
    specialCharactersArrows: "Nyilak",
    specialCharactersDialogOKButton: "oké",
    specialCharactersDialogTitle: "Különleges karakterek beszúrásához",
    specialCharactersGreekAlphabet: "Görög ábécé",
    specialCharactersHelp: "Kattintson a speciális karaktert adja hozzá. Kattintson az \"OK\" Ha végzett, zárja be a párbeszédpanelt",
    specialCharactersMathematics: "Matematika",
    specialCharactersSymbols: "Szimbólumok",
    specialCharactersTitle: "A különleges karakter beszúrása",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} karakter felső határ",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} beírható karakterek száma még",
    statisticsButtonCharacters: "{{characters}} karakterek",
    statisticsDialogCharactersOverLimit: "{{characters}} karakter, {{charactersRemaining}} a javasolt korlátnál több mint",
    statisticsDialogCharactersRemaining: "{{characters}} karakter, a {{charactersRemaining}} a fennmaradó",
    statisticsDialogNotTruncated: "Tartalom nem lesz megcsonkított",
    statisticsDialogOKButton: "oké",
    statisticsDialogSentence: "{{sentences}} mondat",
    statisticsDialogSentences: "{{sentences}} mondatok",
    statisticsDialogTitle: "Tartalom statisztika",
    statisticsDialogTruncated: "Tartalom több, mint {{limit}} karakterek és csonkított",
    statisticsDialogWord: "{{words}} szó",
    statisticsDialogWords: "{{words}} szavak",
    statisticsTitle: "Kattintson a statisztika megtekintése",
    tableCreateTitle: "Táblázat létrehozása",
    tableDeleteColumnTitle: "Táblázat oszlop törlése",
    tableDeleteRowTitle: "Táblázat sorának törlése",
    tableInsertColumnTitle: "Táblázat oszlop beszúrása",
    tableInsertRowTitle: "Táblázatsor beszúrása",
    tableMergeCellsTitle: "Táblázatcellák egyesítése",
    tableSplitCellsTitle: "Táblázatcellák felosztása",
    tagMenuTagAddress: "Cím",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Címsor 1",
    tagMenuTagH2: "Címsor 2",
    tagMenuTagH3: "Címsor 3",
    tagMenuTagH4: "Fejezet 4",
    tagMenuTagNA: "NINCS ADAT",
    tagMenuTagP: "Bekezdés",
    tagMenuTagPre: "Előre formázott",
    tagMenuTitle: "Elem stílusának módosítása",
    tagTreeElementLink: "Válasszon elemet a(z) {{element}} elem",
    tagTreeElementTitle: "Jelölje be a \"{{element}}\" elem tartalmának",
    tagTreeRoot: "gyökér",
    tagTreeRootLink: "Minden szerkeszthető tartalom kijelölése",
    tagTreeRootTitle: "Jelölje be a minden szerkeszthető tartalom",
    textBlockQuoteTitle: "Idézetblokk",
    textBoldTitle: "Merész",
    textItalicTitle: "Dőlt",
    textSizeDecreaseTitle: "Szövegméret csökkentése",
    textSizeIncreaseTitle: "Szövegméret növelése",
    textStrikeTitle: "Áthúzott",
    textSubTitle: "Al script",
    textSuperTitle: "Szuper-script",
    textUnderlineTitle: "Aláhúzás",
    unsavedEditWarningText: "Mentetlen módosítások ezen az oldalon",
    viewSourceDialogCancelButton: "Zár",
    viewSourceDialogOKButton: "Alkalmazni a forrás kód",
    viewSourceDialogTitle: "Tartalomforrás-kód",
    viewSourceTitle: "Megtekintése\/szerkesztése forrás kód"
});