/**
 * @fileOverview Indonesian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('id', 'Indonesia', {
    alignCenterTitle: "Align pusat teks",
    alignJustifyTitle: "Sejajarkan teks membenarkan",
    alignLeftTitle: "Sejajarkan teks kiri",
    alignRightTitle: "Sejajarkan teks kanan",
    cancelDialogCancelButton: "Lanjutkan mengedit",
    cancelDialogContent: "Apakah Anda yakin mau membatalkan mengedit? Semua perubahan akan hilang!",
    cancelDialogOKButton: "Membatalkan mengedit",
    cancelDialogTitle: "Membatalkan mengedit",
    cancelTitle: "Membatalkan mengedit",
    classMenuTitle: "Gaya picker",
    clearFormattingTitle: "Menghapus pemformatan",
    clickButtonToEditText: "Mengedit",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Otomatis",
    colorMenuBasicBlack: "Hitam",
    colorMenuBasicBlue: "Biru",
    colorMenuBasicGreen: "Hijau",
    colorMenuBasicGrey: "Abu-abu",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Ungu",
    colorMenuBasicRed: "Merah",
    colorMenuBasicTitle: "Mengubah warna teks",
    colorMenuBasicWhite: "Putih",
    dockToElementTitle: "Dermaga\/undock editor untuk elemen",
    dockToScreenTitle: "Dermaga\/undock editor untuk layar",
    embedDialogCancelButton: "Batal",
    embedDialogOKButton: "Menanamkan objek",
    embedDialogTabCode: "Menempelkan kode",
    embedDialogTabCodeContent: "Paste kode embed ke dalam area teks di bawah ini:",
    embedDialogTabPreview: "Tinjauan",
    embedDialogTabPreviewContent: "Preview tertanam objek ditampilkan di bawah ini:",
    embedDialogTitle: "Menanamkan objek",
    embedTitle: "Menanamkan objek",
    errorUINoName: "UI \"{{ui}}\" tidak valid (harus memiliki name properti)",
    errorUINotObject: "UI \"{{ui}}\" tidak valid (harus objek)",
    errorUIOverride: "UI \"{{name}}\" telah terdaftar, dan akan ditimpa",
    fileManagerDialogTitle: "Manajer file",
    fileManagerTitle: "Manajer file",
    floatLeftTitle: "Menyelaraskan gambar ke kiri",
    floatNoneTitle: "Menghapus gambar sejajar",
    floatRightTitle: "Menyelaraskan gambar di sebelah kanan",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komik tanpa",
    fontFamilyMenuFontCourier: "Kurir baru",
    fontFamilyMenuFontDefault: "Default Font",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Dampak",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Memilih huruf",
    guidesTitle: "Tampilkan elemen panduan",
    historyRedoTitle: "Mengulang",
    historyUndoTitle: "Membatalkan",
    hrCreateTitle: "Menyisipkan garis horizontal",
    imageResizeButtonDialogCancelButton: "Batal",
    imageResizeButtonDialogHeight: "Tinggi gambar",
    imageResizeButtonDialogHeightPlaceHolder: "Tinggi",
    imageResizeButtonDialogOKButton: "Mengubah ukuran",
    imageResizeButtonDialogTitle: "Resize gambar",
    imageResizeButtonDialogWidth: "Lebar gambar",
    imageResizeButtonDialogWidthPlaceHolder: "Lebar",
    imageResizeButtonText: "Resize gambar",
    insertFileDialogCancelButton: "Batal",
    insertFileDialogOKButton: "Menyisipkan file",
    insertFileNameLabel: "Nama file",
    insertFileNamePlaceHolder: "Nama file...",
    insertFileTitle: "Menyisipkan file",
    insertFileURLLabel: "File URL",
    insertFileURLPlaceHolder: "File URL...",
    languageMenuTitle: "Mengubah bahasa",
    linkCreateDialogCancelButton: "Batal",
    linkCreateDialogMenuHeader: "Pilih jenis link",
    linkCreateDialogOKButton: "Masukkan Link",
    linkCreateDialogTitle: "Masukkan Link",
    linkCreateTitle: "Masukkan Link",
    linkRemoveTitle: "Menghapus Link",
    linkTypeDocumentHeader: "Link ke dokumen atau file lain",
    linkTypeDocumentInfo: "<h2>Tidak yakin apa yang harus dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Pastikan file yang telah di-upload ke situs web Anda.<\/li>    <li>Buka file upload di browser Anda.<\/li>    <li>Salin file URL dari browser Anda address bar dan paste ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumen atau file lain",
    linkTypeDocumentLocationLabel: "Lokasi:",
    linkTypeDocumentLocationPlaceHolder: "Masukkan URL",
    linkTypeDocumentNewWindowHeader: "Jendela baru",
    linkTypeDocumentNewWindowLabel: "Centang kotak ini untuk memiliki file terbuka di browser window baru\/tab.",
    linkTypeEmailHeader: "Link ke alamat email",
    linkTypeEmailLabel: "Alamat email",
    linkTypeEmailSubjectLabel: "Subjek (opsional):",
    linkTypeEmailSubjectPlaceHolder: "Masukkan subjek",
    linkTypeEmailToLabel: "Email:",
    linkTypeEmailToPlaceHolder: "Masukkan alamat email",
    linkTypeExternalHeader: "Link ke halaman di situs lain",
    linkTypeExternalInfo: "<h2>Tidak yakin apa yang harus dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Menemukan halaman web yang Anda ingin link ke.<\/li>    <li>Salin alamat web dari address bar browser Anda dan paste ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeExternalLabel: "Halaman pada situs web lain",
    linkTypeExternalLocationLabel: "Lokasi:",
    linkTypeExternalLocationPlaceHolder: "Masukkan URL",
    linkTypeExternalNewWindowHeader: "Jendela baru",
    linkTypeExternalNewWindowLabel: "Centang kotak ini untuk memiliki link terbuka di browser window baru\/tab.",
    linkTypeInternalHeader: "Link ke halaman di situs ini",
    linkTypeInternalInfo: "<h2>Tidak yakin apa yang harus dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Menemukan halaman link situs ini untuk.<\/li>    <li>Salin alamat web dari browser Anda Alamat bar, termasuk \"{{domain}}\" dan sisipkan ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeInternalLabel: "Halaman di situs ini",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Masukkan URI",
    linkTypeInternalNewWindowHeader: "Jendela baru",
    linkTypeInternalNewWindowLabel: "Centang kotak ini untuk memiliki link terbuka di browser window baru\/tab.",
    listOrderedTitle: "Daftar",
    listUnorderedTitle: "Daftar unordered",
    logoTitle: "Pelajari lebih lanjut tentang Raptor WYSIWYG Editor",
    navigateAway: "\nSana adalah perubahan yang belum disimpan pada Halaman ini. \nJika Anda keluar dari Halaman ini Anda akan kehilangan perubahan Anda belum disimpan",
    pasteDialogCancelButton: "Batal",
    pasteDialogFormattedCleaned: "Diformat &amp; dibersihkan",
    pasteDialogFormattedUnclean: "Diformat najis",
    pasteDialogOKButton: "Masukkan",
    pasteDialogPlain: "Teks biasa",
    pasteDialogSource: "Kode sumber",
    pasteDialogTitle: "Pasta",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Gagal untuk mengambil revisi",
    revisionsApplyButtonDialogCancelButton: "Batal",
    revisionsApplyButtonDialogOKButton: "Rollback",
    revisionsApplyButtonDialogTitle: "Konfirmasi rollback",
    revisionsApplyButtonTitle: "Rollback",
    revisionsApplyDialogContent: "Ini akan mengganti konten saat ini dengan revisi yang dipilih.<br>Konten saat ini akan ditambahkan sebagai revisi, dan akan terlihat dalam daftar revisi untuk blok ini.",
    revisionsButtonCurrent: "Saat ini",
    revisionsButtonViewDiffText: "Perbedaan",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Batal",
    revisionsDialogTitle: "Lihat konten revisi",
    revisionsDiffButtonDialogCancelButton: "Tutup",
    revisionsDiffButtonDialogTitle: "Lihat perbedaan",
    revisionsDiffButtonTitle: "Lihat perbedaan",
    revisionsLoading: "Memuat revisi...",
    revisionsNone: "Tidak ada revisi untuk elemen ini",
    revisionsPreviewButtonTitle: "Tinjauan",
    revisionsText: "Revisi",
    revisionsTextEmpty: "Revisi tidak",
    revisionsTitle: "",
    rfmClose: "Tutup",
    rfmContinue: "Lanjutkan",
    rfmDelete: "Hapus",
    rfmDownload: "Men-download",
    rfmFileActions: "Tindakan",
    rfmFileModificationTime: "Dimodifikasi",
    rfmFileName: "Nama",
    rfmFileSize: "Ukuran",
    rfmFileType: "Jenis",
    rfmFilteredTotal: "Menampilkan {{start}} sampai {{end}} {{filteredTotal}} file",
    rfmFirst: "Pertama",
    rfmHeadingDirectories: "Direktori",
    rfmHeadingSearch: "Cari",
    rfmHeadingTags: "Tag",
    rfmHeadingUpload: "Meng-upload",
    rfmInsert: "Masukkan",
    rfmLast: "Terakhir",
    rfmSearch: "Pergi",
    rfmTotal: ", disaring dari {{total}}",
    rfmUpload: "Meng-upload",
    rfmUploadBrowse: "Jelajahi",
    rfmUploadDrop: "Drop file di sini",
    rfmUploadFileRemove: "Hapus",
    rfmView: "Pemandangan",
    saveJsonFail: "Gagal untuk menyimpan block(s) konten {{failed}}",
    saveJsonSaved: "Berhasil disimpan {{saved}} block(s) konten.",
    saveNotConfigured: "Simpan belum dikonfigurasi, atau dinonaktifkan.",
    saveRestFail: "Gagal untuk menyimpan {{failed}} block(s) konten.",
    saveRestPartial: "Menyelamatkan {{saved}} dari blok-blok konten {{failed}}.",
    saveRestSaved: "Berhasil disimpan {{saved}} block(s) konten.",
    saveTitle: "Menyimpan konten",
    snippetMenuTitle: "Potongan",
    specialCharactersDialogOKButton: "Oke",
    specialCharactersDialogTitle: "Menyisipkan karakter khusus",
    specialCharactersHelp: "Klik karakter khusus untuk menambahkannya. Klik \"OK\" ketika dilakukan untuk menutup dialog ini",
    specialCharactersTitle: "Menyisipkan karakter khusus",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} karakter atas batas",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} karakter tersisa",
    statisticsButtonCharacters: "{{characters}} karakter",
    statisticsDialogCharactersOverLimit: "{{characters}} karakter, {{charactersRemaining}} atas batas direkomendasikan",
    statisticsDialogCharactersRemaining: "karakter {{characters}}, {{charactersRemaining}} tersisa",
    statisticsDialogNotTruncated: "Konten tidak akan terpotong",
    statisticsDialogOKButton: "Oke",
    statisticsDialogSentence: "kalimat {{sentences}}",
    statisticsDialogSentences: "kalimat {{sentences}}",
    statisticsDialogTitle: "Statistik isi",
    statisticsDialogTruncated: "Konten yang berisi lebih dari {{limit}} karakter dan mungkin terpotong",
    statisticsDialogWord: "kata {{words}}",
    statisticsDialogWords: "kata-kata {{words}}",
    statisticsTitle: "Klik untuk melihat statistik",
    tableCreateTitle: "Membuat tabel",
    tableDeleteColumnTitle: "Menghapus kolom table",
    tableDeleteRowTitle: "Menghapus baris tabel",
    tableInsertColumnTitle: "Masukkan kolom table",
    tableInsertRowTitle: "Menyisipkan baris tabel",
    tableMergeCellsTitle: "Menggabungkan sel-sel tabel",
    tableSplitCellsTitle: "Sel-sel tabel Split",
    tagMenuTagAddress: "Alamat",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Pos 1",
    tagMenuTagH2: "Pos 2",
    tagMenuTagH3: "Judul 3",
    tagMenuTagH4: "Pos 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Ayat",
    tagMenuTagPre: "Pra-diformat",
    tagMenuTitle: "Mengubah elemen gaya",
    tagTreeElementLink: "Memilih elemen {{element}}",
    tagTreeElementTitle: "Klik untuk memilih isi dari elemen \"{{element}}\"",
    tagTreeRoot: "akar",
    tagTreeRootLink: "Pilih Semua konten dapat diedit",
    tagTreeRootTitle: "Klik untuk memilih semua konten dapat diedit",
    textBlockQuoteTitle: "Blok kutipan",
    textBoldTitle: "Bold",
    textItalicTitle: "Miring",
    textSizeDecreaseTitle: "Pengurangan ukuran teks",
    textSizeIncreaseTitle: "Meningkatkan ukuran teks",
    textStrikeTitle: "Menyerang melalui",
    textSubTitle: "Sub script",
    textSuperTitle: "Super script",
    textUnderlineTitle: "Menggarisbawahi",
    unsavedEditWarningText: "Sana adalah perubahan yang belum disimpan pada Halaman ini",
    viewSourceDialogCancelButton: "Tutup",
    viewSourceDialogOKButton: "Menerapkan kode sumber",
    viewSourceDialogTitle: "Kode sumber konten",
    viewSourceTitle: "Lihat\/edit kode sumber"
});