<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ar.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>bg.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ca.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>zh-CHS.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>zh-CHT.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>cs.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>da.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>nl.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>en.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>et.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>fa.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>fi.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>fr.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>de.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>el.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ht.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>he.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>hi.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>hu.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>id.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>it.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ja.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ko.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>lv.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>lt.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ms.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>mww.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>no.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>pl.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>pt.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ro.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ru.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>sk.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>sl.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>es.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>sv.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>th.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>tr.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>uk.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>ur.js"></script>
<script type="text/javascript" src="<?= RAPTOR_LOCALES_URI; ?>vi.js"></script>
