/**
 * @fileOverview Italian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('it', 'Italiano', {
    alignCenterTitle: "Allineare testo centro",
    alignJustifyTitle: "Allineare il testo giustificare",
    alignLeftTitle: "Allineare testo sinistra",
    alignRightTitle: "Allineare a destra il testo",
    cancelDialogCancelButton: "Continuare la modifica",
    cancelDialogContent: "Sei sicuro di che voler annullare la modifica? Tutte le modifiche andranno perse!",
    cancelDialogOKButton: "Annullare la modifica",
    cancelDialogTitle: "Annullare la modifica",
    cancelTitle: "Annullare la modifica",
    classMenuTitle: "Selettore di stile",
    clearFormattingTitle: "Annullare la formattazione",
    clickButtonToEditText: "Modifica",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatico",
    colorMenuBasicBlack: "Nero",
    colorMenuBasicBlue: "Blu",
    colorMenuBasicGreen: "Verde",
    colorMenuBasicGrey: "Grigio",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Viola",
    colorMenuBasicRed: "Rosso",
    colorMenuBasicTitle: "Cambiare il colore del testo",
    colorMenuBasicWhite: "Bianco",
    dockToElementTitle: "Dock\/disancorare editor all'elemento",
    dockToScreenTitle: "Dock\/disancorare editor a schermo",
    embedDialogCancelButton: "Annulla",
    embedDialogOKButton: "Incorporare l'oggetto",
    embedDialogTabCode: "Codice embed",
    embedDialogTabCodeContent: "Incollare il codice da incorporare nell'area di testo qui sotto:",
    embedDialogTabPreview: "Anteprima",
    embedDialogTabPreviewContent: "Di seguito viene visualizzata un'anteprima del tuo oggetto incorporato:",
    embedDialogTitle: "Incorporare l'oggetto",
    embedTitle: "Incorporare l'oggetto",
    errorUINoName: "UI interfaccia \"{{ui}}\" non è valido (deve avere una proprietà name)",
    errorUINotObject: "UI interfaccia \"{{ui}}\" non è valido (deve essere un oggetto)",
    errorUIOverride: "Interfaccia utente \"{{name}}\" è già stato registrato e verrà sovrascritto",
    fileManagerDialogTitle: "File Manager",
    fileManagerTitle: "File Manager",
    floatLeftTitle: "Allineare l'immagine a sinistra",
    floatNoneTitle: "Rimuovere l'immagine allineare",
    floatRightTitle: "Allineare l'immagine a destra",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Fumetto senza",
    fontFamilyMenuFontCourier: "Corriere nuovo",
    fontFamilyMenuFontDefault: "Tipo di carattere predefinito",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Impatto",
    fontFamilyMenuFontPalatino: "Palatino",
    fontFamilyMenuFontTimes: "Volte nuovo romano",
    fontFamilyMenuTitle: "Scegli il tuo carattere",
    guidesTitle: "Visualizza elemento guide",
    historyRedoTitle: "Rifare",
    historyUndoTitle: "Annulla",
    hrCreateTitle: "Inserire il righello orizzontale",
    imageResizeButtonDialogCancelButton: "Annulla",
    imageResizeButtonDialogHeight: "Altezza immagine",
    imageResizeButtonDialogHeightPlaceHolder: "Altezza",
    imageResizeButtonDialogOKButton: "Ridimensionare",
    imageResizeButtonDialogTitle: "Ridimensionare immagine",
    imageResizeButtonDialogWidth: "Larghezza immagine",
    imageResizeButtonDialogWidthPlaceHolder: "Larghezza",
    imageResizeButtonText: "Ridimensionare immagine",
    insertFileDialogCancelButton: "Annulla",
    insertFileDialogOKButton: "Inserire il file.",
    insertFileNameLabel: "Nome del file",
    insertFileNamePlaceHolder: "Nome del file...",
    insertFileTitle: "Inserire il file.",
    insertFileURLLabel: "URL del file.",
    insertFileURLPlaceHolder: "File URL...",
    languageMenuTitle: "Cambia lingua",
    linkCreateDialogCancelButton: "Annulla",
    linkCreateDialogMenuHeader: "Scegliere un tipo di collegamento",
    linkCreateDialogOKButton: "Inserire Link",
    linkCreateDialogTitle: "Inserire Link",
    linkCreateTitle: "Inserire Link",
    linkRemoveTitle: "Rimuovere Link",
    linkTypeDocumentHeader: "Link a un documento o un altro file",
    linkTypeDocumentInfo: "<h2>Non so cosa mettere nella casella in alto?<\/h2><ol>    <li>Assicurarsi che il file è stato caricato al tuo sito Web.<\/li>    <li>Aprire il file caricato nel browser.<\/li>    <li>Copia URL del file dalla barra degli indirizzi del browser e incollarlo nella casella in alto.<\/li><\/ol>",
    linkTypeDocumentLabel: "Documenti o altri file",
    linkTypeDocumentLocationLabel: "Ubicazione:",
    linkTypeDocumentLocationPlaceHolder: "Immettere un URL",
    linkTypeDocumentNewWindowHeader: "Nuova finestra",
    linkTypeDocumentNewWindowLabel: "Spuntare questa casella per avere il file aperto in una nuova finestra\/scheda del browser.",
    linkTypeEmailHeader: "Link a un indirizzo email",
    linkTypeEmailLabel: "Indirizzo email",
    linkTypeEmailSubjectLabel: "Oggetto (facoltativo):",
    linkTypeEmailSubjectPlaceHolder: "Inserisci oggetto",
    linkTypeEmailToLabel: "Posta elettronica:",
    linkTypeEmailToPlaceHolder: "Inserisci indirizzo email",
    linkTypeExternalHeader: "Link a una pagina su un altro sito",
    linkTypeExternalInfo: "<h2>Non so cosa mettere nella casella in alto?<\/h2><ol>    <li>Trovare la pagina web che si desidera linkare.<\/li>    <li>Copiare l'indirizzo web dalla barra degli indirizzi del browser e incollarlo nella casella in alto.<\/li><\/ol>",
    linkTypeExternalLabel: "Pagina su un altro sito Web",
    linkTypeExternalLocationLabel: "Ubicazione:",
    linkTypeExternalLocationPlaceHolder: "Immettere un URL",
    linkTypeExternalNewWindowHeader: "Nuova finestra",
    linkTypeExternalNewWindowLabel: "Spuntare questa casella per avere il link aperto in una nuova finestra\/scheda del browser.",
    linkTypeInternalHeader: "Link a una pagina su questo sito",
    linkTypeInternalInfo: "<h2>Non so cosa mettere nella casella in alto?<\/h2><ol>    <li>Trovare la pagina su questo sito link a.<\/li>    <li>Copiare l'indirizzo web dalla barra, escludendo \"{{domain}}\" degli indirizzi del browser e incollarlo nella casella in alto.<\/li><\/ol>",
    linkTypeInternalLabel: "Pagina su questo sito",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Immettere un URI",
    linkTypeInternalNewWindowHeader: "Nuova finestra",
    linkTypeInternalNewWindowLabel: "Spuntare questa casella per avere il link aperto in una nuova finestra\/scheda del browser.",
    listOrderedTitle: "Elenco ordinato",
    listUnorderedTitle: "Elenco non ordinato",
    logoTitle: "Ulteriori informazioni sull'Editor WYSIWYG Raptor",
    loremIpsumTitle: "Inserire un testo fittizio per il test",
    navigateAway: "\nCi sono non salvate le modifiche su questa pagina. \nSe si sposta da questa pagina si perderanno le modifiche non salvate",
    pasteDialogCancelButton: "Annulla",
    pasteDialogFormattedCleaned: "Formattato &amp; pulito",
    pasteDialogFormattedUnclean: "Formattato impuro",
    pasteDialogOKButton: "Inserire",
    pasteDialogPlain: "Testo normale",
    pasteDialogSource: "Codice sorgente",
    pasteDialogTitle: "Incolla",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Impossibile recuperare le revisioni",
    revisionsApplyButtonDialogCancelButton: "Annulla",
    revisionsApplyButtonDialogOKButton: "Rollback",
    revisionsApplyButtonDialogText: "Conferma di rollback",
    revisionsApplyButtonDialogTitle: "Conferma di rollback",
    revisionsApplyButtonText: "Rollback",
    revisionsApplyButtonTitle: "Rollback",
    revisionsApplyDialogContent: "Questo sostituirà l'attuale contenuto della revisione selezionata.<br>Il contenuto corrente verrà aggiunto come una revisione e sarà visibile nell'elenco revisioni per questo blocco.",
    revisionsButtonCurrent: "Corrente",
    revisionsButtonViewDiffText: "Differenze",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Creato",
    revisionsDialogCancelButton: "Annulla",
    revisionsDialogTitle: "Visualizzazione contenuti revisioni",
    revisionsDiffButtonDialogCancelButton: "Chiudere",
    revisionsDiffButtonDialogTitle: "Mostra differenze",
    revisionsDiffButtonText: "Mostra differenze",
    revisionsDiffButtonTitle: "Mostra differenze",
    revisionsLoading: "Caricamento revisioni...",
    revisionsNone: "No revisioni per questo elemento",
    revisionsPreviewButtonText: "Anteprima",
    revisionsPreviewButtonTitle: "Anteprima",
    revisionsText: "Revisioni",
    revisionsTextEmpty: "No revisioni",
    revisionsTitle: "",
    rfmClose: "Chiudere",
    rfmContinue: "Continuare",
    rfmDelete: "Eliminare",
    rfmDownload: "Scarica",
    rfmFileActions: "Azioni",
    rfmFileModificationTime: "Modificato",
    rfmFileName: "Nome",
    rfmFileSize: "Dimensione",
    rfmFileType: "Tipo",
    rfmFilteredTotal: "Visualizzando {{start}} a {{end}} {{filteredTotal}} file",
    rfmFirst: "Primo",
    rfmHeadingDirectories: "Directory",
    rfmHeadingSearch: "Ricerca",
    rfmHeadingTags: "Tag",
    rfmHeadingUpload: "Caricare",
    rfmInsert: "Inserire",
    rfmLast: "Ultima",
    rfmSearch: "Vai",
    rfmTagDocument: "Documento",
    rfmTagImage: "Immagine",
    rfmTotal: ", filtrata da {{total}}",
    rfmUpload: "Caricare",
    rfmUploadBrowse: "Sfoglia",
    rfmUploadDrop: "Rilasciare i file qui",
    rfmUploadFileRemove: "Rimuovere",
    rfmUploadOr: "o",
    rfmView: "Vista",
    saveJsonFail: "Non è riuscito a salvare {{failed}} blocchi (i contenuti)",
    saveJsonSaved: "Salvate correttamente {{saved}} blocchi (i contenuti).",
    saveNotConfigured: "Save non è stato configurato, o è disabilitato.",
    saveRestFail: "Impossibile salvare {{failed}} blocchi (i contenuti).",
    saveRestPartial: "Salvato {{saved}} {{failed}} blocchi di contenuto.",
    saveRestSaved: "Salvate correttamente {{saved}} blocchi (i contenuti).",
    saveTitle: "Salvare il contenuto",
    snippetMenuTitle: "Frammenti",
    specialCharactersArrows: "Frecce",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Inserire caratteri speciali",
    specialCharactersGreekAlphabet: "Alfabeto greco",
    specialCharactersHelp: "Fare clic su un carattere speciale per aggiungerlo. Fare clic su \"OK\" quando fatto per chiudere questa finestra di dialogo",
    specialCharactersMathematics: "Matematica",
    specialCharactersSymbols: "Simboli",
    specialCharactersTitle: "Inserire un carattere speciale",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} caratteri oltre limite",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} caratteri rimanenti",
    statisticsButtonCharacters: "{{characters}} caratteri",
    statisticsDialogCharactersOverLimit: "oltre il limite consigliato caratteri di {{characters}}, {{charactersRemaining}}",
    statisticsDialogCharactersRemaining: "caratteri di {{characters}}, {{charactersRemaining}} rimanenti",
    statisticsDialogNotTruncated: "Contenuto non verrà troncato",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "frase {{sentences}}",
    statisticsDialogSentences: "frasi di {{sentences}}",
    statisticsDialogTitle: "Statistiche di contenuto",
    statisticsDialogTruncated: "Contenuto contiene più di {{limit}} caratteri e può essere troncato",
    statisticsDialogWord: "parola di {{words}}",
    statisticsDialogWords: "Parole di {{words}}",
    statisticsTitle: "Clicca per visualizzare le statistiche",
    tableCreateTitle: "Creare la tabella",
    tableDeleteColumnTitle: "Eliminare la colonna di tabella",
    tableDeleteRowTitle: "Eliminare la riga della tabella",
    tableInsertColumnTitle: "Inserisci colonna tabella",
    tableInsertRowTitle: "Inserire una riga di tabella",
    tableMergeCellsTitle: "Unire le celle di tabella",
    tableSplitCellsTitle: "Dividere le celle della tabella",
    tagMenuTagAddress: "Indirizzo",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Rubrica 1",
    tagMenuTagH2: "Rubrica 2",
    tagMenuTagH3: "Rubrica 3",
    tagMenuTagH4: "Rubrica 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Paragrafo",
    tagMenuTagPre: "Pre-formattato",
    tagMenuTitle: "Cambia tipo di elemento",
    tagTreeElementLink: "Selezionare {{element}}",
    tagTreeElementTitle: "Fare clic per selezionare il contenuto dell'elemento \"{{element}}\" elemento",
    tagTreeRoot: "radice",
    tagTreeRootLink: "Selezionare tutto il contenuto modificabile",
    tagTreeRootTitle: "Fare clic per selezionare tutto il contenuto modificabile",
    textBlockQuoteTitle: "Citazione",
    textBoldTitle: "Grassetto",
    textItalicTitle: "Corsivo",
    textSizeDecreaseTitle: "Diminuire la dimensione del testo",
    textSizeIncreaseTitle: "Aumentare la dimensione del testo",
    textStrikeTitle: "Barrare",
    textSubTitle: "Subscript",
    textSuperTitle: "Super-script di",
    textUnderlineTitle: "Sottolineatura",
    unsavedEditWarningText: "Ci sono non salvate le modifiche su questa pagina",
    viewSourceDialogCancelButton: "Chiudere",
    viewSourceDialogOKButton: "Applicare il codice sorgente",
    viewSourceDialogTitle: "Codice sorgente contenuto",
    viewSourceTitle: "Visualizza\/modifica del codice sorgente"
});