/**
 * @fileOverview Japaneese strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ja', '日本の', {
    alignCenterTitle: "テキストを中央に揃える",
    alignJustifyTitle: "テキストの整列を正当化します。",
    alignLeftTitle: "テキストを左を揃え",
    alignRightTitle: "テキストを右を揃え",
    cancelDialogCancelButton: "編集を続行します。",
    cancelDialogContent: "編集をキャンセルするもよろしいですか。すべての変更は失われます。",
    cancelDialogOKButton: "編集をキャンセルします",
    cancelDialogTitle: "編集をキャンセルします",
    cancelTitle: "編集をキャンセルします",
    classMenuTitle: "スタイルの選択",
    clearFormattingTitle: "書式をクリアします。",
    clickButtonToEditText: "編集",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "自動",
    colorMenuBasicBlack: "ブラック",
    colorMenuBasicBlue: "ブルー",
    colorMenuBasicGreen: "グリーン",
    colorMenuBasicGrey: "グレー",
    colorMenuBasicOrange: "オレンジ",
    colorMenuBasicPurple: "紫色",
    colorMenuBasicRed: "赤",
    colorMenuBasicTitle: "テキストの色を変更します。",
    colorMenuBasicWhite: "ホワイト",
    dockToElementTitle: "ドック\/アンドック要素エディター",
    dockToScreenTitle: "画面エディターのドック\/アンドックします。",
    embedDialogCancelButton: "キャンセル",
    embedDialogOKButton: "オブジェクトを埋め込む",
    embedDialogTabCode: "埋め込みコード",
    embedDialogTabCodeContent: "下のテキスト領域に埋め込みコードを貼り付けます。",
    embedDialogTabPreview: "プレビュー",
    embedDialogTabPreviewContent: "埋め込みオブジェクトのプレビューが下に表示されます。",
    embedDialogTitle: "オブジェクトを埋め込む",
    embedTitle: "オブジェクトを埋め込む",
    errorUINoName: "UI\"{{ui}}\"が無効です (name プロパティが必要です）",
    errorUINotObject: "UI\"{{ui}}\"が無効です (オブジェクトがあります)",
    errorUIOverride: "UI「{{名}}」は既に登録されておよび上書きします。",
    fileManagerDialogTitle: "ファイル マネージャー",
    fileManagerTitle: "ファイル マネージャー",
    floatLeftTitle: "左側にイメージを配置します。",
    floatNoneTitle: "イメージを削除配置",
    floatRightTitle: "右側にイメージを配置します。",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "なしのコミック",
    fontFamilyMenuFontCourier: "新しい宅配便",
    fontFamilyMenuFontDefault: "既定のフォント",
    fontFamilyMenuFontGeorgia: "グルジア",
    fontFamilyMenuFontImpact: "影響",
    fontFamilyMenuFontPalatino: "パラティーノ",
    fontFamilyMenuFontTimes: "新しいローマの時間",
    fontFamilyMenuTitle: "あなたのフォントを選択します。",
    guidesTitle: "要素ガイドを表示します。",
    historyRedoTitle: "やり直し",
    historyUndoTitle: "元に戻す",
    hrCreateTitle: "段落罫線を挿入します。",
    imageResizeButtonDialogCancelButton: "キャンセル",
    imageResizeButtonDialogHeight: "画像の高さ",
    imageResizeButtonDialogHeightPlaceHolder: "高さ",
    imageResizeButtonDialogOKButton: "サイズを変更します。",
    imageResizeButtonDialogTitle: "イメージのサイズを変更します。",
    imageResizeButtonDialogWidth: "画像の幅",
    imageResizeButtonDialogWidthPlaceHolder: "幅",
    imageResizeButtonText: "イメージのサイズを変更します。",
    insertFileDialogCancelButton: "キャンセル",
    insertFileDialogOKButton: "ファイルを挿入します。",
    insertFileNameLabel: "ファイル名",
    insertFileNamePlaceHolder: "ファイル名.",
    insertFileTitle: "ファイルを挿入します。",
    insertFileURLLabel: "ファイルの URL",
    insertFileURLPlaceHolder: "ファイルの URL.",
    languageMenuDE: "ドイツ語",
    languageMenuEN: "英語",
    languageMenuES: "スペイン語",
    languageMenuFR: "フランス語",
    languageMenuNL: "オランダ語",
    languageMenuRU: "ロシア語",
    languageMenuSV: "スウェーデン語",
    languageMenuTitle: "言語の変更",
    languageMenuZHCN: "簡体字中国語",
    linkCreateDialogCancelButton: "キャンセル",
    linkCreateDialogMenuHeader: "リンクの種類を選択します。",
    linkCreateDialogOKButton: "リンクを挿入します。",
    linkCreateDialogTitle: "リンクを挿入します。",
    linkCreateTitle: "リンクを挿入します。",
    linkRemoveTitle: "リンクを削除します。",
    linkTypeDocumentHeader: "ドキュメントまたはその他のファイルへのリンクします。",
    linkTypeDocumentInfo: "<h2>しないでください何を上のボックスに置くか？<\/h2><ol>    <li>ファイルがあなたのウェブサイトにアップロードされてを確認します。<\/li>    <li>お使いのブラウザーでアップロードされたファイルを開きます。<\/li>    <li>ファイルの URL をブラウザーのアドレス バーからコピーし、上記のボックスに貼り付けます。<\/li><\/ol>",
    linkTypeDocumentLabel: "ドキュメントまたはその他のファイル",
    linkTypeDocumentLocationLabel: "場所:",
    linkTypeDocumentLocationPlaceHolder: "URL を入力します。",
    linkTypeDocumentNewWindowHeader: "新しいウィンドウ",
    linkTypeDocumentNewWindowLabel: "このチェック ボックスをファイルが新しいブラウザーのウィンドウ\/タブで開いています。",
    linkTypeEmailHeader: "電子メール アドレスにリンクするには",
    linkTypeEmailLabel: "メール アドレス",
    linkTypeEmailSubjectLabel: "（オプション） 題目：",
    linkTypeEmailSubjectPlaceHolder: "件名を入力してください。",
    linkTypeEmailToLabel: "電子メール：",
    linkTypeEmailToPlaceHolder: "メール アドレスを入力します。",
    linkTypeExternalHeader: "別の web サイト上のページへのリンクします。",
    linkTypeExternalInfo: "<h2>しないでください何を上のボックスに置くか？<\/h2><ol>    <li>リンクする web ページを見つけます。<\/li>    <li>ブラウザーのアドレス バーから web アドレスをコピーし、上記のボックスに貼り付けます。<\/li><\/ol>",
    linkTypeExternalLabel: "別の web サイト上のページ",
    linkTypeExternalLocationLabel: "場所:",
    linkTypeExternalLocationPlaceHolder: "URL を入力します。",
    linkTypeExternalNewWindowHeader: "新しいウィンドウ",
    linkTypeExternalNewWindowLabel: "このチェック ボックスを新しいブラウザー ウィンドウ\/タブで開くリンクを持っています。",
    linkTypeInternalHeader: "このウェブサイト上のページへのリンクします。",
    linkTypeInternalInfo: "<h2>しないでください何を上のボックスに置くか？<\/h2><ol>    <li>このサイトのリンクをページを見つけます。<\/li>    <li>お使いのブラウザーのアドレス バーに、\"{{}}「ドメインを除くから web アドレスをコピーし、、上記のボックスに貼り付けます。<\/li><\/ol>",
    linkTypeInternalLabel: "このウェブサイト上のページ",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "URI を入力してください。",
    linkTypeInternalNewWindowHeader: "新しいウィンドウ",
    linkTypeInternalNewWindowLabel: "このチェック ボックスを新しいブラウザー ウィンドウ\/タブで開くリンクを持っています。",
    listOrderedTitle: "順序付きリスト",
    listUnorderedTitle: "順不同リスト",
    logoTitle: "ラプター WYSIWYG エディターについての詳細します。",
    loremIpsumTitle: "テスト用のダミー テキストを挿入します。",
    navigateAway: "このページは変更保存いません。このページから移動すると未保存の変更が失われます",
    pasteDialogCancelButton: "キャンセル",
    pasteDialogFormattedCleaned: "フォーマット ＆ クリーニング",
    pasteDialogFormattedUnclean: "汚れたフォーマット",
    pasteDialogOKButton: "挿入",
    pasteDialogPlain: "プレーン テキスト",
    pasteDialogSource: "ソース コード",
    pasteDialogTitle: "ペースト",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "リビジョンを取得に失敗しました",
    revisionsApplyButtonDialogCancelButton: "キャンセル",
    revisionsApplyButtonDialogOKButton: "ロールバック",
    revisionsApplyButtonDialogText: "ロールバックの確認",
    revisionsApplyButtonDialogTitle: "ロールバックの確認",
    revisionsApplyButtonText: "ロールバック",
    revisionsApplyButtonTitle: "ロールバック",
    revisionsApplyDialogContent: "これを選択したリビジョンと現在の内容が置換されます。<br>現在のコンテンツ、リビジョンとして追加して、このブロックの履歴一覧に表示されます。",
    revisionsButtonCurrent: "電流",
    revisionsButtonViewDiffText: "相違点",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "作成",
    revisionsDialogCancelButton: "キャンセル",
    revisionsDialogTitle: "ビューのコンテンツの改訂",
    revisionsDiffButtonDialogCancelButton: "閉じる",
    revisionsDiffButtonDialogTitle: "相違点の表示",
    revisionsDiffButtonText: "相違点の表示",
    revisionsDiffButtonTitle: "相違点の表示",
    revisionsLoading: "リビジョンを読み込んでいます.",
    revisionsNone: "この要素のないリビジョン",
    revisionsPreviewButtonText: "プレビュー",
    revisionsPreviewButtonTitle: "プレビュー",
    revisionsText: "リビジョン",
    revisionsTextEmpty: "ないリビジョン",
    revisionsTitle: "",
    rfmClose: "閉じる",
    rfmContinue: "続行",
    rfmDelete: "削除",
    rfmDownload: "ダウンロード",
    rfmFileActions: "アクション",
    rfmFileModificationTime: "変更",
    rfmFileName: "名前",
    rfmFileSize: "サイズ",
    rfmFileType: "タイプ",
    rfmFilteredTotal: "表示 {{スタート}} に {{}} {{filteredTotal}} ファイルの",
    rfmFirst: "最初",
    rfmHeadingDirectories: "ディレクトリ",
    rfmHeadingSearch: "検索",
    rfmHeadingTags: "タグ",
    rfmHeadingUpload: "アップロード",
    rfmInsert: "挿入",
    rfmLast: "最後",
    rfmSearch: "行く",
    rfmTagDocument: "ドキュメント",
    rfmTagImage: "イメージ",
    rfmTotal: "、フィルターから {{}}",
    rfmUpload: "アップロード",
    rfmUploadBrowse: "参照",
    rfmUploadDrop: "ここにファイルをドロップします。",
    rfmUploadFileRemove: "削除",
    rfmUploadOr: "または",
    rfmView: "ビュー",
    saveJsonFail: "{{失敗}} のコンテンツ ブロックの保存に失敗しました",
    saveJsonSaved: "{{}} 保存コンテンツ ブロックを正常に保存されます。",
    saveNotConfigured: "保存が構成されていないまたはが無効になります。",
    saveRestFail: "{{失敗}} のコンテンツ ブロックの保存に失敗しました。",
    saveRestPartial: "{{保存}} {{失敗}} のコンテンツ ブロックから保存されます。",
    saveRestSaved: "{{}} 保存コンテンツ ブロックを正常に保存されます。",
    saveTitle: "コンテンツを保存します。",
    snippetMenuTitle: "スニペット",
    specialCharactersArrows: "矢印",
    specialCharactersDialogOKButton: "わかりました",
    specialCharactersDialogTitle: "特殊文字を挿入します。",
    specialCharactersGreekAlphabet: "ギリシャ語のアルファベット",
    specialCharactersHelp: "追加する特殊文字をクリックします。\"\"完了 [ok] をこのダイアログ ボックスを閉じますをクリックします",
    specialCharactersMathematics: "数学",
    specialCharactersSymbols: "シンボル",
    specialCharactersTitle: "特殊文字を挿入します。",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} 文字制限を超えて",
    statisticsButtonCharacterRemaining: "残りの文字数 {{charactersRemaining}}",
    statisticsButtonCharacters: "{{}} 文字",
    statisticsDialogCharactersOverLimit: "推奨される制限 {{文字}} 文字 {{charactersRemaining}}",
    statisticsDialogCharactersRemaining: "残り {{charactersRemaining}} {{文字}} 文字",
    statisticsDialogNotTruncated: "コンテンツが切り捨てられない",
    statisticsDialogOKButton: "わかりました",
    statisticsDialogSentence: "文 {{文}}",
    statisticsDialogSentences: "文 {{文}}",
    statisticsDialogTitle: "コンテンツの統計",
    statisticsDialogTruncated: "内容 {{制限}} 文字以上が含まれているし、切り詰め可能性があります。",
    statisticsDialogWord: "{{言葉}} 単語",
    statisticsDialogWords: "{{}} 単語",
    statisticsTitle: "統計を表示する] をクリックします",
    tableCreateTitle: "テーブルを作成します。",
    tableDeleteColumnTitle: "テーブルの列を削除します。",
    tableDeleteRowTitle: "テーブルの行を削除します。",
    tableInsertColumnTitle: "テーブルの列を挿入します。",
    tableInsertRowTitle: "テーブルに行を挿入します。",
    tableMergeCellsTitle: "テーブル セルを結合します。",
    tableSplitCellsTitle: "テーブルセルを分割します。",
    tagMenuTagAddress: "アドレス",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "見出し 1",
    tagMenuTagH2: "見出し 2",
    tagMenuTagH3: "見出し 3",
    tagMenuTagH4: "見出し 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "段落",
    tagMenuTagPre: "フォーマット済み",
    tagMenuTitle: "要素のスタイルを変更します。",
    tagTreeElementLink: "{{}} 要素を選択します",
    tagTreeElementTitle: "クリックして、\"{{}}\"要素の内容を選択するには",
    tagTreeRoot: "ルート",
    tagTreeRootLink: "すべての編集可能なコンテンツを選択します。",
    tagTreeRootTitle: "すべての編集可能なコンテンツを選択する] をクリックします",
    textBlockQuoteTitle: "ブロック引用",
    textBoldTitle: "太字",
    textItalicTitle: "斜体",
    textSizeDecreaseTitle: "テキストのサイズを小さきます。",
    textSizeIncreaseTitle: "テキストのサイズを増やす",
    textStrikeTitle: "打ち消し線",
    textSubTitle: "サブ スクリプト",
    textSuperTitle: "スーパー スクリプト",
    textUnderlineTitle: "下線",
    unsavedEditWarningText: "このページで変更が未保存は",
    viewSourceDialogCancelButton: "閉じる",
    viewSourceDialogOKButton: "ソース コードを適用します。",
    viewSourceDialogTitle: "コンテンツ ソース コード",
    viewSourceTitle: "ソース コードの表示\/編集"
});
