/**
 * @fileOverview Japaneese strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ja', '日本語', {
    alignCenterTitle: "テキストを中央に揃える",
    alignJustifyTitle: "テキストを均等に揃える",
    alignLeftTitle: "テキストを左に揃える",
    alignRightTitle: "テキストを右に揃える",
    
    cancelDialogCancelButton: "編集を続行する",
    cancelDialogContent: "編集をキャンセルしてもよろしいですか。すべての変更は失われます。",
    cancelDialogOKButton: "編集をキャンセルする",
    cancelDialogTitle: "編集をキャンセルする",
    cancelTitle: "編集をキャンセルする",
    
    classMenuTitle: "スタイルの選択",
    clearFormattingTitle: "書式をクリアする",
    clickButtonToEditText: "編集",
    clickButtonToEditTitle: null,
    
    colorMenuBasicAutomatic: "自動",
    colorMenuBasicBlack: "黒",
    colorMenuBasicBlue: "青",
    colorMenuBasicGreen: "緑",
    colorMenuBasicGrey: "灰色",
    colorMenuBasicOrange: "オレンジ",
    colorMenuBasicPurple: "紫",
    colorMenuBasicRed: "赤",
    colorMenuBasicTitle: "テキストの色を変更する",
    colorMenuBasicWhite: "白",
    
    dockToElementTitle: "要素にエディターをドック\/アンドックする",
    dockToScreenTitle: "画面にエディターをドック\/アンドックする",
    
    embedTitle: "オブジェクトを埋め込む",
    embedDialogTitle: "オブジェクトを埋め込む",
    embedDialogTabCode: "埋め込みコード",
    embedDialogTabCodeContent: "埋め込みコードを下のテキスト領域に貼り付けてください：",
    embedDialogTabPreview: "プレビュー",
    embedDialogTabPreviewContent: "埋め込みオブジェクトのプレビューが下に表示されます：",
    embedDialogOKButton: "オブジェクトを埋め込む",
    embedDialogCancelButton: "キャンセル",
    
    errorUINoName: "UI\"{{ui}}\"は無効です (name プロパティが必要です）",
    errorUINotObject: "UI\"{{ui}}\"は無効です (オブジェクトである必要があります)",
    errorUIOverride: "UI\"{{name}}\"は既に登録されているため上書きします",
    
    floatLeftTitle: "画像を左側に配置する",
    floatNoneTitle: "画像の配置を削除する",
    floatRightTitle: "画像を右側に配置する",
    
    fontFamilyMenuTitle: "フォントを選択する",
    fontFamilyMenuFontDefault: "既定のフォント",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontPalatino: "Platino",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuFontComicSans: "Comic Sans",
    fontFamilyMenuFontImpact: "Impact",
    fontFamilyMenuFontCourier: "Courier New",
    
    guidesTitle: "要素ガイドを表示する",
    
    historyRedoTitle: "やり直す",
    historyUndoTitle: "元に戻す",
    
    hrCreateTitle: "区切り線を挿入する",
    
    imageResizeButtonText: "画像のサイズを変更する",
    imageResizeButtonDialogWidth: "画像の幅",
    imageResizeButtonDialogHeight: "画像の高さ",
    imageResizeButtonDialogWidthPlaceHolder: "幅",
    imageResizeButtonDialogHeightPlaceHolder: "高さ",
    imageResizeButtonDialogTitle: "画像のサイズを変更する",
    imageResizeButtonDialogOKButton: "サイズを変更します",
    imageResizeButtonDialogCancelButton: "キャンセル",
    
    insertFileTitle: "ファイルを挿入する",
    insertFileDialogOKButton: "ファイルを挿入します",
    insertFileDialogCancelButton: "キャンセル",
    insertFileURLLabel: "ファイルのURL",
    insertFileNameLabel: "ファイル名",
    insertFileURLPlaceHolder: "ファイルのURL...",
    insertFileNamePlaceHolder: "ファイル名...",
    
    languageMenuTitle: "言語の変更",
    languageMenuDE: "ドイツ語",
    languageMenuEN: "英語",
    languageMenuES: "スペイン語",
    languageMenuFR: "フランス語",
    languageMenuNL: "オランダ語",
    languageMenuRU: "ロシア語",
    languageMenuSV: "スウェーデン語",
    languageMenuZHCN: "簡体字中国語",
    
    loremIpsumTitle: "テスト用のダミーテキストを挿入する",
    
    listOrderedTitle: "順序付きリスト",
    listUnorderedTitle: "順不同リスト",
    
    linkCreateTitle: "リンクを挿入する",
    linkRemoveTitle: "リンクを削除する",
    
    linkCreateDialogTitle: "リンクを挿入する",
    linkCreateDialogOKButton: "リンクを挿入します",
    linkCreateDialogCancelButton: "キャンセル",
    linkCreateDialogMenuHeader: "リンクの種類を選択してください",
    
    linkTypeEmailLabel: "メールアドレス",
    linkTypeEmailHeader: "電子メールアドレスにリンクする",
    linkTypeEmailToLabel: "電子メール：",
    linkTypeEmailToPlaceHolder: "メールアドレスを入力してください。",
    linkTypeEmailSubjectLabel: "件名（オプション）：",
    linkTypeEmailSubjectPlaceHolder: "件名を入力してください。",
    
    linkTypeExternalLabel: "外部のウェブサイト上のページ",
    linkTypeExternalHeader: "外部のウェブサイト上のページにリンクする",
    linkTypeExternalLocationLabel: "場所:",
    linkTypeExternalLocationPlaceHolder: "URLを入力してください。",
    linkTypeExternalNewWindowHeader: "新しいウィンドウ",
    linkTypeExternalNewWindowLabel: "リンクをブラウザの新しいウィンドウ\/タブで開くにはこれをチェックしてください。",
    linkTypeExternalInfo: "<h2>何を入力すればよいかわかりませんか？<\/h2><ol><li>リンクしたいウェブページを見つけます。<\/li><li>ブラウザーのアドレスバーからウェブアドレスをコピーして、上記のボックスに貼り付けます。<\/li><\/ol>",
    
    linkTypeDocumentLabel: "ドキュメントまたはその他のファイル",
    linkTypeDocumentHeader: "ドキュメントまたはその他のファイルにリンクする",
    linkTypeDocumentLocationLabel: "場所:",
    linkTypeDocumentLocationPlaceHolder: "URLを入力してください。",
    linkTypeDocumentNewWindowHeader: "新しいウィンドウ",
    linkTypeDocumentNewWindowLabel: "リンクをブラウザの新しいウィンドウ\/タブで開くにはこれをチェックしてください。",
    linkTypeDocumentInfo: "<h2>何を入力すればよいかわかりませんか？<\/h2><ol><li>ファイルがあなたのウェブサイトにアップロードされていることを確認します。<\/li><li>お使いのブラウザーでアップロードされたファイルを開きます。<\/li><li>ファイルのURLをブラウザのアドレスバーからコピーして、上記のボックスに貼り付けます。<\/li><\/ol>",

    linkTypeInternalLabel: "このウェブサイト上のページ",
    linkTypeInternalHeader: "このウェブサイト上のページへリンクする",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "URIを入力してください。",
    linkTypeInternalNewWindowHeader: "新しいウィンドウ",
    linkTypeInternalNewWindowLabel: "リンクをブラウザの新しいウィンドウ\/タブで開くにはこれをチェックしてください。",
    linkTypeInternalInfo: "<h2>何を入力すればよいかわかりませんか？<\/h2><ol><li>リンクしたいウェブページを見つけます。<\/li><li>ブラウザーのアドレスバーからウェブアドレスをコピーして、\"{{domain}}\"を除いた部分を上記のボックスに貼り付けます。<\/li><\/ol>",
    
    logoTitle: "Raptor WYSIWYG Editorの詳細を確認する",
    
    navigateAway: "このページには未保存の変更があります。このページから移動すると未保存の変更が失われます。",
    
    pasteDialogTitle: "ペースト",
    pasteDialogOKButton: "挿入する",
    pasteDialogCancelButton: "キャンセル",
    pasteDialogPlain: "プレインテキスト",
    pasteDialogFormattedCleaned: "フォーマット済み ＆ クリーニング済み",
    pasteDialogFormattedUnclean: "フォーマット済み、未クリーニング",
    pasteDialogSource: "ソースコード",
    
    placeholderPluginDefaultContent: "<br/>",
    
    saveTitle: "コンテンツを保存する",
    saveNotConfigured: "保存が構成されていないか無効化されています。",
    saveJsonFail: "{{failed}}個のコンテンツブロックの保存に失敗しました。",
    saveJsonSaved: "{{saved}}個のコンテンツブロックを正常に保存しました。",
    saveRestFail: "{{failed}}個のコンテンツブロックの保存に失敗しました。",
    saveRestPartial: "{{failed}}個のうち{{saved}}個のコンテンツブロックを保存しました。",
    saveRestSaved: "{{saved}}個のコンテンツブロックを正常に保存しました。",
    
    snippetMenuTitle: "スニペット",
    
    specialCharactersArrows: "矢印",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "特殊文字を挿入する",
    specialCharactersGreekAlphabet: "ギリシャ語のアルファベット",
    specialCharactersHelp: "特殊文字をクリックして追加します。完了したら\"OK\"をクリックしてこのダイアログを閉じます。",
    specialCharactersMathematics: "数学",
    specialCharactersSymbols: "シンボル",
    specialCharactersTitle: "特殊文字を挿入する",
    
    statisticsButtonCharacterOverLimit: "制限超過 {{charactersRemaining}} 文字",
    statisticsButtonCharacterRemaining: "残り {{charactersRemaining}} 文字",
    statisticsButtonCharacters: "{{characters}} 文字",
    statisticsDialogCharactersOverLimit: "{{characters}} 文字、推奨される制限より {{charactersRemaining}} 文字オーバー",
    statisticsDialogCharactersRemaining: "{{characters}} 文字、残り {{charactersRemaining}} 文字",
    statisticsDialogNotTruncated: "コンテンツは切り詰めされません",
    statisticsDialogOKButton: "OK",
    statisticsDialogSentence: "{{sentences}} 文",
    statisticsDialogSentences: "{{sentences}} 文",
    statisticsDialogTitle: "コンテンツの統計",
    statisticsDialogTruncated: "コンテンツは {{limit}} 文字以上が含まれているため、切り詰めされる可能性があります。",
    statisticsDialogWord: "{{words}} 単語",
    statisticsDialogWords: "{{words}} 単語",
    statisticsTitle: "クリックして統計を表示する",
    
    tableCreateTitle: "テーブルを作成する",
    tableDeleteColumnTitle: "テーブルの列を削除する",
    tableDeleteRowTitle: "テーブルの行を削除する",
    tableInsertColumnTitle: "テーブルに列を挿入する",
    tableInsertRowTitle: "テーブルに行を挿入する",
    tableMergeCellsTitle: "テーブルセルを結合する",
    tableSplitCellsTitle: "テーブルセルを分割する",
    
    tagMenuTagH1: "見出し1",
    tagMenuTagH2: "見出し2",
    tagMenuTagH3: "見出し3",
    tagMenuTagH4: "見出し4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "段落",
    tagMenuTagDiv: "Div",
    tagMenuTagPre: "フォーマット済み",
    tagMenuTagAddress: "アドレス",
    tagMenuTitle: "要素のスタイルを変更する",
    
    tagTreeElementLink: "{{}} 要素を選択します",
    tagTreeElementTitle: "クリックして\"{{element}}\"要素のコンテンツを選択する",
    tagTreeRoot: "ルート",
    tagTreeRootLink: "すべての編集可能なコンテンツを選択する",
    tagTreeRootTitle: "クリックしてすべての編集可能なコンテンツを選択する",
    
    textBlockQuoteTitle: "ブロック引用",
    textBoldTitle: "太字",
    textItalicTitle: "斜体",
    textStrikeTitle: "打ち消し線",
    textSubTitle: "下付",
    textSuperTitle: "上付",
    textUnderlineTitle: "下線",
    textSizeDecreaseTitle: "テキストのサイズを小さく",
    textSizeIncreaseTitle: "テキストのサイズを大きく",
    
    unsavedEditWarningText: "このページには未保存の変更があります",
    
    revisionsText: "リビジョン",
    revisionsTextEmpty: "リビジョンなし",
    revisionsTitle: null,
    revisionsCreated: "作成済",
    revisionsApplyButtonTitle: "ロールバック",
    revisionsApplyButtonText: "ロールバック",
    revisionsAJAXFailed: "リビジョンの取得が失敗しました",
    revisionsApplyButtonDialogCancelButton: "キャンセル",
    revisionsApplyButtonDialogOKButton: "ロールバック",
    revisionsApplyButtonDialogTitle: "ロールバックの確認",
    revisionsApplyDialogContent: "選択したリビジョンで現在のコンテンツが上書きされます。<br>現在のコンテンツはリビジョンとして追加され、このブロックのリビジョン一覧に表示されます。",
    revisionsDialogCancelButton: "キャンセル",
    revisionsDialogTitle: "コンテンツのリビジョンを見る",
    revisionsButtonCurrent: "現在",
    revisionsButtonViewDiffText: "差異",
    revisionsButtonViewDiffTitle: null,
    revisionsDiffButtonDialogCancelButton: "閉じる",
    revisionsDiffButtonDialogTitle: "差異の表示",
    revisionsDiffButtonTitle: "差異の表示",
    revisionsDiffButtonText: "差異の表示",
    revisionsLoading: "リビジョンを読み込んでいます...",
    revisionsNone: "この要素にはリビジョンがありません",
    revisionsPreviewButtonTitle: "プレビュー",
    revisionsPreviewButtonText: "プレビュー",

    fileManagerDialogTitle: "ファイルマネージャー",
    fileManagerTitle: "ファイルマネージャー",
    rfmClose: "閉じる",
    rfmContinue: "続行",
    rfmDelete: "削除",
    rfmDownload: "ダウンロード",
    rfmFileActions: "アクション",
    rfmFileModificationTime: "変更",
    rfmFileName: "名前",
    rfmFileSize: "サイズ",
    rfmFileType: "タイプ",
    rfmFilteredTotal: "{{filteredTotal}}個中 {{start}} から {{end}} までのファイルを表示",
    rfmFirst: "最初",
    rfmHeadingDirectories: "ディレクトリ",
    rfmHeadingSearch: "検索",
    rfmHeadingTags: "タグ",
    rfmHeadingUpload: "アップロード",
    rfmInsert: "挿入",
    rfmLast: "最後",
    rfmSearch: "検索",
    rfmTagDocument: "ドキュメント",
    rfmTagImage: "画像",
    rfmTotal: "、{{total}}個からフィルターされています",
    rfmUpload: "アップロード",
    rfmUploadBrowse: "参照",
    rfmUploadDrop: "ここにファイルをドロップしてください",
    rfmUploadFileRemove: "削除",
    rfmUploadOr: "または",
    rfmView: "ビュー",
    
    viewSourceDialogCancelButton: "閉じる",
    viewSourceDialogOKButton: "ソースコードを適用する",
    viewSourceDialogTitle: "コンテンツのソースコード",
    viewSourceTitle: "ソースコードの表示\/編集"
});
