/**
 * @fileOverview Korean strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ko', '한국어', {
    alignCenterTitle: "텍스트 중앙 정렬",
    alignJustifyTitle: "텍스트 정렬 정당화",
    alignLeftTitle: "텍스트 왼쪽 정렬",
    alignRightTitle: "텍스트 오른쪽 정렬",
    cancelDialogCancelButton: "편집 계속",
    cancelDialogContent: "당신은 편집을 취소 하 시겠습니까? 모든 변경 내용이 손실 될 것입니다!",
    cancelDialogOKButton: "편집 취소",
    cancelDialogTitle: "편집 취소",
    cancelTitle: "편집 취소",
    classMenuTitle: "스타일 선택",
    clearFormattingTitle: "서식 지우기",
    clickButtonToEditText: "편집",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "자동 번역",
    colorMenuBasicBlack: "블랙",
    colorMenuBasicBlue: "블루",
    colorMenuBasicGreen: "그린",
    colorMenuBasicGrey: "그레이",
    colorMenuBasicOrange: "오렌지",
    colorMenuBasicPurple: "보라색",
    colorMenuBasicRed: "레드",
    colorMenuBasicTitle: "텍스트 색 변경",
    colorMenuBasicWhite: "화이트",
    dockToElementTitle: "도킹\/도킹 해제 요소 편집기",
    dockToScreenTitle: "도킹\/도킹 해제 화면 편집기",
    embedDialogCancelButton: "취소",
    embedDialogOKButton: "개체 포함",
    embedDialogTabCode: "소스 코드",
    embedDialogTabCodeContent: "텍스트 영역 아래에 소스 코드를 붙여 넣습니다.",
    embedDialogTabPreview: "미리 보기",
    embedDialogTabPreviewContent: "내장된 개체의 미리 보기 아래에 표시 됩니다.",
    embedDialogTitle: "개체 포함",
    embedTitle: "개체 포함",
    errorUINoName: "UI \"{{ui}}\"는 유효 하지 않습니다 (name 속성이 있어야 함)",
    errorUINotObject: "UI \"{{ui}}\"는 유효 하지 않습니다 (개체 여야 합니다)",
    errorUIOverride: "UI \"{{name}}\" 이미 등록 된 고 덮어",
    fileManagerDialogTitle: "파일 관리자",
    fileManagerTitle: "파일 관리자",
    floatLeftTitle: "왼쪽에 이미지를 정렬",
    floatNoneTitle: "이미지 제거 정렬",
    floatRightTitle: "오른쪽에 이미지를 정렬",
    fontFamilyMenuFontArial: "굴림",
    fontFamilyMenuFontComicSans: "없이 만화",
    fontFamilyMenuFontCourier: "새로운 택배",
    fontFamilyMenuFontDefault: "기본 글꼴",
    fontFamilyMenuFontGeorgia: "그루지야",
    fontFamilyMenuFontImpact: "에 미치는 영향",
    fontFamilyMenuFontPalatino: "팔 라틴",
    fontFamilyMenuFontTimes: "새로운 로마 시간",
    fontFamilyMenuTitle: "당신의 글꼴 선택",
    guidesTitle: "표시 요소 가이드",
    historyRedoTitle: "다시 실행",
    historyUndoTitle: "실행 취소",
    hrCreateTitle: "가로줄 삽입",
    imageResizeButtonDialogCancelButton: "취소",
    imageResizeButtonDialogHeight: "이미지 높이",
    imageResizeButtonDialogHeightPlaceHolder: "높이",
    imageResizeButtonDialogOKButton: "크기 조정",
    imageResizeButtonDialogTitle: "이미지 크기를 조정합니다",
    imageResizeButtonDialogWidth: "이미지 너비",
    imageResizeButtonDialogWidthPlaceHolder: "너비",
    imageResizeButtonText: "이미지 크기를 조정합니다",
    insertFileDialogCancelButton: "취소",
    insertFileDialogOKButton: "파일 삽입",
    insertFileNameLabel: "파일 이름",
    insertFileNamePlaceHolder: "파일 이름...",
    insertFileTitle: "파일 삽입",
    insertFileURLLabel: "파일 URL",
    insertFileURLPlaceHolder: "파일 URL...",
    languageMenuTitle: "언어 선택",
    linkCreateDialogCancelButton: "취소",
    linkCreateDialogMenuHeader: "연결 유형 선택",
    linkCreateDialogOKButton: "링크 삽입",
    linkCreateDialogTitle: "링크 삽입",
    linkCreateTitle: "링크 삽입",
    linkRemoveTitle: "링크 제거",
    linkTypeDocumentHeader: "문서 또는 다른 파일에 연결",
    linkTypeDocumentInfo: "<h2>확실히 위의 상자에 넣어 해야할지?<\/h2><ol>    <li>귀하의 웹사이트에 업로드 된 파일 확인 하십시오.<\/li>    <li>브라우저에서 업로드 된 파일을 엽니다.<\/li>    <li>브라우저의 주소 표시줄에서 파일의 URL을 복사 하 고 위의 상자에 붙여 넣습니다.<\/li><\/ol>",
    linkTypeDocumentLabel: "문서 또는 다른 파일",
    linkTypeDocumentLocationLabel: "위치:",
    linkTypeDocumentLocationPlaceHolder: "URL 입력",
    linkTypeDocumentNewWindowHeader: "새 창",
    linkTypeDocumentNewWindowLabel: "새 브라우저 창\/탭에서 열 파일을가지고이 확인란을 선택 합니다.",
    linkTypeEmailHeader: "이메일 주소에 연결",
    linkTypeEmailLabel: "이메일 주소",
    linkTypeEmailSubjectLabel: "제목 (선택 사항):",
    linkTypeEmailSubjectPlaceHolder: "제목을 입력합니다",
    linkTypeEmailToLabel: "메일 주소:",
    linkTypeEmailToPlaceHolder: "이메일 주소를 입력",
    linkTypeExternalHeader: "다른 웹사이트에 있는 페이지에 링크",
    linkTypeExternalInfo: "<h2>확실히 위의 상자에 넣어 해야할지?<\/h2><ol>    <li>링크 하려는 웹 페이지를 찾아.<\/li>    <li>브라우저의 주소 표시줄에서 웹 주소를 복사 하 고 위의 상자에 붙여 넣습니다.<\/li><\/ol>",
    linkTypeExternalLabel: "다른 웹사이트에 페이지",
    linkTypeExternalLocationLabel: "위치:",
    linkTypeExternalLocationPlaceHolder: "URL 입력",
    linkTypeExternalNewWindowHeader: "새 창",
    linkTypeExternalNewWindowLabel: "링크를 새 브라우저 창\/탭에서이 확인란을 선택 합니다.",
    linkTypeInternalHeader: "이 웹사이트에 있는 페이지에 링크",
    linkTypeInternalInfo: "<h2>확실히 위의 상자에 넣어 해야할지?<\/h2><ol>    <li>이 사이트 링크를 페이지를 찾아.<\/li>    <li>브라우저의 주소 표시줄에 \"{{domain}}\"를 제외 하 고에서 웹 주소를 복사 하 고 위의 상자에 붙여 넣습니다.<\/li><\/ol>",
    linkTypeInternalLabel: "이 웹사이트에 페이지",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "URI 입력",
    linkTypeInternalNewWindowHeader: "새 창",
    linkTypeInternalNewWindowLabel: "링크를 새 브라우저 창\/탭에서이 확인란을 선택 합니다.",
    listOrderedTitle: "정렬 된 목록",
    listUnorderedTitle: "순서 없는 목록",
    logoTitle: "랩 터 WYSIWYG 편집기에 대 한 자세한 내용은",
    loremIpsumTitle: "테스트용 더미 텍스트 삽입",
    navigateAway: "\n거기 있다이 페이지에 변경 내용이 저장 되지. \n저장 되지 않은 변경 내용이 손실 됩니다이 페이지에서 이동 하는 경우",
    pasteDialogCancelButton: "취소",
    pasteDialogFormattedCleaned: "포맷 및 청소",
    pasteDialogFormattedUnclean: "부정한 포맷",
    pasteDialogOKButton: "삽입",
    pasteDialogPlain: "일반 텍스트",
    pasteDialogSource: "소스 코드",
    pasteDialogTitle: "붙여넣기",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "개정을 검색 하지 못했습니다.",
    revisionsApplyButtonDialogCancelButton: "취소",
    revisionsApplyButtonDialogOKButton: "롤백",
    revisionsApplyButtonDialogText: "롤백 확인",
    revisionsApplyButtonDialogTitle: "롤백 확인",
    revisionsApplyButtonText: "롤백",
    revisionsApplyButtonTitle: "롤백",
    revisionsApplyDialogContent: "이 선택한 버전으로 현재 내용을 대체 하 게 됩니다.<br>현재 콘텐츠 수정으로 추가 되 고이 블록에 대 한 수정 내용 목록에 표시 됩니다.",
    revisionsButtonCurrent: "전류",
    revisionsButtonViewDiffText: "차이",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "만든",
    revisionsDialogCancelButton: "취소",
    revisionsDialogTitle: "보기 콘텐츠 수정",
    revisionsDiffButtonDialogCancelButton: "닫기",
    revisionsDiffButtonDialogTitle: "차이 보기",
    revisionsDiffButtonText: "차이 보기",
    revisionsDiffButtonTitle: "차이 보기",
    revisionsLoading: "버전 로드...",
    revisionsNone: "이 요소에 대 한 수정 없음",
    revisionsPreviewButtonText: "미리 보기",
    revisionsPreviewButtonTitle: "미리 보기",
    revisionsText: "개정",
    revisionsTextEmpty: "없음 수정",
    revisionsTitle: "",
    rfmClose: "닫기",
    rfmContinue: "계속 해 서",
    rfmDelete: "삭제",
    rfmDownload: "다운로드",
    rfmFileActions: "작업",
    rfmFileModificationTime: "수정",
    rfmFileName: "이름",
    rfmFileSize: "크기",
    rfmFileType: "유형",
    rfmFilteredTotal: "보여주는 {{start}} {{end}}를 {{filteredTotal}} 파일",
    rfmFirst: "첫 번째",
    rfmHeadingDirectories: "디렉토리",
    rfmHeadingSearch: "검색",
    rfmHeadingTags: "태그",
    rfmHeadingUpload: "업로드",
    rfmInsert: "삽입",
    rfmLast: "최근",
    rfmSearch: "가 서",
    rfmTagDocument: "문서",
    rfmTagImage: "이미지",
    rfmTotal: "{{total}}에서 필터링",
    rfmUpload: "업로드",
    rfmUploadBrowse: "찾아보기",
    rfmUploadDrop: "여기 방울 파일",
    rfmUploadFileRemove: "제거",
    rfmUploadOr: "또는",
    rfmView: "보기",
    saveJsonFail: "{{failed}} 콘텐츠 블럭과 저장 하지 못했습니다.",
    saveJsonSaved: "{{saved}} 콘텐츠 블럭과 성공적으로 저장 합니다.",
    saveNotConfigured: "구성 되지 않은 또는 사용할 수 없습니다.",
    saveRestFail: "{{failed}} 콘텐츠 블럭과 저장 하지 못했습니다.",
    saveRestPartial: "{{saved}} {{failed}} 콘텐츠 블록을 저장 합니다.",
    saveRestSaved: "{{saved}} 콘텐츠 블럭과 성공적으로 저장 합니다.",
    saveTitle: "콘텐츠 저장",
    snippetMenuTitle: "미리 보기",
    specialCharactersArrows: "화살표",
    specialCharactersDialogOKButton: "괜찮았던 것",
    specialCharactersDialogTitle: "특수 문자 삽입",
    specialCharactersGreekAlphabet: "그리스 문자",
    specialCharactersHelp: "특수 문자 추가를 클릭 합니다. \"확인\"을 클릭 완료 되 면이 대화 상자를 닫습니다",
    specialCharactersMathematics: "수학",
    specialCharactersSymbols: "기호",
    specialCharactersTitle: "특수 문자 삽입",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} 문자 한도 초과",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} 자 남음",
    statisticsButtonCharacters: "{{characters}} 문자",
    statisticsDialogCharactersOverLimit: "권장 되는 제한은 위에 {{characters}} 문자, {{charactersRemaining}}",
    statisticsDialogCharactersRemaining: "{{characters}} 자, {{charactersRemaining}} 남음",
    statisticsDialogNotTruncated: "콘텐츠가 잘리지 않습니다.",
    statisticsDialogOKButton: "괜찮았던 것",
    statisticsDialogSentence: "{{sentences}} 문장",
    statisticsDialogSentences: "{{sentences}} 문장",
    statisticsDialogTitle: "콘텐츠 통계",
    statisticsDialogTruncated: "{{limit}} 자 이상 포함 내용과 잘릴 수 있습니다.",
    statisticsDialogWord: "{{words}} 단어",
    statisticsDialogWords: "{{words}} 단어",
    statisticsTitle: "클릭 통계 보기",
    tableCreateTitle: "테이블 만들기",
    tableDeleteColumnTitle: "테이블 열 삭제",
    tableDeleteRowTitle: "테이블 행을 삭제",
    tableInsertColumnTitle: "표 열 삽입",
    tableInsertRowTitle: "표 행을 삽입",
    tableMergeCellsTitle: "표 셀 병합",
    tableSplitCellsTitle: "표 셀 분하시오",
    tagMenuTagAddress: "주소",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "제목 1",
    tagMenuTagH2: "제목 2",
    tagMenuTagH3: "제목 3",
    tagMenuTagH4: "제목 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "단락",
    tagMenuTagPre: "사전 포맷",
    tagMenuTitle: "요소의 스타일 변경",
    tagTreeElementLink: "{{element}} 요소 선택",
    tagTreeElementTitle: "\"{{element}}\" 요소 내용을 선택 하려면 클릭 하십시오",
    tagTreeRoot: "루트",
    tagTreeRootLink: "모든 편집 가능한 콘텐츠 선택",
    tagTreeRootTitle: "모든 편집 가능한 콘텐츠를 선택 하려면 클릭 하십시오",
    textBlockQuoteTitle: "블록 인용",
    textBoldTitle: "굵게",
    textItalicTitle: "기울임꼴",
    textSizeDecreaseTitle: "텍스트 크기 감소",
    textSizeIncreaseTitle: "텍스트 크기 증가",
    textStrikeTitle: "통해 파업",
    textSubTitle: "서브 스크립트",
    textSuperTitle: "슈퍼 스크립트",
    textUnderlineTitle: "밑줄",
    unsavedEditWarningText: "거기이 페이지에서 변경을 저장 되지 있습니다.",
    viewSourceDialogCancelButton: "닫기",
    viewSourceDialogOKButton: "소스 코드 적용",
    viewSourceDialogTitle: "콘텐츠 소스 코드",
    viewSourceTitle: "보기\/편집 소스 코드"
});