/**
 * @fileOverview Lithuanian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('lt', 'Lietuvių', {
    alignCenterTitle: "Centruoti tekstą",
    alignJustifyTitle: "Išlygiuoti tekstą pateisinti",
    alignLeftTitle: "Lygiuoti tekstą kairėje",
    alignRightTitle: "Tekstą lygiuoti dešinėje",
    cancelDialogCancelButton: "Tęsti redagavimą",
    cancelDialogContent: "Ar tikrai norite atšaukti redagavimą? Visi pakeitimai bus prarasti!",
    cancelDialogOKButton: "Atšaukti redagavimą",
    cancelDialogTitle: "Atšaukti redagavimą",
    cancelTitle: "Atšaukti redagavimą",
    classMenuTitle: "Stiliaus parinkiklis",
    clearFormattingTitle: "Valyti formatavimą",
    clickButtonToEditText: "Redaguoti",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatinis",
    colorMenuBasicBlack: "Juoda",
    colorMenuBasicBlue: "Mėlyna",
    colorMenuBasicGreen: "Žalioji",
    colorMenuBasicGrey: "Pilka",
    colorMenuBasicOrange: "Oranžinė",
    colorMenuBasicPurple: "Violetinė",
    colorMenuBasicRed: "Raudona",
    colorMenuBasicTitle: "Pakeisti teksto spalvą:",
    colorMenuBasicWhite: "Balta",
    dockToElementTitle: "Elementas redaktorius dokas\/atjungti nuo doko",
    dockToScreenTitle: "Atjungti nuo doko\/doko redaktorius į ekraną",
    embedDialogCancelButton: "Atšaukti",
    embedDialogOKButton: "Įterpti objektą",
    embedDialogTabCode: "Įterpti kodą",
    embedDialogTabCodeContent: "Įklijuokite savo įterpti kodą į teksto srities apačioje:",
    embedDialogTabPreview: "Peržiūra",
    embedDialogTabPreviewContent: "Peržiūrėti savo įdėtasis objektas yra rodomas žemiau:",
    embedDialogTitle: "Įterpti objektą",
    embedTitle: "Įterpti objektą",
    errorUINoName: "UI \"{{ui}}\" yra neteisingas (turi būti ypatybei pavadinimas)",
    errorUINotObject: "UI \"{{ui}}\" yra neteisingas (turi būti objekto)",
    errorUIOverride: "UI \"{{name}}\" jau buvo įregistruotas, ir jis bus perrašytas",
    fileManagerDialogTitle: "Failų tvarkyklė",
    fileManagerTitle: "Failų tvarkyklė",
    floatLeftTitle: "Suderinti vaizdą į kairę",
    floatNoneTitle: "Pašalinti vaizdo lygiuotė",
    floatRightTitle: "Suderinti vaizdą į dešinę",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komiksai be",
    fontFamilyMenuFontCourier: "Kurjerių naujas",
    fontFamilyMenuFontDefault: "Numatytasis šriftas",
    fontFamilyMenuFontGeorgia: "Gruzija",
    fontFamilyMenuFontImpact: "Poveikio",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Pasirinkti šrifto dydį",
    guidesTitle: "Rodyti elementas informacija",
    historyRedoTitle: "Perdaryti",
    historyUndoTitle: "Anuliuoti",
    hrCreateTitle: "Įterpti Horizontal Rule",
    imageResizeButtonDialogCancelButton: "Atšaukti",
    imageResizeButtonDialogHeight: "Nuotraukos aukštis",
    imageResizeButtonDialogHeightPlaceHolder: "Aukštis",
    imageResizeButtonDialogOKButton: "Keisti dydį",
    imageResizeButtonDialogTitle: "Resize vaizdo",
    imageResizeButtonDialogWidth: "Plotis",
    imageResizeButtonDialogWidthPlaceHolder: "Plotis",
    imageResizeButtonText: "Resize vaizdo",
    insertFileDialogCancelButton: "Atšaukti",
    insertFileDialogOKButton: "Įterpti failą",
    insertFileNameLabel: "Failo vardas",
    insertFileNamePlaceHolder: "Failo vardas...",
    insertFileTitle: "Įterpti failą",
    insertFileURLLabel: "Failo URL",
    insertFileURLPlaceHolder: "Failo URL...",
    languageMenuTitle: "Kalbos keitimas",
    linkCreateDialogCancelButton: "Atšaukti",
    linkCreateDialogMenuHeader: "Pasirinkite saito tipas",
    linkCreateDialogOKButton: "Įterpti saitą",
    linkCreateDialogTitle: "Įterpti saitą",
    linkCreateTitle: "Įterpti saitą",
    linkRemoveTitle: "Pašalinti saitą",
    linkTypeDocumentHeader: "Nuoroda į dokumentą ar kitą failą",
    linkTypeDocumentInfo: "<h2>Nesate tikras, ką įtraukti į aukščiau esantį laukelį?<\/h2><ol>    <li>Užtikrinti, kad failas yra įkeltas į jūsų svetainę.<\/li>    <li>Atidaryti nusiųstą failą savo naršyklėje.<\/li>    <li>Kopijuoti failo URL iš savo naršyklės adreso juostą ir įklijuokite jį į aukščiau esantį laukelį.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumento ar kito failo",
    linkTypeDocumentLocationLabel: "Vieta:",
    linkTypeDocumentLocationPlaceHolder: "Įveskite URL",
    linkTypeDocumentNewWindowHeader: "Naujame lange",
    linkTypeDocumentNewWindowLabel: "Pažymėkite šį langelį, kad failą atidaryti naujame naršyklės lange\/skirtuke.",
    linkTypeEmailHeader: "Susieti su el. pašto adresą",
    linkTypeEmailLabel: "Elektroninio pašto adresas",
    linkTypeEmailSubjectLabel: "Tema (neprivaloma):",
    linkTypeEmailSubjectPlaceHolder: "Çra¹ykite tem±",
    linkTypeEmailToLabel: "El. paštas:",
    linkTypeEmailToPlaceHolder: "Įveskite elektroninio pašto adresą",
    linkTypeExternalHeader: "Nuoroda į kitą svetainę puslapyje",
    linkTypeExternalInfo: "<h2>Nesate tikras, ką įtraukti į aukščiau esantį laukelį?<\/h2><ol>    <li>Rasti puslapyje norite susieti su žiniatinklyje.<\/li>    <li>Nukopijuokite interneto adresą, iš savo naršyklės adreso juostą ir įklijuokite jį į aukščiau esantį laukelį.<\/li><\/ol>",
    linkTypeExternalLabel: "Puslapis apie kitą svetainę",
    linkTypeExternalLocationLabel: "Vieta:",
    linkTypeExternalLocationPlaceHolder: "Įveskite URL",
    linkTypeExternalNewWindowHeader: "Naujame lange",
    linkTypeExternalNewWindowLabel: "Paώymλkite πα langelα, kad atidaryti naujame naršyklės lange\/skirtuke nuoroda.",
    linkTypeInternalHeader: "Nuoroda į puslapį šioje svetainėje",
    linkTypeInternalInfo: "<h2>Nesate tikras, ką įtraukti į aukščiau esantį laukelį?<\/h2><ol>    <li>Rasti puslapyje šios svetainės nuorodą.<\/li>    <li>Nukopijuokite interneto adresą, iš savo naršyklės adreso juostoje, išskyrus \"{{domain}}\" ir įklijuokite jį į aukščiau esantį laukelį.<\/li><\/ol>",
    linkTypeInternalLabel: "Puslapis šioje svetainėje",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Įveskite URI",
    linkTypeInternalNewWindowHeader: "Naujame lange",
    linkTypeInternalNewWindowLabel: "Paώymλkite πα langelα, kad atidaryti naujame naršyklės lange\/skirtuke nuoroda.",
    listOrderedTitle: "Sekos sąrašas",
    listUnorderedTitle: "Nesutvarkytas sąrašas",
    logoTitle: "Sužinokite daugiau apie Raptor WYSIWYG redaktorius",
    navigateAway: "\nYra neįrašytų keitimų šiame puslapyje. \nJei jums išeiti iš šio puslapio jums bus prarasti neįrašytus keitimus",
    pasteDialogCancelButton: "Atšaukti",
    pasteDialogFormattedCleaned: "Formatuoti &amp; išvalyti",
    pasteDialogFormattedUnclean: "Suformatuotas nešvarus",
    pasteDialogOKButton: "Įterpti",
    pasteDialogPlain: "Paprastasis tekstas",
    pasteDialogSource: "Šaltinio kodas",
    pasteDialogTitle: "Pasta",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Nepavyko nuskaityti pakeitimus",
    revisionsApplyButtonDialogCancelButton: "Atšaukti",
    revisionsApplyButtonDialogOKButton: "Keitimų atšaukimas",
    revisionsApplyButtonDialogTitle: "Keitimų atšaukimo patvirtinimas",
    revisionsApplyButtonTitle: "Keitimų atšaukimas",
    revisionsApplyDialogContent: "Tai pakeis pasirinktą peržiūrėti turinio.<br>Turinio bus pridedamas kaip peržiūrėti, ir bus matomi pakeitimai šį bloką.",
    revisionsButtonCurrent: "Srovė",
    revisionsButtonViewDiffText: "Skirtumai",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Atšaukti",
    revisionsDialogTitle: "Rodyti turinio pakeitimai",
    revisionsDiffButtonDialogCancelButton: "Uždaryti",
    revisionsDiffButtonDialogTitle: "Rodyti skirtumai",
    revisionsDiffButtonTitle: "Rodyti skirtumai",
    revisionsLoading: "Pakrovimo pakeitimus...",
    revisionsNone: "Nėra pataisymų šio elemento",
    revisionsPreviewButtonTitle: "Peržiūra",
    revisionsText: "Pakeitimai",
    revisionsTextEmpty: "Jokių pataisymų",
    revisionsTitle: "",
    rfmClose: "Uždaryti",
    rfmContinue: "Toliau",
    rfmDelete: "Naikinti",
    rfmDownload: "Parsisiųsti",
    rfmFileActions: "Veiksmai",
    rfmFileModificationTime: "Modifikuotas",
    rfmFileName: "vardas, pavadinimas",
    rfmFileSize: "Dydis",
    rfmFileType: "Tipo",
    rfmFilteredTotal: "Parodydami {{start}} {{end}} {{filteredTotal}} failų",
    rfmFirst: "Pirmosios",
    rfmHeadingDirectories: "Katalogai",
    rfmHeadingSearch: "Paieškos",
    rfmHeadingTags: "Žymos",
    rfmHeadingUpload: "Įkelti",
    rfmInsert: "Įterpti",
    rfmLast: "Paskutinis",
    rfmSearch: "Eiti",
    rfmTotal: ", išfiltruoti iš {{total}}",
    rfmUpload: "Įkelti",
    rfmUploadBrowse: "Naršyti",
    rfmUploadDrop: "Numeskite failus čia",
    rfmUploadFileRemove: "Pašalinti",
    rfmView: "Rodyti",
    saveJsonFail: "Nepavyko įrašyti {{failed}} turinio numerių grupę-ES",
    saveJsonSaved: "Sėkmingai įrašyti {{saved}} turinio numerių grupę-ES.",
    saveNotConfigured: "Įrašyti nesukonfigūruota, arba išjungta.",
    saveRestFail: "Nepavyko įrašyti {{failed}} turinio numerių grupę-ES.",
    saveRestPartial: "Įrašyti {{saved}} iš {{failed}} turinio blokai.",
    saveRestSaved: "Sėkmingai įrašyti {{saved}} turinio numerių grupę-ES.",
    saveTitle: "Išsaugoti turinio",
    snippetMenuTitle: "Fragmentai",
    specialCharactersDialogOKButton: "gerai",
    specialCharactersDialogTitle: "Įterpti specialiuosius simbolius",
    specialCharactersHelp: "Spustelėkite Specialusis simbolis jį įtraukti. Spustelėkite \"Gerai\" kai daroma uždarykite šį dialogo langą",
    specialCharactersTitle: "Specialiojo rašmens įterpimas",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} simbolių ribą",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} simboliai lieka",
    statisticsButtonCharacters: "{{characters}} simboliai",
    statisticsDialogCharactersOverLimit: "{{characters}} simboliai, {{charactersRemaining}} per nurodytas rekomenduojamas limitas",
    statisticsDialogCharactersRemaining: "{{characters}}, {{charactersRemaining}} liko simbolių",
    statisticsDialogNotTruncated: "Turinys bus nukirsta",
    statisticsDialogOKButton: "gerai",
    statisticsDialogSentence: "{{sentences}} sakinys",
    statisticsDialogSentences: "{{sentences}} sakiniai",
    statisticsDialogTitle: "Turinio statistika",
    statisticsDialogTruncated: "Turinį sudaro daugiau negu {{limit}} simbolių ir gali būti sutrumpintas",
    statisticsDialogWord: "{{words}} žodis",
    statisticsDialogWords: "{{words}} žodžiai",
    statisticsTitle: "Paspauskite, jei norite peržiūrėti statistiką",
    tableCreateTitle: "Lentelės kūrimas",
    tableDeleteColumnTitle: "Naikinti lentelės stulpelyje",
    tableDeleteRowTitle: "Naikinti lentelės eilutę",
    tableInsertColumnTitle: "Įterpti lentelės stulpelį",
    tableInsertRowTitle: "Įterpti lentelės eilutę",
    tableMergeCellsTitle: "Sulieti lentelės langelius",
    tableSplitCellsTitle: "Skaidyti lentelės langelius",
    tagMenuTagAddress: "Adresas",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Antraštė 1",
    tagMenuTagH2: "2 Išlaidų kategorija",
    tagMenuTagH3: "3 Pozicijos",
    tagMenuTagH4: "4 Išlaidų kategorijos",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Dalies",
    tagMenuTagPre: "Iš anksto suformatuotas",
    tagMenuTitle: "Pakeisti elemento stilius",
    tagTreeElementLink: "Pasirinkite {{element}} elementas",
    tagTreeElementTitle: "Spustelėkite, kad pasirinktumėte \"{{element}}\" elemento turinį",
    tagTreeRoot: "šaknis",
    tagTreeRootLink: "Pasirinkite Redaguoti pridìti",
    tagTreeRootTitle: "Spustelėkite, kad pažymėtumėte visą redaguojamą turinį",
    textBlockQuoteTitle: "Bloko citata",
    textBoldTitle: "Paryškinti",
    textItalicTitle: "Pasvirasis",
    textSizeDecreaseTitle: "Mažinti teksto dydį",
    textSizeIncreaseTitle: "Didinti teksto dydį",
    textStrikeTitle: "Perbraukti",
    textSubTitle: "Sub-scenarijų",
    textSuperTitle: "Super scenarijus",
    textUnderlineTitle: "Pabraukti",
    unsavedEditWarningText: "Yra neįrašytų keitimų šiame puslapyje",
    viewSourceDialogCancelButton: "Uždaryti",
    viewSourceDialogOKButton: "Taikyti kodą",
    viewSourceDialogTitle: "Turinio šaltinio kodas",
    viewSourceTitle: "Peržiūrėti\/redaguoti kodą"
});