/**
 * @fileOverview Latvian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('lv', 'Latviešu', {
    alignCenterTitle: "Līdzināt tekstu centrs",
    alignJustifyTitle: "Līdzinātu tekstu, kas attaisno",
    alignLeftTitle: "Līdzināt tekstu pa kreisi",
    alignRightTitle: "Līdzināt tekstu pa labi",
    cancelDialogCancelButton: "Turpināt rediģēšanu",
    cancelDialogContent: "Vai tiešām vēlaties atcelt rediģēšanu Visas izmaiņas tiks zaudētas!",
    cancelDialogOKButton: "Atcelt rediģēšanu",
    cancelDialogTitle: "Atcelt rediģēšanu",
    cancelTitle: "Atcelt rediģēšanu",
    classMenuTitle: "Stila izvēles",
    clearFormattingTitle: "Notīrīt formatējumu",
    clickButtonToEditText: "Rediģēt",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automātiska",
    colorMenuBasicBlack: "Black",
    colorMenuBasicBlue: "Zila",
    colorMenuBasicGreen: "Green",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Violeta",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Teksta krāsas maiņa",
    colorMenuBasicWhite: "White",
    dockToElementTitle: "Elementu redaktoru doks\/atdokošana",
    dockToScreenTitle: "Dock\/atdokot redaktora ekrānā",
    embedDialogCancelButton: "Atcelt",
    embedDialogOKButton: "Iegultu objektu",
    embedDialogTabCode: "Iegulto kodu",
    embedDialogTabCodeContent: "Ielīmējiet iegultu kodu teksta apgabalu zemāk:",
    embedDialogTabPreview: "Priekšskatījums",
    embedDialogTabPreviewContent: "Iegulto objektu priekšskatījums tiek parādīts zemāk:",
    embedDialogTitle: "Iegultu objektu",
    embedTitle: "Iegultu objektu",
    errorUINoName: "Lietotāja Interfeisu \"{{ui}}\" ir nederīga (jābūt nosaukuma rekvizītu)",
    errorUINotObject: "Lietotāja Interfeisu \"{{ui}}\" ir nederīga (jābūt objektam)",
    errorUIOverride: "UI \"{{name}}\" jau ir reģistrēta, un tiks pārrakstīti",
    fileManagerDialogTitle: "Failu pārvaldnieks",
    fileManagerTitle: "Failu pārvaldnieks",
    floatLeftTitle: "Līdzināt attēlu pa kreisi",
    floatNoneTitle: "Noņemiet attēla līdzināšana",
    floatRightTitle: "Līdzināt attēlu pa labi",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komiksu bez",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Noklusējuma fonts",
    fontFamilyMenuFontGeorgia: "Gruzija",
    fontFamilyMenuFontImpact: "Ietekme",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Izvēlieties savu fontu",
    guidesTitle: "Rādīt elementu ceļveži",
    historyRedoTitle: "Atcelt atsaukšanu",
    historyUndoTitle: "Atsaukt",
    hrCreateTitle: "Iespraust horizontāla līnija",
    imageResizeButtonDialogCancelButton: "Atcelt",
    imageResizeButtonDialogHeight: "Attēla augstums",
    imageResizeButtonDialogHeightPlaceHolder: "Augstums",
    imageResizeButtonDialogOKButton: "Mainīt izmērus",
    imageResizeButtonDialogTitle: "Mainītu attēla izmērus",
    imageResizeButtonDialogWidth: "Attēla platums",
    imageResizeButtonDialogWidthPlaceHolder: "Platums",
    imageResizeButtonText: "Mainītu attēla izmērus",
    insertFileDialogCancelButton: "Atcelt",
    insertFileDialogOKButton: "Faila iespraušana",
    insertFileNameLabel: "Faila nosaukums",
    insertFileNamePlaceHolder: "Faila nosaukumu...",
    insertFileTitle: "Faila iespraušana",
    insertFileURLLabel: "Faila URL",
    insertFileURLPlaceHolder: "Faila URL...",
    languageMenuTitle: "Mainīt valodu",
    linkCreateDialogCancelButton: "Atcelt",
    linkCreateDialogMenuHeader: "Izvēlieties saites tipu",
    linkCreateDialogOKButton: "Ievietot saiti",
    linkCreateDialogTitle: "Ievietot saiti",
    linkCreateTitle: "Ievietot saiti",
    linkRemoveTitle: "Noņemt saiti",
    linkTypeDocumentHeader: "Saiti uz dokumentu vai citu failu",
    linkTypeDocumentInfo: "<h2>Nav pārliecināts, ko likt lodziņā augstāk?<\/h2><ol>    <li>Pārliecinieties, ka fails ir augšupielādēts uz jūsu vietni.<\/li>    <li>Pārlūkprogrammā atvērtu augšupielādēto failu.<\/li>    <li>Kopēsit failu URL pārlūkprogrammas adrešu joslā un ielīmējiet lodziņā augstāk.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumentu vai citu failu",
    linkTypeDocumentLocationLabel: "Atrašanās vieta:",
    linkTypeDocumentLocationPlaceHolder: "Ievadiet URL",
    linkTypeDocumentNewWindowHeader: "Jaunā logā",
    linkTypeDocumentNewWindowLabel: "Atzīmējiet šo izvēles rūtiņu, lai failu atvērtu jaunā pārlūkprogrammas logā\/TAB.",
    linkTypeEmailHeader: "Saiti uz e-pasta adresi",
    linkTypeEmailLabel: "E-pasta adresi",
    linkTypeEmailSubjectLabel: "Tēma (neobligāti):",
    linkTypeEmailSubjectPlaceHolder: "Ievadiet tēmu",
    linkTypeEmailToLabel: "E-pasts:",
    linkTypeEmailToPlaceHolder: "Ievadiet e-pasta adresi",
    linkTypeExternalHeader: "Saiti uz lapu citā vietnē",
    linkTypeExternalInfo: "<h2>Nav pārliecināts, ko likt lodziņā augstāk?<\/h2><ol>    <li>Atrast lapu tīmeklī, kuru vēlaties izveidot saiti.<\/li>    <li>Kopējiet web adresi no pārlūkprogrammas adrešu joslā un ielīmējiet to lodziņā augstāk.<\/li><\/ol>",
    linkTypeExternalLabel: "Lappusi citā vietnē",
    linkTypeExternalLocationLabel: "Atrašanās vieta:",
    linkTypeExternalLocationPlaceHolder: "Ievadiet URL",
    linkTypeExternalNewWindowHeader: "Jaunā logā",
    linkTypeExternalNewWindowLabel: "Atzīmējiet šo izvēles rūtiņu, lai saite atvērt jaunu pārlūka logu\/cilni.",
    linkTypeInternalHeader: "Saiti uz lapu šajā vietnē",
    linkTypeInternalInfo: "<h2>Nav pārliecināts, ko likt lodziņā augstāk?<\/h2><ol>    <li>Uz vietnes saites, lai atrastu lapu.<\/li>    <li>Kopējiet web adresi no pārlūkprogrammas adrešu joslā, izņemot \"{{domain}}\" un ielīmējiet to lodziņā augstāk.<\/li><\/ol>",
    linkTypeInternalLabel: "Lapu šajā vietnē",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Ievadiet URI",
    linkTypeInternalNewWindowHeader: "Jaunā logā",
    linkTypeInternalNewWindowLabel: "Atzīmējiet šo izvēles rūtiņu, lai saite atvērt jaunu pārlūka logu\/cilni.",
    listOrderedTitle: "Sakārtotu sarakstu",
    listUnorderedTitle: "Nenumurēts saraksts",
    logoTitle: "Uzziniet vairāk par Raptor WYSIWYG redaktors",
    loremIpsumTitle: "Ievietot lelles teksts testēšanai",
    navigateAway: "\nŠajā lapā ir nesaglabātas izmaiņas. \nJa naviģēsit prom no šīs lapas, jūs zaudēsiet nesaglabātās izmaiņas",
    pasteDialogCancelButton: "Atcelt",
    pasteDialogFormattedCleaned: "Formatēts &amp; jātīra",
    pasteDialogFormattedUnclean: "Formatēts nešķīsts",
    pasteDialogOKButton: "Iespraust",
    pasteDialogPlain: "Vienkārša teksta",
    pasteDialogSource: "Avota kods",
    pasteDialogTitle: "Ielīmēt",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Neizdevās izgūt pārskatījumus",
    revisionsApplyButtonDialogCancelButton: "Atcelt",
    revisionsApplyButtonDialogOKButton: "Atrite",
    revisionsApplyButtonDialogText: "Atrite apstiprinājums",
    revisionsApplyButtonDialogTitle: "Atrite apstiprinājums",
    revisionsApplyButtonText: "Atrite",
    revisionsApplyButtonTitle: "Atrite",
    revisionsApplyDialogContent: "Tas aizstās pašreizējo saturu atlasītajā pārskatīšanu.<br>Pašreizējais saturs tiks pievienots kā pārskatīšana, un būs redzama šī bloka saraksta pārskatīšanu.",
    revisionsButtonCurrent: "Pašreizējā",
    revisionsButtonViewDiffText: "Atšķirības",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Izveidots",
    revisionsDialogCancelButton: "Atcelt",
    revisionsDialogTitle: "Skata satura pārskatīšanu",
    revisionsDiffButtonDialogCancelButton: "Aizvērt",
    revisionsDiffButtonDialogTitle: "Skatīt atšķirības",
    revisionsDiffButtonText: "Skatīt atšķirības",
    revisionsDiffButtonTitle: "Skatīt atšķirības",
    revisionsLoading: "Pārskatīšana notiek ielāde...",
    revisionsNone: "Šim elementam nav pārskatījumus",
    revisionsPreviewButtonText: "Priekšskatījums",
    revisionsPreviewButtonTitle: "Priekšskatījums",
    revisionsText: "Labojumi",
    revisionsTextEmpty: "Nekādas izmaiņas",
    revisionsTitle: "",
    rfmClose: "Aizvērt",
    rfmContinue: "Turpināt",
    rfmDelete: "Dzēst",
    rfmDownload: "Lejupielādēt",
    rfmFileActions: "Darbības",
    rfmFileModificationTime: "Modificēt",
    rfmFileName: "vārds",
    rfmFileSize: "Lielums",
    rfmFileType: "Tips",
    rfmFilteredTotal: "{{start}} rāda izbeigt {{end}} {{filteredTotal}} failiem",
    rfmFirst: "Pirmais",
    rfmHeadingDirectories: "Katalogi",
    rfmHeadingSearch: "Meklēšanas",
    rfmHeadingTags: "Tagus",
    rfmHeadingUpload: "Augšupielādēt",
    rfmInsert: "Iespraust",
    rfmLast: "Pēdējais",
    rfmSearch: "Iet",
    rfmTagDocument: "Dokumentu",
    rfmTagImage: "Attēlu",
    rfmTotal: ", plūda {{total}}",
    rfmUpload: "Augšupielādēt",
    rfmUploadBrowse: "Pārlūkot",
    rfmUploadDrop: "Nomest failus šeit",
    rfmUploadFileRemove: "Noņemt",
    rfmUploadOr: "vai",
    rfmView: "Skats",
    saveJsonFail: "Neizdevās saglabāt saturu izdota {{failed}}",
    saveJsonSaved: "Veiksmīgi saglabāta {{saved}} satura izdota.",
    saveNotConfigured: "Saglabāt nav konfigurēts, vai tas ir atspējots.",
    saveRestFail: "Neizdevās saglabāt saturu izdota {{failed}}.",
    saveRestPartial: "Saglabāti {{saved}} no {{failed}} satura blokus.",
    saveRestSaved: "Veiksmīgi saglabāta {{saved}} satura izdota.",
    saveTitle: "Saglabāt saturu",
    snippetMenuTitle: "Fragmentus",
    specialCharactersArrows: "Bultas",
    specialCharactersDialogOKButton: "labi",
    specialCharactersDialogTitle: "Ievietotu speciālās rakstzīmes",
    specialCharactersGreekAlphabet: "Grieķu alfabēts",
    specialCharactersHelp: "Noklikšķiniet uz speciālās rakstzīmes, lai to pievienotu. Noklikšķiniet uz Labi, kad izdarīts, lai aizvērtu šo dialogu",
    specialCharactersMathematics: "Matemātika",
    specialCharactersSymbols: "Simboli",
    specialCharactersTitle: "Ievietotu speciālo rakstzīmi",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} rakstzīmes, kas pārsniedz ierobežojumus",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} rakstzīmju, pārējais",
    statisticsButtonCharacters: "{{characters}} rakstzīmes",
    statisticsDialogCharactersOverLimit: "{{characters}} rakstzīmes, {{charactersRemaining}} pārsniedz ieteicamo robežu",
    statisticsDialogCharactersRemaining: "{{characters}} rakstzīmes, {{charactersRemaining}} atlikušo",
    statisticsDialogNotTruncated: "Saturs nevar tikt apcirsti",
    statisticsDialogOKButton: "labi",
    statisticsDialogSentence: "{{sentences}} teikumu",
    statisticsDialogSentences: "{{sentences}} teikumus",
    statisticsDialogTitle: "Satura statistiku",
    statisticsDialogTruncated: "Saturu, kas satur vairāk nekā {{limit}} rakstzīmēm un var saīsināt",
    statisticsDialogWord: "{{words}} vārdu",
    statisticsDialogWords: "{{words}} vārdus",
    statisticsTitle: "Noklikšķiniet, lai skatītu statistiku",
    tableCreateTitle: "Izveidot tabulu",
    tableDeleteColumnTitle: "Dzēst tabulas kolonnas",
    tableDeleteRowTitle: "Dzēst tabulas rindas",
    tableInsertColumnTitle: "Ievietot tabulas kolonnu",
    tableInsertRowTitle: "Ievietot tabulas rindu",
    tableMergeCellsTitle: "Sapludināt tabulas šūnas",
    tableSplitCellsTitle: "Sadalīt tabulas šūnas",
    tagMenuTagAddress: "Adrese",
    tagMenuTagDiv: "DIV",
    tagMenuTagH1: "Virsraksts 1",
    tagMenuTagH2: "Virsraksts 2",
    tagMenuTagH3: "Virsraksts 3",
    tagMenuTagH4: "4. Pozīcijā",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Punkts",
    tagMenuTagPre: "Sākotnēji formatētas",
    tagMenuTitle: "Elementu stila mainīšana",
    tagTreeElementLink: "Atlasiet elementu {{element}}",
    tagTreeElementTitle: "Noklikšķiniet, lai atlasītu saturu no \"{{element}}\" elements",
    tagTreeRoot: "saknes",
    tagTreeRootLink: "Izvēlieties Rediģēt visu saturu",
    tagTreeRootTitle: "Noklikšķiniet, lai atlasītu visu labot saturu",
    textBlockQuoteTitle: "Bloka citāta",
    textBoldTitle: "Treknraksts",
    textItalicTitle: "Italic",
    textSizeDecreaseTitle: "Samazināt teksta lielumu",
    textSizeIncreaseTitle: "Palielināt teksta izmēru",
    textStrikeTitle: "Pārsvītrojums",
    textSubTitle: "Sub-skriptu",
    textSuperTitle: "Super-skriptu",
    textUnderlineTitle: "Pasvītrojums",
    unsavedEditWarningText: "Ir nesaglabātas izmaiņas šajā lapā",
    viewSourceDialogCancelButton: "Aizvērt",
    viewSourceDialogOKButton: "Lietojiet avota kodu",
    viewSourceDialogTitle: "Satura avota kods",
    viewSourceTitle: "Skatīt\/rediģēt avota kodu"
});