/**
 * @fileOverview Malay strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ms', 'Melayu', {
    alignCenterTitle: "Menjajarkan teks Pusat",
    alignJustifyTitle: "Menjajarkan teks justifikasi",
    alignLeftTitle: "Menjajarkan teks kiri",
    alignRightTitle: "Menjajarkan teks hak",
    cancelDialogCancelButton: "Terus mengedit",
    cancelDialogContent: "Adakah anda pasti anda mahu membatalkan menyunting? Semua perubahan akan hilang!",
    cancelDialogOKButton: "Membatalkan penyuntingan",
    cancelDialogTitle: "Membatalkan penyuntingan",
    cancelTitle: "Membatalkan penyuntingan",
    classMenuTitle: "Gaya picker",
    clearFormattingTitle: "Format yang jelas",
    clickButtonToEditText: "Edit",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatik",
    colorMenuBasicBlack: "Hitam",
    colorMenuBasicBlue: "Biru",
    colorMenuBasicGreen: "Hijau",
    colorMenuBasicGrey: "Kelabu",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Purple",
    colorMenuBasicRed: "Merah",
    colorMenuBasicTitle: "Menukar warna teks",
    colorMenuBasicWhite: "Putih",
    dockToElementTitle: "Keluar Dok\/dok editor untuk elemen",
    dockToScreenTitle: "Keluar Dok\/dok editor untuk skrin",
    embedDialogCancelButton: "Batal",
    embedDialogOKButton: "Menerapkan objek",
    embedDialogTabCode: "Embed kod",
    embedDialogTabCodeContent: "Paste kod embed anda dalam kawasan teks di bawah:",
    embedDialogTabPreview: "Pratonton",
    embedDialogTabPreviewContent: "Pratonton objek terbenam anda dipaparkan di bawah:",
    embedDialogTitle: "Menerapkan objek",
    embedTitle: "Menerapkan objek",
    errorUINoName: "UI \"{{ui}}\" tidak sah (mesti mempunyai sifat nama)",
    errorUINotObject: "UI \"{{ui}}\" tidak sah (mestilah objek)",
    errorUIOverride: "UI \"{{name}}\" telah berdaftar dan akan ditulis ganti",
    fileManagerDialogTitle: "Pengurus fail",
    fileManagerTitle: "Pengurus fail",
    floatLeftTitle: "Menyelaraskan imej di sebelah kiri",
    floatNoneTitle: "Alih Keluar imej menyelaraskan",
    floatRightTitle: "Menyelaraskan imej ke kanan",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komik tanpa",
    fontFamilyMenuFontCourier: "Kurier yang baru",
    fontFamilyMenuFontDefault: "Fon lalai",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Kesan",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Masa baru Rom",
    fontFamilyMenuTitle: "Sila pilih teks anda",
    guidesTitle: "Menunjukkan panduan elemen",
    historyRedoTitle: "Buat semula",
    historyUndoTitle: "Buat asal",
    hrCreateTitle: "Sisipkan garisan lintang",
    imageResizeButtonDialogCancelButton: "Batal",
    imageResizeButtonDialogHeight: "Tinggi imej",
    imageResizeButtonDialogHeightPlaceHolder: "Ketinggian",
    imageResizeButtonDialogOKButton: "Saiz semula",
    imageResizeButtonDialogTitle: "Mengubah saiz imej",
    imageResizeButtonDialogWidth: "Lebar imej",
    imageResizeButtonDialogWidthPlaceHolder: "Lebar",
    imageResizeButtonText: "Mengubah saiz imej",
    insertFileDialogCancelButton: "Batal",
    insertFileDialogOKButton: "Masukkan fail",
    insertFileNameLabel: "Nama fail",
    insertFileNamePlaceHolder: "Nama fail...",
    insertFileTitle: "Masukkan fail",
    insertFileURLLabel: "URL fail",
    insertFileURLPlaceHolder: "URL fail...",
    languageMenuTitle: "Tukar Bahasa",
    linkCreateDialogCancelButton: "Batal",
    linkCreateDialogMenuHeader: "Pilih jenis pautan",
    linkCreateDialogOKButton: "Masukkan pautan",
    linkCreateDialogTitle: "Masukkan pautan",
    linkCreateTitle: "Masukkan pautan",
    linkRemoveTitle: "Mengalih keluar pautan",
    linkTypeDocumentHeader: "Pautan ke dokumen atau fail lain",
    linkTypeDocumentInfo: "<h2>Tidak pasti apa yang perlu dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Memastikan fail yang telah dimuat naik ke laman web anda.<\/li>    <li>Membuka fail gambar dalam pelayar anda.<\/li>    <li>Copy URL fail dari bar alamat penyemak imbas anda dan paste ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumen atau fail lain",
    linkTypeDocumentLocationLabel: "Lokasi:",
    linkTypeDocumentLocationPlaceHolder: "Masukkan URL",
    linkTypeDocumentNewWindowHeader: "Tetingkap baru",
    linkTypeDocumentNewWindowLabel: "Semak kotak ini mempunyai fail yang dibuka di dalam tetingkap\/tab browser baru.",
    linkTypeEmailHeader: "Link ke alamat e-mel",
    linkTypeEmailLabel: "Alamat e-mel",
    linkTypeEmailSubjectLabel: "Subjek (pilihan):",
    linkTypeEmailSubjectPlaceHolder: "Masukkan subjek",
    linkTypeEmailToLabel: "E-mel:",
    linkTypeEmailToPlaceHolder: "Masukkan alamat e-mel",
    linkTypeExternalHeader: "Pautan ke halaman di laman web lain",
    linkTypeExternalInfo: "<h2>Tidak pasti apa yang perlu dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Mencari laman web yang anda mahu pautkan ke.<\/li>    <li>Salin alamat web dari bar alamat penyemak imbas anda dan paste ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeExternalLabel: "Laman di laman web lain",
    linkTypeExternalLocationLabel: "Lokasi:",
    linkTypeExternalLocationPlaceHolder: "Masukkan URL",
    linkTypeExternalNewWindowHeader: "Tetingkap baru",
    linkTypeExternalNewWindowLabel: "Semak kotak ini mempunyai link yang dibuka di dalam tetingkap\/tab browser baru.",
    linkTypeInternalHeader: "Pautan ke halaman di laman web ini",
    linkTypeInternalInfo: "<h2>Tidak pasti apa yang perlu dimasukkan ke dalam kotak di atas?<\/h2><ol>    <li>Mencari halaman pautan laman web ini.<\/li>    <li>Salin alamat web dari bar tidak termasuk \"{{domain}}\" alamat penyemak imbas anda dan paste ke dalam kotak di atas.<\/li><\/ol>",
    linkTypeInternalLabel: "Laman laman web ini",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Masukkan URI yang",
    linkTypeInternalNewWindowHeader: "Tetingkap baru",
    linkTypeInternalNewWindowLabel: "Semak kotak ini mempunyai link yang dibuka di dalam tetingkap\/tab browser baru.",
    listOrderedTitle: "Senarai disusun",
    listUnorderedTitle: "Senarai",
    logoTitle: "Ketahui lebih lanjut mengenai haiwan liar WYSIWYG Editor",
    navigateAway: "\nTidak ada yang disimpan perubahan pada Laman ini. \nJika anda meninggalkan halaman ini anda akan kehilangan perubahan anda tidak disimpan",
    pasteDialogCancelButton: "Batal",
    pasteDialogFormattedCleaned: "Diformat &amp; dibersihkan",
    pasteDialogFormattedUnclean: "Diformat kotor",
    pasteDialogOKButton: "Masukkan",
    pasteDialogPlain: "Teks biasa",
    pasteDialogSource: "Kod sumber",
    pasteDialogTitle: "Tampal",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Gagal mendapatkan semula semakan",
    revisionsApplyButtonDialogCancelButton: "Batal",
    revisionsApplyButtonDialogOKButton: "Gulung balik",
    revisionsApplyButtonDialogTitle: "Gulung balik pengesahan",
    revisionsApplyButtonTitle: "Gulung balik",
    revisionsApplyDialogContent: "Ini akan menggantikan kandungan semasa dengan semakan terpilih.<br>Kandungan semasa akan ditambah sebagai semakan, dan akan kelihatan dalam senarai semakan bagi blok ini.",
    revisionsButtonCurrent: "Semasa",
    revisionsButtonViewDiffText: "Perbezaan",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Batal",
    revisionsDialogTitle: "Semakan kandungan paparan",
    revisionsDiffButtonDialogCancelButton: "Tutup",
    revisionsDiffButtonDialogTitle: "Perbezaan pandangan",
    revisionsDiffButtonTitle: "Perbezaan pandangan",
    revisionsLoading: "Memuatkan semakan...",
    revisionsNone: "Tiada semakan bagi elemen ini",
    revisionsPreviewButtonTitle: "Pratonton",
    revisionsText: "Semakan",
    revisionsTextEmpty: "Tiada pindaan",
    revisionsTitle: "",
    rfmClose: "Tutup",
    rfmContinue: "Terus",
    rfmDelete: "Menghapuskan",
    rfmDownload: "Muat turun",
    rfmFileActions: "Tindakan-tindakan",
    rfmFileModificationTime: "Kali",
    rfmFileName: "Nama",
    rfmFileSize: "Saiz",
    rfmFileType: "Jenis",
    rfmFilteredTotal: "Yang menunjukkan {{start}} untuk {{end}} fail {{filteredTotal}}",
    rfmFirst: "Pertama",
    rfmHeadingDirectories: "Direktori",
    rfmHeadingSearch: "Cari",
    rfmHeadingTags: "Tag",
    rfmHeadingUpload: "Muat naik",
    rfmInsert: "Masukkan",
    rfmLast: "Terakhir",
    rfmSearch: "Pergi",
    rfmTotal: ", ditapis daripada {{total}}",
    rfmUpload: "Muat naik",
    rfmUploadBrowse: "Semak seimbas",
    rfmUploadDrop: "Drop fail-fail di sini",
    rfmUploadFileRemove: "Alih Keluar",
    rfmView: "Pandangan",
    saveJsonFail: "Gagal untuk menyelamatkan block(s) kandungan {{failed}}",
    saveJsonSaved: "Berjaya disimpan block(s) kandungan {{saved}}.",
    saveNotConfigured: "Simpan tidak dikonfigurasi, atau yang Kurang Upaya.",
    saveRestFail: "Gagal untuk menyelamatkan block(s) kandungan {{failed}}.",
    saveRestPartial: "Disimpan {{saved}} daripada blok kandungan {{failed}}.",
    saveRestSaved: "Berjaya disimpan block(s) kandungan {{saved}}.",
    saveTitle: "Menyimpan kandungan",
    snippetMenuTitle: "Coretan",
    specialCharactersDialogOKButton: "ok",
    specialCharactersDialogTitle: "Masukkan aksara khas",
    specialCharactersHelp: "Klik aksara khas untuk menambahkannya. Klik \"OK\" apabila dilakukan untuk menutup dialog ini",
    specialCharactersTitle: "Masukkan aksara khas",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} aksara melebihi had",
    statisticsButtonCharacterRemaining: "watak-watak {{charactersRemaining}} yang tinggal",
    statisticsButtonCharacters: "watak-watak {{characters}}",
    statisticsDialogCharactersOverLimit: "{{characters}} aksara, {{charactersRemaining}} melebihi had yang disyorkan",
    statisticsDialogCharactersRemaining: "aksara {{characters}}, {{charactersRemaining}} baki",
    statisticsDialogNotTruncated: "Kandungan tidak boleh dipendekkan",
    statisticsDialogOKButton: "ok",
    statisticsDialogSentence: "hukuman {{sentences}}",
    statisticsDialogSentences: "ayat {{sentences}}",
    statisticsDialogTitle: "Statistik kandungan",
    statisticsDialogTruncated: "Kandungan yang mengandungi lebih daripada watak-watak {{limit}} dan mungkin dipendekkan",
    statisticsDialogWord: "perkataan {{words}}",
    statisticsDialogWords: "kata-kata {{words}}",
    statisticsTitle: "Klik untuk melihat statistik",
    tableCreateTitle: "Mencipta jadual",
    tableDeleteColumnTitle: "Hapuskan kolum Jadual",
    tableDeleteRowTitle: "Menghapuskan jadual row",
    tableInsertColumnTitle: "Masukkan Jadual Ruang",
    tableInsertRowTitle: "Masukkan Jadual row",
    tableMergeCellsTitle: "Menggabungkan sel-sel Jadual",
    tableSplitCellsTitle: "Sel-sel Jadual Split",
    tagMenuTagAddress: "Alamat",
    tagMenuTagDiv: "Bhg.",
    tagMenuTagH1: "Tajuk 1",
    tagMenuTagH2: "Tajuk 2",
    tagMenuTagH3: "Tajuk 3",
    tagMenuTagH4: "Tajuk 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Perenggan",
    tagMenuTagPre: "Terlebih dahulu diformat",
    tagMenuTitle: "Perubahan unsur gaya",
    tagTreeElementLink: "Pilih elemen {{element}}",
    tagTreeElementTitle: "Klik untuk memilih kandungan elemen \"{{element}}\"",
    tagTreeRoot: "akar",
    tagTreeRootLink: "Pilih semua kandungan yang boleh diedit",
    tagTreeRootTitle: "Klik untuk memilih semua kandungan yang boleh diedit",
    textBlockQuoteTitle: "Quote blok",
    textBoldTitle: "Tebal",
    textItalicTitle: "Huruf",
    textSizeDecreaseTitle: "Kurangkan saiz teks",
    textSizeIncreaseTitle: "Besarkan saiz teks",
    textStrikeTitle: "Menyerang melalui",
    textSubTitle: "Skrip sub",
    textSuperTitle: "Script Super",
    textUnderlineTitle: "Gariskan",
    unsavedEditWarningText: "Tidak ada yang disimpan perubahan pada Laman ini",
    viewSourceDialogCancelButton: "Tutup",
    viewSourceDialogOKButton: "Menggunakan kod sumber",
    viewSourceDialogTitle: "Kod kandungan sumber",
    viewSourceTitle: "Pemandangan\/edit kod sumber"
});