/**
 * @fileOverview Hmong Daw strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('mww', 'Hmoob Daw', {
    alignCenterTitle: "Dlhos ntawv chaw",
    alignJustifyTitle: "Dlhos ntawv nyeem hais kom ncaj ncees",
    alignLeftTitle: "Dlhos ntawv nyeem laug",
    alignRightTitle: "Dlhos tau phau ntawv txoj cai",
    cancelDialogCancelButton: "Tseem Editing",
    cancelDialogContent: "Koj puas paub hais tias koj xav rho editing? Txhua yam kev hloov yuav tsum poob lawm!",
    cancelDialogOKButton: "Ncua tseg Editing",
    cancelDialogTitle: "Ncua tseg Editing",
    cancelTitle: "Ncua tseg editing",
    classMenuTitle: "Style picker",
    clearFormattingTitle: "Luaj formatting",
    clickButtonToEditText: "Kho kom raug",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Tsis siv neeg",
    colorMenuBasicBlack: "Dub nciab",
    colorMenuBasicBlue: "Xia",
    colorMenuBasicGreen: "Ntsuab",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Txiv kab ntxwv",
    colorMenuBasicPurple: "Ntshav",
    colorMenuBasicRed: "Liab",
    colorMenuBasicTitle: "Hloov cov phau ntawv muaj xim",
    colorMenuBasicWhite: "Dawb",
    dockToElementTitle: "Ntsaws cov kab nrib\/undock editor yuav caij",
    dockToScreenTitle: "Ntsaws cov kab nrib\/undock editor yuav npo",
    embedDialogCancelButton: "Ncua tseg",
    embedDialogOKButton: "Embed kwv",
    embedDialogTabCode: "Embed Code",
    embedDialogTabCodeContent: "Paste koj qhov embed code hauv cov ntawv nyeem qhov nram qab no:",
    embedDialogTabPreview: "Saib ua ntej",
    embedDialogTabPreviewContent: "Tus saib ua ntej ntawm koj cov kwv embedded yog dlhau theem teev nram qab no:",
    embedDialogTitle: "Embed kwv",
    embedTitle: "Embed kwv",
    errorUINoName: "UI \"{{ui}}\" yog invalid (yuav tsum muaj ib lub npe khoom)",
    errorUINotObject: "UI \"{{ui}}\" yog invalid (yuav tsum tau ib lub nruas)",
    errorUIOverride: "UI \"{{name}}\" sau lawm twb tau npe, thiab yuav tsum overwritten",
    fileManagerDialogTitle: "Cov ntaub ntawv tus thawj tswj",
    fileManagerTitle: "Cov ntaub ntawv tus thawj tswj",
    floatLeftTitle: "Dlhos duab mus rau sab laug",
    floatNoneTitle: "Tshem cov duab dlhos",
    floatRightTitle: "Dlhos duab rau ntawm sab xis",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic tsis",
    fontFamilyMenuFontCourier: "Courier tshiab",
    fontFamilyMenuFontDefault: "Default Font",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Tej yam",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Lub sij hawm Roman tshiab",
    fontFamilyMenuTitle: "Xaiv cov koj font",
    guidesTitle: "Qhia tus ntawm cov caij",
    historyRedoTitle: "Redo",
    historyUndoTitle: "Undo",
    hrCreateTitle: "Ntxig txoj cai",
    imageResizeButtonDialogCancelButton: "Ncua tseg",
    imageResizeButtonDialogHeight: "Duab qhov siab",
    imageResizeButtonDialogHeightPlaceHolder: "Qhov siab",
    imageResizeButtonDialogOKButton: "Resize",
    imageResizeButtonDialogTitle: "Resize duab",
    imageResizeButtonDialogWidth: "Duab dav",
    imageResizeButtonDialogWidthPlaceHolder: "Dav",
    imageResizeButtonText: "Resize duab",
    insertFileDialogCancelButton: "Ncua tseg",
    insertFileDialogOKButton: "Ntxig tej ntaub ntawv",
    insertFileNameLabel: "Cov ntaub ntawv npe",
    insertFileNamePlaceHolder: "Tej ntaub ntawv lub npe...",
    insertFileTitle: "Ntxig tej ntaub ntawv",
    insertFileURLLabel: "Cov ntaub ntawv URL",
    insertFileURLPlaceHolder: "URL tej ntaub ntawv...",
    languageMenuTitle: "Hloov cov lus",
    linkCreateDialogCancelButton: "Ncua tseg",
    linkCreateDialogMenuHeader: "Xaiv ib qhov txuas yam",
    linkCreateDialogOKButton: "Ntxig Link",
    linkCreateDialogTitle: "Ntxig Link",
    linkCreateTitle: "Ntxig Link",
    linkRemoveTitle: "Tshem cov Link",
    linkTypeDocumentHeader: "Txuas mus rau ib daim ntawv los yog lwm yam ntaub ntawv",
    linkTypeDocumentInfo: "<h2>Tsis paub hais tias yuav muab tso rau hauv lub npov saum toj no li cas?<\/h2><ol>    <li>Xyuas cov ntaub ntawv twb tau uploaded rau koj lub website.<\/li>    <li>Qhib uploaded ntawv nyob rau hauv koj tus browser.<\/li>    <li>Luam cov ntaub ntawv URL ntawm koj tus browser chaw bar thiab paste rau hauv lub npov saum toj no.<\/li><\/ol>",
    linkTypeDocumentLabel: "Daim ntawv los yog lwm yam ntaub ntawv",
    linkTypeDocumentLocationLabel: "Qhov chaw nyob:",
    linkTypeDocumentLocationPlaceHolder: "Sau ib qhov URL",
    linkTypeDocumentNewWindowHeader: "Qhov rai uas tshiab",
    linkTypeDocumentNewWindowLabel: "Khij lub npov no muaj cov ntaub ntawv qhib rau ib tug tshiab browser qhov rai\/tab.",
    linkTypeEmailHeader: "Txuas mus rau tus email chaw nyob",
    linkTypeEmailLabel: "Email chaw nyob",
    linkTypeEmailSubjectLabel: "Kawm (optional):",
    linkTypeEmailSubjectPlaceHolder: "Sau ntawv",
    linkTypeEmailToLabel: "Email:",
    linkTypeEmailToPlaceHolder: "Sau email chaw nyob",
    linkTypeExternalHeader: "Txuas mus rau ib sab ntawm lwm lub website",
    linkTypeExternalInfo: "<h2>Tsis paub hais tias yuav muab tso rau hauv lub npov saum toj no li cas?<\/h2><ol>    <li>Nrhiav cov nplooj hauv web uas koj xav tau kev txuas mus rau.<\/li>    <li>Luam cov qhov Web site nyob ntawm koj tus browser chaw bar thiab paste rau hauv lub npov saum toj no.<\/li><\/ol>",
    linkTypeExternalLabel: "Nplooj ntawv nyob rau lwm lub website",
    linkTypeExternalLocationLabel: "Qhov chaw nyob:",
    linkTypeExternalLocationPlaceHolder: "Sau ib qhov URL",
    linkTypeExternalNewWindowHeader: "Qhov rai uas tshiab",
    linkTypeExternalNewWindowLabel: "Khij lub npov no yuav muaj qhov txuas qhib rau ib tug tshiab browser qhov rai\/tab.",
    linkTypeInternalHeader: "Txuas mus rau ib sab rau cov website no",
    linkTypeInternalInfo: "<h2>Tsis paub hais tias yuav muab tso rau hauv lub npov saum toj no li cas?<\/h2><ol>    <li>Nrhiav cov nplooj ntawv rau qhov chaw txuas mus.<\/li>    <li>Luam cov qhov Web site nyob ntawm qhov chaw nyob koj tus browser bar, excluding \"{{domain}}\" thiab paste rau hauv lub npov saum toj no.<\/li><\/ol>",
    linkTypeInternalLabel: "Nplooj ntawv rau qhov website",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Ntaus ib PAS",
    linkTypeInternalNewWindowHeader: "Qhov rai uas tshiab",
    linkTypeInternalNewWindowLabel: "Khij lub npov no yuav muaj qhov txuas qhib rau ib tug tshiab browser qhov rai\/tab.",
    listOrderedTitle: "Sau kom",
    listUnorderedTitle: "Unordered sau",
    logoTitle: "Kawm ntxiv txog tus Raptor WYSIWYG Editor",
    loremIpsumTitle: "Ntxig dummy ntawv rau qhov kev tshuaj ntsuam txog",
    navigateAway: "\nMuaj cov unsaved kev hloov rau ntawm nplooj ntawv no. \nYog koj tus next ntawm nplooj ntawv no koj yuav poob koj cov kev hloov unsaved",
    pasteDialogCancelButton: "Ncua tseg",
    pasteDialogFormattedCleaned: "Formatted &amp; ntxuav",
    pasteDialogFormattedUnclean: "Formatted tsis huv",
    pasteDialogOKButton: "Ntxig",
    pasteDialogPlain: "Cov ntawv nyeem lub tiaj",
    pasteDialogSource: "Qhov chaws",
    pasteDialogTitle: "Muab tshuaj",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Tejyam uas retrieve koos",
    revisionsApplyButtonDialogCancelButton: "Ncua tseg",
    revisionsApplyButtonDialogOKButton: "Rollback",
    revisionsApplyButtonDialogText: "Rollback kabke",
    revisionsApplyButtonDialogTitle: "Rollback kabke",
    revisionsApplyButtonText: "Rollback",
    revisionsApplyButtonTitle: "Rollback",
    revisionsApplyDialogContent: "Qhov no yuav hloov cov lus qhia tam sim no nrog rau qhov kho nqi lus xaiv.<br>Cov lus qhia tam sim no yuav muab ntxiv ua tus kho nqi lus, thiab yuav pom nyob hauv daim ntawv muab rau lub nkev no.",
    revisionsButtonCurrent: "Tam sim no",
    revisionsButtonViewDiffText: "Txawv",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Tsim",
    revisionsDialogCancelButton: "Ncua tseg",
    revisionsDialogTitle: "Saib cov koos",
    revisionsDiffButtonDialogCancelButton: "Kaw",
    revisionsDiffButtonDialogTitle: "Saib txawv",
    revisionsDiffButtonText: "Saib txawv",
    revisionsDiffButtonTitle: "Saib txawv",
    revisionsLoading: "Chaw thau khoom koos...",
    revisionsNone: "Tsis muab rau cov caij no",
    revisionsPreviewButtonText: "Saib ua ntej",
    revisionsPreviewButtonTitle: "Saib ua ntej",
    revisionsText: "Koos",
    revisionsTextEmpty: "Tsis muaj koos",
    revisionsTitle: "",
    rfmClose: "Kaw",
    rfmContinue: "Ntxiv mus",
    rfmDelete: "Rho tawm",
    rfmDownload: "Download tau",
    rfmFileActions: "Tej yam ua tau",
    rfmFileModificationTime: "Hloov",
    rfmFileName: "Lub npe",
    rfmFileSize: "Loj",
    rfmFileType: "Hom",
    rfmFilteredTotal: "Qhia {{start}} {{end}} ntawm cov ntaub ntawv {{filteredTotal}}",
    rfmFirst: "Ua ntej",
    rfmHeadingDirectories: "Wage",
    rfmHeadingSearch: "Kev nrhiav",
    rfmHeadingTags: "Cim npe",
    rfmHeadingUpload: "Upload",
    rfmInsert: "Ntxig",
    rfmLast: "Kav",
    rfmSearch: "Mus",
    rfmTagDocument: "Daim ntawv",
    rfmTagImage: "Duab",
    rfmTotal: ", filtered ntawm {{total}}",
    rfmUpload: "Upload",
    rfmUploadBrowse: "Xauj",
    rfmUploadDrop: "Xa cov ntaub ntawv ntawm no",
    rfmUploadFileRemove: "Tshem tawm",
    rfmUploadOr: "los sis",
    rfmView: "Saib",
    saveJsonFail: "Tejyam uas muaj tseg tau qha block(s) {{failed}}",
    saveJsonSaved: "Block(s) {{saved}} qha rua ntse.",
    saveNotConfigured: "Txuag tau tsis tau configured, los yog neeg xiam.",
    saveRestFail: "Ua tsis tau tejyam txuag cov block(s) {{failed}}.",
    saveRestPartial: "Rua {{saved}} tawm plaws blocks {{failed}}.",
    saveRestSaved: "Block(s) {{saved}} qha rua ntse.",
    saveTitle: "Tseg tau cov ntsiab lus",
    snippetMenuTitle: "Snippets",
    specialCharactersArrows: "Sub",
    specialCharactersDialogOKButton: "ua li",
    specialCharactersDialogTitle: "Ntxig cim tshwj xeeb",
    specialCharactersGreekAlphabet: "Greek niam ntawv",
    specialCharactersHelp: "Nyem ib cim tshwj xeeb rau nws ntxiv. Nyem qhov \"Ywm\" thaum ua kaw no dialog",
    specialCharactersMathematics: "Kev kawm txog zauv",
    specialCharactersSymbols: "Cim",
    specialCharactersTitle: "Ntxig ib tus cim tshwj xeeb",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} cim pem txwv",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} cim seem",
    statisticsButtonCharacters: "{{characters}} cim",
    statisticsDialogCharactersOverLimit: "{{characters}} cim, {{charactersRemaining}} ntau tshaj qhov pom zoo",
    statisticsDialogCharactersRemaining: "{{characters}} cim, {{charactersRemaining}} seem",
    statisticsDialogNotTruncated: "Cov ntawv yuav tsis raug truncated",
    statisticsDialogOKButton: "ua li",
    statisticsDialogSentence: "{{sentences}} kab lus",
    statisticsDialogSentences: "{{sentences}} ua ke",
    statisticsDialogTitle: "Cov txheeb cais",
    statisticsDialogTruncated: "Ntsiab lus ntawv muaj ntau dua {{limit}} cim thiab tej zaum yuav tau truncated",
    statisticsDialogWord: "{{words}} lo lus",
    statisticsDialogWords: "{{words}} lo lus",
    statisticsTitle: "Nyem qhov mus saib txheeb cais",
    tableCreateTitle: "Ua tau ib cov lus",
    tableDeleteColumnTitle: "Rho tawm rooj sab",
    tableDeleteRowTitle: "Rho tawm rooj leej",
    tableInsertColumnTitle: "Ntxig rooj sab",
    tableInsertRowTitle: "Ntxig rooj leej",
    tableMergeCellsTitle: "Merge cov lus hlwb",
    tableSplitCellsTitle: "Phua lub rooj hlwb",
    tagMenuTagAddress: "Chaw nyob",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Nqe 1",
    tagMenuTagH2: "Nqe 2",
    tagMenuTagH3: "Nqe lus hais txog 3",
    tagMenuTagH4: "Nqe 4",
    tagMenuTagNA: "TSIS TXUAM NROG",
    tagMenuTagP: "Pawg lus",
    tagMenuTagPre: "Tos formatted",
    tagMenuTitle: "Hloov cov caij style",
    tagTreeElementLink: "Xaiv {{element}} caij",
    tagTreeElementTitle: "Nyem qhov mus xaiv tus txheem ntawm lub \"{{element}}\" caij",
    tagTreeRoot: "hauv paus",
    tagTreeRootLink: "Xaiv cov ntsiab lus editable",
    tagTreeRootTitle: "Nyem qhov xaiv tag nrho cov ntawv editable",
    textBlockQuoteTitle: "Thaiv tsocai",
    textBoldTitle: "Ntawv tuab",
    textItalicTitle: "Ntawv qaij",
    textSizeDecreaseTitle: "Txo tau raws li cov ntawv nyeem",
    textSizeIncreaseTitle: "Ua kom raws li cov ntawv nyeem",
    textStrikeTitle: "Thos mus txog",
    textSubTitle: "Cov tsab ntawv ncua",
    textSuperTitle: "Super-tsab ntawv",
    textUnderlineTitle: "Kos kab hauv qab",
    unsavedEditWarningText: "Muaj cov unsaved kev hloov rau ntawm nplooj ntawv no",
    viewSourceDialogCancelButton: "Kaw",
    viewSourceDialogOKButton: "Siv qhov chaws",
    viewSourceDialogTitle: "Cov khawb hauv qhov chaws",
    viewSourceTitle: "Saib\/edit qhov chaws"
});