/**
 * @fileOverview Dutch strings file.
 * @license http://www.raptor-editor.com/license
 *
 * @author Ruben Vincenten, rubenvincenten@gmail.com, https://github.com/rubenvincenten
 */
extendLocale('nl', 'Nederlands', {
    alignCenterTitle: "Centreren",
    alignJustifyTitle: "Uitlijnen aan beide kanten",
    alignLeftTitle: "Links uitlijnen",
    alignRightTitle: "Rechts Uitlijnen",
    cancelDialogCancelButton: "Sluiten",
    cancelDialogContent: "Weet u zeker dat u wilt stoppen met aanpassen? Alle aanpassingen zullen verloren gaan!",
    cancelDialogOKButton: false,
    cancelDialogTitle: "Cancel Editing",
    cancelTitle: "Cancel editing",
    classMenuTitle: "Stijl picker",
    clearFormattingTitle: "Verwijder opmaak",
    clickButtonToEditPluginButton: "Klik hier voor het beginnen met bewerken",
    clickButtonToEditText: "Bewerken",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatic",
    colorMenuBasicBlack: "Black",
    colorMenuBasicBlue: "Blue",
    colorMenuBasicGreen: "Green",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Purple",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Change text color",
    colorMenuBasicWhite: "White",
    dockToElementTitle: "Dock editor to element",
    dockToScreenTitle: "Dock editor to screen",
    embedDialogCancelButton: "Annuleren",
    embedDialogOKButton: "Object insluiten",
    embedDialogTabCode: "Embed-Code",
    embedDialogTabCodeContent: "Plak uw embed-code in het tekstgebied hieronder:",
    embedDialogTabPreview: "Voorbeeld",
    embedDialogTabPreviewContent: "Hieronder wordt een voorbeeld van uw ingesloten object weergegeven:",
    embedDialogTitle: "Object insluiten",
    embedTitle: "Object insluiten",
    errorPluginNoName: "Plugin \"{{plugin}}\" is invalid (must have a name property)",
    errorPluginNotObject: "Plugin \"{{plugin}}\" is invalid (must be an object)",
    errorPluginOverride: "Plugin \"{{name}}\" has already been registered, and will be overwritten",
    errorUINoName: "UI \"{{ui}}\" is invalid (must have a name property)",
    errorUINotObject: "UI \"{{ui}}\" is invalid (must be an object)",
    errorUIOverride: "UI \"{{name}}\" has already been registered, and will be overwritten",
    fileManagerDialogTitle: "Bestandsbeheer",
    fileManagerTitle: "Bestandsbeheer",
    floatLeftTitle: "Tekst omsluiten rechts van afbeelding",
    floatNoneTitle: "Remove image align",
    floatRightTitle: "Tekst omsluiten links van afbeelding",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic zonder",
    fontFamilyMenuFontCourier: "Courier nieuwe",
    fontFamilyMenuFontDefault: "Standaardlettertype",
    fontFamilyMenuFontGeorgia: "Georgië",
    fontFamilyMenuFontImpact: "Effect",
    fontFamilyMenuFontPalatino: "Palts",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Kies uw lettertype",
    guidesTitle: "Rooster Tonen (Onderwatermodus)",
    historyRedoTitle: "Redo",
    historyUndoTitle: "Undo",
    hrCreateTitle: "Horizontale lijn invoegen",
    imageResizeButtonDialogCancelButton: "Annuleren",
    imageResizeButtonDialogHeight: "Afbeeldingshoogte",
    imageResizeButtonDialogHeightPlaceHolder: "Hoogte",
    imageResizeButtonDialogOKButton: "Vergroten\/verkleinen",
    imageResizeButtonDialogTitle: "Resize beeld",
    imageResizeButtonDialogWidth: "Breedte van afbeelding",
    imageResizeButtonDialogWidthPlaceHolder: "Breedte",
    imageResizeButtonText: "Resize beeld",
    insertFileDialogCancelButton: "Annuleren",
    insertFileDialogOKButton: "Bestand invoegen",
    insertFileNameLabel: "Bestandsnaam",
    insertFileNamePlaceHolder: "De naam van het bestand...",
    insertFileTitle: "Bestand invoegen",
    insertFileURLLabel: "Bestand URL",
    insertFileURLPlaceHolder: "Bestand URL...",
    languageMenuTitle: "Taal wijzigen",
    linkCreateDialogCancelButton: "Annuleren",
    linkCreateDialogMenuHeader: "Kies een koppelingstype",
    linkCreateDialogOKButton: "Koppeling invoegen",
    linkCreateDialogTitle: "Koppeling invoegen",
    linkCreateTitle: "Koppeling invoegen",
    linkDialogCancelButton: "Annuleren",
    linkDialogMenuHeader: "Kies het type link:",
    linkDialogOKButton: "Link Invoegen",
    linkDialogTitle: "Link Invoegen",
    linkRemoveTitle: "Koppeling verwijderen",
    linkTypeDocumentHeader: "Een koppeling naar een document of een ander bestand",
    linkTypeDocumentInfo: "<h2>Niet zeker wat te zetten in het vak hierboven?<\/h2><ol>    <li>Zorgen dat het bestand is geüpload naar uw website.<\/li>    <li>Open het ge-uploade bestand in uw browser.<\/li>    <li>Kopieer het bestand URL van adresbalk van uw browser en plak deze in bovenstaand vak.<\/li><\/ol>",
    linkTypeDocumentLabel: "Document of een ander bestand",
    linkTypeDocumentLocationLabel: "Locatie:",
    linkTypeDocumentLocationPlaceHolder: "Voer een URL",
    linkTypeDocumentNewWindowHeader: "Nieuw venster",
    linkTypeDocumentNewWindowLabel: "Schakel dit selectievakje in als u wilt dat het bestand opent in een nieuw browser venster\/een lusje.",
    linkTypeEmailHeader: "Link naar een emailadres",
    linkTypeEmailLabel: "E-mail adres",
    linkTypeEmailSubjectLabel: "Onderwerp (optioneel):",
    linkTypeEmailSubjectPlaceHolder: "Voeg het onderwerp in",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Voeg het e-mail adres in",
    linkTypeExternalHeader: "Link to a page on another website",
    linkTypeExternalInfo: "<h2>Onzeker over wat er in het veld moet staan hierboven?<\/h2><ol>    <li>Vind de pagina op het internet waar u naartoe wilt linken.<\/li>    <li>Kopieër het internetadres uit de adresbalk van uw browser en plak het in het veld hierboven.<\/li><\/ol>",
    linkTypeExternalLabel: "Page on another website",
    linkTypeExternalLocationLabel: "Locatie",
    linkTypeExternalLocationPlaceHolder: "Voer een URL",
    linkTypeExternalNewWindowHeader: "Nieuw venster",
    linkTypeExternalNewWindowLabel: "Vink dit aan om de link te laten opnenen in een nieuw browser venster.",
    linkTypeInternalHeader: "Link to a page on this website",
    linkTypeInternalInfo: "<h2>Onzeker over wat er in het veld moet staan hierboven?<\/h2><ol>    <li>Vind de pagina op het internet waar u naartoe wilt linken.<\/li>    <li>Copy the web address from your browser's address bar, excluding \"{{domain}}\" and paste it into the box above.<\/li><\/ol>",
    linkTypeInternalLabel: "Page on this website",
    linkTypeInternalLocationLabel: "Locatie",
    linkTypeInternalLocationPlaceHolder: "Voer een URI",
    linkTypeInternalNewWindowHeader: "Nieuw venster",
    linkTypeInternalNewWindowLabel: "Vink dit aan om de link te laten opnenen in een nieuw browser venster.",
    listOrderedTitle: "Genummerde lijst",
    listUnorderedTitle: "Lijst Van Opsommingstekens",
    logoTitle: "Meer leren over Rapor WYSIWYG Editor",
    navigateAway: "\nEr zijn opgeslagen wijzigingen op deze pagina. \nAls u deze pagina verlaat en verder navigeert verliest u uw niet-opgeslagen wijzigingen",
    pasteDialogCancelButton: "Annuleren",
    pasteDialogFormattedCleaned: "Opgemaakt &amp; gereinigd",
    pasteDialogFormattedUnclean: "Opgemaakt onrein",
    pasteDialogOKButton: "Invoegen",
    pasteDialogPlain: "Tekst zonder opmaak",
    pasteDialogSource: "Broncode",
    pasteDialogTitle: "Plakken",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Fout bij ophalen van revisies",
    revisionsApplyButtonDialogCancelButton: "Annuleren",
    revisionsApplyButtonDialogOKButton: "Terugdraaien",
    revisionsApplyButtonDialogTitle: "Terugdraaien bevestiging",
    revisionsApplyButtonTitle: "Terugdraaien",
    revisionsApplyDialogContent: "Dit zal de huidige inhoud vervangen door de geselecteerde revisie.<br>De huidige inhoud zal worden toegevoegd als een herziening, en zullen zichtbaar zijn in de lijst wijzigingen voor dit blok.",
    revisionsButtonCurrent: "Huidige",
    revisionsButtonViewDiffText: "Verschillen",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Annuleren",
    revisionsDialogTitle: "Weergave inhoud revisies",
    revisionsDiffButtonDialogCancelButton: "Sluiten",
    revisionsDiffButtonDialogTitle: "Weergave verschillen",
    revisionsDiffButtonTitle: "Weergave verschillen",
    revisionsLoading: "Herzieningen bezig met laden...",
    revisionsNone: "Geen revisies van dit element",
    revisionsPreviewButtonTitle: "Voorbeeld",
    revisionsText: "Revisies",
    revisionsTextEmpty: "Geen revisies",
    revisionsTitle: "",
    rfmClose: "Sluiten",
    rfmContinue: "Blijven",
    rfmDelete: "Verwijderen",
    rfmDownload: "Downloaden",
    rfmFileActions: "Acties",
    rfmFileModificationTime: "Gewijzigd",
    rfmFileName: "Naam",
    rfmFileSize: "Grootte",
    rfmFileType: "Type",
    rfmFilteredTotal: "Weergegeven: {{start}} {{end}} {{filteredTotal}} bestanden",
    rfmFirst: "Eerste",
    rfmHeadingDirectories: "Mappen",
    rfmHeadingSearch: "Zoeken",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Upload",
    rfmInsert: "Invoegen",
    rfmLast: "Laatste",
    rfmSearch: "Gaan",
    rfmTotal: ", gefilterd van {{total}}",
    rfmUpload: "Upload",
    rfmUploadBrowse: "Bladeren",
    rfmUploadDrop: "Bestanden hier neerzetten",
    rfmUploadFileRemove: "Verwijderen",
    rfmView: "Weergave",
    saveJsonFail: "{{failed}} inhoud scripttags opslaan mislukt",
    saveJsonSaved: "{{saved}} inhoud scripttags opgeslagen.",
    saveNotConfigured: "Opslaan is niet geconfigureerd, of is uitgeschakeld.",
    saveRestFail: "{{failed}} inhoud scripttags opslaan mislukt.",
    saveRestPartial: "{{saved}} uit {{failed}} blokken inhoud opgeslagen.",
    saveRestSaved: "{{saved}} inhoud scripttags opgeslagen.",
    saveTitle: "Save content",
    snippetMenuTitle: "Fragmenten",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "Speciale tekens invoegen",
    specialCharactersHelp: "Klik op een speciaal teken toe te voegen. Klik op \"OK\" als je klaar bent om dit dialoogvenster te sluiten",
    specialCharactersTitle: "Een speciaal teken invoegen",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} karakters over het limiet",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} karakters over",
    statisticsButtonCharacters: "{{characters}} karakters",
    statisticsDialogCharactersOverLimit: "{{characters}} karakters, {{charactersRemaining}} over het aangeraden limiet",
    statisticsDialogCharactersRemaining: "{{characters}} karakters, {{charactersRemaining}} over",
    statisticsDialogNotTruncated: "Inhoud wordt niet ingekort",
    statisticsDialogOKButton: false,
    statisticsDialogSentence: "{{sentences}} sentence",
    statisticsDialogSentences: "{{sentences}} zinnen",
    statisticsDialogTitle: "Inhoud Statistieken",
    statisticsDialogTruncated: "Inhoud bevat meer dan {{limit}} tekens en kan worden ingekort",
    statisticsDialogWord: "{{words}} woord",
    statisticsDialogWords: "{{words}} woorden",
    statisticsTitle: "Click to view statistics",
    tableCreateTitle: "Create table",
    tableDeleteColumnTitle: "Delete table column",
    tableDeleteRowTitle: "Delete table row",
    tableInsertColumnTitle: "Insert table column",
    tableInsertRowTitle: "Insert table row",
    tableMergeCellsTitle: "Tabelcellen samenvoegen",
    tableSplitCellsTitle: "Tabelcellen splitsen",
    tagMenuTagAddress: "Adres",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Kopniveau&nbsp;1",
    tagMenuTagH2: "Kopniveau&nbsp;2",
    tagMenuTagH3: "Kopniveau&nbsp;23",
    tagMenuTagH4: "Rubriek 4",
    tagMenuTagNA: "n.v.t.",
    tagMenuTagP: "Alinea",
    tagMenuTagPre: "Voorgeformatteerd",
    tagMenuTitle: "Change element style",
    tagTreeElementLink: "Selecteer {{element}} element",
    tagTreeElementTitle: "Klik om de inhoud te selecteren van het \"{{element}}\" element",
    tagTreeRoot: false,
    tagTreeRootLink: "Alle aanpasbare inhoud selecteren",
    tagTreeRootTitle: "Klik om alle bewerkbare inhoud te selecteren",
    textBlockQuoteTitle: "Blokcitaat",
    textBoldTitle: "Vetgedrukt",
    textItalicTitle: "Schuingedrukt",
    textSizeDecreaseTitle: "Tekengrootte",
    textSizeIncreaseTitle: "Tekst vergroten",
    textStrikeTitle: "Doorstrepen",
    textSubTitle: "Subscript",
    textSuperTitle: "Superscript",
    textUnderlineTitle: "Onderstrepen",
    unsavedEditWarningText: "There are unsaved changes on this page",
    viewSourceDialogCancelButton: "Sluiten",
    viewSourceDialogOKButton: "Broncode toepassen code",
    viewSourceDialogTitle: "Content source code",
    viewSourceTitle: "Broncode Bekijken\/Bewerken code"
});
