/**
 * @fileOverview Norwegian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('no', 'Norsk', {
    alignCenterTitle: "Midtstill teksten",
    alignJustifyTitle: "Justere tekst rettferdiggjøre",
    alignLeftTitle: "Juster tekst til venstre",
    alignRightTitle: "Juster tekst til høyre",
    cancelDialogCancelButton: "Fortsett redigering",
    cancelDialogContent: "Er du sikker på at du vil avbryte redigeringen? Alle endringer vil gå tapt!",
    cancelDialogOKButton: "Avbryte redigeringen",
    cancelDialogTitle: "Avbryte redigeringen",
    cancelTitle: "Avbryte redigeringen",
    classMenuTitle: "Valg av stil",
    clearFormattingTitle: "Fjern formatering",
    clickButtonToEditText: "Rediger",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatisk",
    colorMenuBasicBlack: "Svart",
    colorMenuBasicBlue: "Blå",
    colorMenuBasicGreen: "Grønn",
    colorMenuBasicGrey: "Grå",
    colorMenuBasicOrange: "Oransje",
    colorMenuBasicPurple: "Lilla",
    colorMenuBasicRed: "Rød",
    colorMenuBasicTitle: "Endre tekstfarge",
    colorMenuBasicWhite: "Hvit",
    dockToElementTitle: "Merke\/oppheve forankringen redaktør element",
    dockToScreenTitle: "Merke\/oppheve forankringen redaktør skjermen",
    embedDialogCancelButton: "Avbryt",
    embedDialogOKButton: "Bygge inn objekt",
    embedDialogTabCode: "Embed-koden",
    embedDialogTabCodeContent: "Lim inn embed koden i tekstområdet under:",
    embedDialogTabPreview: "Forhåndsvisning",
    embedDialogTabPreviewContent: "En forhåndsvisning av innebygde objektet vises nedenfor:",
    embedDialogTitle: "Bygge inn objekt",
    embedTitle: "Bygge inn objekt",
    errorUINoName: "UI \"{{ui}}\" er ugyldig (må ha et name eiendom)",
    errorUINotObject: "UI \"{{ui}}\" er ugyldig (må være et objekt)",
    errorUIOverride: "UI \"{{name}}\" er allerede registrert og vil bli overskrevet",
    fileManagerDialogTitle: "Filbehandling",
    fileManagerTitle: "Filbehandling",
    floatLeftTitle: "Juster bildet til venstre",
    floatNoneTitle: "Fjerne bildet justeres",
    floatRightTitle: "Justere bildet til høyre",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Tegneserie uten",
    fontFamilyMenuFontCourier: "Courier nye",
    fontFamilyMenuFontDefault: "Standardskriften",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Innvirkning",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Ganger nye Roman",
    fontFamilyMenuTitle: "Velg skriften",
    guidesTitle: "Vis element guider",
    historyRedoTitle: "Gjør om",
    historyUndoTitle: "Angre",
    hrCreateTitle: "Sett inn vannrett linje",
    imageResizeButtonDialogCancelButton: "Avbryt",
    imageResizeButtonDialogHeight: "Bildehøyde",
    imageResizeButtonDialogHeightPlaceHolder: "Høyde",
    imageResizeButtonDialogOKButton: "Endre størrelse",
    imageResizeButtonDialogTitle: "Endre størrelsen på bildet",
    imageResizeButtonDialogWidth: "Bildebredde",
    imageResizeButtonDialogWidthPlaceHolder: "Bredde",
    imageResizeButtonText: "Endre størrelsen på bildet",
    insertFileDialogCancelButton: "Avbryt",
    insertFileDialogOKButton: "Sett inn fil",
    insertFileNameLabel: "Filnavn",
    insertFileNamePlaceHolder: "Filnavn...",
    insertFileTitle: "Sett inn fil",
    insertFileURLLabel: "Filen URL",
    insertFileURLPlaceHolder: "Filen URL...",
    languageMenuTitle: "Endre språk",
    linkCreateDialogCancelButton: "Avbryt",
    linkCreateDialogMenuHeader: "Velg koblingstype",
    linkCreateDialogOKButton: "Sett inn kobling",
    linkCreateDialogTitle: "Sett inn kobling",
    linkCreateTitle: "Sett inn kobling",
    linkRemoveTitle: "Fjerne kobling",
    linkTypeDocumentHeader: "Koble til et dokument eller en annen fil",
    linkTypeDocumentInfo: "<h2>Ikke sikker på hva du legger i boksen ovenfor?<\/h2><ol>    <li>Kontroller filen er lastet opp til ditt nettsted.<\/li>    <li>Åpne den opplastede filen i leseren.<\/li>    <li>Kopier filen URL fra adresselinjen i webleseren og lime den inn i boksen ovenfor.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokumenter eller andre filer",
    linkTypeDocumentLocationLabel: "Sted:",
    linkTypeDocumentLocationPlaceHolder: "Angi en URL",
    linkTypeDocumentNewWindowHeader: "Nytt vindu",
    linkTypeDocumentNewWindowLabel: "Merk av i denne boksen hvis filen åpnes i en ny kikker vindu\/fane.",
    linkTypeEmailHeader: "Koble til en e-postadresse",
    linkTypeEmailLabel: "E-postadresse",
    linkTypeEmailSubjectLabel: "Emne (valgfritt):",
    linkTypeEmailSubjectPlaceHolder: "Angi emnet",
    linkTypeEmailToLabel: "Epost:",
    linkTypeEmailToPlaceHolder: "Angi e-postadresse",
    linkTypeExternalHeader: "Kobling til en side på et annet nettsted",
    linkTypeExternalInfo: "<h2>Ikke sikker på hva du legger i boksen ovenfor?<\/h2><ol>    <li>Finn siden på nettet du vil koble til.<\/li>    <li>Kopier webadressen fra adresselinjen i webleseren og lim den inn i boksen ovenfor.<\/li><\/ol>",
    linkTypeExternalLabel: "Side på et annet nettsted",
    linkTypeExternalLocationLabel: "Sted:",
    linkTypeExternalLocationPlaceHolder: "Angi en URL",
    linkTypeExternalNewWindowHeader: "Nytt vindu",
    linkTypeExternalNewWindowLabel: "Merk av i denne boksen hvis du vil at linken åpnes i et nytt nettleservindu vindu\/tab.",
    linkTypeInternalHeader: "Kobling til en side på denne nettsiden",
    linkTypeInternalInfo: "<h2>Ikke sikker på hva du legger i boksen ovenfor?<\/h2><ol>    <li>Finn siden på denne områdekoblingen til.<\/li>    <li>Kopier webadressen fra webleserens adressefeltet, unntatt \"{{domain}}\" og lim den inn i boksen ovenfor.<\/li><\/ol>",
    linkTypeInternalLabel: "Siden på denne nettsiden",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Angi en URI",
    linkTypeInternalNewWindowHeader: "Nytt vindu",
    linkTypeInternalNewWindowLabel: "Merk av i denne boksen hvis du vil at linken åpnes i et nytt nettleservindu vindu\/tab.",
    listOrderedTitle: "Sortert liste",
    listUnorderedTitle: "Sorterte liste",
    logoTitle: "Lær mer om Raptor WYSIWYG-redigeringsprogrammet",
    loremIpsumTitle: "Sette inn dummy tekst for testing",
    navigateAway: "\nDet finnes ulagrede endringer på denne siden. \nHvis du navigerer bort fra denne siden vil du miste din ulagrede endringer",
    pasteDialogCancelButton: "Avbryt",
    pasteDialogFormattedCleaned: "Formatert og renset",
    pasteDialogFormattedUnclean: "Formatert uren",
    pasteDialogOKButton: "Sett inn",
    pasteDialogPlain: "Ren tekst",
    pasteDialogSource: "Kildekoden",
    pasteDialogTitle: "Lim inn",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Kan ikke hente revisjoner",
    revisionsApplyButtonDialogCancelButton: "Avbryt",
    revisionsApplyButtonDialogOKButton: "Tilbakeføring",
    revisionsApplyButtonDialogText: "Tilbakerulling bekreftelse",
    revisionsApplyButtonDialogTitle: "Tilbakerulling bekreftelse",
    revisionsApplyButtonText: "Tilbakeføring",
    revisionsApplyButtonTitle: "Tilbakeføring",
    revisionsApplyDialogContent: "Dette erstatter gjeldende innhold i den valgte revisjonen.<br>Gjeldende innhold vil bli lagt til som en revisjon, og vises i listen endringer for denne blokken.",
    revisionsButtonCurrent: "Gjeldende",
    revisionsButtonViewDiffText: "Forskjeller",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Opprettet",
    revisionsDialogCancelButton: "Avbryt",
    revisionsDialogTitle: "Vis innhold revisjoner",
    revisionsDiffButtonDialogCancelButton: "Lukk",
    revisionsDiffButtonDialogTitle: "Vis forskjeller",
    revisionsDiffButtonText: "Vis forskjeller",
    revisionsDiffButtonTitle: "Vis forskjeller",
    revisionsLoading: "Lasting endringer...",
    revisionsNone: "Ingen endringer i dette elementet",
    revisionsPreviewButtonText: "Forhåndsvisning",
    revisionsPreviewButtonTitle: "Forhåndsvisning",
    revisionsText: "Revisjoner",
    revisionsTextEmpty: "Ingen revisjoner",
    revisionsTitle: "",
    rfmClose: "Lukk",
    rfmContinue: "Fortsett",
    rfmDelete: "Slette",
    rfmDownload: "Last ned",
    rfmFileActions: "Handlinger",
    rfmFileModificationTime: "Endret",
    rfmFileName: "navn",
    rfmFileSize: "Størrelse",
    rfmFileType: "Type",
    rfmFilteredTotal: "Viser {{start}} {{end}} {{filteredTotal}} filer",
    rfmFirst: "Første",
    rfmHeadingDirectories: "Kataloger",
    rfmHeadingSearch: "Søk",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Laste opp",
    rfmInsert: "Sett inn",
    rfmLast: "Siste",
    rfmSearch: "Gå",
    rfmTagDocument: "Dokumentet",
    rfmTagImage: "Bilde",
    rfmTotal: ", filtrert fra {{total}}",
    rfmUpload: "Laste opp",
    rfmUploadBrowse: "Bla gjennom",
    rfmUploadDrop: "Slipp filer her",
    rfmUploadFileRemove: "Fjerne",
    rfmUploadOr: "eller",
    rfmView: "Vis",
    saveJsonFail: "Kan ikke lagre {{failed}} innhold block(s)",
    saveJsonSaved: "Lagret {{saved}} innhold block(s).",
    saveNotConfigured: "Lagre ikke er konfigurert eller er deaktivert.",
    saveRestFail: "Kan ikke lagre {{failed}} innhold block(s).",
    saveRestPartial: "Lagret {{saved}} av {{failed}} blokker.",
    saveRestSaved: "Lagret {{saved}} innhold block(s).",
    saveTitle: "Lagre innholdet",
    snippetMenuTitle: "Tekstutdrag",
    specialCharactersArrows: "Piler",
    specialCharactersDialogOKButton: "ok",
    specialCharactersDialogTitle: "Sette inn spesialtegn",
    specialCharactersGreekAlphabet: "Greske alfabetet",
    specialCharactersHelp: "Klikk Spesialtegn for å legge den. Klikk \"OK\" når du er ferdig for å lukke denne dialogboksen",
    specialCharactersMathematics: "Matematikk",
    specialCharactersSymbols: "Symboler",
    specialCharactersTitle: "Sette inn spesialtegn",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} tegn over grensen",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} tegn gjenstår",
    statisticsButtonCharacters: "{{characters}} tegn",
    statisticsDialogCharactersOverLimit: "{{characters}} tegn, {{charactersRemaining}} over anbefalte grensen",
    statisticsDialogCharactersRemaining: "{{characters}} tegn, {{charactersRemaining}} igjen",
    statisticsDialogNotTruncated: "Innhold vil ikke bli avkortet",
    statisticsDialogOKButton: "ok",
    statisticsDialogSentence: "{{sentences}} setning",
    statisticsDialogSentences: "{{sentences}} setninger",
    statisticsDialogTitle: "Innhold statistikk",
    statisticsDialogTruncated: "Innhold inneholder mer enn {{limit}} tegn og kan være forkortet",
    statisticsDialogWord: "{{words}} ord",
    statisticsDialogWords: "{{words}} ord",
    statisticsTitle: "Klikk for å vise statistikk",
    tableCreateTitle: "Opprett tabell",
    tableDeleteColumnTitle: "Slett kolonne",
    tableDeleteRowTitle: "Slette tabellrad",
    tableInsertColumnTitle: "Sett inn",
    tableInsertRowTitle: "Sett inn tabellrad",
    tableMergeCellsTitle: "Slå sammen tabellceller",
    tableSplitCellsTitle: "Dele tabellceller",
    tagMenuTagAddress: "Adresse",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Overskrift 1",
    tagMenuTagH2: "Overskrift 2",
    tagMenuTagH3: "Overskrift 3",
    tagMenuTagH4: "Overskrift 4",
    tagMenuTagNA: "I\/T",
    tagMenuTagP: "Avsnitt",
    tagMenuTagPre: "Pre-formatert",
    tagMenuTitle: "Endre element stil",
    tagTreeElementLink: "Velg {{element}} element",
    tagTreeElementTitle: "Merk innholdet i elementet \"{{element}}\"",
    tagTreeRoot: "rot",
    tagTreeRootLink: "Velg alle redigerbart innhold",
    tagTreeRootTitle: "Merk alle redigerbart innhold",
    textBlockQuoteTitle: "Sitatblokk",
    textBoldTitle: "Fet",
    textItalicTitle: "Kursiv",
    textSizeDecreaseTitle: "Reduser tekststørrelse",
    textSizeIncreaseTitle: "Øk tekststørrelse",
    textStrikeTitle: "Gjennomstreke",
    textSubTitle: "Senket skrift",
    textSuperTitle: "Super skript",
    textUnderlineTitle: "Understreking",
    unsavedEditWarningText: "Det finnes ulagrede endringer på denne siden",
    viewSourceDialogCancelButton: "Lukk",
    viewSourceDialogOKButton: "Bruke kildekoden",
    viewSourceDialogTitle: "Innhold kildekoden",
    viewSourceTitle: "Vise\/redigere kildekoden"
});