/**
 * @fileOverview Polish strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('pl', 'Polski', {
    alignCenterTitle: "Wyrównać tekst centrum",
    alignJustifyTitle: "Wyrównać tekst uzasadnienia",
    alignLeftTitle: "Wyrównaj tekst do lewej",
    alignRightTitle: "Wyrównaj tekst do prawej",
    cancelDialogCancelButton: "Kontynuuj edycję",
    cancelDialogContent: "Czy na pewno chcesz anulować edycję? Wszystkie zmiany zostaną utracone!",
    cancelDialogOKButton: "Anulowanie edycji",
    cancelDialogTitle: "Anulowanie edycji",
    cancelTitle: "Anulowanie edycji",
    classMenuTitle: "Selektor stylu",
    clearFormattingTitle: "Wyczyść formatowanie",
    clickButtonToEditText: "Edycja",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatyczne",
    colorMenuBasicBlack: "Czarny",
    colorMenuBasicBlue: "Niebieski",
    colorMenuBasicGreen: "Zielony",
    colorMenuBasicGrey: "Szary",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Fioletowy",
    colorMenuBasicRed: "Czerwony",
    colorMenuBasicTitle: "Zmienianie koloru tekstu",
    colorMenuBasicWhite: "Biały",
    dockToElementTitle: "Dok\/oddokować edytor do elementu",
    dockToScreenTitle: "Dok\/oddokować edytor do ekranu",
    embedDialogCancelButton: "Anuluj",
    embedDialogOKButton: "Osadzić obiekt",
    embedDialogTabCode: "Osadzić kod",
    embedDialogTabCodeContent: "Wklej kod HTML w polu tekstowym poniżej:",
    embedDialogTabPreview: "Podgląd",
    embedDialogTabPreviewContent: "Podgląd obiektu osadzonego jest wyświetlany poniżej:",
    embedDialogTitle: "Osadzić obiekt",
    embedTitle: "Osadzić obiekt",
    errorUINoName: "UI \"{{ui}}\" jest nieprawidłowy (musi mieć Właściwość name)",
    errorUINotObject: "UI \"{{ui}}\" jest nieprawidłowy (musi być obiektem)",
    errorUIOverride: "UI \"{{name}}\" została już zarejestrowana i zostaną zastąpione",
    fileManagerDialogTitle: "Menedżer plików",
    fileManagerTitle: "Menedżer plików",
    floatLeftTitle: "Wyrównanie obrazu w lewo",
    floatNoneTitle: "Usuń obraz wyrównać",
    floatRightTitle: "Wyrównanie obrazu w prawo",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komiks bez",
    fontFamilyMenuFontCourier: "Nowy Kurier",
    fontFamilyMenuFontDefault: "Domyślna czcionka",
    fontFamilyMenuFontGeorgia: "Gruzja",
    fontFamilyMenuFontImpact: "Wpływ",
    fontFamilyMenuFontPalatino: "Palatyn",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Wybierz czcionki",
    guidesTitle: "Pokaż element przewodników",
    historyRedoTitle: "Wykonaj ponownie",
    historyUndoTitle: "Cofnij",
    hrCreateTitle: "Wstaw pozioma",
    imageResizeButtonDialogCancelButton: "Anuluj",
    imageResizeButtonDialogHeight: "Wysokość obrazu",
    imageResizeButtonDialogHeightPlaceHolder: "Wysokość",
    imageResizeButtonDialogOKButton: "Zmiana rozmiaru",
    imageResizeButtonDialogTitle: "Rozmiar obrazu",
    imageResizeButtonDialogWidth: "Szerokość obrazu",
    imageResizeButtonDialogWidthPlaceHolder: "Szerokość",
    imageResizeButtonText: "Rozmiar obrazu",
    insertFileDialogCancelButton: "Anuluj",
    insertFileDialogOKButton: "Wstaw plik",
    insertFileNameLabel: "Nazwa pliku",
    insertFileNamePlaceHolder: "Nazwa pliku...",
    insertFileTitle: "Wstaw plik",
    insertFileURLLabel: "Adres URL pliku",
    insertFileURLPlaceHolder: "Adres URL pliku...",
    languageMenuTitle: "Zmień język",
    linkCreateDialogCancelButton: "Anuluj",
    linkCreateDialogMenuHeader: "Wybierz typ łącza",
    linkCreateDialogOKButton: "Wstaw Link",
    linkCreateDialogTitle: "Wstaw Link",
    linkCreateTitle: "Wstaw Link",
    linkRemoveTitle: "Usuń Link",
    linkTypeDocumentHeader: "Link do dokumentu lub inny plik",
    linkTypeDocumentInfo: "<h2>Nie wiesz, co należy umieścić w polu powyżej?<\/h2><ol>    <li>Upewnij się, że plik został przesłany do Twojej witryny.<\/li>    <li>Otwórz plik przesłane w przeglądarce.<\/li>    <li>Skopiuj adres URL pliku z paska adresu przeglądarki i wklej go w polu powyżej.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokument lub inny plik",
    linkTypeDocumentLocationLabel: "Lokalizacja:",
    linkTypeDocumentLocationPlaceHolder: "Wprowadź adres URL",
    linkTypeDocumentNewWindowHeader: "Nowe okno",
    linkTypeDocumentNewWindowLabel: "Zaznacz to pole aby plik jest otwarty w przeglądarce nowe okno\/kartę.",
    linkTypeEmailHeader: "Link do adresu e-mail",
    linkTypeEmailLabel: "Adres e-mail",
    linkTypeEmailSubjectLabel: "Temat (opcjonalne):",
    linkTypeEmailSubjectPlaceHolder: "Wpisz temat",
    linkTypeEmailToLabel: "Adres e-mail:",
    linkTypeEmailToPlaceHolder: "Wpisz adres e-mail",
    linkTypeExternalHeader: "Link do strony na innej stronie internetowej",
    linkTypeExternalInfo: "<h2>Nie wiesz, co należy umieścić w polu powyżej?<\/h2><ol>    <li>Znajdź stronę sieci web, którą chcesz się połączyć.<\/li>    <li>Skopiuj adres internetowy z paska adresu przeglądarki i wklej go w polu powyżej.<\/li><\/ol>",
    linkTypeExternalLabel: "Strony na innej stronie internetowej",
    linkTypeExternalLocationLabel: "Lokalizacja:",
    linkTypeExternalLocationPlaceHolder: "Wprowadź adres URL",
    linkTypeExternalNewWindowHeader: "Nowe okno",
    linkTypeExternalNewWindowLabel: "Zaznacz to pole, aby otworzyć nowe okno przeglądarki\/karcie link.",
    linkTypeInternalHeader: "Link do strony na tej stronie",
    linkTypeInternalInfo: "<h2>Nie wiesz, co należy umieścić w polu powyżej?<\/h2><ol>    <li>Znajdź strony na tej stronie link do.<\/li>    <li>Skopiuj adres www z przeglądarki adres baru, z wyjątkiem \"{{domain}}\" i wklej go w polu powyżej.<\/li><\/ol>",
    linkTypeInternalLabel: "Na stronie tej witryny",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Podaj identyfikator URI",
    linkTypeInternalNewWindowHeader: "Nowe okno",
    linkTypeInternalNewWindowLabel: "Zaznacz to pole, aby otworzyć nowe okno przeglądarki\/karcie link.",
    listOrderedTitle: "Uporządkowana lista",
    listUnorderedTitle: "Lista nieuporządkowana",
    logoTitle: "Dowiedz się więcej o edytorze WYSIWYG Raptor",
    navigateAway: "\nNa tej stronie są niezapisane zmiany. \nJeśli można przejść od tej strony stracisz niezapisane zmiany",
    pasteDialogCancelButton: "Anuluj",
    pasteDialogFormattedCleaned: "Sformatowany i oczyszczone",
    pasteDialogFormattedUnclean: "Sformatowany nieczyste",
    pasteDialogOKButton: "Wstaw",
    pasteDialogPlain: "Zwykły tekst",
    pasteDialogSource: "Kod źródłowy",
    pasteDialogTitle: "Wklej",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Nie można pobrać wersje",
    revisionsApplyButtonDialogCancelButton: "Anuluj",
    revisionsApplyButtonDialogOKButton: "Wycofywanie",
    revisionsApplyButtonDialogTitle: "Potwierdzenie wycofania",
    revisionsApplyButtonTitle: "Wycofywanie",
    revisionsApplyDialogContent: "Spowoduje to zastąpienie aktualnej treści z wybranej wersji.<br>Zawartość bieżącego zostaną dodane jako zmianę i będzie widoczna na liście poprawki dla tego bloku.",
    revisionsButtonCurrent: "Prąd",
    revisionsButtonViewDiffText: "Różnice",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Anuluj",
    revisionsDialogTitle: "Zobacz treść poprawki",
    revisionsDiffButtonDialogCancelButton: "Zamknij",
    revisionsDiffButtonDialogTitle: "Zobacz różnice",
    revisionsDiffButtonTitle: "Zobacz różnice",
    revisionsLoading: "Ładowanie poprawki...",
    revisionsNone: "Nie korekt dla tego elementu",
    revisionsPreviewButtonTitle: "Podgląd",
    revisionsText: "Poprawki",
    revisionsTextEmpty: "Nie zmian",
    revisionsTitle: "",
    rfmClose: "Zamknij",
    rfmContinue: "W dalszym ciągu",
    rfmDelete: "Usuń",
    rfmDownload: "Pobierz za darmo",
    rfmFileActions: "Działania",
    rfmFileModificationTime: "Zmodyfikowany",
    rfmFileName: "Nazwa",
    rfmFileSize: "Rozmiar",
    rfmFileType: "Typ",
    rfmFilteredTotal: "Wyświetlone {{start}} {{end}} {{filteredTotal}} plików",
    rfmFirst: "Pierwszy",
    rfmHeadingDirectories: "Katalogi",
    rfmHeadingSearch: "Szukaj",
    rfmHeadingTags: "Tagi",
    rfmHeadingUpload: "Przesłać",
    rfmInsert: "Wstaw",
    rfmLast: "Ostatnia",
    rfmSearch: "Iść",
    rfmTotal: ", filtrowane z {{total}}",
    rfmUpload: "Przesłać",
    rfmUploadBrowse: "Przeglądaj",
    rfmUploadDrop: "Usuwanie plików tutaj",
    rfmUploadFileRemove: "Usuń",
    rfmView: "Widok",
    saveJsonFail: "Nie udało się uratować {{failed}} zawartość bloku",
    saveJsonSaved: "Zapisane {{saved}} zawartość bloku.",
    saveNotConfigured: "Zapisz nie został skonfigurowany, lub jest wyłączona.",
    saveRestFail: "Nie udało się uratować {{failed}} zawartość bloku.",
    saveRestPartial: "Zapisane {{saved}} {{failed}} bloki zawartości.",
    saveRestSaved: "Zapisane {{saved}} zawartość bloku.",
    saveTitle: "Zapisywanie zawartości",
    snippetMenuTitle: "Fragmenty",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Wstawianie znaków specjalnych",
    specialCharactersHelp: "Kliknij przycisk dodać znak specjalny. Kliknij przycisk \"OK\" po zakończeniu zamknij to okno",
    specialCharactersTitle: "Wstawianie znaków specjalnych",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} znaków ponad limit",
    statisticsButtonCharacterRemaining: "pozostało znaków {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} znaków",
    statisticsDialogCharactersOverLimit: "znaki {{characters}}, {{charactersRemaining}} przekroczenie zalecanej",
    statisticsDialogCharactersRemaining: "{{characters}} pozostało, {{charactersRemaining}}",
    statisticsDialogNotTruncated: "Zawartości nie zostanie obcięty",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "zdanie {{sentences}}",
    statisticsDialogSentences: "{{sentences}} zdań",
    statisticsDialogTitle: "Statystyki zawartości",
    statisticsDialogTruncated: "Zawartość zawiera więcej niż {{limit}} znaków i może zostać obcięta",
    statisticsDialogWord: "słowo {{words}}",
    statisticsDialogWords: "{{words}} słów",
    statisticsTitle: "Kliknij, aby wyświetlić statystyki",
    tableCreateTitle: "Tworzenie tabeli",
    tableDeleteColumnTitle: "Usuń kolumnę tabeli",
    tableDeleteRowTitle: "Usuwanie wiersza tabeli",
    tableInsertColumnTitle: "Wstaw kolumnę tabeli",
    tableInsertRowTitle: "Wstaw wiersz tabeli",
    tableMergeCellsTitle: "Scalanie komórek tabeli",
    tableSplitCellsTitle: "Podział komórek tabeli",
    tagMenuTagAddress: "Adres",
    tagMenuTagDiv: "DIV",
    tagMenuTagH1: "Nagłówek 1",
    tagMenuTagH2: "Nagłówek 2",
    tagMenuTagH3: "Pozycja 3",
    tagMenuTagH4: "Pozycja 4",
    tagMenuTagNA: "N\/D!",
    tagMenuTagP: "Ust.",
    tagMenuTagPre: "Wstępnie sformatowany",
    tagMenuTitle: "Zmienić styl",
    tagTreeElementLink: "Wybierz opcję {{element}}",
    tagTreeElementTitle: "Kliknij, aby zaznaczyć zawartość elementu \"{{element}}\"",
    tagTreeRoot: "korzeń",
    tagTreeRootLink: "Wybierz wszystkie edytowalna treść",
    tagTreeRootTitle: "Kliknij, aby zaznaczyć całą zawartość edycji",
    textBlockQuoteTitle: "Cytat blokowy",
    textBoldTitle: "Pogrubienie",
    textItalicTitle: "Kursywa",
    textSizeDecreaseTitle: "Zmniejsz rozmiar tekstu",
    textSizeIncreaseTitle: "Zwiększyć rozmiar tekstu",
    textStrikeTitle: "Strajku poprzez",
    textSubTitle: "Sub-skrypt",
    textSuperTitle: "Super skrypt",
    textUnderlineTitle: "Podkreślenie",
    unsavedEditWarningText: "Na tej stronie są niezapisane zmiany",
    viewSourceDialogCancelButton: "Zamknij",
    viewSourceDialogOKButton: "Stosuje się kod źródłowy",
    viewSourceDialogTitle: "Kod źródłowy zawartości",
    viewSourceTitle: "Wyświetl\/Edytuj kod źródłowy"
});