/**
 * @fileOverview Portuguese strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('pt', 'Português', {
    alignCenterTitle: "Centralizar o texto",
    alignJustifyTitle: "Alinhar texto justificar",
    alignLeftTitle: "Alinhar texto à esquerda",
    alignRightTitle: "Alinhar a direita de texto",
    cancelDialogCancelButton: "Continuar edição",
    cancelDialogContent: "Tem certeza que deseja cancelar a edição? Todas as alterações serão perdidas!",
    cancelDialogOKButton: "Cancelar a edição",
    cancelDialogTitle: "Cancelar a edição",
    cancelTitle: "Cancelar a edição",
    classMenuTitle: "Seletor de estilo",
    clearFormattingTitle: "Limpar formatação",
    clickButtonToEditText: "Editar",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automático",
    colorMenuBasicBlack: "Preto",
    colorMenuBasicBlue: "Azul",
    colorMenuBasicGreen: "Verde",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Laranja",
    colorMenuBasicPurple: "Roxo",
    colorMenuBasicRed: "Vermelho",
    colorMenuBasicTitle: "Mudar a cor do texto",
    colorMenuBasicWhite: "Branco",
    dockToElementTitle: "Doca\/desencaixar o editor para o elemento",
    dockToScreenTitle: "Doca\/desencaixar editor de tela",
    embedDialogCancelButton: "Cancelar",
    embedDialogOKButton: "Inserir objeto",
    embedDialogTabCode: "Código embed",
    embedDialogTabCodeContent: "Cole o código embed para a área de texto abaixo:",
    embedDialogTabPreview: "Visualizar",
    embedDialogTabPreviewContent: "Uma prévia do seu objeto incorporado é exibida abaixo:",
    embedDialogTitle: "Inserir objeto",
    embedTitle: "Inserir objeto",
    errorUINoName: "UI \"{{ui}}\" é inválido (deve ter um propriedade de nome)",
    errorUINotObject: "UI \"{{ui}}\" é inválido (deve ser um objeto)",
    errorUIOverride: "UI \"{{name}}\" já foi registrado e será substituído",
    fileManagerDialogTitle: "Gerenciador de arquivos",
    fileManagerTitle: "Gerenciador de arquivos",
    floatLeftTitle: "Alinhe a imagem à esquerda",
    floatNoneTitle: "Remover imagem alinhar",
    floatRightTitle: "Alinhe a imagem à direita",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Quadrinhos sem",
    fontFamilyMenuFontCourier: "Courier novo",
    fontFamilyMenuFontDefault: "Fonte padrão",
    fontFamilyMenuFontGeorgia: "Geórgia",
    fontFamilyMenuFontImpact: "Impacto",
    fontFamilyMenuFontPalatino: "Palatino",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Escolha a sua fonte",
    guidesTitle: "Mostrar guias de elemento",
    historyRedoTitle: "Refazer",
    historyUndoTitle: "Desfazer",
    hrCreateTitle: "Inserir regra Horizontal",
    imageResizeButtonDialogCancelButton: "Cancelar",
    imageResizeButtonDialogHeight: "Altura da imagem",
    imageResizeButtonDialogHeightPlaceHolder: "Altura",
    imageResizeButtonDialogOKButton: "Redimensionar",
    imageResizeButtonDialogTitle: "Redimensionar imagem",
    imageResizeButtonDialogWidth: "Largura da imagem",
    imageResizeButtonDialogWidthPlaceHolder: "Largura",
    imageResizeButtonText: "Redimensionar imagem",
    insertFileDialogCancelButton: "Cancelar",
    insertFileDialogOKButton: "Inserir arquivo",
    insertFileNameLabel: "Nome do arquivo",
    insertFileNamePlaceHolder: "Nome do arquivo...",
    insertFileTitle: "Inserir arquivo",
    insertFileURLLabel: "URL do arquivo",
    insertFileURLPlaceHolder: "URL do arquivo...",
    languageMenuTitle: "Alterar Idioma",
    linkCreateDialogCancelButton: "Cancelar",
    linkCreateDialogMenuHeader: "Escolha um tipo de link",
    linkCreateDialogOKButton: "Inserir Link",
    linkCreateDialogTitle: "Inserir Link",
    linkCreateTitle: "Inserir Link",
    linkRemoveTitle: "Remover Link",
    linkTypeDocumentHeader: "Link para um documento ou outro arquivo.",
    linkTypeDocumentInfo: "<h2>Não sei o que colocar na caixa acima?<\/h2><ol>    <li>Garantir que o arquivo foi carregado para o seu site.<\/li>    <li>Abra o arquivo carregado em seu navegador.<\/li>    <li>Copie a URL do arquivo da barra de endereços do seu navegador e colá-lo na caixa acima.<\/li><\/ol>",
    linkTypeDocumentLabel: "Documento ou outro arquivo.",
    linkTypeDocumentLocationLabel: "Localização:",
    linkTypeDocumentLocationPlaceHolder: "Digite uma URL",
    linkTypeDocumentNewWindowHeader: "Nova janela",
    linkTypeDocumentNewWindowLabel: "Marque esta caixa para que o arquivo abrir em uma nova janela\/aba do navegador.",
    linkTypeEmailHeader: "Link para um endereço de e-mail",
    linkTypeEmailLabel: "Endereço de e-mail",
    linkTypeEmailSubjectLabel: "Assunto (opcional):",
    linkTypeEmailSubjectPlaceHolder: "Digite o assunto",
    linkTypeEmailToLabel: "Email:",
    linkTypeEmailToPlaceHolder: "Digite o endereço de e-mail",
    linkTypeExternalHeader: "Link para uma página em outro site",
    linkTypeExternalInfo: "<h2>Não sei o que colocar na caixa acima?<\/h2><ol>    <li>Encontre a página na web que você deseja se vincular.<\/li>    <li>Copie o endereço web da barra de endereços do seu navegador e colá-lo na caixa acima.<\/li><\/ol>",
    linkTypeExternalLabel: "Página em outro site",
    linkTypeExternalLocationLabel: "Localização:",
    linkTypeExternalLocationPlaceHolder: "Digite uma URL",
    linkTypeExternalNewWindowHeader: "Nova janela",
    linkTypeExternalNewWindowLabel: "Marque esta caixa para ter o link abrir em uma nova janela\/aba do navegador.",
    linkTypeInternalHeader: "Link para uma página neste Web site",
    linkTypeInternalInfo: "<h2>Não sei o que colocar na caixa acima?<\/h2><ol>    <li>Encontre a página neste link do site para.<\/li>    <li>Copiem o endereço web barra de endereço do seu navegador, excluindo \"{{domain}}\" e colá-lo na caixa acima.<\/li><\/ol>",
    linkTypeInternalLabel: "Página deste site",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Insira um URI",
    linkTypeInternalNewWindowHeader: "Nova janela",
    linkTypeInternalNewWindowLabel: "Marque esta caixa para ter o link abrir em uma nova janela\/aba do navegador.",
    listOrderedTitle: "Lista ordenada",
    listUnorderedTitle: "Lista não ordenada",
    logoTitle: "Saiba mais sobre o Editor WYSIWYG Raptor",
    loremIpsumTitle: "Inserir texto fictício para testes",
    navigateAway: "\nLá são alterações não salvas nesta página. \nSe você navegar longe nesta página, você perderá as alterações não salvas",
    pasteDialogCancelButton: "Cancelar",
    pasteDialogFormattedCleaned: "Formatado &amp; limpo",
    pasteDialogFormattedUnclean: "Formatado impuro",
    pasteDialogOKButton: "Inserir",
    pasteDialogPlain: "Texto sem formatação",
    pasteDialogSource: "Código-fonte",
    pasteDialogTitle: "Colar",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Falha ao recuperar as revisões",
    revisionsApplyButtonDialogCancelButton: "Cancelar",
    revisionsApplyButtonDialogOKButton: "Reversão",
    revisionsApplyButtonDialogText: "Confirmação de reversão",
    revisionsApplyButtonDialogTitle: "Confirmação de reversão",
    revisionsApplyButtonText: "Reversão",
    revisionsApplyButtonTitle: "Reversão",
    revisionsApplyDialogContent: "Isto irá substituir o conteúdo atual com a revisão selecionada.<br>O conteúdo será adicionado como uma revisão e será visível na lista de revisões para este bloco.",
    revisionsButtonCurrent: "Corrente",
    revisionsButtonViewDiffText: "Diferenças",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Criado",
    revisionsDialogCancelButton: "Cancelar",
    revisionsDialogTitle: "Exibir conteúdas revisões",
    revisionsDiffButtonDialogCancelButton: "Fechar",
    revisionsDiffButtonDialogTitle: "Diferenças de opinião",
    revisionsDiffButtonText: "Diferenças de opinião",
    revisionsDiffButtonTitle: "Diferenças de opinião",
    revisionsLoading: "Revisões de carregamento...",
    revisionsNone: "Não há revisões para este elemento",
    revisionsPreviewButtonText: "Visualizar",
    revisionsPreviewButtonTitle: "Visualizar",
    revisionsText: "Revisões",
    revisionsTextEmpty: "Não há revisões",
    revisionsTitle: "",
    rfmClose: "Fechar",
    rfmContinue: "Continuar",
    rfmDelete: "Excluir",
    rfmDownload: "Baixar",
    rfmFileActions: "Ações",
    rfmFileModificationTime: "Modificado",
    rfmFileName: "Nome",
    rfmFileSize: "Tamanho",
    rfmFileType: "Tipo",
    rfmFilteredTotal: "Mostrando {{start}} para {{end}} de {{filteredTotal}} arquivos",
    rfmFirst: "Primeiro",
    rfmHeadingDirectories: "Diretórios",
    rfmHeadingSearch: "Pesquisa",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Fazer upload",
    rfmInsert: "Inserir",
    rfmLast: "Última",
    rfmSearch: "Ir",
    rfmTagDocument: "Documento",
    rfmTagImage: "Imagem",
    rfmTotal: ", filtrado de {{total}}",
    rfmUpload: "Fazer upload",
    rfmUploadBrowse: "Browse",
    rfmUploadDrop: "Solte os arquivos aqui",
    rfmUploadFileRemove: "Remover",
    rfmUploadOr: "ou",
    rfmView: "Vista",
    saveJsonFail: "Falha ao salvar o bloco de conteúdo {{failed}} (s)",
    saveJsonSaved: "Salvo com sucesso {{saved}} blocos de conteúdo.",
    saveNotConfigured: "Salvar não foi configurado, ou está desabilitado.",
    saveRestFail: "Falha ao salvar o bloco de conteúdo {{failed}} (s).",
    saveRestPartial: "Salvou {{saved}} de {{failed}} blocos de conteúdo.",
    saveRestSaved: "Salvo com sucesso {{saved}} blocos de conteúdo.",
    saveTitle: "Salvar conteúdo",
    snippetMenuTitle: "Trechos",
    specialCharactersArrows: "Setas",
    specialCharactersDialogOKButton: "Razoável",
    specialCharactersDialogTitle: "Inserir caracteres especiais",
    specialCharactersGreekAlphabet: "Alfabeto grego",
    specialCharactersHelp: "Clique em um caractere especial para adicioná-lo. Clique em \"OK\" quando pronto para fechar esta caixa de diálogo",
    specialCharactersMathematics: "Matemática",
    specialCharactersSymbols: "Símbolos",
    specialCharactersTitle: "Inserir um caractere especial",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} caracteres sobre limite",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} caracteres restantes",
    statisticsButtonCharacters: "{{characters}} caracteres",
    statisticsDialogCharactersOverLimit: "caracteres {{characters}}, {{charactersRemaining}} acima do limite recomendado",
    statisticsDialogCharactersRemaining: "caracteres {{characters}}, {{charactersRemaining}} restantes",
    statisticsDialogNotTruncated: "Conteúdo não será truncado",
    statisticsDialogOKButton: "Razoável",
    statisticsDialogSentence: "frase de {{sentences}}",
    statisticsDialogSentences: "frases de {{sentences}}",
    statisticsDialogTitle: "Estatísticas de conteúdo",
    statisticsDialogTruncated: "Conteúdo contém mais de {{limit}} caracteres e pode ser truncado",
    statisticsDialogWord: "palavra de {{words}}",
    statisticsDialogWords: "palavras de {{words}}",
    statisticsTitle: "Clique para ver as estatísticas",
    tableCreateTitle: "Criar tabela",
    tableDeleteColumnTitle: "Excluir a coluna da tabela",
    tableDeleteRowTitle: "Excluir linhas da tabela",
    tableInsertColumnTitle: "Inserir coluna da tabela",
    tableInsertRowTitle: "Inserir uma linha de tabela",
    tableMergeCellsTitle: "Mesclar células de tabela",
    tableSplitCellsTitle: "Dividir células de tabela",
    tagMenuTagAddress: "Endereço",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Rubrica 1",
    tagMenuTagH2: "Rubrica 2",
    tagMenuTagH3: "Rubrica 3",
    tagMenuTagH4: "Rubrica 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "N.",
    tagMenuTagPre: "Pré-formatado",
    tagMenuTitle: "Mudar o estilo do elemento",
    tagTreeElementLink: "Selecione {{element}} elemento",
    tagTreeElementTitle: "Clique para selecionar o conteúdo do elemento \"{{element}}\"",
    tagTreeRoot: "raiz",
    tagTreeRootLink: "Selecione todo o conteúdo editável",
    tagTreeRootTitle: "Clique para selecionar todo o conteúdo editável",
    textBlockQuoteTitle: "Citação de bloco",
    textBoldTitle: "Bold (realce)",
    textItalicTitle: "Itálico",
    textSizeDecreaseTitle: "Diminuir tamanho do texto",
    textSizeIncreaseTitle: "Aumentar o tamanho do texto",
    textStrikeTitle: "Tachar",
    textSubTitle: "Script de sub",
    textSuperTitle: "Super script",
    textUnderlineTitle: "Sublinhado",
    unsavedEditWarningText: "Lá são alterações não salvas nesta página",
    viewSourceDialogCancelButton: "Fechar",
    viewSourceDialogOKButton: "Aplicar o código-fonte",
    viewSourceDialogTitle: "Código de fonte de conteúdo",
    viewSourceTitle: "Exibir\/editar código-fonte"
});