/**
 * @fileOverview Romanian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ro', 'Română', {
    alignCenterTitle: "Aliniaţi textul centru",
    alignJustifyTitle: "Aliniaţi textul justifica",
    alignLeftTitle: "Aliniere la stânga text",
    alignRightTitle: "Aliniere text la dreapta",
    cancelDialogCancelButton: "Continua editarea",
    cancelDialogContent: "Sigur revocați editarea? Toate modificările vor fi pierdute!",
    cancelDialogOKButton: "Revocați editarea",
    cancelDialogTitle: "Revocați editarea",
    cancelTitle: "Revocați editarea",
    classMenuTitle: "Selectorul de stil",
    clearFormattingTitle: "Clare de formatare",
    clickButtonToEditText: "Editare",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automată",
    colorMenuBasicBlack: "Negru",
    colorMenuBasicBlue: "Albastru",
    colorMenuBasicGreen: "Verde",
    colorMenuBasicGrey: "Gri",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Violet",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Schimba culoarea textului",
    colorMenuBasicWhite: "Alb",
    dockToElementTitle: "Doc\/detaşaţi editor element",
    dockToScreenTitle: "Doc\/detaşaţi editor pentru a ecran",
    embedDialogCancelButton: "Revocare",
    embedDialogOKButton: "Încorporaţi obiectul",
    embedDialogTabCode: "Codul embed",
    embedDialogTabCodeContent: "Lipiţi codul de încorporare în zona de text de mai jos:",
    embedDialogTabPreview: "Previzualizare",
    embedDialogTabPreviewContent: "O previzualizare a obiectului încorporat este afişat mai jos:",
    embedDialogTitle: "Încorporaţi obiectul",
    embedTitle: "Încorporaţi obiectul",
    errorUINoName: "UI \"{{ui}}\" este nevalid (trebuie să aveţi un nume de proprietate)",
    errorUINotObject: "UI \"{{ui}}\" este nevalid (trebuie să fie un obiect)",
    errorUIOverride: "UI \"{{name}}\" a fost deja înregistrat, și va fi suprascris",
    fileManagerDialogTitle: "File Manager",
    fileManagerTitle: "File Manager",
    floatLeftTitle: "Aliniați imaginea la stânga",
    floatNoneTitle: "Elimina imaginea aliniaţi",
    floatRightTitle: "Aliniați imaginea din dreapta",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Benzi desenate fără",
    fontFamilyMenuFontCourier: "Noi de curierat",
    fontFamilyMenuFontDefault: "Fontul implicit",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Impactul",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Alegeţi dumneavoastră font",
    guidesTitle: "Ghiduri de element Arată",
    historyRedoTitle: "Refacere",
    historyUndoTitle: "Anulare",
    hrCreateTitle: "Inserare regulă orizontale",
    imageResizeButtonDialogCancelButton: "Revocare",
    imageResizeButtonDialogHeight: "Inaltime imagine",
    imageResizeButtonDialogHeightPlaceHolder: "",
    imageResizeButtonDialogOKButton: "Redimensiona",
    imageResizeButtonDialogTitle: "Redimensiona imaginea",
    imageResizeButtonDialogWidth: "Latime imagine",
    imageResizeButtonDialogWidthPlaceHolder: "Lăţime",
    imageResizeButtonText: "Redimensiona imaginea",
    insertFileDialogCancelButton: "Revocare",
    insertFileDialogOKButton: "Inserare fișier",
    insertFileNameLabel: "Nume de fişier",
    insertFileNamePlaceHolder: "Numele de fișier...",
    insertFileTitle: "Inserare fișier",
    insertFileURLLabel: "Fişier URL",
    insertFileURLPlaceHolder: "URL dosar...",
    languageMenuTitle: "Schimba limba",
    linkCreateDialogCancelButton: "Revocare",
    linkCreateDialogMenuHeader: "Alege un tip de legătură",
    linkCreateDialogOKButton: "Introduceţi link-ul",
    linkCreateDialogTitle: "Introduceţi link-ul",
    linkCreateTitle: "Introduceţi link-ul",
    linkRemoveTitle: "Elimina link-ul",
    linkTypeDocumentHeader: "Link la un document sau alt fişier",
    linkTypeDocumentInfo: "<h2>Nu sunt sigur ce să puneţi în caseta de mai sus?<\/h2><ol>    <li>Asigura fişierul a fost încărcat la site-ul dvs.<\/li>    <li>Deschideţi fişierul încărcat în browser-ul dumneavoastră.<\/li>    <li>Copiaţi fişierul pe URL-ul din bara de adrese a browser-ul şi lipiţi-l în caseta de mai sus.<\/li><\/ol>",
    linkTypeDocumentLabel: "Document sau alt fişier",
    linkTypeDocumentLocationLabel: "Locaţie:",
    linkTypeDocumentLocationPlaceHolder: "Introduceţi o adresă URL",
    linkTypeDocumentNewWindowHeader: "Fereastră nouă",
    linkTypeDocumentNewWindowLabel: "Bifați această casetă pentru a avea dosar deschis într-o nouă fereastră de browser\/tab.",
    linkTypeEmailHeader: "Se leagă o adresa de e-mail",
    linkTypeEmailLabel: "Adresa de e-mail",
    linkTypeEmailSubjectLabel: "Subiect (optional):",
    linkTypeEmailSubjectPlaceHolder: "Introduceţi subiectul",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Introduceţi adresa de e-mail",
    linkTypeExternalHeader: "Link la o pagină de pe un alt site",
    linkTypeExternalInfo: "<h2>Nu sunt sigur ce să puneţi în caseta de mai sus?<\/h2><ol>    <li>Găsi pe pagina web pe care doriţi să se leagă.<\/li>    <li>Copiaţi adresa web din bara de adrese a browser-ul şi lipiţi-l în caseta de mai sus.<\/li><\/ol>",
    linkTypeExternalLabel: "Pagina de pe un alt site",
    linkTypeExternalLocationLabel: "Locaţie:",
    linkTypeExternalLocationPlaceHolder: "Introduceţi o adresă URL",
    linkTypeExternalNewWindowHeader: "Fereastră nouă",
    linkTypeExternalNewWindowLabel: "Bifați această casetă pentru a avea link-ul de deschidere înãuntru un nou maro fereastră\/tab.",
    linkTypeInternalHeader: "Link la o pagină de pe acest site",
    linkTypeInternalInfo: "<h2>Nu sunt sigur ce să puneţi în caseta de mai sus?<\/h2><ol>    <li>Găsi pagina de pe acest site de link-ul de la.<\/li>    <li>Copiaţi adresa web din browserul pe bara de adrese, cu excepția \"{{domain}}\" şi lipiţi-l în caseta de mai sus.<\/li><\/ol>",
    linkTypeInternalLabel: "Pagina de pe acest site",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Introduceţi un URI",
    linkTypeInternalNewWindowHeader: "Fereastră nouă",
    linkTypeInternalNewWindowLabel: "Bifați această casetă pentru a avea link-ul de deschidere înãuntru un nou maro fereastră\/tab.",
    listOrderedTitle: "Lista ordonata",
    listUnorderedTitle: "Listă neordonată",
    logoTitle: "Aflaţi mai multe despre Raptor WYSIWYG Editor",
    navigateAway: "\nSunt nesalvate modificări pe această pagină. \nDacă navigaţi la această pagină veți pierde modificările nesalvate",
    pasteDialogCancelButton: "Revocare",
    pasteDialogFormattedCleaned: "Formatat &amp; curăţate",
    pasteDialogFormattedUnclean: "Formatat necurate",
    pasteDialogOKButton: "Inserare",
    pasteDialogPlain: "Text simplu",
    pasteDialogSource: "Codul sursă",
    pasteDialogTitle: "Pastă",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "A reuşit să regăsească revizii",
    revisionsApplyButtonDialogCancelButton: "Revocare",
    revisionsApplyButtonDialogOKButton: "Derulare înapoi",
    revisionsApplyButtonDialogTitle: "Derulare înapoi confirmare",
    revisionsApplyButtonTitle: "Derulare înapoi",
    revisionsApplyDialogContent: "Acest lucru va înlocui conținutul curent cu revizuirea selectate.<br>Conținutul curent va fi adăugat ca o revizuire, şi vor fi vizibile în lista de revizii pentru acest bloc.",
    revisionsButtonCurrent: "Curent",
    revisionsButtonViewDiffText: "Diferenţele",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Revocare",
    revisionsDialogTitle: "Vezi conţinut revizii",
    revisionsDiffButtonDialogCancelButton: "Închide",
    revisionsDiffButtonDialogTitle: "Vezi diferentele",
    revisionsDiffButtonTitle: "Vezi diferentele",
    revisionsLoading: "Încărcare revizii...",
    revisionsNone: "Nu revizuiri pentru acest element",
    revisionsPreviewButtonTitle: "Previzualizare",
    revisionsText: "Revizii",
    revisionsTextEmpty: "Nu revizuiri",
    revisionsTitle: "",
    rfmClose: "Închide",
    rfmContinue: "Continua",
    rfmDelete: "Ştergeţi",
    rfmDownload: "Descarca",
    rfmFileActions: "Acţiunile",
    rfmFileModificationTime: "Modificat",
    rfmFileName: "nume",
    rfmFileSize: "Dimensiune",
    rfmFileType: "Tip",
    rfmFilteredTotal: "Prezentarea {{start}} la {{end}} {{filteredTotal}} fișiere",
    rfmFirst: "Prima",
    rfmHeadingDirectories: "Directoare",
    rfmHeadingSearch: "Căutare",
    rfmHeadingTags: "Tag-uri",
    rfmHeadingUpload: "Încărcaţi",
    rfmInsert: "Inserare",
    rfmLast: "Ultima",
    rfmSearch: "Du-te",
    rfmTotal: ", filtrat din {{total}}",
    rfmUpload: "Încărcaţi",
    rfmUploadBrowse: "Răsfoire",
    rfmUploadDrop: "Fixaţi fişierele aici",
    rfmUploadFileRemove: "Elimina",
    rfmView: "Vezi",
    saveJsonFail: "Nu a reuşit să salveze {{failed}} conţinut bloc (uri)",
    saveJsonSaved: "Salvat cu succes {{saved}} conţinut bloc (uri).",
    saveNotConfigured: "A salva nu a fost configurată, sau dezactivat.",
    saveRestFail: "Nu a reușit să salveze {{failed}} conţinut bloc (uri).",
    saveRestPartial: "Salvat {{saved}} din {{failed}} blocuri de conţinut.",
    saveRestSaved: "Salvat cu succes {{saved}} conţinut bloc (uri).",
    saveTitle: "Salvaţi conţinut",
    snippetMenuTitle: "Fragmentele",
    specialCharactersDialogOKButton: "ok",
    specialCharactersDialogTitle: "Inseraţi caractere speciale",
    specialCharactersHelp: "Faceţi clic pe un caracter special pentru a o adăuga. Faceţi clic pe \"OK\" Când aţi terminat pentru a închide acest dialog",
    specialCharactersTitle: "Inserarea unui caracter special",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} caractere peste limita",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} caractere rămase",
    statisticsButtonCharacters: "{{characters}} caractere",
    statisticsDialogCharactersOverLimit: "caractere {{characters}}, {{charactersRemaining}} peste limita recomandata",
    statisticsDialogCharactersRemaining: "caractere {{characters}}, {{charactersRemaining}} rămase",
    statisticsDialogNotTruncated: "Conţinut nu vor fi trunchiate",
    statisticsDialogOKButton: "ok",
    statisticsDialogSentence: "{{sentences}} teză",
    statisticsDialogSentences: "{{sentences}} propoziţii",
    statisticsDialogTitle: "Conţinut statistici",
    statisticsDialogTruncated: "Conţinutul conține mai mult de {{limit}} caractere şi pot fi trunchiate",
    statisticsDialogWord: "{{words}} de cuvinte",
    statisticsDialogWords: "{{words}} cuvinte",
    statisticsTitle: "Click pentru a vizualiza statistici",
    tableCreateTitle: "Creare tabel",
    tableDeleteColumnTitle: "Ștergeți tabelul coloană",
    tableDeleteRowTitle: "Ștergere rând de tabel",
    tableInsertColumnTitle: "Inserare coloană de tabel",
    tableInsertRowTitle: "Inserare rând de tabel",
    tableMergeCellsTitle: "Îmbinare celule tabel",
    tableSplitCellsTitle: "Scindare celule tabel",
    tagMenuTagAddress: "Adresa",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Rubrica 1",
    tagMenuTagH2: "Capitolul 2",
    tagMenuTagH3: "Rubrica 3",
    tagMenuTagH4: "Rubrica 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Alin",
    tagMenuTagPre: "Pre-formatat",
    tagMenuTitle: "Schimba stilul de element",
    tagTreeElementLink: "Selectaţi elementul {{element}}",
    tagTreeElementTitle: "Faceţi clic şi selectaţi conţinutul elementul \"{{element}}\"",
    tagTreeRoot: "rădăcină",
    tagTreeRootLink: "Selectaţi toate conţinut editabile",
    tagTreeRootTitle: "Faceţi clic pentru a selecta toate conţinut editabile",
    textBlockQuoteTitle: "Citat de bloc",
    textBoldTitle: "Bold",
    textItalicTitle: "Cursiv",
    textSizeDecreaseTitle: "Micșorare dimensiune text",
    textSizeIncreaseTitle: "Măriţi dimensiunea textului",
    textStrikeTitle: "Baraţi",
    textSubTitle: "Sub-script",
    textSuperTitle: "Super-script",
    textUnderlineTitle: "Subliniere",
    unsavedEditWarningText: "Acolo sunt nesalvate modificări pe această pagină",
    viewSourceDialogCancelButton: "Închide",
    viewSourceDialogOKButton: "Se aplică codul sursă",
    viewSourceDialogTitle: "Codul sursă de conținut",
    viewSourceTitle: "Vizualizare\/Editare codul sursă"
});