/**
 * @fileOverview Russian strings file.
 * @author Ivan Gromov, summer.is.gone@gmail.com
 */
extendLocale('ru', 'Russian', {
    alignCenterTitle: "По центру",
    alignJustifyTitle: "По ширине",
    alignLeftTitle: "По левому краю",
    alignRightTitle: "По правому краю",
    cancelDialogCancelButton: "Продолжить редактирование",
    cancelDialogContent: "Вы уверены, что хотите завершить редактирование? Все изменения будут утеряны!",
    cancelDialogOKButton: "Завершить редактирование",
    cancelDialogTitle: "Завершить редактирование",
    cancelTitle: "Завершить редактирование",
    classMenuTitle: "Выбор стиля",
    clearFormattingTitle: "Очистить форматирование",
    clickButtonToEditPluginButton: "Нажмите для начала редактирования",
    clickButtonToEditText: "Редактировать",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Автоматически",
    colorMenuBasicBlack: "Черный",
    colorMenuBasicBlue: "Синий",
    colorMenuBasicGreen: "Зеленый",
    colorMenuBasicGrey: "Серый",
    colorMenuBasicOrange: "Оранжевый",
    colorMenuBasicPurple: "Лиловый",
    colorMenuBasicRed: "Красный",
    colorMenuBasicTitle: "Изменить цевет текста",
    colorMenuBasicWhite: "Белый",
    dockToElementTitle: "Прикрепить редактор к элементу",
    dockToScreenTitle: "Прикрепить редактор к документу",
    embedDialogCancelButton: "Отмена",
    embedDialogOKButton: "Встраиваемый объект",
    embedDialogTabCode: "Встраиваемый код",
    embedDialogTabCodeContent: "Вставьте код в поле ниже:",
    embedDialogTabPreview: "Предпросмотр",
    embedDialogTabPreviewContent: "Предпросмотр встраиваемого объекта:",
    embedDialogTitle: "Встраиваемый объект",
    embedTitle: "Встраиваемый объект",
    errorPluginNoName: "Модуль \"{{plugin}}\" содержит ошибку (поле свойство обязательное)",
    errorPluginNotObject: "Модуль \"{{plugin}}\" содержит ошибку (предполагается наличие объекта)",
    errorPluginOverride: "Модуль \"{{name}}\" уже был зарегистрирован и будет перезаписан",
    errorUINoName: "Интерфейс \"{{ui}}\" содержит ошибку (поле свойство обязательное)",
    errorUINotObject: "Интерфейс \"{{ui}}\" содержит ошибку (предполагается наличие объекта)",
    errorUIOverride: "Интерфейс \"{{name}}\" уже был зарегистрирован и будет перезаписан",
    fileManagerDialogTitle: "Файловый менеджер",
    fileManagerTitle: "Файловый менеджер",
    floatLeftTitle: "Выровнять изображение по левому краю",
    floatNoneTitle: "Отменить выравнивание изображения",
    floatRightTitle: "Выровнять изображение по правому краю",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Комикс без",
    fontFamilyMenuFontCourier: "Новый Курьер",
    fontFamilyMenuFontDefault: "Шрифт по умолчанию",
    fontFamilyMenuFontGeorgia: "Грузия",
    fontFamilyMenuFontImpact: "Влияние",
    fontFamilyMenuFontPalatino: "Палатин",
    fontFamilyMenuFontTimes: "Раз новый роман",
    fontFamilyMenuTitle: "Выбрать свой шрифт",
    guidesTitle: "Показать направляющие",
    historyRedoTitle: "Повторить действие",
    historyUndoTitle: "Отменить действие",
    hrCreateTitle: "Вставить горизонтальную линию",
    imageResizeButtonDialogCancelButton: "Отмена",
    imageResizeButtonDialogHeight: "Высота изображения",
    imageResizeButtonDialogHeightPlaceHolder: "Высота",
    imageResizeButtonDialogOKButton: "Изменить размер",
    imageResizeButtonDialogTitle: "Изменить размер изображения",
    imageResizeButtonDialogWidth: "Ширина изображения",
    imageResizeButtonDialogWidthPlaceHolder: "Ширина",
    imageResizeButtonText: "Изменить размер изображения",
    insertFileDialogCancelButton: "Отмена",
    insertFileDialogOKButton: "Вставить файл",
    insertFileNameLabel: "Имя файла",
    insertFileNamePlaceHolder: "Имя файла...",
    insertFileTitle: "Вставить файл",
    insertFileURLLabel: "URL-адрес файла",
    insertFileURLPlaceHolder: "URL-адрес файла...",
    languageMenuDE: "Немецкий",
    languageMenuEN: "Английский",
    languageMenuES: "Испанский",
    languageMenuFR: "Французский",
    languageMenuNL: "Голландский",
    languageMenuSV: "Шведский",
    languageMenuTitle: "Изменить язык",
    languageMenuZHCN: "Упрощенный китайский",
    linkCreateDialogCancelButton: "Отмена",
    linkCreateDialogMenuHeader: "Выбарите тип ссылки",
    linkCreateDialogOKButton: "Вставить ссылку",
    linkCreateDialogTitle: "Вставить ссылку",
    linkCreateTitle: "Вставить ссылку",
    linkRemoveTitle: "Удалить ссылку",
    linkTypeDocumentHeader: "Ссылка на документ или другой файл",
    linkTypeDocumentInfo: "<h2>Не знаете что ввести в это поле?<\/h2><ol>    <li>Удостоверьтесь, что файл был загружен на ваш сайт.<\/li>    <li>Откройте файл в браузере.<\/li>    <li>Скопируйте адрес из строки браузера в поле выше.<\/li><\/ol>",
    linkTypeDocumentLabel: "Документ или другой файл",
    linkTypeDocumentLocationLabel: "Адрес:",
    linkTypeDocumentLocationPlaceHolder: "Введите URL",
    linkTypeDocumentNewWindowHeader: "В новом окне",
    linkTypeDocumentNewWindowLabel: "Поставьте флажок, чтобы страница открылась в новой вкладке.",
    linkTypeEmailHeader: "Ссылка на адрес эл. почты",
    linkTypeEmailLabel: "Адрес эл. почты",
    linkTypeEmailSubjectLabel: "Тема (необязательно):",
    linkTypeEmailSubjectPlaceHolder: "Введите тему",
    linkTypeEmailToLabel: "Почта:",
    linkTypeEmailToPlaceHolder: "Введите адрес эл. почты",
    linkTypeExternalHeader: "Ссылка на страницу другого сайта",
    linkTypeExternalInfo: "<h2>Не знаете что ввести в это поле?<\/h2><ol>    <li>Найдите страницу, на которую вы хотите сделать ссылку<\/li>    <li>Скопируйте адрес из строки браузера и вставьте в поле выше<\/li><\/ol>",
    linkTypeExternalLabel: "Страница на другом сайте",
    linkTypeExternalLocationLabel: "Адрес:",
    linkTypeExternalLocationPlaceHolder: "Введите URL",
    linkTypeExternalNewWindowHeader: "В новом окне",
    linkTypeExternalNewWindowLabel: "Поставьте флажок, чтобы страница открылась в новой вкладке.",
    linkTypeInternalHeader: "Ссылка на страницу на этом сайте",
    linkTypeInternalInfo: "<h2>Не знаете что ввести в это поле?<\/h2><ol>    <li>Выберите страницу на сайте, на которую хотите сделать ссылку.<\/li>    <li>Скопируйте адрес из строки браузера, исключив \"{{domain}}\" и вставьте его в поле выше.<\/li><\/ol>",
    linkTypeInternalLabel: "Страница на этом сайте",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Введите URL",
    linkTypeInternalNewWindowHeader: "В новом окне",
    linkTypeInternalNewWindowLabel: "Поставьте флажок, чтобы страница открылась в новой вкладке.",
    listOrderedTitle: "Нумерованый список",
    listUnorderedTitle: "Ненумерованый список",
    logoTitle: "Узнать больше о редакторе Raptor",
    navigateAway: "\nНа странице несохраненные изменения. \nЕсли вы покинете страницу, изменения будут утеряны",
    pasteDialogCancelButton: "Отмена",
    pasteDialogFormattedCleaned: "Отформатировано и очищено",
    pasteDialogFormattedUnclean: "Отформатировано без очистки",
    pasteDialogOKButton: "Вставить",
    pasteDialogPlain: "Простой текст",
    pasteDialogSource: "Код",
    pasteDialogTitle: "Вставить",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Не удалось получить изменения",
    revisionsApplyButtonDialogCancelButton: "Отмена",
    revisionsApplyButtonDialogOKButton: "Откат",
    revisionsApplyButtonDialogTitle: "Подтверждение отката",
    revisionsApplyButtonTitle: "Откат",
    revisionsApplyDialogContent: "Это заменит текущее содержимое выбранной ревизии.<br>Текущее содержимое будет добавлен как исправление и будет виден в списке изменений для данного блока.",
    revisionsButtonCurrent: "Ток",
    revisionsButtonViewDiffText: "Различия",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Отмена",
    revisionsDialogTitle: "Просмотр содержимого изменения",
    revisionsDiffButtonDialogCancelButton: "Закрыть",
    revisionsDiffButtonDialogTitle: "Просмотр различий",
    revisionsDiffButtonTitle: "Просмотр различий",
    revisionsLoading: "Загрузка изменений...",
    revisionsNone: "Никаких изменений для этого элемента",
    revisionsPreviewButtonTitle: "Предварительный просмотр",
    revisionsText: "Изменения",
    revisionsTextEmpty: "Без изменений",
    revisionsTitle: "",
    rfmClose: "Закрыть",
    rfmContinue: "Продолжить",
    rfmDelete: "Удалить",
    rfmDownload: "Скачать",
    rfmFileActions: "Действия",
    rfmFileModificationTime: "Изменение",
    rfmFileName: "Имя",
    rfmFileSize: "Размер",
    rfmFileType: "Тип",
    rfmFilteredTotal: "Показывать {{start}} {{end}} {{filteredTotal}} файлов",
    rfmFirst: "Первый",
    rfmHeadingDirectories: "Каталоги",
    rfmHeadingSearch: "Поиск",
    rfmHeadingTags: "Теги",
    rfmHeadingUpload: "Загрузить",
    rfmInsert: "Вставка",
    rfmLast: "Последний",
    rfmSearch: "Перейти",
    rfmTotal: ", отфильтровываются из {{total}}",
    rfmUpload: "Загрузить",
    rfmUploadBrowse: "Обзор",
    rfmUploadDrop: "Перетащите файлы сюда",
    rfmUploadFileRemove: "Удалить",
    rfmView: "Вид",
    saveJsonFail: "Не удалось сохранить {{failed}} блок (блоков).",
    saveJsonSaved: "Сохранено {{saved}} блоков текста.",
    saveNotConfigured: "Сохранить не настроена или отключена.",
    saveRestFail: "Не удалось сохранить {{failed}} блок (блоков).",
    saveRestPartial: "Сохранено {{saved}} из {{failed}} блоков текста.",
    saveRestSaved: "Сохранено {{saved}} блоков текста.",
    saveTitle: "Сохранить содержимое",
    snippetMenuTitle: "Модули",
    specialCharactersDialogOKButton: "OK",
    specialCharactersDialogTitle: "Вставить специальные символы",
    specialCharactersHelp: "Нажмите на спецсимвол чтобы добавить. Нажмите \"OK\" для закрытия диалога",
    specialCharactersTitle: "Вставить специальные символы",
    statisticsButtonCharacterOverLimit: "Символов больше ограничения: {{charactersRemaining}}",
    statisticsButtonCharacterRemaining: "Символов осталось: {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} символов",
    statisticsDialogCharactersOverLimit: "{{characters}} символов, свыше ограничения: {{charactersRemaining}}",
    statisticsDialogCharactersRemaining: "{{characters}} символов, до ограничения ещё {{charactersRemaining}}",
    statisticsDialogNotTruncated: "Текст не будет урезан",
    statisticsDialogOKButton: "Ок",
    statisticsDialogSentence: "{{sentences}} предложение",
    statisticsDialogSentences: "{{sentences}} предложений",
    statisticsDialogTitle: "Статистика содержимого",
    statisticsDialogTruncated: "Текст содержит более {{limit}} символов и может быть урезан",
    statisticsDialogWord: "{{words}} слово",
    statisticsDialogWords: "{{words}} слов",
    statisticsTitle: "Нажмите для просмотра статистики",
    tableCreateTitle: "Создать таблицу",
    tableDeleteColumnTitle: "Удалить колонку",
    tableDeleteRowTitle: "Удалить строку",
    tableInsertColumnTitle: "Вставить колонку",
    tableInsertRowTitle: "Вставить строку",
    tableMergeCellsTitle: "Объединить ячейки",
    tableSplitCellsTitle: "Разбить ячейки",
    tagMenuTagAddress: "Адрес",
    tagMenuTagDiv: "Блок",
    tagMenuTagH1: "Заголовок&nbsp;1",
    tagMenuTagH2: "Заголовок&nbsp;2",
    tagMenuTagH3: "Заголовок&nbsp;3",
    tagMenuTagH4: "Заголовок&nbsp;4",
    tagMenuTagNA: "Н\/Д",
    tagMenuTagP: "Параграф",
    tagMenuTagPre: "Форматированный",
    tagMenuTitle: "Изменить стиль элемента",
    tagTreeElementLink: "ВЫбрано {{element}} элементов",
    tagTreeElementTitle: "Нажмите чтобы выбрать содержимое элемента \"{{element}}\"",
    tagTreeRoot: "корень",
    tagTreeRootLink: "Выбрать всё",
    tagTreeRootTitle: "Нажмите чтобы выбрать всё",
    textBlockQuoteTitle: "Цитата",
    textBoldTitle: "Жирный",
    textItalicTitle: "Курсив",
    textSizeDecreaseTitle: "Уменьшить размер шрифта",
    textSizeIncreaseTitle: "Увеличить размер шрифта",
    textStrikeTitle: "Перечеркнутый",
    textSubTitle: "Нижний индекс",
    textSuperTitle: "Верхний индекс",
    textUnderlineTitle: "Подчеркнутый",
    unsavedEditWarningText: "На странице имеются несохраненные изменения",
    viewSourceDialogCancelButton: "Закрыть",
    viewSourceDialogOKButton: "Примеить код",
    viewSourceDialogTitle: "Исходный код содержимого",
    viewSourceTitle: "Посмотреть или изменить код"
});
