/**
 * @fileOverview Slovak strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('sk', 'slovenčina', {
    alignCenterTitle: "Zarovnať text na stred",
    alignJustifyTitle: "Zarovnanie textu odôvodnenie",
    alignLeftTitle: "Zarovnanie textu doľava",
    alignRightTitle: "Zarovnanie textu vpravo",
    cancelDialogCancelButton: "Pokračovať v úprave",
    cancelDialogContent: "Naozaj chcete zrušiť upravovanie? Všetky zmeny budú stratené!",
    cancelDialogOKButton: "Zrušiť úpravu",
    cancelDialogTitle: "Zrušiť úpravu",
    cancelTitle: "Zrušiť úpravu",
    classMenuTitle: "Výber štýlov",
    clearFormattingTitle: "Vymazať formátovanie",
    clickButtonToEditText: "Upraviť",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatické",
    colorMenuBasicBlack: "Čierna",
    colorMenuBasicBlue: "Modrá",
    colorMenuBasicGreen: "Zelená",
    colorMenuBasicGrey: "Sivá",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Fialová",
    colorMenuBasicRed: "Červená",
    colorMenuBasicTitle: "Zmena farby textu",
    colorMenuBasicWhite: "Biela",
    dockToElementTitle: "Z doku Dock\/editor prvok",
    dockToScreenTitle: "Vybratie z doku\/doku editor obrazovka",
    embedDialogCancelButton: "Zrušiť",
    embedDialogOKButton: "Vložiť objekt",
    embedDialogTabCode: "Vložiť kód",
    embedDialogTabCodeContent: "Vložiť vložiť kód do textovej oblasti nižšie:",
    embedDialogTabPreview: "Náhľad",
    embedDialogTabPreviewContent: "Náhľad vašich vložený objekt je zobrazená nižšie:",
    embedDialogTitle: "Vložiť objekt",
    embedTitle: "Vložiť objekt",
    errorUINoName: "UI \"{{ui}}\" je neplatný (musí mať vlastnosť name)",
    errorUINotObject: "UI \"{{ui}}\" je neplatný (musí byť objekt)",
    errorUIOverride: "UI \"{{name}}\" sa už zaregistroval a budú prepísané",
    fileManagerDialogTitle: "Správca súborov",
    fileManagerTitle: "Správca súborov",
    floatLeftTitle: "Zarovnať obraz na ľavej",
    floatNoneTitle: "Odstrániť obrázok zarovnať",
    floatRightTitle: "Zosúladiť obrázku vpravo",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Komické bez",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Predvolené písmo",
    fontFamilyMenuFontGeorgia: "Gruzínsko",
    fontFamilyMenuFontImpact: "Vplyv",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Krát New Roman",
    fontFamilyMenuTitle: "Vyberte vaše písmo",
    guidesTitle: "Ukázať prvok sprievodcov",
    historyRedoTitle: "Prerobiť",
    historyUndoTitle: "Vrátiť späť",
    hrCreateTitle: "Vložiť vodorovnú čiaru",
    imageResizeButtonDialogCancelButton: "Zrušiť",
    imageResizeButtonDialogHeight: "Výška obrázka",
    imageResizeButtonDialogHeightPlaceHolder: "Výška",
    imageResizeButtonDialogOKButton: "Zmena veľkosti",
    imageResizeButtonDialogTitle: "Veľkosť obrázka",
    imageResizeButtonDialogWidth: "Šírka obrázka",
    imageResizeButtonDialogWidthPlaceHolder: "Šírka",
    imageResizeButtonText: "Veľkosť obrázka",
    insertFileDialogCancelButton: "Zrušiť",
    insertFileDialogOKButton: "Vloženie súboru",
    insertFileNameLabel: "Názov súboru",
    insertFileNamePlaceHolder: "Názov súboru...",
    insertFileTitle: "Vloženie súboru",
    insertFileURLLabel: "Súbor URL",
    insertFileURLPlaceHolder: "Súbor URL...",
    languageMenuTitle: "Zmena jazyka",
    linkCreateDialogCancelButton: "Zrušiť",
    linkCreateDialogMenuHeader: "Vyberte typ prepojenia",
    linkCreateDialogOKButton: "Vložiť prepojenie",
    linkCreateDialogTitle: "Vložiť prepojenie",
    linkCreateTitle: "Vložiť prepojenie",
    linkRemoveTitle: "Odstrániť odkaz",
    linkTypeDocumentHeader: "Odkaz na dokument alebo iný súbor",
    linkTypeDocumentInfo: "<h2>Nie ste si istí čo dať do poľa vyššie?<\/h2><ol>    <li>Skontrolujte súbor bol nahraný na vašich webových stránkach.<\/li>    <li>Nahraný súbor otvoriť v prehľadávači.<\/li>    <li>Skopírujte adresu URL súboru z panela s adresou prehliadača a vložte ho do vyššie zobrazeného poľa.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokument alebo iný súbor",
    linkTypeDocumentLocationLabel: "Umiestnenie:",
    linkTypeDocumentLocationPlaceHolder: "Zadajte adresu URL",
    linkTypeDocumentNewWindowHeader: "Nové okno",
    linkTypeDocumentNewWindowLabel: "Začiarknutím tohto políčka sa súbor otvoriť v novom okne\/záložke.",
    linkTypeEmailHeader: "Odkaz na e-mailovú adresu",
    linkTypeEmailLabel: "E-mailovú adresu",
    linkTypeEmailSubjectLabel: "Predmet (voliteľné):",
    linkTypeEmailSubjectPlaceHolder: "Zadajte predmet",
    linkTypeEmailToLabel: "E-mail:",
    linkTypeEmailToPlaceHolder: "Zadajte e-mailovú adresu",
    linkTypeExternalHeader: "Odkaz na stránku na inom webe",
    linkTypeExternalInfo: "<h2>Nie ste si istí čo dať do poľa vyššie?<\/h2><ol>    <li>Nájsť stránky na webe chcete prepojiť.<\/li>    <li>Skopírujte webovú adresu z prehliadača do adresného riadku a vložte ho do vyššie zobrazeného poľa.<\/li><\/ol>",
    linkTypeExternalLabel: "Stránky na inú webovú stránku",
    linkTypeExternalLocationLabel: "Umiestnenie:",
    linkTypeExternalLocationPlaceHolder: "Zadajte adresu URL",
    linkTypeExternalNewWindowHeader: "Nové okno",
    linkTypeExternalNewWindowLabel: "Toto políčko prepojenie otvoriť v novom okne\/záložke.",
    linkTypeInternalHeader: "Odkaz na stránky na tejto webovej stránke",
    linkTypeInternalInfo: "<h2>Nie ste si istí čo dať do poľa vyššie?<\/h2><ol>    <li>Nájsť stránky na tejto stránke odkaz.<\/li>    <li>Skopírujte webovú adresu z prehliadača adresného riadku, s výnimkou \"{{domain}}\" a vložte ho do vyššie zobrazeného poľa.<\/li><\/ol>",
    linkTypeInternalLabel: "Stránky na tejto webovej stránke",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Zadajte identifikátor URI",
    linkTypeInternalNewWindowHeader: "Nové okno",
    linkTypeInternalNewWindowLabel: "Toto políčko prepojenie otvoriť v novom okne\/záložke.",
    listOrderedTitle: "Zoradený zoznam",
    listUnorderedTitle: "Nečíslovaný zoznam",
    logoTitle: "Ďalšie informácie o editore WYSIWYG Raptor",
    loremIpsumTitle: "Vložiť fiktívny text pre testovanie",
    navigateAway: "\nExistujú neuložené zmeny na tejto stránke. \nAk opustíte túto stránku stratíte neuložené zmeny",
    pasteDialogCancelButton: "Zrušiť",
    pasteDialogFormattedCleaned: "Formátovať &amp; vyčistiť",
    pasteDialogFormattedUnclean: "Nečistí naformátovaná",
    pasteDialogOKButton: "Vložiť",
    pasteDialogPlain: "Obyčajný Text",
    pasteDialogSource: "Zdrojový kód",
    pasteDialogTitle: "Pasta",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Nepodarilo sa načítať revízie",
    revisionsApplyButtonDialogCancelButton: "Zrušiť",
    revisionsApplyButtonDialogOKButton: "Vrátenie zmien",
    revisionsApplyButtonDialogText: "Potvrdenie vrátenia",
    revisionsApplyButtonDialogTitle: "Potvrdenie vrátenia",
    revisionsApplyButtonText: "Vrátenie zmien",
    revisionsApplyButtonTitle: "Vrátenie zmien",
    revisionsApplyDialogContent: "To nahradí súčasný obsah vybranej revízií.<br>Súčasný obsah budú pridané ako revíziu, a bude viditeľný v zozname revízie pre tento blok.",
    revisionsButtonCurrent: "Aktuálne",
    revisionsButtonViewDiffText: "Rozdiely",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Vytvoril",
    revisionsDialogCancelButton: "Zrušiť",
    revisionsDialogTitle: "Zobraziť obsah revízií",
    revisionsDiffButtonDialogCancelButton: "Zavrieť",
    revisionsDiffButtonDialogTitle: "Zobrazenie rozdielov",
    revisionsDiffButtonText: "Zobrazenie rozdielov",
    revisionsDiffButtonTitle: "Zobrazenie rozdielov",
    revisionsLoading: "Načítanie revízie...",
    revisionsNone: "Žiadne revízie pre tento prvok",
    revisionsPreviewButtonText: "Náhľad",
    revisionsPreviewButtonTitle: "Náhľad",
    revisionsText: "Revízie",
    revisionsTextEmpty: "Žiadne revízie",
    revisionsTitle: "",
    rfmClose: "Zavrieť",
    rfmContinue: "Pokračovať",
    rfmDelete: "Odstrániť",
    rfmDownload: "Na stiahnutie",
    rfmFileActions: "Akcie",
    rfmFileModificationTime: "Upravené",
    rfmFileName: "meno",
    rfmFileSize: "Veľkosť",
    rfmFileType: "Typ",
    rfmFilteredTotal: "Zobrazuje sa {{start}} {{end}} {{filteredTotal}} súborov",
    rfmFirst: "Prvý",
    rfmHeadingDirectories: "Adresáre",
    rfmHeadingSearch: "Hľadať",
    rfmHeadingTags: "Tagy",
    rfmHeadingUpload: "Nahrať",
    rfmInsert: "Vložiť",
    rfmLast: "Posledný",
    rfmSearch: "Ísť",
    rfmTagDocument: "Dokument",
    rfmTagImage: "Obrázok",
    rfmTotal: ", filtrované z {{total}}",
    rfmUpload: "Nahrať",
    rfmUploadBrowse: "Prehľadávať",
    rfmUploadDrop: "Presuňte súbory sem",
    rfmUploadFileRemove: "Odstrániť",
    rfmUploadOr: "alebo",
    rfmView: "Zobrazenie",
    saveJsonFail: "Nepodarilo sa uložiť {{failed}} obsahu tomto",
    saveJsonSaved: "Úspešne uložený {{saved}} tomto obsahu.",
    saveNotConfigured: "Uloženie nie je nakonfigurovaná alebo je vypnutá.",
    saveRestFail: "Nepodarilo sa uložiť {{failed}} tomto obsahu.",
    saveRestPartial: "Uložiť {{saved}} z {{failed}} obsah blokov.",
    saveRestSaved: "Úspešne uložený {{saved}} tomto obsahu.",
    saveTitle: "Uložiť obsah",
    snippetMenuTitle: "Úryvky",
    specialCharactersArrows: "Šípky",
    specialCharactersDialogOKButton: "ok",
    specialCharactersDialogTitle: "Vkladanie špeciálnych znakov",
    specialCharactersGreekAlphabet: "Grécka abeceda",
    specialCharactersHelp: "Kliknite na špeciálny znak pridať. Kliknutím na tlačidlo \"OK\" po dokončení Zavrite toto dialógové okno",
    specialCharactersMathematics: "Matematika",
    specialCharactersSymbols: "Symboly",
    specialCharactersTitle: "Vloženie špeciálneho znaku",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} znakov nad limit",
    statisticsButtonCharacterRemaining: "Počet zostávajúcich znakov {{charactersRemaining}}",
    statisticsButtonCharacters: "znaky {{characters}}",
    statisticsDialogCharactersOverLimit: "znaky {{characters}}, {{charactersRemaining}} prekročenie odporúčanej",
    statisticsDialogCharactersRemaining: "Počet {{characters}}, {{charactersRemaining}} zostávajúcich znakov",
    statisticsDialogNotTruncated: "Obsah bude nie skrátený",
    statisticsDialogOKButton: "ok",
    statisticsDialogSentence: "{{sentences}} veta",
    statisticsDialogSentences: "{{sentences}} viet.",
    statisticsDialogTitle: "Obsah štatistiky",
    statisticsDialogTruncated: "Obsah obsahuje viac ako {{limit}} znakov a môže byť skrátený",
    statisticsDialogWord: "{{words}} lá",
    statisticsDialogWords: "{{words}} slová",
    statisticsTitle: "Kliknite pre zobrazenie štatistiky",
    tableCreateTitle: "Vytvorenie tabuľky",
    tableDeleteColumnTitle: "Odstrániť stĺpec tabuľky",
    tableDeleteRowTitle: "Odstrániť riadok tabuľky",
    tableInsertColumnTitle: "Vložiť stĺpec tabuľky",
    tableInsertRowTitle: "Vložiť riadok tabuľky",
    tableMergeCellsTitle: "Zlúčiť bunky tabuľky",
    tableSplitCellsTitle: "Rozdeliť bunky tabuľky",
    tagMenuTagAddress: "Adresa",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Nadpis 1",
    tagMenuTagH2: "Nadpis 2",
    tagMenuTagH3: "Nadpis 3",
    tagMenuTagH4: "Nadpis 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Odseku",
    tagMenuTagPre: "Vopred naformátované",
    tagMenuTitle: "Zmena prvku štýlu",
    tagTreeElementLink: "Vybrať prvok {{element}}",
    tagTreeElementTitle: "Kliknutím vyberte obsah prvku \"{{element}}\"",
    tagTreeRoot: "koreň",
    tagTreeRootLink: "Vyberte všetky možné upravovať obsah",
    tagTreeRootTitle: "Kliknutím vyberte všetky možné upravovať obsah",
    textBlockQuoteTitle: "Blok citácie",
    textBoldTitle: "Tučné",
    textItalicTitle: "Kurzíva",
    textSizeDecreaseTitle: "Zmenšenie veľkosti textu",
    textSizeIncreaseTitle: "Zväčšiť veľkosť textu",
    textStrikeTitle: "Prečiarknutie",
    textSubTitle: "Sub-skript",
    textSuperTitle: "Super skript",
    textUnderlineTitle: "Podčiarknutie",
    unsavedEditWarningText: "Existujú neuložené zmeny na tejto stránke",
    viewSourceDialogCancelButton: "Zavrieť",
    viewSourceDialogOKButton: "Použiť zdrojový kód",
    viewSourceDialogTitle: "Kód zdroja obsahu",
    viewSourceTitle: "Zobraziť\/upraviť zdrojový kód"
});