/**
 * @fileOverview Slovenian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('sl', 'slovenščina', {
    alignCenterTitle: "Poravnaj besedilo na sredino",
    alignJustifyTitle: "Besedilo poravnajte upravičujejo",
    alignLeftTitle: "Poravnaj besedilo levo",
    alignRightTitle: "Poravnaj besedilo na desno",
    cancelDialogCancelButton: "Nadaljuj urejanje",
    cancelDialogContent: "Ali ste prepričani, da želite preklicati urejanje? Vse spremembe bodo izgubljene!",
    cancelDialogOKButton: "Preklicati urejanje",
    cancelDialogTitle: "Preklicati urejanje",
    cancelTitle: "Preklicati urejanje",
    classMenuTitle: "Slog izbirnik",
    clearFormattingTitle: "Počisti oblikovanje",
    clickButtonToEditText: "Urejanje",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Avtomatski",
    colorMenuBasicBlack: "Black",
    colorMenuBasicBlue: "Modra",
    colorMenuBasicGreen: "Zelena",
    colorMenuBasicGrey: "Siva",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Vijolična",
    colorMenuBasicRed: "Rdeča",
    colorMenuBasicTitle: "Spreminjanje barve besedila",
    colorMenuBasicWhite: "Bela",
    dockToElementTitle: "Nabrežje\/razdružitev urednik za element",
    dockToScreenTitle: "Urednik zaslon nabrežje\/razdružitev",
    embedDialogCancelButton: "Prekliči",
    embedDialogOKButton: "Vdelati predmet",
    embedDialogTabCode: "Vlagati zbornik",
    embedDialogTabCodeContent: "Embed kodo prilepite v besedilno polje spodaj:",
    embedDialogTabPreview: "Predogled",
    embedDialogTabPreviewContent: "Predogled vdelanega predmeta je prikazano spodaj:",
    embedDialogTitle: "Vdelati predmet",
    embedTitle: "Vdelati predmet",
    errorUINoName: "UI \"{{ui}}\" ni veljaven (mora imeti lastnost name)",
    errorUINotObject: "UI \"{{ui}}\" ni veljaven (mora biti predmet)",
    errorUIOverride: "UI »{{name}} «je že registrirano, in ne bo prepisan",
    fileManagerDialogTitle: "File Manager",
    fileManagerTitle: "File Manager",
    floatLeftTitle: "Poravnaj sliko levo",
    floatNoneTitle: "Odstranite sliko poravnate",
    floatRightTitle: "Poravnaj sliko desno",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Strip, brez",
    fontFamilyMenuFontCourier: "Courier New",
    fontFamilyMenuFontDefault: "Privzeta pisava",
    fontFamilyMenuFontGeorgia: "Gruzija",
    fontFamilyMenuFontImpact: "Vpliv",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Krat nov rimski",
    fontFamilyMenuTitle: "Izberite vašo pisavo",
    guidesTitle: "Pokaži element vodniki",
    historyRedoTitle: "Uveljavi",
    historyUndoTitle: "Razveljavi",
    hrCreateTitle: "Vstavite vodoravno pravilo",
    imageResizeButtonDialogCancelButton: "Prekliči",
    imageResizeButtonDialogHeight: "Višina slike",
    imageResizeButtonDialogHeightPlaceHolder: "Višina",
    imageResizeButtonDialogOKButton: "Spremeni velikost",
    imageResizeButtonDialogTitle: "Velikost slike",
    imageResizeButtonDialogWidth: "Širina slike",
    imageResizeButtonDialogWidthPlaceHolder: "Širina",
    imageResizeButtonText: "Velikost slike",
    insertFileDialogCancelButton: "Prekliči",
    insertFileDialogOKButton: "Vstavljanje datoteke",
    insertFileNameLabel: "Ime datoteke",
    insertFileNamePlaceHolder: "Ime datoteke...",
    insertFileTitle: "Vstavljanje datoteke",
    insertFileURLLabel: "URL datoteke",
    insertFileURLPlaceHolder: "URL datoteke...",
    languageMenuTitle: "Menjava jezika",
    linkCreateDialogCancelButton: "Prekliči",
    linkCreateDialogMenuHeader: "Izberite vrsto povezave",
    linkCreateDialogOKButton: "Vstavi povezavo",
    linkCreateDialogTitle: "Vstavi povezavo",
    linkCreateTitle: "Vstavi povezavo",
    linkRemoveTitle: "Odstrani povezavo",
    linkTypeDocumentHeader: "Povezava do dokumenta ali druge datoteke",
    linkTypeDocumentInfo: "<h2>Ne vem, kaj naj v zgornje polje?<\/h2><ol>    <li>Zagotovitev datoteke je prenesena na vašo spletno stran.<\/li>    <li>Odprite naložena datoteka v vašem brskalniku.<\/li>    <li>Copy URL datoteke iz naslovno vrstico vašega brskalnika in ga prilepite v zgornje polje.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokument ali drugo datoteko",
    linkTypeDocumentLocationLabel: "Lokacija:",
    linkTypeDocumentLocationPlaceHolder: "Vnesite spletni naslov",
    linkTypeDocumentNewWindowHeader: "Novo okno",
    linkTypeDocumentNewWindowLabel: "Potrdite to polje, da imajo odprto v a nov obrv okno\/zanka.",
    linkTypeEmailHeader: "Povezava na e-poštni naslov",
    linkTypeEmailLabel: "E-poštni naslov",
    linkTypeEmailSubjectLabel: "Predmet (neobvezno):",
    linkTypeEmailSubjectPlaceHolder: "Vnesite predmet",
    linkTypeEmailToLabel: "E-pošta:",
    linkTypeEmailToPlaceHolder: "Nastopiti email ogovor",
    linkTypeExternalHeader: "Povezava do strani na drugo spletno stran",
    linkTypeExternalInfo: "<h2>Ne vem, kaj naj v zgornje polje?<\/h2><ol>    <li>Poišči stran na spletu, ki jih želite povezati.<\/li>    <li>Kopirajte spletni naslov iz naslovne vrstice brskalnika in ga prilepite v zgornje polje.<\/li><\/ol>",
    linkTypeExternalLabel: "Strani na drugo spletno stran",
    linkTypeExternalLocationLabel: "Lokacija:",
    linkTypeExternalLocationPlaceHolder: "Vnesite spletni naslov",
    linkTypeExternalNewWindowHeader: "Novo okno",
    linkTypeExternalNewWindowLabel: "Potrdite to polje, da povezava odpre novo okno\/zavihek.",
    linkTypeInternalHeader: "Povezava do strani na tej spletni strani",
    linkTypeInternalInfo: "<h2>Ne vem, kaj naj v zgornje polje?<\/h2><ol>    <li>Poišči stran v to povezavo mesta za.<\/li>    <li>Kopirajte spletni naslov s vaš obrv ogovor zasova, razen \"{{domain}}\" in ga prilepite v zgornje polje.<\/li><\/ol>",
    linkTypeInternalLabel: "Strani na tej spletni strani",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Vnesite URI",
    linkTypeInternalNewWindowHeader: "Novo okno",
    linkTypeInternalNewWindowLabel: "Potrdite to polje, da povezava odpre novo okno\/zavihek.",
    listOrderedTitle: "Urejen seznam",
    listUnorderedTitle: "Neurejen seznam",
    logoTitle: "Želite izvedeti več o Raptor WYSIWYG urednik",
    navigateAway: "\nNa tej strani so neshranjene spremembe. \nČe vi zapustiti to stran, boste izgubili neshranjene spremembe",
    pasteDialogCancelButton: "Prekliči",
    pasteDialogFormattedCleaned: "Oblikovan &amp; očistiti",
    pasteDialogFormattedUnclean: "Oblikovano nečisto",
    pasteDialogOKButton: "Vstavite",
    pasteDialogPlain: "Golo besedilo",
    pasteDialogSource: "Izvorno kodo",
    pasteDialogTitle: "Paste",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Ni bilo mogoče pridobiti revizije",
    revisionsApplyButtonDialogCancelButton: "Prekliči",
    revisionsApplyButtonDialogOKButton: "Povrnitev prejšnjega stanja",
    revisionsApplyButtonDialogTitle: "Potrditev razveljavitve",
    revisionsApplyButtonTitle: "Povrnitev prejšnjega stanja",
    revisionsApplyDialogContent: "Ta bo nadomestil sedanji vsebini z izbrano revizijo.<br>Trenutne vsebine bodo dodani kot revizije in bo viden na seznamu popravkov za ta blok.",
    revisionsButtonCurrent: "Tok",
    revisionsButtonViewDiffText: "Razlike",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Prekliči",
    revisionsDialogTitle: "Ogled vsebine revizije",
    revisionsDiffButtonDialogCancelButton: "Zaprite",
    revisionsDiffButtonDialogTitle: "Pogled razlike",
    revisionsDiffButtonTitle: "Pogled razlike",
    revisionsLoading: "Nalaganje revizije...",
    revisionsNone: "Ni popravkov za ta element",
    revisionsPreviewButtonTitle: "Predogled",
    revisionsText: "Revizije",
    revisionsTextEmpty: "Ne revizije",
    revisionsTitle: "",
    rfmClose: "Zaprite",
    rfmContinue: "Še",
    rfmDelete: "Izbrisati",
    rfmDownload: "Download",
    rfmFileActions: "Dejanja",
    rfmFileModificationTime: "Spremenil",
    rfmFileName: "ime",
    rfmFileSize: "Velikost",
    rfmFileType: "Vrsta",
    rfmFilteredTotal: "Kazanje {{start}} zdelati {{end}} {{filteredTotal}} datotek",
    rfmFirst: "Prvi",
    rfmHeadingDirectories: "Imeniki",
    rfmHeadingSearch: "Išči",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Upload",
    rfmInsert: "Vstavite",
    rfmLast: "Nazadnje",
    rfmSearch: "Go",
    rfmTotal: ", izločeni iz {{total}}",
    rfmUpload: "Upload",
    rfmUploadBrowse: "Prebrskaj",
    rfmUploadDrop: "Spustite datoteke tukaj",
    rfmUploadFileRemove: "Odstrani",
    rfmView: "Pogled",
    saveJsonFail: "Shranite {{failed}} skupino(-e) vsebine ni uspelo",
    saveJsonSaved: "Uspešno shranjene vsebine skupino(-e) {{saved}}.",
    saveNotConfigured: "Shrani ni konfigurirana ali je onemogočen.",
    saveRestFail: "Shranite {{failed}} skupino(-e) vsebine ni uspelo.",
    saveRestPartial: "Shranjene {{saved}} od {{failed}} vsebine blokov.",
    saveRestSaved: "Uspešno shranjene vsebine skupino(-e) {{saved}}.",
    saveTitle: "Shranite vsebino",
    snippetMenuTitle: "Odrezki",
    specialCharactersDialogOKButton: "v redu",
    specialCharactersDialogTitle: "Vstavljanje posebnih znakov",
    specialCharactersHelp: "Kliknite poseben znak, da ga dodate. Kliknite \"OK\" Ko končate zapreti to pogovorno okno",
    specialCharactersTitle: "Vstavljanje posebnih znakov",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} znakov nad mejo",
    statisticsButtonCharacterRemaining: "Preostali znaki {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} znakov",
    statisticsDialogCharactersOverLimit: "{{characters}} znakov, {{charactersRemaining}} nad priporočeno mejo",
    statisticsDialogCharactersRemaining: "{{characters}}, {{charactersRemaining}} preostali znaki",
    statisticsDialogNotTruncated: "Vsebine ne prirezal",
    statisticsDialogOKButton: "v redu",
    statisticsDialogSentence: "{{sentences}} stavek",
    statisticsDialogSentences: "{{sentences}} kazni",
    statisticsDialogTitle: "Vsebine statistika",
    statisticsDialogTruncated: "Vsebine vsebuje več kot {{limit}} znakov in morda skrajšana",
    statisticsDialogWord: "beseda {{words}}",
    statisticsDialogWords: "{{words}} besede",
    statisticsTitle: "Kliknite za ogled statistike",
    tableCreateTitle: "Ustvarjanje tabele",
    tableDeleteColumnTitle: "Izbriši stolpec tabele",
    tableDeleteRowTitle: "Izbriši vrstice tabele",
    tableInsertColumnTitle: "Vstavite stolpec tabele",
    tableInsertRowTitle: "Vstavite vrstice tabele",
    tableMergeCellsTitle: "Spoji celice tabele",
    tableSplitCellsTitle: "Razdelitev celic tabele",
    tagMenuTagAddress: "Naslov",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Naslov 1",
    tagMenuTagH2: "Razdelek 2",
    tagMenuTagH3: "Naslov 3",
    tagMenuTagH4: "Naslov 4",
    tagMenuTagNA: "N \/",
    tagMenuTagP: "Odstavka",
    tagMenuTagPre: "Vnaprej oblikovano",
    tagMenuTitle: "Spreminjanje slog element",
    tagTreeElementLink: "Izberite element {{element}}",
    tagTreeElementTitle: "Kliknite, da izberete vsebino elementa \"{{element}}\"",
    tagTreeRoot: "koren",
    tagTreeRootLink: "Izberite vse mogoče urejati vsebine",
    tagTreeRootTitle: "Kliknite, če želite izbrati vse mogoče urejati vsebine",
    textBlockQuoteTitle: "Citat v bloku",
    textBoldTitle: "Krepko",
    textItalicTitle: "Ležeče",
    textSizeDecreaseTitle: "Pomanjšaj velikost besedila",
    textSizeIncreaseTitle: "Rast tekst velikost",
    textStrikeTitle: "Prečrtano",
    textSubTitle: "Sub-skripta",
    textSuperTitle: "Super-skripta",
    textUnderlineTitle: "Podčrtano",
    unsavedEditWarningText: "Obstajajo neshranjene spremembe na tej strani",
    viewSourceDialogCancelButton: "Zaprite",
    viewSourceDialogOKButton: "Uporablja izvorno kodo",
    viewSourceDialogTitle: "Vsebine izvorne kode",
    viewSourceTitle: "Ogled\/urejanje izvorne kode"
});