/**
 * @fileOverview Swedish strings file.
 * @license http://www.raptor-editor.com/license
 *
 * @author Christoffer Bubach, asmhacker@gmail.com, http://www.bubach.net/
 */
extendLocale('sv', 'Svenska', {
    alignCenterTitle: "Centrerad",
    alignJustifyTitle: "Marginaljustera",
    alignLeftTitle: "Vänsterjustera",
    alignRightTitle: "Högerjustera",
    cancelDialogCancelButton: "Stäng",
    cancelDialogContent: "Är du säker på att du vill sluta redigera? Alla ändringar kommer förloras!",
    cancelDialogOKButton: "OK",
    cancelDialogTitle: "Cancel Editing",
    cancelTitle: "Cancel editing",
    classMenuTitle: "Stil picker",
    clearFormattingTitle: "Ta bort formatering",
    clickButtonToEditPluginButton: "Klicka här för att redigera",
    clickButtonToEditText: "Redigera",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Automatic",
    colorMenuBasicBlack: "Black",
    colorMenuBasicBlue: "Blue",
    colorMenuBasicGreen: "Green",
    colorMenuBasicGrey: "Grey",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Purple",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Change text color",
    colorMenuBasicWhite: "White",
    dockToElementTitle: "Dock editor to element",
    dockToScreenTitle: "Dock editor to screen",
    embedDialogCancelButton: "Avbryt",
    embedDialogOKButton: "Bädda in objekt",
    embedDialogTabCode: "Bädda in kod",
    embedDialogTabCodeContent: "Klistra in embed-koden i textområdet nedan:",
    embedDialogTabPreview: "Förhandsgranskning",
    embedDialogTabPreviewContent: "En förhandsgranskning av dina inbäddat objekt visas nedan:",
    embedDialogTitle: "Bädda in objekt",
    embedTitle: "Bädda in objekt",
    errorPluginNoName: "Plugin \"{{plugin}}\" is invalid (must have a name property)",
    errorPluginNotObject: "Plugin \"{{plugin}}\" is invalid (must be an object)",
    errorPluginOverride: "Plugin \"{{name}}\" has already been registered, and will be overwritten",
    errorUINoName: "UI \"{{ui}}\" is invalid (must have a name property)",
    errorUINotObject: "UI \"{{ui}}\" is invalid (must be an object)",
    errorUIOverride: "UI \"{{name}}\" has already been registered, and will be overwritten",
    fileManagerDialogTitle: "File Manager",
    fileManagerTitle: "File Manager",
    floatLeftTitle: "Vänsterjustera bild",
    floatNoneTitle: "Remove image align",
    floatRightTitle: "Högerjustera bild",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Comic utan",
    fontFamilyMenuFontCourier: "Courier nya",
    fontFamilyMenuFontDefault: "Standardteckensnitt",
    fontFamilyMenuFontGeorgia: "Georgien",
    fontFamilyMenuFontImpact: "Inverkan",
    fontFamilyMenuFontPalatino: "Palatinen",
    fontFamilyMenuFontTimes: "Gånger nya Roman",
    fontFamilyMenuTitle: "Välj teckensnittets",
    guidesTitle: "Visa stödlinjer",
    historyRedoTitle: "Redo",
    historyUndoTitle: "Undo",
    hrCreateTitle: "Infoga vågräta linjen",
    imageResizeButtonDialogCancelButton: "Avbryt",
    imageResizeButtonDialogHeight: "Bildens höjd",
    imageResizeButtonDialogHeightPlaceHolder: "Höjd",
    imageResizeButtonDialogOKButton: "Ändra storlek på",
    imageResizeButtonDialogTitle: "Ändra storlek på bilden",
    imageResizeButtonDialogWidth: "Bildens bredd",
    imageResizeButtonDialogWidthPlaceHolder: "Bredd",
    imageResizeButtonText: "Ändra storlek på bilden",
    insertFileDialogCancelButton: "Avbryt",
    insertFileDialogOKButton: "Infoga fil",
    insertFileNameLabel: "Filnamn",
    insertFileNamePlaceHolder: "Filnamn...",
    insertFileTitle: "Infoga fil",
    insertFileURLLabel: "URL till fil",
    insertFileURLPlaceHolder: "URL till fil...",
    languageMenuTitle: "Ändra språk",
    linkCreateDialogCancelButton: "Avbryt",
    linkCreateDialogMenuHeader: "Välj en länk",
    linkCreateDialogOKButton: "Infoga länk",
    linkCreateDialogTitle: "Infoga länk",
    linkCreateTitle: "Infoga länk",
    linkDialogCancelButton: "Avbryt",
    linkDialogMenuHeader: "Välj en länktyp:",
    linkDialogOKButton: "Infoga länk",
    linkDialogTitle: "Infoga länk",
    linkRemoveTitle: "Ta bort länk",
    linkTypeDocumentHeader: "Länk till ett dokument eller annan fil",
    linkTypeDocumentInfo: "<h2>Inte säker på vad att sätta i rutan ovan?<\/h2><ol>    <li>Se till att filen har överförts till din webbplats.<\/li>    <li>Öppna den belastat upp arkivera i din webbläsare.<\/li>    <li>Kopiera filens URL från webbläsarens adressfält och klistra in den i rutan ovan.<\/li><\/ol>",
    linkTypeDocumentLabel: "Dokument eller annan fil",
    linkTypeDocumentLocationLabel: "Plats:",
    linkTypeDocumentLocationPlaceHolder: "Ange en URL",
    linkTypeDocumentNewWindowHeader: "Nytt fönster",
    linkTypeDocumentNewWindowLabel: "Markera den här kryssrutan om du vill ha filen öppnas i ett nytt fönster\/flik.",
    linkTypeEmailHeader: "Länka till en epost-adress",
    linkTypeEmailLabel: "Epost adress",
    linkTypeEmailSubjectLabel: "Ämne (frivilligt):",
    linkTypeEmailSubjectPlaceHolder: "Ange ämne",
    linkTypeEmailToLabel: "Epost:",
    linkTypeEmailToPlaceHolder: "Ange epost-adress",
    linkTypeExternalHeader: "Link to a page on another website",
    linkTypeExternalInfo: "<h2>Inte säker på vad som ska fyllas i?<\/h2><ol>    <li>Hitta sidan på webben som du vill länka till.<\/li>    <li>Kopiera webbadressen från webbläsarens adressfält och klistra in i fältet ovan.<\/li><\/ol>",
    linkTypeExternalLabel: "Page on another website",
    linkTypeExternalLocationLabel: "Plats",
    linkTypeExternalLocationPlaceHolder: "Ange en URL",
    linkTypeExternalNewWindowHeader: "Nytt fönster",
    linkTypeExternalNewWindowLabel: "Kryssa i denna box för att öppna länken i ett nytt fönster.",
    linkTypeInternalHeader: "Link to a page on this website",
    linkTypeInternalInfo: "<h2>Inte säker på vad som ska fyllas i?<\/h2><ol>    <li>Find the page on this site link to.<\/li>    <li>Copy the web address from your browser's address bar, excluding \"{{domain}}\" and paste it into the box above.<\/li><\/ol>",
    linkTypeInternalLabel: "Page on this website",
    linkTypeInternalLocationLabel: "Plats",
    linkTypeInternalLocationPlaceHolder: "Ange en URI",
    linkTypeInternalNewWindowHeader: "Nytt fönster",
    linkTypeInternalNewWindowLabel: "Kryssa i denna box för att öppna länken i ett nytt fönster.",
    listOrderedTitle: "Ordnad lista",
    listUnorderedTitle: "Oordnad lista",
    logoTitle: "Lär dig mer om Raptor WYSIWYG Editor",
    loremIpsumTitle: "Infoga dummy text för testning",
    navigateAway: "\nDet finns osparade ändringar på denna sida. \nOm du navigerar bort från denna sida kommer du förlora dina osparade ändringar",
    pasteDialogCancelButton: "Avbryt",
    pasteDialogFormattedCleaned: "Formaterade &amp; rengöras",
    pasteDialogFormattedUnclean: "Formaterade orena",
    pasteDialogOKButton: "Infoga",
    pasteDialogPlain: "Oformaterad Text",
    pasteDialogSource: "Källkoden",
    pasteDialogTitle: "Klistra in",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Det gick inte att hämta revideringar",
    revisionsApplyButtonDialogCancelButton: "Avbryt",
    revisionsApplyButtonDialogOKButton: "Ångring",
    revisionsApplyButtonDialogText: "Rollback bekräftelse",
    revisionsApplyButtonDialogTitle: "Rollback bekräftelse",
    revisionsApplyButtonText: "Ångring",
    revisionsApplyButtonTitle: "Ångring",
    revisionsApplyDialogContent: "Detta kommer att ersätta det aktuella innehållet med valda revideringen.<br>Aktuellt innehåll kommer att läggas som en revidering, och kommer att visas i listan revideringar för detta block.",
    revisionsButtonCurrent: "Nuvarande",
    revisionsButtonViewDiffText: "Skillnader",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Skapad",
    revisionsDialogCancelButton: "Avbryt",
    revisionsDialogTitle: "Visa innehåll revideringar",
    revisionsDiffButtonDialogCancelButton: "Stäng",
    revisionsDiffButtonDialogTitle: "Visa skillnader",
    revisionsDiffButtonText: "Visa skillnader",
    revisionsDiffButtonTitle: "Visa skillnader",
    revisionsLoading: "Laddar ändringar...",
    revisionsNone: "Inga revideringar för detta element",
    revisionsPreviewButtonText: "Förhandsgranskning",
    revisionsPreviewButtonTitle: "Förhandsgranskning",
    revisionsText: "Revideringar",
    revisionsTextEmpty: "Inga ändringar",
    revisionsTitle: "",
    rfmClose: "Stäng",
    rfmContinue: "Fortsätta",
    rfmDelete: "Ta bort",
    rfmDownload: "Hämta",
    rfmFileActions: "Åtgärder",
    rfmFileModificationTime: "Modifierade",
    rfmFileName: "Namn",
    rfmFileSize: "Storlek",
    rfmFileType: "Typ",
    rfmFilteredTotal: "{{start}} visar att {{end}} {{filteredTotal}} filer",
    rfmFirst: "Första",
    rfmHeadingDirectories: "Kataloger",
    rfmHeadingSearch: "Sök",
    rfmHeadingTags: "Taggar",
    rfmHeadingUpload: "Ladda upp",
    rfmInsert: "Infoga",
    rfmLast: "Senaste",
    rfmSearch: "Gå",
    rfmTagDocument: "Dokument",
    rfmTagImage: "Bild",
    rfmTotal: ", filtreras från {{total}}",
    rfmUpload: "Ladda upp",
    rfmUploadBrowse: "Bläddra",
    rfmUploadDrop: "Släpp filer här",
    rfmUploadFileRemove: "Ta bort",
    rfmUploadOr: "eller",
    rfmView: "Visa",
    saveJsonFail: "Det gick inte att spara {{failed}} innehåll (n)",
    saveJsonSaved: "Har sparats {{saved}} innehåll (n).",
    saveNotConfigured: "Spara inte har konfigurerats, eller är inaktiverad.",
    saveRestFail: "Det gick inte att spara {{failed}} innehåll (n).",
    saveRestPartial: "Sparade {{saved}} av {{failed}} innehåll.",
    saveRestSaved: "Har sparats {{saved}} innehåll (n).",
    saveTitle: "Save content",
    snippetMenuTitle: "Snuttar",
    specialCharactersArrows: "Pilar",
    specialCharactersDialogOKButton: "Okej",
    specialCharactersDialogTitle: "Infoga specialtecken",
    specialCharactersGreekAlphabet: "Grekiska alfabetet",
    specialCharactersHelp: "Klicka på ett specialtecken för att lägga till den. Klicka på \"OK\" när du är klar för att stänga dialogrutan",
    specialCharactersMathematics: "Matematik",
    specialCharactersSymbols: "Symboler",
    specialCharactersTitle: "Infoga ett specialtecken",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} bokstäver över gränsen",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} bokstäver återstår",
    statisticsButtonCharacters: "{{characters}} bokstäver",
    statisticsDialogCharactersOverLimit: "{{characters}} bokstäver, {{charactersRemaining}} över den rekommenderade gränsen",
    statisticsDialogCharactersRemaining: "{{characters}} bokstäver, {{charactersRemaining}} kvarstående",
    statisticsDialogNotTruncated: "Innehållet kommer inte att avkortas",
    statisticsDialogOKButton: "OK",
    statisticsDialogSentence: "{{sentences}} sentence",
    statisticsDialogSentences: "{{sentences}} meningar",
    statisticsDialogTitle: "Innehållsstatistik",
    statisticsDialogTruncated: "Innehållet omfattar mer än {{limit}} bokstäver och kan bli avkortat",
    statisticsDialogWord: "{{words}} ord",
    statisticsDialogWords: "{{words}} ord",
    statisticsTitle: "Klicka här för visa statistik",
    tableCreateTitle: "Create table",
    tableDeleteColumnTitle: "Delete table column",
    tableDeleteRowTitle: "Delete table row",
    tableInsertColumnTitle: "Insert table column",
    tableInsertRowTitle: "Insert table row",
    tableMergeCellsTitle: "Sammanfoga tabellceller",
    tableSplitCellsTitle: "Dela tabellceller",
    tagMenuTagAddress: "Adress",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Rubrik&nbsp;1",
    tagMenuTagH2: "Rubrik&nbsp;2",
    tagMenuTagH3: "Rubrik&nbsp;3",
    tagMenuTagH4: "Rubrik 4",
    tagMenuTagNA: "Ej tillgänglig",
    tagMenuTagP: "Paragraf",
    tagMenuTagPre: "Förformaterade",
    tagMenuTitle: "Change element style",
    tagTreeElementLink: "Markera {{element}} elementet",
    tagTreeElementTitle: "Klicka här för att markera \"{{element}}\" elementet",
    tagTreeRoot: "root",
    tagTreeRootLink: "Markera alla redigerbara områden",
    tagTreeRootTitle: "Klicka här för att markera allt redigerbart innehåll",
    textBlockQuoteTitle: "Citat",
    textBoldTitle: "Fet",
    textItalicTitle: "Kursiv",
    textSizeDecreaseTitle: "Förminska text",
    textSizeIncreaseTitle: "Öka textstorleken",
    textStrikeTitle: "Genomstryken",
    textSubTitle: "Nedsänkt",
    textSuperTitle: "Upphöjt",
    textUnderlineTitle: "Understryken",
    unsavedEditWarningText: "There are unsaved changes on this page",
    viewSourceDialogCancelButton: "Stäng",
    viewSourceDialogOKButton: "Apply source code",
    viewSourceDialogTitle: "Content source code",
    viewSourceTitle: "View\/edit source code"
});
