/**
 * @fileOverview Thai strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('th', 'ไทย', {
    alignCenterTitle: "จัดกึ่งกลางข้อความ",
    alignJustifyTitle: "จัดตำแหน่งข้อความชิดขอบ",
    alignLeftTitle: "จัดชิดซ้ายข้อความ",
    alignRightTitle: "จัดชิดขวาข้อความ",
    cancelDialogCancelButton: "ดำเนินการแก้ไขต่อไป",
    cancelDialogContent: "คุณต้องการยกเลิกการแก้ไขได้หรือไม่ การเปลี่ยนแปลงทั้งหมดจะหายไป",
    cancelDialogOKButton: "ยกเลิกการแก้ไข",
    cancelDialogTitle: "ยกเลิกการแก้ไข",
    cancelTitle: "ยกเลิกการแก้ไข",
    classMenuTitle: "เลือกลักษณะ",
    clearFormattingTitle: "ล้างการจัดรูปแบบ",
    clickButtonToEditText: "แก้ไข",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "อัตโนมัติ",
    colorMenuBasicBlack: "สีดำ",
    colorMenuBasicBlue: "บลู",
    colorMenuBasicGreen: "กรีน",
    colorMenuBasicGrey: "สีเทา",
    colorMenuBasicOrange: "สีส้ม",
    colorMenuBasicPurple: "สีม่วง",
    colorMenuBasicRed: "สีแดง",
    colorMenuBasicTitle: "เปลี่ยนสีข้อความ",
    colorMenuBasicWhite: "สีขาว",
    dockToElementTitle: "ท่าเรือ\/ชิดแก้ไของค์ประกอบ",
    dockToScreenTitle: "ท่าเรือ\/ชิดตัวแก้ไขหน้าจอ",
    embedDialogCancelButton: "ยกเลิก",
    embedDialogOKButton: "ฝังวัตถุ",
    embedDialogTabCode: "ฝังรหัส",
    embedDialogTabCodeContent: "วางโค้ดของคุณฝังในบริเวณข้อความด้านล่างนี้:",
    embedDialogTabPreview: "ดูตัวอย่าง",
    embedDialogTabPreviewContent: "ตัวอย่างของวัตถุที่ฝังตัวอยู่ด้านล่าง:",
    embedDialogTitle: "ฝังวัตถุ",
    embedTitle: "ฝังวัตถุ",
    errorUINoName: "UI \"{{ui}}\" ไม่ถูกต้อง (ต้องมีคุณสมบัติชื่อ)",
    errorUINotObject: "UI \"{{ui}}\" ไม่ถูกต้อง (ต้องเป็นวัตถุ)",
    errorUIOverride: "UI \"{{name}}\" รับลงทะเบียนแล้ว และจะถูกเขียนทับ",
    fileManagerDialogTitle: "ตัวจัดการแฟ้ม",
    fileManagerTitle: "ตัวจัดการแฟ้ม",
    floatLeftTitle: "จัดตำแหน่งรูปภาพไปทางซ้าย",
    floatNoneTitle: "เอาภาพการจัดตำแหน่ง",
    floatRightTitle: "จัดตำแหน่งรูปภาพทางด้านขวา",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "การ์ตูนไม่มี",
    fontFamilyMenuFontCourier: "พัสดุใหม่",
    fontFamilyMenuFontDefault: "แบบอักษรเริ่มต้น",
    fontFamilyMenuFontGeorgia: "จอร์เจีย",
    fontFamilyMenuFontImpact: "ผลกระทบต่อ",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "เวลาโรมันใหม่",
    fontFamilyMenuTitle: "เลือกแบบอักษรของคุณ",
    guidesTitle: "แสดงองค์ประกอบแผนที่",
    historyRedoTitle: "ทำซ้ำ",
    historyUndoTitle: "เลิกทำ",
    hrCreateTitle: "แทรกเส้นแนวนอน",
    imageResizeButtonDialogCancelButton: "ยกเลิก",
    imageResizeButtonDialogHeight: "ความสูงของรูป",
    imageResizeButtonDialogHeightPlaceHolder: "ความสูง",
    imageResizeButtonDialogOKButton: "การปรับขนาด",
    imageResizeButtonDialogTitle: "ปรับขนาดรูปภาพ",
    imageResizeButtonDialogWidth: "ความกว้างของรูป",
    imageResizeButtonDialogWidthPlaceHolder: "ความกว้าง",
    imageResizeButtonText: "ปรับขนาดรูปภาพ",
    insertFileDialogCancelButton: "ยกเลิก",
    insertFileDialogOKButton: "แทรกแฟ้ม",
    insertFileNameLabel: "ชื่อแฟ้ม",
    insertFileNamePlaceHolder: "ชื่อแฟ้ม...",
    insertFileTitle: "แทรกแฟ้ม",
    insertFileURLLabel: "URL ของแฟ้ม",
    insertFileURLPlaceHolder: "แฟ้ม URL ...",
    languageMenuTitle: "เปลี่ยนภาษา",
    linkCreateDialogCancelButton: "ยกเลิก",
    linkCreateDialogMenuHeader: "เลือกชนิดของลิงค์",
    linkCreateDialogOKButton: "แทรกการเชื่อมโยง",
    linkCreateDialogTitle: "แทรกการเชื่อมโยง",
    linkCreateTitle: "แทรกการเชื่อมโยง",
    linkRemoveTitle: "ลบลิงค์",
    linkTypeDocumentHeader: "เชื่อมโยงไปยังเอกสารหรือแฟ้มอื่น ๆ",
    linkTypeDocumentInfo: "<h2>ไม่แน่ใจที่จะใส่ลงในกล่องข้างต้น<\/h2><ol>    <li>ให้แน่ใจว่า แฟ้มได้ถูกอัปโหลดไปยังเว็บไซต์ของคุณ<\/li>    <li>เปิดแฟ้มอัปโหลดในเบราว์เซอร์ของคุณ<\/li>    <li>คัดลอก URL ของแฟ้มจากแถบอยู่ของเบราว์เซอร์ของคุณ และวางลงในช่องด้านบน<\/li><\/ol>",
    linkTypeDocumentLabel: "เอกสารหรือแฟ้มอื่น ๆ",
    linkTypeDocumentLocationLabel: "สถานที่ตั้ง:",
    linkTypeDocumentLocationPlaceHolder: "ใส่ URL",
    linkTypeDocumentNewWindowHeader: "หน้าต่างใหม่",
    linkTypeDocumentNewWindowLabel: "เลือกกล่องนี้จะมีแฟ้มที่เปิดในเบราว์เซอร์หน้าต่าง\/แท็บใหม่",
    linkTypeEmailHeader: "เชื่อมโยงไปยังที่อยู่อีเมล์",
    linkTypeEmailLabel: "ที่อยู่อีเมล์",
    linkTypeEmailSubjectLabel: "เรื่อง (เลือกได้):",
    linkTypeEmailSubjectPlaceHolder: "ป้อนชื่อเรื่อง",
    linkTypeEmailToLabel: "อีเมล:",
    linkTypeEmailToPlaceHolder: "ป้อนที่อยู่อีเมล์",
    linkTypeExternalHeader: "เชื่อมโยงไปยังหน้าเว็บไซต์อื่น",
    linkTypeExternalInfo: "<h2>ไม่แน่ใจที่จะใส่ลงในกล่องข้างต้น<\/h2><ol>    <li>ค้นหาหน้าเว็บที่คุณต้องการเชื่อมโยง<\/li>    <li>คัดลอกอยู่เว็บจากแถบที่อยู่ของเบราว์เซอร์ของคุณ และวางลงในช่องด้านบน<\/li><\/ol>",
    linkTypeExternalLabel: "หน้าบนเว็บไซต์อื่น",
    linkTypeExternalLocationLabel: "สถานที่ตั้ง:",
    linkTypeExternalLocationPlaceHolder: "ใส่ URL",
    linkTypeExternalNewWindowHeader: "หน้าต่างใหม่",
    linkTypeExternalNewWindowLabel: "เลือกกล่องนี้จะมีการเชื่อมโยงที่เปิดในเบราว์เซอร์หน้าต่าง\/แท็บใหม่",
    linkTypeInternalHeader: "เชื่อมโยงไปยังหน้าเว็บไซต์นี้",
    linkTypeInternalInfo: "<h2>ไม่แน่ใจที่จะใส่ลงในกล่องข้างต้น<\/h2><ol>    <li>พบหน้าเชื่อมโยงกับเว็บไซต์นี้<\/li>    <li>คัดลอกอยู่เว็บจากแถบ ยกเว้น \"{{domain}}\" ที่อยู่ในเบราว์เซอร์ของคุณ และวางลงในช่องด้านบน<\/li><\/ol>",
    linkTypeInternalLabel: "หน้าบนเว็บไซต์นี้",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "ระบุ URI",
    linkTypeInternalNewWindowHeader: "หน้าต่างใหม่",
    linkTypeInternalNewWindowLabel: "เลือกกล่องนี้จะมีการเชื่อมโยงที่เปิดในเบราว์เซอร์หน้าต่าง\/แท็บใหม่",
    listOrderedTitle: "รายการสั่งซื้อ",
    listUnorderedTitle: "โดยปกติ",
    logoTitle: "เรียนรู้เพิ่มเติมเกี่ยวกับ WYSIWYG Editor ของ Raptor",
    loremIpsumTitle: "แทรกข้อความกระพริบสำหรับการทดสอบ",
    navigateAway: "\nมีแปลงหน้านี้ไว้ \nถ้าคุณออกจากหน้านี้ คุณจะสูญเสียการเปลี่ยนแปลงของคุณไม่ได้บันทึก",
    pasteDialogCancelButton: "ยกเลิก",
    pasteDialogFormattedCleaned: "รูปแบบ และการทำความสะอาด",
    pasteDialogFormattedUnclean: "รูปเที่ยว",
    pasteDialogOKButton: "แทรก",
    pasteDialogPlain: "ข้อความล้วน",
    pasteDialogSource: "รหัสแหล่งที่มา",
    pasteDialogTitle: "วาง",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "ไม่สามารถเรียกใช้การปรับปรุง",
    revisionsApplyButtonDialogCancelButton: "ยกเลิก",
    revisionsApplyButtonDialogOKButton: "ย้อนกลับ",
    revisionsApplyButtonDialogTitle: "ย้อนกลับยืนยัน",
    revisionsApplyButtonText: "ย้อนกลับ",
    revisionsApplyButtonTitle: "ย้อนกลับ",
    revisionsApplyDialogContent: "นี้จะแทนเนื้อหาปัจจุบัน ด้วยการปรับปรุงที่เลือก<br>เนื้อหาปัจจุบันจะเพิ่มเป็นการปรับปรุง และจะปรากฏในรายการการปรับปรุงสำหรับบล็อกนี้",
    revisionsButtonCurrent: "ปัจจุบัน",
    revisionsButtonViewDiffText: "ความแตกต่าง",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "สร้าง",
    revisionsDialogCancelButton: "ยกเลิก",
    revisionsDialogTitle: "ดูการปรับปรุงเนื้อหา",
    revisionsDiffButtonDialogCancelButton: "ปิด",
    revisionsDiffButtonDialogTitle: "ดูความแตกต่าง",
    revisionsDiffButtonText: "ดูความแตกต่าง",
    revisionsDiffButtonTitle: "ดูความแตกต่าง",
    revisionsLoading: "โหลดปรับปรุง...",
    revisionsNone: "การปรับปรุงสำหรับองค์ประกอบนี้",
    revisionsPreviewButtonText: "ดูตัวอย่าง",
    revisionsPreviewButtonTitle: "ดูตัวอย่าง",
    revisionsText: "การปรับปรุง",
    revisionsTextEmpty: "ไม่ปรับปรุง",
    revisionsTitle: "",
    rfmClose: "ปิด",
    rfmContinue: "ดำเนินการต่อไป",
    rfmDelete: "ลบ",
    rfmDownload: "ดาวน์โหลด",
    rfmFileActions: "การดำเนินการ",
    rfmFileModificationTime: "การปรับเปลี่ยน",
    rfmFileName: "ชื่อ",
    rfmFileSize: "ขนาด",
    rfmFileType: "ชนิด",
    rfmFilteredTotal: "แสดง {{start}} {{end}} {{filteredTotal}} แฟ้ม",
    rfmFirst: "ครั้งแรก",
    rfmHeadingDirectories: "ไดเรกทอรี",
    rfmHeadingSearch: "ค้นหา",
    rfmHeadingTags: "แท็ก",
    rfmHeadingUpload: "อัปโหลด",
    rfmInsert: "แทรก",
    rfmLast: "ล่าสุด",
    rfmSearch: "ไป",
    rfmTagDocument: "เอกสาร",
    rfmTagImage: "รูปภาพ",
    rfmTotal: "กรองจาก {{total}}",
    rfmUpload: "อัปโหลด",
    rfmUploadBrowse: "เรียกดู",
    rfmUploadDrop: "วางไฟล์ที่นี่",
    rfmUploadFileRemove: "เอาออก",
    rfmUploadOr: "หรือ",
    rfmView: "ดู",
    saveJsonFail: "ไม่สามารถบันทึกเนื้อหา block(s) {{failed}}",
    saveJsonSaved: "บันทึกเนื้อหา block(s) {{saved}} เรียบร้อยแล้ว",
    saveNotConfigured: "บันทึกไม่ได้รับการกำหนดค่า หรือถูกปิดใช้งาน",
    saveRestFail: "ไม่สามารถบันทึกเนื้อหา block(s) {{failed}}",
    saveRestPartial: "บันทึก {{saved}} จากบล็อกเนื้อหาไม่ {{failed}}",
    saveRestSaved: "บันทึกเนื้อหา block(s) {{saved}} เรียบร้อยแล้ว",
    saveTitle: "บันทึกเนื้อหา",
    snippetMenuTitle: "โค้ด",
    specialCharactersArrows: "ลูกศร",
    specialCharactersDialogOKButton: "ตกลง, ได้",
    specialCharactersDialogTitle: "แทรกอักขระพิเศษ",
    specialCharactersGreekAlphabet: "อักษรกรีก",
    specialCharactersHelp: "คลิกเพื่อเพิ่มอักขระพิเศษ คลิก \"ตกลง\" เมื่อเสร็จสิ้นเพื่อปิดกล่องโต้ตอบนี้",
    specialCharactersMathematics: "คณิตศาสตร์",
    specialCharactersSymbols: "สัญลักษณ์",
    specialCharactersTitle: "แทรกอักขระพิเศษ",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} อักขระเกินกว่า",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} อักขระที่เหลือ",
    statisticsButtonCharacters: "อักขระ {{characters}}",
    statisticsDialogCharactersOverLimit: "{{characters}} อักขระ, {{charactersRemaining}} มากกว่าขีดจำกัดแนะนำ",
    statisticsDialogCharactersRemaining: "อักขระ {{characters}}, {{charactersRemaining}} ที่เหลือ",
    statisticsDialogNotTruncated: "เนื้อหาจะไม่ถูกตัด",
    statisticsDialogOKButton: "ตกลง, ได้",
    statisticsDialogSentence: "ประโยค {{sentences}}",
    statisticsDialogSentences: "ประโยค {{sentences}}",
    statisticsDialogTitle: "เนื้อหาสถิติ",
    statisticsDialogTruncated: "เนื้อหาประกอบด้วยมากกว่าตัว {{limit}} และอาจถูกตัดทอน",
    statisticsDialogWord: "{{words}} คำ",
    statisticsDialogWords: "{{words}} หา",
    statisticsTitle: "คลิกเพื่อดูสถิติ",
    tableCreateTitle: "สร้างตาราง",
    tableDeleteColumnTitle: "ลบคอลัมน์ในตาราง",
    tableDeleteRowTitle: "ลบแถวของตาราง",
    tableInsertColumnTitle: "แทรกคอลัมน์ตาราง",
    tableInsertRowTitle: "แทรกแถวตาราง",
    tableMergeCellsTitle: "ผสานเซลล์ตาราง",
    tableSplitCellsTitle: "แบ่งเซลล์",
    tagMenuTagAddress: "ที่อยู่",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "หัวเรื่อง 1",
    tagMenuTagH2: "หัวข้อ 2",
    tagMenuTagH3: "หัวข้อ 3",
    tagMenuTagH4: "หัวข้อ 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "ย่อหน้า",
    tagMenuTagPre: "จัดรูปแบบไว้ล่วงหน้า",
    tagMenuTitle: "เปลี่ยนลักษณะองค์ประกอบ",
    tagTreeElementLink: "เลือกองค์ประกอบ {{element}}",
    tagTreeElementTitle: "คลิกเพื่อเลือกเนื้อหาขององค์ประกอบ \"{{element}}\"",
    tagTreeRoot: "ราก",
    tagTreeRootLink: "เลือกเนื้อหาทั้งหมดสามารถแก้ไขได้",
    tagTreeRootTitle: "คลิกเพื่อเลือกเนื้อหาทั้งหมดสามารถแก้ไขได้",
    textBlockQuoteTitle: "บล็อกใบเสนอราคา",
    textBoldTitle: "ตัวหนา",
    textItalicTitle: "ตัวเอียง",
    textSizeDecreaseTitle: "ลดขนาดข้อความ",
    textSizeIncreaseTitle: "เพิ่มขนาดข้อความ",
    textStrikeTitle: "ตีผ่าน",
    textSubTitle: "สคริปต์ย่อย",
    textSuperTitle: "ซุปเปอร์สคริปต์",
    textUnderlineTitle: "ขีดเส้นใต้",
    unsavedEditWarningText: "มีแปลงที่หน้านี้",
    viewSourceDialogCancelButton: "ปิด",
    viewSourceDialogOKButton: "ใช้รหัสแหล่งที่มา",
    viewSourceDialogTitle: "รหัสแหล่งที่มาเนื้อหา",
    viewSourceTitle: "ดูหรือแก้ไขรหัสแหล่งที่มา"
});