/**
 * @fileOverview Turkish strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('tr', 'Türkçe', {
    alignCenterTitle: "Metin Hizala",
    alignJustifyTitle: "Metin hizalama haklı",
    alignLeftTitle: "Metni Sola Hizala",
    alignRightTitle: "Metni Sağa Hizala",
    cancelDialogCancelButton: "Düzenlemeye devam",
    cancelDialogContent: "Düzenlemeyi iptal etmek istediğinizden emin misiniz? Tüm değişiklikler kaybolacak.",
    cancelDialogOKButton: "Düzenlemeyi iptal et",
    cancelDialogTitle: "Düzenlemeyi iptal et",
    cancelTitle: "Düzenlemeyi iptal et",
    classMenuTitle: "Stil seçicisini",
    clearFormattingTitle: "Biçimlendirmeyi Temizle",
    clickButtonToEditText: "Düzenle",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Otomatik",
    colorMenuBasicBlack: "Siyah",
    colorMenuBasicBlue: "Mavi",
    colorMenuBasicGreen: "Yeşil",
    colorMenuBasicGrey: "Gri",
    colorMenuBasicOrange: "Turuncu",
    colorMenuBasicPurple: "Mor",
    colorMenuBasicRed: "Kırmızı",
    colorMenuBasicTitle: "Metin rengini değiştirme",
    colorMenuBasicWhite: "Beyaz",
    dockToElementTitle: "Rıhtım\/yuvadan editörü öğesi",
    dockToScreenTitle: "Dock yuvadan\/Editör ekranına",
    embedDialogCancelButton: "İptal",
    embedDialogOKButton: "Nesneyi katıştırma",
    embedDialogTabCode: "Embed kodu",
    embedDialogTabCodeContent: "Embed kodu ve metin alanına yapıştırın:",
    embedDialogTabPreview: "Önizleme",
    embedDialogTabPreviewContent: "Önizleme katıştırılmış nesnenin altında görüntülenir:",
    embedDialogTitle: "Nesneyi katıştırma",
    embedTitle: "Nesneyi katıştırma",
    errorUINoName: "UI \"{{ui}}\" geçersiz (name özelliği olması gerekir)",
    errorUINotObject: "UI \"{{ui}}\" geçersiz (bir nesne olması gerekir)",
    errorUIOverride: "UI \"{{name}}\" zaten kayıtlı ve üzerine yazılır.",
    fileManagerDialogTitle: "Dosya Yöneticisi",
    fileManagerTitle: "Dosya Yöneticisi",
    floatLeftTitle: "Resmi sola hizala",
    floatNoneTitle: "Resmi kaldırma hizalamak",
    floatRightTitle: "Resim sağa hizalama",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Çizgi olmadan",
    fontFamilyMenuFontCourier: "Kurye yeni",
    fontFamilyMenuFontDefault: "Varsayılan yazı tipi",
    fontFamilyMenuFontGeorgia: "Gürcistan",
    fontFamilyMenuFontImpact: "Etkisi",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Times New Roman",
    fontFamilyMenuTitle: "Yazı tipi seç",
    guidesTitle: "Öğe kılavuzları göster",
    historyRedoTitle: "Yinele",
    historyUndoTitle: "Geri alma",
    hrCreateTitle: "Yatay çizgi ekle",
    imageResizeButtonDialogCancelButton: "İptal",
    imageResizeButtonDialogHeight: "Resim yüksekliği",
    imageResizeButtonDialogHeightPlaceHolder: "Yükseklik",
    imageResizeButtonDialogOKButton: "Yeniden boyutlandırma",
    imageResizeButtonDialogTitle: "Resim yeniden boyutlandırma",
    imageResizeButtonDialogWidth: "Resim genişliği",
    imageResizeButtonDialogWidthPlaceHolder: "Genişlik",
    imageResizeButtonText: "Resim yeniden boyutlandırma",
    insertFileDialogCancelButton: "İptal",
    insertFileDialogOKButton: "Dosya Ekle",
    insertFileNameLabel: "Dosya adı",
    insertFileNamePlaceHolder: "Dosya adı...",
    insertFileTitle: "Dosya Ekle",
    insertFileURLLabel: "URL dosya",
    insertFileURLPlaceHolder: "URL dosya...",
    languageMenuTitle: "Dili Değiştir",
    linkCreateDialogCancelButton: "İptal",
    linkCreateDialogMenuHeader: "Bir bağlantı türü seçin",
    linkCreateDialogOKButton: "Bağlantı Ekle",
    linkCreateDialogTitle: "Bağlantı Ekle",
    linkCreateTitle: "Bağlantı Ekle",
    linkRemoveTitle: "Bağlantıyı Kaldır",
    linkTypeDocumentHeader: "Bir belge veya başka bir dosyaya bağlantı",
    linkTypeDocumentInfo: "<h2>Değil emin ne Yukarıdaki kutuya koymak?<\/h2><ol>    <li>Dosya, Web sitenize karşıya emin olun.<\/li>    <li>Karşıya yüklenen dosyayı tarayıcınızda açın.<\/li>    <li>Tarayıcınızın adres çubuğundan dosyasının URL'sini kopyalayın ve Yukarıdaki kutuya yapıştırın.<\/li><\/ol>",
    linkTypeDocumentLabel: "Belge veya diğer dosya",
    linkTypeDocumentLocationLabel: "Yer:",
    linkTypeDocumentLocationPlaceHolder: "Bir URL girin",
    linkTypeDocumentNewWindowHeader: "Yeni pencere",
    linkTypeDocumentNewWindowLabel: "Bir tarayıcı penceresi\/açık içinde yeni etiket dosya için bu kutuyu işaretleyin.",
    linkTypeEmailHeader: "Bir e-posta adresine bağlantı",
    linkTypeEmailLabel: "E-posta adresi",
    linkTypeEmailSubjectLabel: "Konu (isteğe bağlı):",
    linkTypeEmailSubjectPlaceHolder: "Konu girin",
    linkTypeEmailToLabel: "E-posta:",
    linkTypeEmailToPlaceHolder: "E-posta adresinizi girin",
    linkTypeExternalHeader: "Başka bir Web sayfasına bağlantı",
    linkTypeExternalInfo: "<h2>Değil emin ne Yukarıdaki kutuya koymak?<\/h2><ol>    <li>Bağlantı kurmak istediğiniz Web sayfası bulabilirsiniz.<\/li>    <li>Web adresi tarayıcınızın adres çubuğundan kopyalayın ve Yukarıdaki kutuya yapıştırın.<\/li><\/ol>",
    linkTypeExternalLabel: "Başka bir Web sayfasında",
    linkTypeExternalLocationLabel: "Yer:",
    linkTypeExternalLocationPlaceHolder: "Bir URL girin",
    linkTypeExternalNewWindowHeader: "Yeni pencere",
    linkTypeExternalNewWindowLabel: "Bir tarayıcı penceresi\/açık içinde yeni etiket bağlantı için bu kutuyu işaretleyin.",
    linkTypeInternalHeader: "Bu Web sayfasına bağlantı",
    linkTypeInternalInfo: "<h2>Değil emin ne Yukarıdaki kutuya koymak?<\/h2><ol>    <li>Sayfayı bu site bağlantısını bulun.<\/li>    <li>Tarayıcınızın adres çubuğu \"{{domain}}\" hariç olmak üzere web adresini kopyalayın ve Yukarıdaki kutuya yapıştırın.<\/li><\/ol>",
    linkTypeInternalLabel: "Bu Web sayfası",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "URL girin",
    linkTypeInternalNewWindowHeader: "Yeni pencere",
    linkTypeInternalNewWindowLabel: "Bir tarayıcı penceresi\/açık içinde yeni etiket bağlantı için bu kutuyu işaretleyin.",
    listOrderedTitle: "Sıralı liste",
    listUnorderedTitle: "Sırasız liste",
    logoTitle: "Raptor WYSIWYG Düzenleyicisi hakkında daha fazla bilgi edinin",
    loremIpsumTitle: "Test dummy metin ekleme",
    navigateAway: "\nBu sayfada kaydedilmemiş değişiklikler. \nBu sayfadan ayrılırsanız kaydedilmemiş değişiklikleriniz kaybolur.",
    pasteDialogCancelButton: "İptal",
    pasteDialogFormattedCleaned: "Biçimlendirilmiş &amp; temizlik",
    pasteDialogFormattedUnclean: "Pis biçimlendirilmiş",
    pasteDialogOKButton: "Ekle",
    pasteDialogPlain: "Düz metin",
    pasteDialogSource: "Kaynak kodu",
    pasteDialogTitle: "Yapıştır",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Revizyonlar alınamadı",
    revisionsApplyButtonDialogCancelButton: "İptal",
    revisionsApplyButtonDialogOKButton: "Geri alma",
    revisionsApplyButtonDialogText: "Geri alma onayı",
    revisionsApplyButtonDialogTitle: "Geri alma onayı",
    revisionsApplyButtonText: "Geri alma",
    revisionsApplyButtonTitle: "Geri alma",
    revisionsApplyDialogContent: "Bu seçilen revizyonu ile geçerli içeriğin yerini alır.<br>Geçerli içerik bir revizyon eklenir ve bu bloğun düzeltmeler listesinde görünecektir.",
    revisionsButtonCurrent: "Akım",
    revisionsButtonViewDiffText: "Farklılıklar",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "Oluşturulan",
    revisionsDialogCancelButton: "İptal",
    revisionsDialogTitle: "Görünümü içerik düzeltme",
    revisionsDiffButtonDialogCancelButton: "Kapat",
    revisionsDiffButtonDialogTitle: "Görüş farklılıkları",
    revisionsDiffButtonText: "Görüş farklılıkları",
    revisionsDiffButtonTitle: "Görüş farklılıkları",
    revisionsLoading: "Revizyon yükleniyor...",
    revisionsNone: "Bu öğe hiçbir düzeltme",
    revisionsPreviewButtonText: "Önizleme",
    revisionsPreviewButtonTitle: "Önizleme",
    revisionsText: "Düzeltmeleri",
    revisionsTextEmpty: "Hiçbir düzeltme",
    revisionsTitle: "",
    rfmClose: "Kapat",
    rfmContinue: "Devam etmek",
    rfmDelete: "Sil",
    rfmDownload: "Download",
    rfmFileActions: "Eylemler",
    rfmFileModificationTime: "Değiştirilme tarihi",
    rfmFileName: "Adı",
    rfmFileSize: "Boyutu",
    rfmFileType: "Türü",
    rfmFilteredTotal: "{{start}} gösteren {{end}} {{filteredTotal}} dosya",
    rfmFirst: "İlk",
    rfmHeadingDirectories: "Dizinleri",
    rfmHeadingSearch: "Arama",
    rfmHeadingTags: "Etiketler",
    rfmHeadingUpload: "Karşıya yükleme",
    rfmInsert: "Ekle",
    rfmLast: "Son",
    rfmSearch: "Git",
    rfmTagDocument: "Belge",
    rfmTagImage: "Görüntü",
    rfmTotal: ", {{total}} filtre",
    rfmUpload: "Karşıya yükleme",
    rfmUploadBrowse: "Gözat",
    rfmUploadDrop: "Dosyaları buraya bırakın",
    rfmUploadFileRemove: "Kaldır",
    rfmUploadOr: "ya da",
    rfmView: "Görünüm",
    saveJsonFail: "{{failed}} içerik block(s) kaydedilemedi",
    saveJsonSaved: "{{saved}} içerik block(s) ba├╛ar├╜yla kaydedildi.",
    saveNotConfigured: "Kaydet, yapılandırılmamış veya devre dışı bırakılır.",
    saveRestFail: "{{failed}} içerik block(s) kaydedilemedi.",
    saveRestPartial: "{{saved}} {{failed}} içerik blokları dışında kurtardı.",
    saveRestSaved: "{{saved}} içerik block(s) ba├╛ar├╜yla kaydedildi.",
    saveTitle: "İçerik kaydetmek",
    snippetMenuTitle: "Parçacıkları",
    specialCharactersArrows: "Oklar",
    specialCharactersDialogOKButton: "Tamam",
    specialCharactersDialogTitle: "Özel karakterler eklemek",
    specialCharactersGreekAlphabet: "Yunan Alfabesi",
    specialCharactersHelp: "Özel bir karakter eklemek için tıklatın. Bu iletişim kutusunu kapatmak için ne zaman bitmiş tıkırtı \"OK\"",
    specialCharactersMathematics: "Matematik",
    specialCharactersSymbols: "Sembolleri",
    specialCharactersTitle: "Özel bir karakter ekleme",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} karakter sınırı üzerinde",
    statisticsButtonCharacterRemaining: "kalan {{charactersRemaining}} karakter sayısı",
    statisticsButtonCharacters: "{{characters}} karakterleri",
    statisticsDialogCharactersOverLimit: "{{characters}} karakterleri, {{charactersRemaining}} üzerinde önerilen limit",
    statisticsDialogCharactersRemaining: "{{characters}} kalan karakter sayısı, {{charactersRemaining}}",
    statisticsDialogNotTruncated: "İçerik kesilecek değil",
    statisticsDialogOKButton: "Tamam",
    statisticsDialogSentence: "{{sentences}} cümle",
    statisticsDialogSentences: "{{sentences}} cümleler",
    statisticsDialogTitle: "İçerik istatistikleri",
    statisticsDialogTruncated: "İçerik {{limit}} karakterden fazlasını içeren ve kesilebilir",
    statisticsDialogWord: "{{words}} kelime",
    statisticsDialogWords: "{{words}} sözcükleri",
    statisticsTitle: "İstatistiklerini görüntülemek için tıklatın",
    tableCreateTitle: "Tablo oluşturma",
    tableDeleteColumnTitle: "Tablo sütun sil",
    tableDeleteRowTitle: "Tablo satır Sil",
    tableInsertColumnTitle: "Tablo sütunu Ekle",
    tableInsertRowTitle: "Tablo satırı ekle",
    tableMergeCellsTitle: "Tabloda hücreleri birleştirme",
    tableSplitCellsTitle: "Tablo hücrelerini bölme",
    tagMenuTagAddress: "Adres",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Başlık 1",
    tagMenuTagH2: "Başlık 2",
    tagMenuTagH3: "Başlık 3",
    tagMenuTagH4: "Başlık 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Paragraf",
    tagMenuTagPre: "Önceden biçimlendirilmiş",
    tagMenuTitle: "Öğe stili değiştirme",
    tagTreeElementLink: "{{element}} Öğesi öğesini seçin",
    tagTreeElementTitle: "\"{{element}} Öğesi\" öğesinin içeriği seçmek için tıklatın",
    tagTreeRoot: "kök",
    tagTreeRootLink: "Tüm düzenlenebilir içeriğini seçin",
    tagTreeRootTitle: "Tüm düzenlenebilir içerik seçmek için tıklatın",
    textBlockQuoteTitle: "Blok alıntı",
    textBoldTitle: "Kalın",
    textItalicTitle: "İtalik",
    textSizeDecreaseTitle: "Metin boyutunu azalt",
    textSizeIncreaseTitle: "Metin boyutunu Artır",
    textStrikeTitle: "Üstü Çizgili",
    textSubTitle: "Alt komut dosyası",
    textSuperTitle: "Süper script",
    textUnderlineTitle: "Alt çizgi",
    unsavedEditWarningText: "Bu sayfada kaydedilmemiş değişiklikler",
    viewSourceDialogCancelButton: "Kapat",
    viewSourceDialogOKButton: "Kaynak kodu uygulamak",
    viewSourceDialogTitle: "İçerik kaynak kodu",
    viewSourceTitle: "Görünüm\/kaynak kodunu düzenle"
});