/**
 * @fileOverview Ukrainian strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('uk', 'українська', {
    alignCenterTitle: "Вирівняти текст по центру",
    alignJustifyTitle: "Вирівняти текст виправдати",
    alignLeftTitle: "Вирівняти текст зліва",
    alignRightTitle: "Вирівняти текст справа",
    cancelDialogCancelButton: "Продовжити редагування",
    cancelDialogContent: "Ви дійсно бажаєте скасувати змінення? Всі зміни буде втрачено!",
    cancelDialogOKButton: "Відмінити редагування",
    cancelDialogTitle: "Відмінити редагування",
    cancelTitle: "Відмінити редагування",
    classMenuTitle: "Стиль палітра",
    clearFormattingTitle: "Зняти форматування",
    clickButtonToEditText: "Редагувати",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Автоматичні",
    colorMenuBasicBlack: "Чорний",
    colorMenuBasicBlue: "Синій",
    colorMenuBasicGreen: "Грін",
    colorMenuBasicGrey: "Ґрей",
    colorMenuBasicOrange: "Помаранчевий",
    colorMenuBasicPurple: "Пурпурний колір",
    colorMenuBasicRed: "Червоний",
    colorMenuBasicTitle: "Зміна кольору тексту",
    colorMenuBasicWhite: "Білий",
    dockToElementTitle: "Док-станція\/Відстикувати редактору елемент",
    dockToScreenTitle: "Док-станція\/Відстикувати редактор екран",
    embedDialogCancelButton: "\"Скасувати\"",
    embedDialogOKButton: "Вбудувати об'єкт",
    embedDialogTabCode: "Код вставлення",
    embedDialogTabCodeContent: "Вставити вставляти код у текстовій області знизу:",
    embedDialogTabPreview: "Попередній перегляд",
    embedDialogTabPreviewContent: "Попередній перегляд впровадженого об'єкта відображаються нижче:",
    embedDialogTitle: "Вбудувати об'єкт",
    embedTitle: "Вбудувати об'єкт",
    errorUINoName: "UI \"{{ui}}\" є неприпустимим (повинен мати ім'я властивості)",
    errorUINotObject: "UI \"{{ui}}\" є неприпустимим (повинні бути об'єктом)",
    errorUIOverride: "UI \"{{name}}\" уже зареєстровано і буде перезаписаний",
    fileManagerDialogTitle: "Файловий менеджер",
    fileManagerTitle: "Файловий менеджер",
    floatLeftTitle: "Вирівнювання зображення ліворуч",
    floatNoneTitle: "Видалити зображення Вирівняти",
    floatRightTitle: "Вирівнювання зображення праворуч",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Комічного без",
    fontFamilyMenuFontCourier: "Кур'єр нові",
    fontFamilyMenuFontDefault: "Шрифт за промовчанням",
    fontFamilyMenuFontGeorgia: "Грузія",
    fontFamilyMenuFontImpact: "Вплив",
    fontFamilyMenuFontPalatino: "Палатін",
    fontFamilyMenuFontTimes: "Нові римських часів",
    fontFamilyMenuTitle: "Оберіть розмір шрифту",
    guidesTitle: "Відображати елемент вказівки",
    historyRedoTitle: "Повторити",
    historyUndoTitle: "Скасувати",
    hrCreateTitle: "Вставлення горизонтальної правило",
    imageResizeButtonDialogCancelButton: "\"Скасувати\"",
    imageResizeButtonDialogHeight: "Висота зображення",
    imageResizeButtonDialogHeightPlaceHolder: "Висота",
    imageResizeButtonDialogOKButton: "Змінити розмір",
    imageResizeButtonDialogTitle: "Зміна розміру зображення",
    imageResizeButtonDialogWidth: "Ширина зображення",
    imageResizeButtonDialogWidthPlaceHolder: "Ширина",
    imageResizeButtonText: "Зміна розміру зображення",
    insertFileDialogCancelButton: "\"Скасувати\"",
    insertFileDialogOKButton: "Вставити файл",
    insertFileNameLabel: "Ім'я файлу",
    insertFileNamePlaceHolder: "Ім'я файлу...",
    insertFileTitle: "Вставити файл",
    insertFileURLLabel: "URL-адреса файлу",
    insertFileURLPlaceHolder: "URL-адреса файлу...",
    languageMenuTitle: "Змінити мову",
    linkCreateDialogCancelButton: "\"Скасувати\"",
    linkCreateDialogMenuHeader: "Виберіть тип посилання",
    linkCreateDialogOKButton: "Вставити посилання",
    linkCreateDialogTitle: "Вставити посилання",
    linkCreateTitle: "Вставити посилання",
    linkRemoveTitle: "Видалити посилання",
    linkTypeDocumentHeader: "Посилання на документ або інший файл",
    linkTypeDocumentInfo: "<h2>Не впевнений, що покласти в розташованому вище полі?<\/h2><ol>    <li>Переконайтеся, що файл був завантажений на ваш сайт.<\/li>    <li>Відкрити завантажений файл у веб-переглядачі.<\/li>    <li>Скопіювати його URL-адресу з рядку вашого браузера і вставте його в розташованому вище полі.<\/li><\/ol>",
    linkTypeDocumentLabel: "Документ або інший файл",
    linkTypeDocumentLocationLabel: "Розташування:",
    linkTypeDocumentLocationPlaceHolder: "Введіть URL-адресу",
    linkTypeDocumentNewWindowHeader: "Нове вікно",
    linkTypeDocumentNewWindowLabel: "Позначте цей пункт, щоб мати файл відкрити в новому вікні\/вкладці браузера.",
    linkTypeEmailHeader: "Посилання на адресу електронної пошти",
    linkTypeEmailLabel: "Адреса електронної пошти",
    linkTypeEmailSubjectLabel: "Тема (необов'язково):",
    linkTypeEmailSubjectPlaceHolder: "Введіть тему",
    linkTypeEmailToLabel: "Електронна пошта:",
    linkTypeEmailToPlaceHolder: "Введіть адресу електронної пошти",
    linkTypeExternalHeader: "Посилання на сторінку на інший веб-сайт",
    linkTypeExternalInfo: "<h2>Не впевнений, що покласти в розташованому вище полі?<\/h2><ol>    <li>Знайти сторінки в Інтернеті, вам потрібно зв'язати.<\/li>    <li>Скопіювати веб-адресу з рядку адреси вашого браузера і вставте його в розташованому вище полі.<\/li><\/ol>",
    linkTypeExternalLabel: "Сторінка на інший веб-сайт",
    linkTypeExternalLocationLabel: "Розташування:",
    linkTypeExternalLocationPlaceHolder: "Введіть URL-адресу",
    linkTypeExternalNewWindowHeader: "Нове вікно",
    linkTypeExternalNewWindowLabel: "Позначте цей пункт, щоб посилання відкрити в новому вікні\/вкладці браузера.",
    linkTypeInternalHeader: "Посилання на сторінку на цьому сайті",
    linkTypeInternalInfo: "<h2>Не впевнений, що покласти в розташованому вище полі?<\/h2><ol>    <li>Цей сайт посилання, щоб знайти сторінки.<\/li>    <li>Скопіювати веб-адресу зі свого веб-переглядача адресного рядка, за винятком \"{{domain}}\" і вставте його в розташованому вище полі.<\/li><\/ol>",
    linkTypeInternalLabel: "Сторінок на цьому сайті",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Введіть URI",
    linkTypeInternalNewWindowHeader: "Нове вікно",
    linkTypeInternalNewWindowLabel: "Позначте цей пункт, щоб посилання відкрити в новому вікні\/вкладці браузера.",
    listOrderedTitle: "Впорядкований список",
    listUnorderedTitle: "Неупорядкований список",
    logoTitle: "Дізнайтеся більше про Raptor WYSIWYG редактор",
    navigateAway: "\nНа цій сторінці є незбережені зміни. \nЯкщо залишити цю сторінку незбережені зміни буде втрачено",
    pasteDialogCancelButton: "\"Скасувати\"",
    pasteDialogFormattedCleaned: "Формат &amp; чистити",
    pasteDialogFormattedUnclean: "Відформатовані нечистого",
    pasteDialogOKButton: "Вставте",
    pasteDialogPlain: "Звичайний текст",
    pasteDialogSource: "Вихідний код",
    pasteDialogTitle: "Пасти",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Не вдалося отримати зміни",
    revisionsApplyButtonDialogCancelButton: "\"Скасувати\"",
    revisionsApplyButtonDialogOKButton: "Відкат",
    revisionsApplyButtonDialogTitle: "Підтвердження скасування установки",
    revisionsApplyButtonTitle: "Відкат",
    revisionsApplyDialogContent: "Це буде замінити поточний вміст виділеного редакція.<br>Поточний зміст буде додано як виправлену версію і буде показано у списку доопрацювання цей блок.",
    revisionsButtonCurrent: "Струм",
    revisionsButtonViewDiffText: "Відмінності",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "\"Скасувати\"",
    revisionsDialogTitle: "Перегляд вмісту зміни",
    revisionsDiffButtonDialogCancelButton: "Закрити",
    revisionsDiffButtonDialogTitle: "Перегляд відмінності",
    revisionsDiffButtonTitle: "Перегляд відмінності",
    revisionsLoading: "Завантаження виправлення...",
    revisionsNone: "Немає виправлення для цього елемента.",
    revisionsPreviewButtonTitle: "Попередній перегляд",
    revisionsText: "Доопрацювання",
    revisionsTextEmpty: "Не змін",
    revisionsTitle: "",
    rfmClose: "Закрити",
    rfmContinue: "Продовжити",
    rfmDelete: "Видалити",
    rfmDownload: "Завантажити",
    rfmFileActions: "Дії",
    rfmFileModificationTime: "Змінено",
    rfmFileName: "Ім’я",
    rfmFileSize: "Розмір",
    rfmFileType: "Тип",
    rfmFilteredTotal: "Показ {{start}} {{end}} {{filteredTotal}} файлів",
    rfmFirst: "Перший",
    rfmHeadingDirectories: "Каталоги",
    rfmHeadingSearch: "Пошук",
    rfmHeadingTags: "Мітки",
    rfmHeadingUpload: "Завантажити",
    rfmInsert: "Вставте",
    rfmLast: "Останнє",
    rfmSearch: "Піти",
    rfmTotal: ", фільтрується від {{total}}",
    rfmUpload: "Завантажити",
    rfmUploadBrowse: "Огляд",
    rfmUploadDrop: "Перетягніть файли сюди",
    rfmUploadFileRemove: "Видалити",
    rfmView: "Подання",
    saveJsonFail: "Не вдалося зберегти {{failed}} вмісту block(s)",
    saveJsonSaved: "Успішно збережено {{saved}} вмісту block(s).",
    saveNotConfigured: "Зберегти не настроєно, або вимкнуто.",
    saveRestFail: "Не вдалося зберегти {{failed}} вмісту block(s).",
    saveRestPartial: "Збережені {{saved}} з {{failed}} вмісту блоків.",
    saveRestSaved: "Успішно збережено {{saved}} вмісту block(s).",
    saveTitle: "Зберегти вміст",
    snippetMenuTitle: "Фрагменти",
    specialCharactersDialogOKButton: "Гаразд",
    specialCharactersDialogTitle: "Вставлення спеціальних символів",
    specialCharactersHelp: "Натисніть кнопку спеціальний символ, щоб додати його. Натисніть кнопку \"OK\" по завершенні закрити це діалогове вікно",
    specialCharactersTitle: "Вставити спеціальний символ",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} символів за обмеження",
    statisticsButtonCharacterRemaining: "залишилося знаків {{charactersRemaining}}",
    statisticsButtonCharacters: "{{characters}} символів",
    statisticsDialogCharactersOverLimit: "{{characters}} символів, {{charactersRemaining}} над рекомендованою межею",
    statisticsDialogCharactersRemaining: "{{characters}}, {{charactersRemaining}} лишилося знаків",
    statisticsDialogNotTruncated: "Вміст не буде скорочено",
    statisticsDialogOKButton: "Гаразд",
    statisticsDialogSentence: "{{sentences}} речення",
    statisticsDialogSentences: "{{sentences}} речень",
    statisticsDialogTitle: "Зміст статистика",
    statisticsDialogTruncated: "Зміст містить більше символів {{limit}} і може бути скорочено",
    statisticsDialogWord: "{{words}} слово",
    statisticsDialogWords: "{{words}} слів",
    statisticsTitle: "Натисніть, щоб подивитися статистику",
    tableCreateTitle: "Створення таблиці",
    tableDeleteColumnTitle: "Видалити стовпці таблиці",
    tableDeleteRowTitle: "Видалити рядок таблиці",
    tableInsertColumnTitle: "Вставити стовпець таблиці",
    tableInsertRowTitle: "Вставити рядок таблиці",
    tableMergeCellsTitle: "Об'єднування декількох клітинок таблиці",
    tableSplitCellsTitle: "Розділити клітинки таблиці",
    tagMenuTagAddress: "Адреса",
    tagMenuTagDiv: "DIV",
    tagMenuTagH1: "Заголовок 1",
    tagMenuTagH2: "Заголовок 2",
    tagMenuTagH3: "Заголовок 3",
    tagMenuTagH4: "Заголовок 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Абзац",
    tagMenuTagPre: "Попередньо відформатований",
    tagMenuTitle: "Змінити стиль елемента",
    tagTreeElementLink: "Виберіть елемент {{element}}",
    tagTreeElementTitle: "Натисніть, щоб виділити вміст елемента «{{element}}»",
    tagTreeRoot: "корінь",
    tagTreeRootLink: "Виділіть весь вміст для редагування",
    tagTreeRootTitle: "Натисніть, щоб вибрати весь вміст для редагування",
    textBlockQuoteTitle: "Блок (цитата)",
    textBoldTitle: "Жирним шрифтом",
    textItalicTitle: "Курсив",
    textSizeDecreaseTitle: "Зменшити розмір тексту",
    textSizeIncreaseTitle: "Збільшити розмір тексту",
    textStrikeTitle: "Перекреслити",
    textSubTitle: "Суб сценарій",
    textSuperTitle: "Супер-сценарій",
    textUnderlineTitle: "Підкреслення",
    unsavedEditWarningText: "Виявлено незбереженні зміни на цій сторінці",
    viewSourceDialogCancelButton: "Закрити",
    viewSourceDialogOKButton: "Застосувати вихідний код",
    viewSourceDialogTitle: "Код джерела вмісту",
    viewSourceTitle: "Перегляд або змінення вихідного коду"
});