/**
 * @fileOverview Urdu strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('ur', 'اردو', {
    alignCenterTitle: "متن کو بمرکز سیدھ کریں",
    alignJustifyTitle: "متن سیدھ کریں سطربند کریں",
    alignLeftTitle: "متن بائیں سیدھ کریں",
    alignRightTitle: "متن دائیں سیدھ میں لائیں",
    cancelDialogCancelButton: "تدوین کاری جاری رکھیں",
    cancelDialogContent: "اثبات کریں کہ آپ تدوین کرنے کے لیے منسوخ کرنا چاہتے ہیں؟ تمام تبدیلیاں ضائع ہو جائیں گے!",
    cancelDialogOKButton: "تدوین منسوخ کریں",
    cancelDialogTitle: "تدوین منسوخ کریں",
    cancelTitle: "تدوین منسوخ کریں",
    classMenuTitle: "طرز چنندہ",
    clearFormattingTitle: "وضع کاری صاف کریں",
    clickButtonToEditText: "تدوین کریں",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "خود کار",
    colorMenuBasicBlack: "سیاہ",
    colorMenuBasicBlue: "بلیو",
    colorMenuBasicGreen: "سبز",
    colorMenuBasicGrey: "گرے",
    colorMenuBasicOrange: "نارنگی",
    colorMenuBasicPurple: "جامنی",
    colorMenuBasicRed: "سرخ",
    colorMenuBasicTitle: "متن کا رنگ تبدیل کریں",
    colorMenuBasicWhite: "سفيد",
    dockToElementTitle: "ڈوک ناکنار\/عنصر کے لیے تدوین کار",
    dockToScreenTitle: "ڈوک\/ناکنار سکرین کے لیے تدوین کار",
    embedDialogCancelButton: "منسوخ کریں",
    embedDialogOKButton: "آبجیکٹ شامل کریں",
    embedDialogTabCode: "کوڈ شامل کریں",
    embedDialogTabCodeContent: "آپ آبجیکٹ کوڈ متن علاقہ میں نیچے چسپاں کر دیں:",
    embedDialogTabPreview: "پیش منظر",
    embedDialogTabPreviewContent: "آپ شامل آبجیکٹ کے پیش منظر کے نیچے دکھایا جاتا ہے:",
    embedDialogTitle: "آبجیکٹ شامل کریں",
    embedTitle: "آبجیکٹ شامل کریں",
    errorUINoName: "UI \"{{ui}}\" ناجائز ہے (ایک نام خاصیت ہونا ضروری ہے)",
    errorUINotObject: "UI \"{{ui}}\" ناجائز ہے (ایک آبجیکٹ ہونی چاہیے)",
    errorUIOverride: "UI \"{{name}}\" پہلے سے ہی اندراج کیا جا چکا ہے، اور تحریر کیا جائے گا",
    fileManagerDialogTitle: "فائل مینیجر",
    fileManagerTitle: "فائل مینیجر",
    floatLeftTitle: "تصویر کے بائیں طرف سیدھ میں لائیں",
    floatNoneTitle: "تصویر ہٹائیں سیدھ میں لائیں",
    floatRightTitle: "دائیں طرف سیدھ میں لائیں",
    fontFamilyMenuFontArial: "ایریئل",
    fontFamilyMenuFontComicSans: "بغیر میں کامک",
    fontFamilyMenuFontCourier: "Courier نیا",
    fontFamilyMenuFontDefault: "طے شدہ فانٹ",
    fontFamilyMenuFontGeorgia: "جورجيا",
    fontFamilyMenuFontImpact: "اثر",
    fontFamilyMenuFontPalatino: "پالاٹانا",
    fontFamilyMenuFontTimes: "ٹائمز نیو رومن",
    fontFamilyMenuTitle: "آپ فانٹ کا انتخاب کریں",
    guidesTitle: "عنصر رہنما نمایش کریں",
    historyRedoTitle: "اعادہ کریں",
    historyUndoTitle: "کالعدم کریں",
    hrCreateTitle: "افقی رول ڈالیں",
    imageResizeButtonDialogCancelButton: "منسوخ کریں",
    imageResizeButtonDialogHeight: "نقش اونچائی",
    imageResizeButtonDialogHeightPlaceHolder: "اونچائی",
    imageResizeButtonDialogOKButton: "نیا سائز کریں",
    imageResizeButtonDialogTitle: "تصویر کا نیا سائز کریں",
    imageResizeButtonDialogWidth: "نقش چوڑائی",
    imageResizeButtonDialogWidthPlaceHolder: "چوڑائی",
    imageResizeButtonText: "تصویر کا نیا سائز کریں",
    insertFileDialogCancelButton: "منسوخ کریں",
    insertFileDialogOKButton: "مسل داخل کریں",
    insertFileNameLabel: "نام مسل",
    insertFileNamePlaceHolder: "نام مسل...",
    insertFileTitle: "مسل داخل کریں",
    insertFileURLLabel: "مسل URL",
    insertFileURLPlaceHolder: "URL مسل...",
    languageMenuTitle: "زبان تبدیل کریں",
    linkCreateDialogCancelButton: "منسوخ کریں",
    linkCreateDialogMenuHeader: "لنک کی ایک قسم کا انتخاب کریں",
    linkCreateDialogOKButton: "ربط داخل کریں",
    linkCreateDialogTitle: "ربط داخل کریں",
    linkCreateTitle: "ربط داخل کریں",
    linkRemoveTitle: "ربط ہٹائیں",
    linkTypeDocumentHeader: "ایک دستاویز یا دیگر مسل سے ربط کریں",
    linkTypeDocumentInfo: "<h2>نہیں یقین ہے کہ مذکورہ بالا خانہ میں رکھ کر کیا؟<\/h2><ol>    <li>اس بات کو یقینی بنانے کے لئے آپ کی ویب سائٹ مسل اپ لوڈ کیا گیا ہے ۔<\/li>    <li>اپ لوڈ مسل آپ کے براؤزر میں کھولیں ۔<\/li>    <li>مسل کا یو آر ایل آپ کے براؤزر کی پتہ بار سے نقل کریں اور اسے مذکورہ بالا خانہ میں پیسٹ کریں ۔<\/li><\/ol>",
    linkTypeDocumentLabel: "دستاویز یا دیگر مسل",
    linkTypeDocumentLocationLabel: "محل وقوع:",
    linkTypeDocumentLocationPlaceHolder: "URL داخل کریں",
    linkTypeDocumentNewWindowHeader: "نیا دریچہ",
    linkTypeDocumentNewWindowLabel: "ایک نئی براؤزر ونڈو\/ٹیب میں کھولیں مسل کو اس خانہ پڑتال کریں ۔",
    linkTypeEmailHeader: "ایک ای میل ایڈریس سے ربط کریں",
    linkTypeEmailLabel: "ای میل ایڈریس",
    linkTypeEmailSubjectLabel: "موضوع (اختیاری):",
    linkTypeEmailSubjectPlaceHolder: "موضوع داخل کریں",
    linkTypeEmailToLabel: "ای میل ایڈریس:",
    linkTypeEmailToPlaceHolder: "ای میل ایڈریس درج کریں",
    linkTypeExternalHeader: "ایک اور ویب سائٹ پر ایک صفحہ سے ربط کریں",
    linkTypeExternalInfo: "<h2>نہیں یقین ہے کہ مذکورہ بالا خانہ میں رکھ کر کیا؟<\/h2><ol>    <li>صفحہ پر ربط کے لیے حسب خواہش ویب تلاش.<\/li>    <li>ویب پتا آپ کے براؤزر کی پتہ بار سے نقل کریں اور اسے مذکورہ بالا خانہ میں پیسٹ کریں ۔<\/li><\/ol>",
    linkTypeExternalLabel: "ایک اور ویب سائٹ پر صفحہ",
    linkTypeExternalLocationLabel: "محل وقوع:",
    linkTypeExternalLocationPlaceHolder: "URL داخل کریں",
    linkTypeExternalNewWindowHeader: "نیا دریچہ",
    linkTypeExternalNewWindowLabel: "ایک نئی براؤزر ونڈو\/ٹیب میں کھولیں ربط کے لئے اس خانہ پڑتال کریں ۔",
    linkTypeInternalHeader: "اس ویب سائٹ پر ایک صفحہ سے ربط کریں",
    linkTypeInternalInfo: "<h2>نہیں یقین ہے کہ مذکورہ بالا خانہ میں رکھ کر کیا؟<\/h2><ol>    <li>صفحہ کے لیے یہ سائٹ لنک پر ملے ہیں ۔<\/li>    <li>ویب پتا بار، \"{{domain}}\" کو چھوڑ کر آپ کے براؤزر کی پتہ سے نقل کریں اور اسے مذکورہ بالا خانہ میں پیسٹ کریں ۔<\/li><\/ol>",
    linkTypeInternalLabel: "اس ویب سائٹ پر صفحہ",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "ایک URI داخل کریں",
    linkTypeInternalNewWindowHeader: "نیا دریچہ",
    linkTypeInternalNewWindowLabel: "ایک نئی براؤزر ونڈو\/ٹیب میں کھولیں ربط کے لئے اس خانہ پڑتال کریں ۔",
    listOrderedTitle: "حکم دیا فہرست",
    listUnorderedTitle: "انوردراد کی فہرست",
    logoTitle: "ریپٹر جو دیکھا وہ پایا ایڈیٹر کے بارے میں مزید معلومات حاصل کریں",
    loremIpsumTitle: "جانچ کے لئے کٹھ پُتلی متن داخل کریں",
    navigateAway: "\nوہاں تبدیلیاں اس صفحہ پر غیر محفوظ ہیں ۔ \nاگر آپ اس صفحہ کی گشت آپ اپنی محفوظ شدہ تبدیلیاں کھودیں گے",
    pasteDialogCancelButton: "منسوخ کریں",
    pasteDialogFormattedCleaned: "وضع کاری &amp; صاف کر",
    pasteDialogFormattedUnclean: "ناپاک وضع شدہ",
    pasteDialogOKButton: "داخل کریں",
    pasteDialogPlain: "سادہ متن",
    pasteDialogSource: "سورس کوڈ",
    pasteDialogTitle: "جوڑیں",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "نظرثانی کی بازیافت کرنے میں ناکام رہے",
    revisionsApplyButtonDialogCancelButton: "منسوخ کریں",
    revisionsApplyButtonDialogOKButton: "رول بیک",
    revisionsApplyButtonDialogText: "رول بیک کی تصدیق",
    revisionsApplyButtonDialogTitle: "رول بیک کی تصدیق",
    revisionsApplyButtonText: "رول بیک",
    revisionsApplyButtonTitle: "رول بیک",
    revisionsApplyDialogContent: "یہ حالیہ مشمول منتخب نظرِثانی کے بعد بدل دے گا ۔<br>حالیہ مشمول ایک نظرِ ثانی کے طور پر شامل ہو جائیں گے، اور نظرثانی کی فہرست میں اس بلاک کے لیے مرئی ہو گا ۔",
    revisionsButtonCurrent: "موجودہ",
    revisionsButtonViewDiffText: "اختلافات",
    revisionsButtonViewDiffTitle: "",
    revisionsCreated: "بنائی",
    revisionsDialogCancelButton: "منسوخ کریں",
    revisionsDialogTitle: "منظر مشمولات نظرثانی",
    revisionsDiffButtonDialogCancelButton: "بند کریں",
    revisionsDiffButtonDialogTitle: "منظر اختلافات",
    revisionsDiffButtonText: "منظر اختلافات",
    revisionsDiffButtonTitle: "منظر اختلافات",
    revisionsLoading: "نظرثانی لوڈ کر رہا ہے...",
    revisionsNone: "یہ عنصر کے لئے کوئی نظرثانی",
    revisionsPreviewButtonText: "پیش منظر",
    revisionsPreviewButtonTitle: "پیش منظر",
    revisionsText: "نظرثانی",
    revisionsTextEmpty: "کوئی نظرثانی",
    revisionsTitle: "",
    rfmClose: "بند کریں",
    rfmContinue: "جاری رکھیں",
    rfmDelete: "حذف کریں",
    rfmDownload: "ڈاؤن لوڈ، اتارنا",
    rfmFileActions: "اعمال",
    rfmFileModificationTime: "ترمیم",
    rfmFileName: "نام",
    rfmFileSize: "سائز",
    rfmFileType: "قسم",
    rfmFilteredTotal: "{{start}} دکھاتے {{end}} {{filteredTotal}} مسلیں",
    rfmFirst: "سب سے پہلے",
    rfmHeadingDirectories: "ڈائریکٹریاں",
    rfmHeadingSearch: "تلاش کریں",
    rfmHeadingTags: "ٹیگز",
    rfmHeadingUpload: "اپ لوڈ کریں",
    rfmInsert: "داخل کریں",
    rfmLast: "آخری",
    rfmSearch: "جانا",
    rfmTagDocument: "دستاویز",
    rfmTagImage: "نقش",
    rfmTotal: "، {{total}} فلٹر کیا جائے گا",
    rfmUpload: "اپ لوڈ کریں",
    rfmUploadBrowse: "براؤز کریں",
    rfmUploadDrop: "مسلوں کو یہاں چھوڑیں",
    rfmUploadFileRemove: "ہٹانا",
    rfmUploadOr: "یا",
    rfmView: "منظر",
    saveJsonFail: "{{failed}} مواد block(s) محفوظ کرنے میں ناکام",
    saveJsonSaved: "{{saved}} مواد block(s) کامیابی سے محفوظ کرلی ہے ۔",
    saveNotConfigured: "محفوظ تشکیل نہیں دیا گیا، یا نااہل ہے ۔",
    saveRestFail: "{{failed}} مواد block(s) محفوظ کرنے میں ناکام ہے ۔",
    saveRestPartial: "{{saved}} مشمول بلاک سے {{failed}} محفوظ نہیں ۔",
    saveRestSaved: "{{saved}} مواد block(s) کامیابی سے محفوظ کرلی ہے ۔",
    saveTitle: "مشمول محفوظ کریں",
    snippetMenuTitle: "سنیٹ کریں",
    specialCharactersArrows: "تیر",
    specialCharactersDialogOKButton: "ٹھيک ہے",
    specialCharactersDialogTitle: "خاص کریکٹر داخل کریں",
    specialCharactersGreekAlphabet: "یونانی حروف تہجی",
    specialCharactersHelp: "یہ اضافہ کرنے کے لیے ایک خاص کریکٹر پر کلک کریں ۔ \"یہ مکالمہ بند کرنے کے لیے ٹھیک سے کیا کب ہے\" پر کلک کریں",
    specialCharactersMathematics: "ریاضی",
    specialCharactersSymbols: "علامات",
    specialCharactersTitle: "ایک خاص کریکٹر داخل کریں",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} کریکٹر کی حد کو پار",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} کے حروف باقی",
    statisticsButtonCharacters: "{{characters}} کریکٹر",
    statisticsDialogCharactersOverLimit: "{{characters}} کریکٹر، {{charactersRemaining}} سفارش کردہ حد کو پار",
    statisticsDialogCharactersRemaining: "باقی {{characters}} کریکٹر، {{charactersRemaining}}",
    statisticsDialogNotTruncated: "مشمول نہیں مقطوع ہو جائے گی",
    statisticsDialogOKButton: "ٹھيک ہے",
    statisticsDialogSentence: "{{sentences}} کی سزا",
    statisticsDialogSentences: "{{sentences}} کی سزائیں",
    statisticsDialogTitle: "مشمول کے اعداد و شمار",
    statisticsDialogTruncated: "مشمول سے زائد {{limit}} کریکٹر کا حامل ہے اور مقطوع ہو سکتا ہے",
    statisticsDialogWord: "{{words}} کے کلام",
    statisticsDialogWords: "{{words}} کے الفاظ",
    statisticsTitle: "اعداد و شمار دیکھنے کے لیے کلک کریں",
    tableCreateTitle: "جدول بنائیں",
    tableDeleteColumnTitle: "جدول کالم حذف کریں",
    tableDeleteRowTitle: "جدول صف حذف کریں",
    tableInsertColumnTitle: "جدول کالم داخل کریں",
    tableInsertRowTitle: "جدول صف داخل کریں",
    tableMergeCellsTitle: "جدول سیلوں کو ضم کریں",
    tableSplitCellsTitle: "جدول سیلوں کو الگ کریں",
    tagMenuTagAddress: "پتا",
    tagMenuTagDiv: "دو",
    tagMenuTagH1: "سرخی 1",
    tagMenuTagH2: "سرخی 2",
    tagMenuTagH3: "سرخی 3",
    tagMenuTagH4: "سرخی 4",
    tagMenuTagNA: "لاگو نہیں",
    tagMenuTagP: "پیرا گراف",
    tagMenuTagPre: "پہلے سے وضع شدہ",
    tagMenuTitle: "عنصر طرز تبدیل کریں",
    tagTreeElementLink: "{{element}} عنصر منتخب کریں",
    tagTreeElementTitle: "\"{{element}}\" عنصر کے مشمولات کو منتخب کرنے کے لیے کلک کریں",
    tagTreeRoot: "اساس",
    tagTreeRootLink: "ہر ایک قابل تدوین مواد کو منتخب کریں",
    tagTreeRootTitle: "ہر ایک قابل تدوین مواد کو منتخب کرنے کے لیے کلک کریں",
    textBlockQuoteTitle: "بلاک اقتباس",
    textBoldTitle: "نڈر",
    textItalicTitle: "اٹالک",
    textSizeDecreaseTitle: "متن کا سائز گھٹائیں",
    textSizeIncreaseTitle: "متن کا سائز بڑھائیں",
    textStrikeTitle: "کے ذریعے ہڑتال",
    textSubTitle: "ذیلی نوشتہ",
    textSuperTitle: "اعلی ترین نوشتہ",
    textUnderlineTitle: "خط کشیدہ",
    unsavedEditWarningText: "وہاں تبدیلیاں اس صفحہ پر غیر محفوظ ہیں",
    viewSourceDialogCancelButton: "بند کریں",
    viewSourceDialogOKButton: "سورس کوڈ لگائیں",
    viewSourceDialogTitle: "مشمول سورس کوڈ",
    viewSourceTitle: "ماخذ ضابطہ منظر\/تدوین کریں"
});