/**
 * @fileOverview Vietnamese strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('vi', 'Việt Nam', {
    alignCenterTitle: "Căn chỉnh văn bản Trung tâm",
    alignJustifyTitle: "Căn chỉnh văn bản biện minh cho",
    alignLeftTitle: "Căn chỉnh văn bản trái",
    alignRightTitle: "Căn chỉnh văn bản quyền",
    cancelDialogCancelButton: "Tiếp tục chỉnh sửa",
    cancelDialogContent: "Bạn có chắc bạn muốn hủy bỏ chỉnh sửa không? Mọi thay đổi sẽ bị mất!",
    cancelDialogOKButton: "Hủy bỏ chỉnh sửa",
    cancelDialogTitle: "Hủy bỏ chỉnh sửa",
    cancelTitle: "Hủy bỏ chỉnh sửa",
    classMenuTitle: "Chọn phong cách",
    clearFormattingTitle: "Xoá định dạng",
    clickButtonToEditText: "Chỉnh sửa",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "Tự động",
    colorMenuBasicBlack: "Đen",
    colorMenuBasicBlue: "Màu xanh",
    colorMenuBasicGreen: "Màu xanh lá cây",
    colorMenuBasicGrey: "Xám",
    colorMenuBasicOrange: "Orange",
    colorMenuBasicPurple: "Màu tím",
    colorMenuBasicRed: "Red",
    colorMenuBasicTitle: "Thay đổi màu văn bản",
    colorMenuBasicWhite: "Trắng",
    dockToElementTitle: "Dock\/tháo trình soạn thảo để nguyên tố",
    dockToScreenTitle: "Dock\/tháo trình soạn thảo để màn hình",
    embedDialogCancelButton: "Hủy bỏ",
    embedDialogOKButton: "Nhúng đối tượng",
    embedDialogTabCode: "Mã nhúng",
    embedDialogTabCodeContent: "Dán mã nhúng vào vùng văn bản dưới đây:",
    embedDialogTabPreview: "Xem trước",
    embedDialogTabPreviewContent: "Một bản xem trước của đối tượng nhúng của bạn sẽ được hiển thị dưới đây:",
    embedDialogTitle: "Nhúng đối tượng",
    embedTitle: "Nhúng đối tượng",
    errorUINoName: "Giao diện người dùng \"{{ui}}\" là không hợp lệ (phải có một tài sản tên)",
    errorUINotObject: "Giao diện người dùng \"{{ui}}\" là không hợp lệ (phải là một đối tượng)",
    errorUIOverride: "Giao diện người dùng \"{{name}}\" đã được đăng ký, và sẽ được ghi đè",
    fileManagerDialogTitle: "Quản lý tập tin",
    fileManagerTitle: "Quản lý tập tin",
    floatLeftTitle: "Sắp xếp các hình ảnh bên trái",
    floatNoneTitle: "Loại bỏ hình ảnh sắp xếp",
    floatRightTitle: "Sắp xếp các hình ảnh ở bên phải",
    fontFamilyMenuFontArial: "Arial",
    fontFamilyMenuFontComicSans: "Các truyện tranh mà không có",
    fontFamilyMenuFontCourier: "Chuyển phát nhanh mới",
    fontFamilyMenuFontDefault: "Phông chữ mặc định",
    fontFamilyMenuFontGeorgia: "Georgia",
    fontFamilyMenuFontImpact: "Tác động",
    fontFamilyMenuFontPalatino: "Palatine",
    fontFamilyMenuFontTimes: "Thời gian mới La Mã",
    fontFamilyMenuTitle: "Chọn phông chữ của bạn",
    guidesTitle: "Hiển thị phần tử hướng dẫn",
    historyRedoTitle: "Làm lại",
    historyUndoTitle: "Hoàn tác",
    hrCreateTitle: "Chèn ngang quy tắc",
    imageResizeButtonDialogCancelButton: "Hủy bỏ",
    imageResizeButtonDialogHeight: "Chiều cao hình ảnh",
    imageResizeButtonDialogHeightPlaceHolder: "Chiều cao",
    imageResizeButtonDialogOKButton: "Thay đổi kích cỡ",
    imageResizeButtonDialogTitle: "Thay đổi kích cỡ hình ảnh",
    imageResizeButtonDialogWidth: "Chiều rộng hình ảnh",
    imageResizeButtonDialogWidthPlaceHolder: "Chiều rộng",
    imageResizeButtonText: "Thay đổi kích cỡ hình ảnh",
    insertFileDialogCancelButton: "Hủy bỏ",
    insertFileDialogOKButton: "Chèn tệp",
    insertFileNameLabel: "Tên tập tin",
    insertFileNamePlaceHolder: "Tên tập tin...",
    insertFileTitle: "Chèn tệp",
    insertFileURLLabel: "Tập tin",
    insertFileURLPlaceHolder: "Tập tin URL...",
    languageMenuTitle: "Thay đổi ngôn ngữ",
    linkCreateDialogCancelButton: "Hủy bỏ",
    linkCreateDialogMenuHeader: "Chọn một loại liên kết",
    linkCreateDialogOKButton: "Chèn liên kết",
    linkCreateDialogTitle: "Chèn liên kết",
    linkCreateTitle: "Chèn liên kết",
    linkRemoveTitle: "Loại bỏ liên kết",
    linkTypeDocumentHeader: "Liên kết với một tài liệu hoặc tập tin khác",
    linkTypeDocumentInfo: "<h2>Không chắc chắn những gì để đặt trong các hộp ở trên?<\/h2><ol>    <li>Đảm bảo các tập tin đã được tải lên trang web của bạn.<\/li>    <li>Mở tập tin được tải lên trong trình duyệt của bạn.<\/li>    <li>Sao chép tập tin từ thanh địa chỉ của trình duyệt và dán nó vào hộp ở trên.<\/li><\/ol>",
    linkTypeDocumentLabel: "Tài liệu hoặc tập tin khác",
    linkTypeDocumentLocationLabel: "Địa điểm:",
    linkTypeDocumentLocationPlaceHolder: "Nhập một URL",
    linkTypeDocumentNewWindowHeader: "Cửa sổ mới",
    linkTypeDocumentNewWindowLabel: "Đánh dấu ô này có tập tin mở trong một cửa sổ trình duyệt mới\/tab.",
    linkTypeEmailHeader: "Liên kết với một địa chỉ email",
    linkTypeEmailLabel: "Địa chỉ email",
    linkTypeEmailSubjectLabel: "Tiêu đề (tùy chọn):",
    linkTypeEmailSubjectPlaceHolder: "Nhập Chủ đề",
    linkTypeEmailToLabel: "Thư điện tử:",
    linkTypeEmailToPlaceHolder: "Nhập địa chỉ email",
    linkTypeExternalHeader: "Liên kết đến một trang trên trang web khác",
    linkTypeExternalInfo: "<h2>Không chắc chắn những gì để đặt trong các hộp ở trên?<\/h2><ol>    <li>Tìm thấy trang trên các trang web mà bạn muốn liên kết đến.<\/li>    <li>Sao chép địa chỉ web từ thanh địa chỉ của trình duyệt và dán nó vào hộp ở trên.<\/li><\/ol>",
    linkTypeExternalLabel: "Trang trên trang web khác",
    linkTypeExternalLocationLabel: "Địa điểm:",
    linkTypeExternalLocationPlaceHolder: "Nhập một URL",
    linkTypeExternalNewWindowHeader: "Cửa sổ mới",
    linkTypeExternalNewWindowLabel: "Đánh dấu ô này có liên kết mở trong một cửa sổ trình duyệt mới\/tab.",
    linkTypeInternalHeader: "Liên kết đến một trang trên trang web này",
    linkTypeInternalInfo: "<h2>Không chắc chắn những gì để đặt trong các hộp ở trên?<\/h2><ol>    <li>Tìm thấy trang này liên kết trang web để.<\/li>    <li>Sao chép địa chỉ web từ trình duyệt của bạn địa chỉ bar, không bao gồm \"{{domain}}\" và dán nó vào hộp ở trên.<\/li><\/ol>",
    linkTypeInternalLabel: "Trang trên trang web này",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "Nhập một URI",
    linkTypeInternalNewWindowHeader: "Cửa sổ mới",
    linkTypeInternalNewWindowLabel: "Đánh dấu ô này có liên kết mở trong một cửa sổ trình duyệt mới\/tab.",
    listOrderedTitle: "Danh sách đặt hàng",
    listUnorderedTitle: "Danh sách có thứ tự",
    logoTitle: "Tìm hiểu thêm về trình soạn thảo WYSIWYG Raptor",
    navigateAway: "\nCó được lưu thay đổi trên Trang này. \nNếu bạn rời khỏi trang này bạn sẽ mất các thay đổi chưa được lưu",
    pasteDialogCancelButton: "Hủy bỏ",
    pasteDialogFormattedCleaned: "Định dạng &amp; làm sạch",
    pasteDialogFormattedUnclean: "Định dạng ô uế",
    pasteDialogOKButton: "Chèn",
    pasteDialogPlain: "Văn bản thuần",
    pasteDialogSource: "Mã nguồn",
    pasteDialogTitle: "Dán",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "Không thể lấy sửa đổi lại",
    revisionsApplyButtonDialogCancelButton: "Hủy bỏ",
    revisionsApplyButtonDialogOKButton: "Quay ngược lại",
    revisionsApplyButtonDialogTitle: "Quay ngược lại xác nhận",
    revisionsApplyButtonTitle: "Quay ngược lại",
    revisionsApplyDialogContent: "Điều này sẽ thay thế nội dung hiện tại với phiên bản đã chọn.<br>Nội dung hiện tại sẽ được thêm vào như là một phiên bản, và sẽ được hiển thị trong danh sách sửa đổi cho khối này.",
    revisionsButtonCurrent: "Hiện tại",
    revisionsButtonViewDiffText: "Sự khác biệt",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "Hủy bỏ",
    revisionsDialogTitle: "Xem Sửa đổi nội dung",
    revisionsDiffButtonDialogCancelButton: "Đóng",
    revisionsDiffButtonDialogTitle: "Xem sự khác biệt",
    revisionsDiffButtonTitle: "Xem sự khác biệt",
    revisionsLoading: "Tải phiên bản...",
    revisionsNone: "Không có sửa đổi cho nguyên tố này",
    revisionsPreviewButtonTitle: "Xem trước",
    revisionsText: "Sửa đổi",
    revisionsTextEmpty: "Không có sửa đổi",
    revisionsTitle: "",
    rfmClose: "Đóng",
    rfmContinue: "Tiếp tục",
    rfmDelete: "Xóa",
    rfmDownload: "Tải về",
    rfmFileActions: "Hành động",
    rfmFileModificationTime: "Sửa đổi lần",
    rfmFileName: "Tên",
    rfmFileSize: "Kích thước",
    rfmFileType: "Loại",
    rfmFilteredTotal: "Đang hiện {{start}} kết {{end}} {{filteredTotal}} tập tin",
    rfmFirst: "Đầu tiên",
    rfmHeadingDirectories: "Thư mục",
    rfmHeadingSearch: "Tìm",
    rfmHeadingTags: "Tags",
    rfmHeadingUpload: "Tải lên",
    rfmInsert: "Chèn",
    rfmLast: "Kéo",
    rfmSearch: "Đi",
    rfmTotal: ", lọc từ {{total}}",
    rfmUpload: "Tải lên",
    rfmUploadBrowse: "Trình duyệt",
    rfmUploadDrop: "Thả tập tin ở đây",
    rfmUploadFileRemove: "Loại bỏ",
    rfmView: "Xem",
    saveJsonFail: "Không lưu nội dung block(s) {{failed}}",
    saveJsonSaved: "Thành công lưu {{saved}} nội dung block(s).",
    saveNotConfigured: "Lưu đã không được cấu hình, hoặc bị vô hiệu hóa.",
    saveRestFail: "Không lưu nội dung {{failed}} block(s).",
    saveRestPartial: "Lưu {{saved}} ra khỏi khối nội dung {{failed}}.",
    saveRestSaved: "Thành công lưu {{saved}} nội dung block(s).",
    saveTitle: "Lưu nội dung",
    snippetMenuTitle: "Đoạn",
    specialCharactersDialogOKButton: "Ok",
    specialCharactersDialogTitle: "Chèn ký tự đặc biệt",
    specialCharactersHelp: "Nhấp vào một ký tự đặc biệt để thêm nó. Nhấp \"OK\" khi thực hiện để đóng hộp thoại này",
    specialCharactersTitle: "Nhập một ký tự đặc biệt",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} ký tự vượt quá giới hạn",
    statisticsButtonCharacterRemaining: "{{charactersRemaining}} ký tự còn lại",
    statisticsButtonCharacters: "{{characters}} ký tự",
    statisticsDialogCharactersOverLimit: "{{characters}} vật, {{charactersRemaining}} vượt quá giới hạn đề nghị",
    statisticsDialogCharactersRemaining: "nhân vật {{characters}}, {{charactersRemaining}} còn lại",
    statisticsDialogNotTruncated: "Nội dung sẽ không được cắt ngắn",
    statisticsDialogOKButton: "Ok",
    statisticsDialogSentence: "{{sentences}} câu",
    statisticsDialogSentences: "{{sentences}} câu",
    statisticsDialogTitle: "Số liệu thống kê nội dung",
    statisticsDialogTruncated: "Nội dung có chứa nhiều hơn {{limit}} nhân vật và có thể được cắt ngắn",
    statisticsDialogWord: "{{words}} từ",
    statisticsDialogWords: "{{words}} từ",
    statisticsTitle: "Nhấn vào đây để xem số liệu thống kê",
    tableCreateTitle: "Tạo bảng",
    tableDeleteColumnTitle: "Xóa bảng cột",
    tableDeleteRowTitle: "Xóa các hàng của bảng",
    tableInsertColumnTitle: "Chèn bảng cột",
    tableInsertRowTitle: "Chèn hàng của bảng",
    tableMergeCellsTitle: "Hợp nhất các tế bào bảng",
    tableSplitCellsTitle: "Phân chia tế bào bảng",
    tagMenuTagAddress: "Địa chỉ",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "Nhóm 1",
    tagMenuTagH2: "Nhóm 2",
    tagMenuTagH3: "Nhóm 3",
    tagMenuTagH4: "Nhóm 4",
    tagMenuTagNA: "N\/A",
    tagMenuTagP: "Đoạn",
    tagMenuTagPre: "Trước định dạng",
    tagMenuTitle: "Thay đổi phong cách yếu tố",
    tagTreeElementLink: "Chọn phần tử {{element}}",
    tagTreeElementTitle: "Nhấn vào đây để chọn các nội dung của các yếu tố \"{{element}}\"",
    tagTreeRoot: "gốc",
    tagTreeRootLink: "Chọn tất cả nội dung có thể chỉnh sửa",
    tagTreeRootTitle: "Bấm vào để chọn tất cả nội dung có thể chỉnh sửa",
    textBlockQuoteTitle: "Khối trích dẫn",
    textBoldTitle: "Đậm",
    textItalicTitle: "Nghiêng",
    textSizeDecreaseTitle: "Giảm cỡ chữ",
    textSizeIncreaseTitle: "Tăng cỡ chữ",
    textStrikeTitle: "Tấn công thông qua",
    textSubTitle: "Kịch bản phụ",
    textSuperTitle: "Siêu kịch bản",
    textUnderlineTitle: "Gạch dưới",
    unsavedEditWarningText: "Có được lưu thay đổi trên Trang này",
    viewSourceDialogCancelButton: "Đóng",
    viewSourceDialogOKButton: "Áp dụng mã nguồn",
    viewSourceDialogTitle: "Nội dung nguồn mã",
    viewSourceTitle: "Xem\/chỉnh sửa mã nguồn"
});