/**
 * @fileOverview Chinese (Simplified) strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('zh-CHS', '中文 (简体)', {
    alignCenterTitle: "文本居中对齐",
    alignJustifyTitle: "对齐文本的理由",
    alignLeftTitle: "使文本左对齐",
    alignRightTitle: "右对齐文本",
    cancelDialogCancelButton: "继续编辑",
    cancelDialogContent: "确实要取消编辑吗?所有更改将都会丢失!",
    cancelDialogOKButton: "取消编辑",
    cancelDialogTitle: "取消编辑",
    cancelTitle: "取消编辑",
    classMenuTitle: "样式选择器",
    clearFormattingTitle: "清除格式",
    clickButtonToEditText: "编辑",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "自动",
    colorMenuBasicBlack: "黑色",
    colorMenuBasicBlue: "蓝色",
    colorMenuBasicGreen: "绿色",
    colorMenuBasicGrey: "灰色",
    colorMenuBasicOrange: "橙色",
    colorMenuBasicPurple: "紫色",
    colorMenuBasicRed: "红色",
    colorMenuBasicTitle: "更改文本颜色",
    colorMenuBasicWhite: "白色",
    dockToElementTitle: "坞站\/取消停靠到元素编辑器",
    dockToScreenTitle: "坞站\/取消停靠到屏幕编辑器",
    embedDialogCancelButton: "取消",
    embedDialogOKButton: "嵌入的对象",
    embedDialogTabCode: "嵌入代码",
    embedDialogTabCodeContent: "将您嵌入代码粘贴到下面的文本区域：",
    embedDialogTabPreview: "预览",
    embedDialogTabPreviewContent: "嵌入对象的预览将显示如下：",
    embedDialogTitle: "嵌入的对象",
    embedTitle: "嵌入的对象",
    errorUINoName: "UI\"{{ui}}\"是无效的 （必须有一个名称属性）",
    errorUINotObject: "UI\"{{ui}}\"是无效的 （必须是一个对象)",
    errorUIOverride: "UI\"{{name}}\"已被注册，并将被覆盖",
    fileManagerDialogTitle: "文件管理器",
    fileManagerTitle: "文件管理器",
    floatLeftTitle: "对齐图像向左",
    floatNoneTitle: "删除图像对齐",
    floatRightTitle: "对齐图像向右",
    fontFamilyMenuFontArial: "宋体",
    fontFamilyMenuFontComicSans: "没有漫画",
    fontFamilyMenuFontCourier: "新宋体",
    fontFamilyMenuFontDefault: "默认字体",
    fontFamilyMenuFontGeorgia: "格鲁吉亚",
    fontFamilyMenuFontImpact: "影响",
    fontFamilyMenuFontPalatino: "帕拉蒂尼",
    fontFamilyMenuFontTimes: "倍新罗马",
    fontFamilyMenuTitle: "选择您的字体",
    guidesTitle: "显示元素参考线",
    historyRedoTitle: "重做",
    historyUndoTitle: "撤消",
    hrCreateTitle: "插入水平线规则",
    imageResizeButtonDialogCancelButton: "取消",
    imageResizeButtonDialogHeight: "图像高度",
    imageResizeButtonDialogHeightPlaceHolder: "高度",
    imageResizeButtonDialogOKButton: "调整大小",
    imageResizeButtonDialogTitle: "调整图像的大小",
    imageResizeButtonDialogWidth: "图像宽度",
    imageResizeButtonDialogWidthPlaceHolder: "宽度",
    imageResizeButtonText: "调整图像的大小",
    insertFileDialogCancelButton: "取消",
    insertFileDialogOKButton: "插入文件",
    insertFileNameLabel: "文件名称",
    insertFileNamePlaceHolder: "文件名称...",
    insertFileTitle: "插入文件",
    insertFileURLLabel: "文件的 URL",
    insertFileURLPlaceHolder: "文件的 URL......",
    languageMenuTitle: "更改语言",
    linkCreateDialogCancelButton: "取消",
    linkCreateDialogMenuHeader: "选择一个链接类型",
    linkCreateDialogOKButton: "插入链接",
    linkCreateDialogTitle: "插入链接",
    linkCreateTitle: "插入链接",
    linkRemoveTitle: "删除链接",
    linkTypeDocumentHeader: "链接到文件或其他文件",
    linkTypeDocumentInfo: "<h2>不确定要放置在上面的框中的内容吗？<\/h2><ol>    <li>确保文件已上载到您的网站。<\/li>    <li>在您的浏览器中打开已上载的文件。<\/li>    <li>从您的浏览器的地址栏中复制文件的 URL 并将其粘贴到上面的框。<\/li><\/ol>",
    linkTypeDocumentLabel: "文档或其他文件",
    linkTypeDocumentLocationLabel: "位置：",
    linkTypeDocumentLocationPlaceHolder: "输入一个 URL",
    linkTypeDocumentNewWindowHeader: "新窗口",
    linkTypeDocumentNewWindowLabel: "选中此复选框有一个新的浏览器窗口\/选项卡中打开该文件。",
    linkTypeEmailHeader: "链接到电子邮件地址",
    linkTypeEmailLabel: "电子邮件地址",
    linkTypeEmailSubjectLabel: "主题 （可选）：",
    linkTypeEmailSubjectPlaceHolder: "输入主题",
    linkTypeEmailToLabel: "电子邮件：",
    linkTypeEmailToPlaceHolder: "输入电子邮件地址",
    linkTypeExternalHeader: "链接到另一个网站上的网页",
    linkTypeExternalInfo: "<h2>不确定要放置在上面的框中的内容吗？<\/h2><ol>    <li>找到你想要链接到的 web 上的页面。<\/li>    <li>从您的浏览器的地址栏复制 web 地址并将其粘贴到上面的框。<\/li><\/ol>",
    linkTypeExternalLabel: "另一个网站的网页上",
    linkTypeExternalLocationLabel: "位置：",
    linkTypeExternalLocationPlaceHolder: "输入一个 URL",
    linkTypeExternalNewWindowHeader: "新窗口",
    linkTypeExternalNewWindowLabel: "选中此复选框以在新的浏览器窗口\/选项卡中打开该链接。",
    linkTypeInternalHeader: "链接到本网站上的网页",
    linkTypeInternalInfo: "<h2>不确定要放置在上面的框中的内容吗？<\/h2><ol>    <li>找到关于此站点链接到的页面。<\/li>    <li>从您的浏览器的地址栏，不包括\"{{domain}}\"域中复制 web 地址并将其粘贴到上面的框。<\/li><\/ol>",
    linkTypeInternalLabel: "本网站上的页面",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "输入一个 URI",
    linkTypeInternalNewWindowHeader: "新窗口",
    linkTypeInternalNewWindowLabel: "选中此复选框以在新的浏览器窗口\/选项卡中打开该链接。",
    listOrderedTitle: "排序的列表",
    listUnorderedTitle: "未排序的列表",
    logoTitle: "了解更多关于猛禽所见即所得编辑器",
    navigateAway: "在此页上未保存的更改。如果您导航到其他页面，您将丢失未保存的更改",
    pasteDialogCancelButton: "取消",
    pasteDialogFormattedCleaned: "格式化和清理",
    pasteDialogFormattedUnclean: "格式化不洁",
    pasteDialogOKButton: "插入",
    pasteDialogPlain: "纯文本",
    pasteDialogSource: "源代码",
    pasteDialogTitle: "粘贴",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "未能检索的修订",
    revisionsApplyButtonDialogCancelButton: "取消",
    revisionsApplyButtonDialogOKButton: "回滚",
    revisionsApplyButtonDialogTitle: "回滚确认",
    revisionsApplyButtonTitle: "回滚",
    revisionsApplyDialogContent: "这将替换当前的内容与选定的修订版本。<br>当前内容将被添加为修订，并将在此块的修订列表中可见。",
    revisionsButtonCurrent: "当前",
    revisionsButtonViewDiffText: "差异",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "取消",
    revisionsDialogTitle: "视图内容修订",
    revisionsDiffButtonDialogCancelButton: "关闭",
    revisionsDiffButtonDialogTitle: "查看差异",
    revisionsDiffButtonTitle: "查看差异",
    revisionsLoading: "正在加载修订...",
    revisionsNone: "此元素没有修订",
    revisionsPreviewButtonTitle: "预览",
    revisionsText: "修订",
    revisionsTextEmpty: "没有修订",
    revisionsTitle: "",
    rfmClose: "关闭",
    rfmContinue: "继续",
    rfmDelete: "删除",
    rfmDownload: "下载",
    rfmFileActions: "行动",
    rfmFileModificationTime: "修改",
    rfmFileName: "名称",
    rfmFileSize: "大小",
    rfmFileType: "类型",
    rfmFilteredTotal: "显示 {{start}} {{end}} {{filteredTotal}} 的文件",
    rfmFirst: "第一次",
    rfmHeadingDirectories: "目录",
    rfmHeadingSearch: "搜索",
    rfmHeadingTags: "标签",
    rfmHeadingUpload: "上传",
    rfmInsert: "插入",
    rfmLast: "最后",
    rfmSearch: "转到",
    rfmTotal: "{{total}} 从筛选",
    rfmUpload: "上传",
    rfmUploadBrowse: "浏览",
    rfmUploadDrop: "将文件拖至此处",
    rfmUploadFileRemove: "删除",
    rfmView: "视图",
    saveJsonFail: "未能保存 {{failed}} 内容提供数据块",
    saveJsonSaved: "已成功保存 {{saved}} 内容提供的数据块。",
    saveNotConfigured: "保存未配置，或被禁用。",
    saveRestFail: "未能保存 {{failed}} 内容提供的数据块。",
    saveRestPartial: "保存 {{saved}} {{failed}} 的内容块了。",
    saveRestSaved: "已成功保存 {{saved}} 内容提供的数据块。",
    saveTitle: "保存的内容",
    snippetMenuTitle: "代码段",
    specialCharactersDialogOKButton: "还行",
    specialCharactersDialogTitle: "插入特殊字符",
    specialCharactersHelp: "单击要添加特殊字符。单击\"确定\"完成后关闭此对话框",
    specialCharactersTitle: "插入特殊字符",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} 字符超出限制",
    statisticsButtonCharacterRemaining: "剩余的 {{charactersRemaining}} 字符",
    statisticsButtonCharacters: "{{characters}} 字符",
    statisticsDialogCharactersOverLimit: "在建议的限制 {{characters}} {{charactersRemaining}} 字符",
    statisticsDialogCharactersRemaining: "{{characters}} {{charactersRemaining}} 字符剩余",
    statisticsDialogNotTruncated: "内容不会被截断",
    statisticsDialogOKButton: "还行",
    statisticsDialogSentence: "{{sentences}} 句子",
    statisticsDialogSentences: "{{sentences}} 的句子",
    statisticsDialogTitle: "内容统计",
    statisticsDialogTruncated: "内容包含超过 {{limit}} 字符和可能会被截断",
    statisticsDialogWord: "{{words}} 字",
    statisticsDialogWords: "{{words}} 字",
    statisticsTitle: "单击此处，查看统计信息",
    tableCreateTitle: "创建表",
    tableDeleteColumnTitle: "删除表格列",
    tableDeleteRowTitle: "删除表格行",
    tableInsertColumnTitle: "插入表格列",
    tableInsertRowTitle: "插入表格行",
    tableMergeCellsTitle: "合并表格单元格",
    tableSplitCellsTitle: "拆分表格单元格",
    tagMenuTagAddress: "地址",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "标题 1",
    tagMenuTagH2: "标题 2",
    tagMenuTagH3: "标题 3",
    tagMenuTagH4: "标题 4",
    tagMenuTagNA: "不适用",
    tagMenuTagP: "段",
    tagMenuTagPre: "预格式化",
    tagMenuTitle: "更改元素的样式",
    tagTreeElementLink: "选择 {{element}} 元素",
    tagTreeElementTitle: "单击以选中\"{{element}}\"元素的内容",
    tagTreeRoot: "根",
    tagTreeRootLink: "选择所有可编辑内容",
    tagTreeRootTitle: "单击以选择所有可编辑内容",
    textBlockQuoteTitle: "块引用",
    textBoldTitle: "加粗",
    textItalicTitle: "斜体",
    textSizeDecreaseTitle: "减小文本大小",
    textSizeIncreaseTitle: "增加文本的大小",
    textStrikeTitle: "通过罢工",
    textSubTitle: "分脚本",
    textSuperTitle: "超级脚本",
    textUnderlineTitle: "下划线",
    unsavedEditWarningText: "在此页上那里未保存的更改",
    viewSourceDialogCancelButton: "关闭",
    viewSourceDialogOKButton: "应用源代码",
    viewSourceDialogTitle: "内容源的代码",
    viewSourceTitle: "查看\/编辑源代码"
});