/**
 * @fileOverview Chinese (Traditional) strings file.
 * @license http://www.raptor-editor.com/license
 *
 * Note: this file was automatically translated and may not be 100% correct.
 *
 * @author David Neilsen <david@panmedia.co.nz>
 */
extendLocale('zh-CHT', '中文 (繁體)', {
    alignCenterTitle: "文本居中對齊",
    alignJustifyTitle: "對齊文本的理由",
    alignLeftTitle: "使文本左對齊",
    alignRightTitle: "右對齊文本",
    cancelDialogCancelButton: "繼續編輯",
    cancelDialogContent: "確實要取消編輯嗎?所有更改將都會丟失!",
    cancelDialogOKButton: "取消編輯",
    cancelDialogTitle: "取消編輯",
    cancelTitle: "取消編輯",
    classMenuTitle: "樣式選擇器",
    clearFormattingTitle: "清除格式",
    clickButtonToEditText: "編輯",
    clickButtonToEditTitle: "",
    colorMenuBasicAutomatic: "自動",
    colorMenuBasicBlack: "黑色",
    colorMenuBasicBlue: "藍色",
    colorMenuBasicGreen: "綠色",
    colorMenuBasicGrey: "灰色",
    colorMenuBasicOrange: "橙色",
    colorMenuBasicPurple: "紫色",
    colorMenuBasicRed: "紅色",
    colorMenuBasicTitle: "更改文本顏色",
    colorMenuBasicWhite: "白色",
    dockToElementTitle: "塢站\/取消停靠到元素編輯器",
    dockToScreenTitle: "塢站\/取消停靠到螢幕編輯器",
    embedDialogCancelButton: "取消",
    embedDialogOKButton: "嵌入的物件",
    embedDialogTabCode: "嵌入代碼",
    embedDialogTabCodeContent: "將您嵌入代碼粘貼到下面的文本區域：",
    embedDialogTabPreview: "預覽",
    embedDialogTabPreviewContent: "內嵌物件的預覽將顯示如下：",
    embedDialogTitle: "嵌入的物件",
    embedTitle: "嵌入的物件",
    errorUINoName: "UI\"{{ui}}\"是不正確 （必須有一個名稱屬性）",
    errorUINotObject: "UI\"{{ui}}\"是不正確 （必須是一個物件)",
    errorUIOverride: "UI\"{{name}}\"已被註冊，並將被覆蓋",
    fileManagerDialogTitle: "檔案管理員",
    fileManagerTitle: "檔案管理員",
    floatLeftTitle: "對齊圖像向左",
    floatNoneTitle: "刪除圖像對齊",
    floatRightTitle: "對齊圖像向右",
    fontFamilyMenuFontArial: "宋體",
    fontFamilyMenuFontComicSans: "沒有漫畫",
    fontFamilyMenuFontCourier: "新宋體",
    fontFamilyMenuFontDefault: "預設字型",
    fontFamilyMenuFontGeorgia: "格魯吉亞",
    fontFamilyMenuFontImpact: "影響",
    fontFamilyMenuFontPalatino: "帕拉蒂尼",
    fontFamilyMenuFontTimes: "倍新羅馬",
    fontFamilyMenuTitle: "選擇您的字體",
    guidesTitle: "顯示元素輔助線",
    historyRedoTitle: "重做",
    historyUndoTitle: "撤銷",
    hrCreateTitle: "插入水平線規則",
    imageResizeButtonDialogCancelButton: "取消",
    imageResizeButtonDialogHeight: "圖像高度",
    imageResizeButtonDialogHeightPlaceHolder: "高度",
    imageResizeButtonDialogOKButton: "調整大小",
    imageResizeButtonDialogTitle: "調整圖像的大小",
    imageResizeButtonDialogWidth: "圖像寬度",
    imageResizeButtonDialogWidthPlaceHolder: "寬度",
    imageResizeButtonText: "調整圖像的大小",
    insertFileDialogCancelButton: "取消",
    insertFileDialogOKButton: "插入檔",
    insertFileNameLabel: "檔案名稱",
    insertFileNamePlaceHolder: "檔案名稱...",
    insertFileTitle: "插入檔",
    insertFileURLLabel: "檔的 URL",
    insertFileURLPlaceHolder: "檔的 URL......",
    languageMenuTitle: "更改語言",
    linkCreateDialogCancelButton: "取消",
    linkCreateDialogMenuHeader: "選擇一個連結類型",
    linkCreateDialogOKButton: "插入連結",
    linkCreateDialogTitle: "插入連結",
    linkCreateTitle: "插入連結",
    linkRemoveTitle: "刪除連結",
    linkTypeDocumentHeader: "連結到檔或其他檔",
    linkTypeDocumentInfo: "<h2>不確定要放置在上面的框中的內容嗎？<\/h2><ol>    <li>確保檔已上載到您的網站。<\/li>    <li>在您的瀏覽器中打開已上載的檔。<\/li>    <li>從您的瀏覽器的網址列中複製檔的 URL 並將其粘貼到上面的框。<\/li><\/ol>",
    linkTypeDocumentLabel: "文檔或其他檔",
    linkTypeDocumentLocationLabel: "位置：",
    linkTypeDocumentLocationPlaceHolder: "輸入一個 URL",
    linkTypeDocumentNewWindowHeader: "新視窗",
    linkTypeDocumentNewWindowLabel: "選中此核取方塊有一個新的瀏覽器視窗\/選項卡中打開該檔。",
    linkTypeEmailHeader: "連結到電子郵件地址",
    linkTypeEmailLabel: "電子郵件地址",
    linkTypeEmailSubjectLabel: "主題 （可選）：",
    linkTypeEmailSubjectPlaceHolder: "輸入主題",
    linkTypeEmailToLabel: "電子郵件：",
    linkTypeEmailToPlaceHolder: "輸入電子郵件地址",
    linkTypeExternalHeader: "連結到另一個網站上的網頁",
    linkTypeExternalInfo: "<h2>不確定要放置在上面的框中的內容嗎？<\/h2><ol>    <li>找到你想要連結到的 web 上的頁面。<\/li>    <li>從您的瀏覽器的網址列複製 web 位址並將其粘貼到上面的框。<\/li><\/ol>",
    linkTypeExternalLabel: "另一個網站的網頁上",
    linkTypeExternalLocationLabel: "位置：",
    linkTypeExternalLocationPlaceHolder: "輸入一個 URL",
    linkTypeExternalNewWindowHeader: "新視窗",
    linkTypeExternalNewWindowLabel: "選中此核取方塊以在新的瀏覽器視窗\/選項卡中打開該連結。",
    linkTypeInternalHeader: "連結到本網站上的網頁",
    linkTypeInternalInfo: "<h2>不確定要放置在上面的框中的內容嗎？<\/h2><ol>    <li>找到關於此站台連結到的頁面。<\/li>    <li>從您的瀏覽器的網址列，不包括\"{{domain}}\"域中複製 web 位址並將其粘貼到上面的框。<\/li><\/ol>",
    linkTypeInternalLabel: "本網站上的頁面",
    linkTypeInternalLocationLabel: "",
    linkTypeInternalLocationPlaceHolder: "輸入一個 URI",
    linkTypeInternalNewWindowHeader: "新視窗",
    linkTypeInternalNewWindowLabel: "選中此核取方塊以在新的瀏覽器視窗\/選項卡中打開該連結。",
    listOrderedTitle: "排序的清單",
    listUnorderedTitle: "未排序的清單",
    logoTitle: "瞭解更多關於猛禽所見即所得編輯器",
    navigateAway: "在此頁上未保存的更改。如果您導航到其他頁面，您將丟失未保存的更改",
    pasteDialogCancelButton: "取消",
    pasteDialogFormattedCleaned: "格式化和清理",
    pasteDialogFormattedUnclean: "格式化不潔",
    pasteDialogOKButton: "插入",
    pasteDialogPlain: "純文字",
    pasteDialogSource: "原始程式碼",
    pasteDialogTitle: "粘貼",
    placeholderPluginDefaultContent: "",
    revisionsAJAXFailed: "未能檢索的修訂",
    revisionsApplyButtonDialogCancelButton: "取消",
    revisionsApplyButtonDialogOKButton: "回滾",
    revisionsApplyButtonDialogTitle: "回滾確認",
    revisionsApplyButtonTitle: "回滾",
    revisionsApplyDialogContent: "這將替換當前的內容與選定的修訂版本。<br>當前內容將被添加為修訂，並將在此塊的修訂清單中可見。",
    revisionsButtonCurrent: "當前",
    revisionsButtonViewDiffText: "差異",
    revisionsButtonViewDiffTitle: "",
    revisionsDialogCancelButton: "取消",
    revisionsDialogTitle: "視圖內容修訂",
    revisionsDiffButtonDialogCancelButton: "關閉",
    revisionsDiffButtonDialogTitle: "查看差異",
    revisionsDiffButtonTitle: "查看差異",
    revisionsLoading: "正在載入修訂...",
    revisionsNone: "此元素沒有修訂",
    revisionsPreviewButtonTitle: "預覽",
    revisionsText: "修訂",
    revisionsTextEmpty: "沒有修訂",
    revisionsTitle: "",
    rfmClose: "關閉",
    rfmContinue: "繼續",
    rfmDelete: "刪除",
    rfmDownload: "下載",
    rfmFileActions: "行動",
    rfmFileModificationTime: "修改",
    rfmFileName: "名稱",
    rfmFileSize: "大小",
    rfmFileType: "類型",
    rfmFilteredTotal: "顯示 {{start}} {{end}} {{filteredTotal}} 的檔",
    rfmFirst: "第一次",
    rfmHeadingDirectories: "目錄",
    rfmHeadingSearch: "搜索",
    rfmHeadingTags: "標籤",
    rfmHeadingUpload: "上傳",
    rfmInsert: "插入",
    rfmLast: "最後",
    rfmSearch: "轉到",
    rfmTotal: "{{total}} 從篩選",
    rfmUpload: "上傳",
    rfmUploadBrowse: "流覽",
    rfmUploadDrop: "將檔拖至此處",
    rfmUploadFileRemove: "刪除",
    rfmView: "視圖",
    saveJsonFail: "未能保存 {{failed}} 內容提供資料塊",
    saveJsonSaved: "已成功保存 {{saved}} 內容提供的資料塊。",
    saveNotConfigured: "保存未配置，或被禁用。",
    saveRestFail: "未能保存 {{failed}} 內容提供的資料塊。",
    saveRestPartial: "保存 {{saved}} {{failed}} 的內容塊了。",
    saveRestSaved: "已成功保存 {{saved}} 內容提供的資料塊。",
    saveTitle: "保存的內容",
    snippetMenuTitle: "程式碼片段",
    specialCharactersDialogOKButton: "還行",
    specialCharactersDialogTitle: "插入特殊字元",
    specialCharactersHelp: "按一下要添加特殊字元。按一下\"確定\"完成後關閉此對話方塊",
    specialCharactersTitle: "插入特殊字元",
    statisticsButtonCharacterOverLimit: "{{charactersRemaining}} 字元超出限制",
    statisticsButtonCharacterRemaining: "剩餘的 {{charactersRemaining}} 字元",
    statisticsButtonCharacters: "{{characters}} 字元",
    statisticsDialogCharactersOverLimit: "在建議的限制 {{characters}} {{charactersRemaining}} 字元",
    statisticsDialogCharactersRemaining: "{{characters}} {{charactersRemaining}} 字元剩餘",
    statisticsDialogNotTruncated: "內容不會被截斷",
    statisticsDialogOKButton: "還行",
    statisticsDialogSentence: "{{sentences}} 句子",
    statisticsDialogSentences: "{{sentences}} 的句子",
    statisticsDialogTitle: "內容統計",
    statisticsDialogTruncated: "內容包含超過 {{limit}} 字元和可能會被截斷",
    statisticsDialogWord: "{{words}} 字",
    statisticsDialogWords: "{{words}} 字",
    statisticsTitle: "按一下此處，查看統計資訊",
    tableCreateTitle: "創建表",
    tableDeleteColumnTitle: "刪除表格列",
    tableDeleteRowTitle: "刪除表格行",
    tableInsertColumnTitle: "插入表格列",
    tableInsertRowTitle: "插入表格行",
    tableMergeCellsTitle: "合併表格儲存格",
    tableSplitCellsTitle: "拆分表格儲存格",
    tagMenuTagAddress: "位址",
    tagMenuTagDiv: "Div",
    tagMenuTagH1: "標題 1",
    tagMenuTagH2: "標題 2",
    tagMenuTagH3: "標題 3",
    tagMenuTagH4: "標題 4",
    tagMenuTagNA: "不適用",
    tagMenuTagP: "段",
    tagMenuTagPre: "預格式化",
    tagMenuTitle: "更改元素的樣式",
    tagTreeElementLink: "選擇 {{element}} 元素",
    tagTreeElementTitle: "按一下以選中\"{{element}}\"元素的內容",
    tagTreeRoot: "根",
    tagTreeRootLink: "選擇所有可編輯內容",
    tagTreeRootTitle: "按一下以選擇所有可編輯內容",
    textBlockQuoteTitle: "塊引用",
    textBoldTitle: "加粗",
    textItalicTitle: "斜體",
    textSizeDecreaseTitle: "減小文本大小",
    textSizeIncreaseTitle: "增加文本的大小",
    textStrikeTitle: "通過罷工",
    textSubTitle: "分腳本",
    textSuperTitle: "超級腳本",
    textUnderlineTitle: "底線",
    unsavedEditWarningText: "在此頁上那裡未保存的更改",
    viewSourceDialogCancelButton: "關閉",
    viewSourceDialogOKButton: "應用原始程式碼",
    viewSourceDialogTitle: "內容源的代碼",
    viewSourceTitle: "查看\/編輯原始程式碼"
});